Game Theory Tools (full documentation): GT::GTL::Context Class Reference
GT::GTL::Context Class Reference
Context containing identifiers and values befind then.
#include <context.hpp>
Public Types
typedef map< Identifier, ParamPtr > KnownObjects
Known objects map.
Public Member Functions
Context ()
Default constructor.
Context (const ContextPtr parentContext)
Constructor with parental context inheritance.
virtual ~Context ()
Default destructor.
virtual Context & registerParam (const IdentifierPtr identifier, const ParamPtr param)
Adds/overrides identifier with value.
virtual Context & registerParam (const DefinitionPtr definition)
Adds/overrides identifier with value.
virtual bool hasRegistered (const Identifier &identifier) const
Returns true if Identifier has been registed.
virtual const NumberPtr getNumber (const Identifier &identifier) const
Obtains value from context by identifer.
virtual const ObjectPtr getObject (const Identifier &identifier) const
Obtains value from context by identifer.
virtual const ParamPtr getParam (const Identifier &identifier) const
Obtains param from context by identifer.
virtual const KnownObjects getKnownObjects () const
Returns map of KnownObjects.
virtual Message serialize () const
Returns serialized Message for a Context.
virtual Message toString () const override
Returns Message about Context.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
ContextPtr parentContext
Possible parent Context.
map< Identifier, ParamPtr > knownObjects
Registerd Objects.
Detailed Description
Context containing identifiers and values befind then.
Has the ability to dynamically inherit parent Context filling it with data specific to itself.
Used by Drivers to store Params under some name. They can be later accessed by their names.
Example of code recognized by Parsr that would use Context undernath:
LET game1 BE [game definition];
FIND mixed_equilibrium FOR game1;
Author
Mateusz Kubuszok
See Also
Definition
Param
ParamFactory
Definition at line 56 of file context.hpp.
Member Typedef Documentation
typedef map<Identifier, ParamPtr> GT::GTL::Context::KnownObjects
Known objects map.
Definition at line 71 of file context.hpp.
Constructor & Destructor Documentation
GT::GTL::Context::Context ()
Default constructor.
Definition at line 36 of file context.cpp.
References GT::createIdentifierPtr(), GT::GTL::ParamFactory::getInstance(), and registerParam().
                  :
     parentContext(),
     knownObjects()
 {
     registerParam(
         createIdentifierPtr("context"),
         ParamFactory::getInstance().createParam(
             ObjectPtr(new CurrentContext(this))
         )
     );
 }
GT::GTL::Context::Context (const ContextPtr parentContext) explicit
Constructor with parental context inheritance.
Parameters
parentContext parental Context
Definition at line 48 of file context.cpp.
References GT::createIdentifierPtr(), GT::GTL::ParamFactory::getInstance(), and registerParam().
   :
     parentContext(parentContext),
     knownObjects()
 {
     registerParam(
         createIdentifierPtr("context"),
         ParamFactory::getInstance().createParam(
             ObjectPtr(new CurrentContext(this))
         )
     );
 }
GT::GTL::Context::~Context () virtual
Default destructor.
Definition at line 62 of file context.cpp.
 {}
Member Function Documentation
const Context::KnownObjects GT::GTL::Context::getKnownObjects () const virtual
Returns map of KnownObjects.
Returns
KnownObjects map
Definition at line 115 of file context.cpp.
References knownObjects, and parentContext.
Referenced by GT::GTL::CurrentContextValuesProperty::findForConditions().
{
     KnownObjects allKnownObjects;
     if (parentContext)
         allKnownObjects = parentContext->getKnownObjects();
     for (const KnownObjects::value_type& knownObject : knownObjects)
         allKnownObjects[knownObject.first] = knownObject.second;
     return allKnownObjects;
 }
const NumberPtr GT::GTL::Context::getNumber (const Identifier & identifier) const virtual
Obtains value from context by identifer.
Parameters
identifier identifier to obtain
Returns
value to retur
Reimplemented in GT::GTL::NullContext.
Definition at line 85 of file context.cpp.
References GT::GTL::ExceptionFactory::getInstance(), knownObjects, GT::GTL::ExceptionFactory::notDefinedParam(), and parentContext.
         {
     if (knownObjects.count(identifier))
         return knownObjects.at(identifier)->getNumber(*this);
     if (parentContext && parentContext->hasRegistered(identifier))
         return parentContext->getNumber(identifier);
     throw ExceptionFactory::getInstance().notDefinedParam(identifier);
 }
const ObjectPtr GT::GTL::Context::getObject (const Identifier & identifier) const virtual
Obtains value from context by identifer.
Parameters
identifier identifier to obtain
Returns
value to retur
Reimplemented in GT::GTL::NullContext.
Definition at line 95 of file context.cpp.
References GT::GTL::ExceptionFactory::getInstance(), knownObjects, GT::GTL::ExceptionFactory::notDefinedParam(), and parentContext.
         {
     if (knownObjects.count(identifier))
         return knownObjects.at(identifier)->getObject(*this);
     if (parentContext && parentContext->hasRegistered(identifier))
         return parentContext->getObject(identifier);
     throw ExceptionFactory::getInstance().notDefinedParam(identifier);
 }
const ParamPtr GT::GTL::Context::getParam (const Identifier & identifier) const virtual
Obtains param from context by identifer.
If Object is not a Param then exception will be thrown.
Parameters
identifier param to obtain
Returns
value to retur
Reimplemented in GT::GTL::NullContext.
Definition at line 105 of file context.cpp.
References GT::GTL::ExceptionFactory::getInstance(), knownObjects, GT::GTL::ExceptionFactory::notDefinedParam(), and parentContext.
Referenced by GT::GTL::IdentifierParam::getNumber(), and GT::GTL::IdentifierParam::getObject().
         {
     if (knownObjects.count(identifier))
         return knownObjects.at(identifier);
     if (parentContext && parentContext->hasRegistered(identifier))
         return parentContext->getParam(identifier);
     throw ExceptionFactory::getInstance().notDefinedParam(identifier);
 }
bool GT::GTL::Context::hasRegistered (const Identifier & identifier) const virtual
Returns true if Identifier has been registed.
Returns
true if Identifier has been registerd
Definition at line 79 of file context.cpp.
References knownObjects, and parentContext.
         {
     return knownObjects.count(identifier) || (parentContext && parentContext->hasRegistered(identifier));
 }
Context & GT::GTL::Context::registerParam (const IdentifierPtr identifier, const ParamPtr param) virtual
Adds/overrides identifier with value.
Parameters
identifier identifer to register
param new value to register
Returns
reference to context for chaining
Reimplemented in GT::GTL::NullContext.
Definition at line 64 of file context.cpp.
References knownObjects.
Referenced by Context(), and GT::GTL::ExecutionStatementDriver::executeDefinition().
   {
     knownObjects.insert( KnownObjects::value_type(*identifier, param) );
     return *this;
 }
Context & GT::GTL::Context::registerParam (const DefinitionPtr definition) virtual
Adds/overrides identifier with value.
Parameters
definition definition of an Object with name
Returns
reference to context for chaining
Reimplemented in GT::GTL::NullContext.
Definition at line 72 of file context.cpp.
References knownObjects.
   {
     knownObjects.insert( KnownObjects::value_type(*definition->getName(), definition->getValue()) );
     return *this;
 }
Message GT::GTL::Context::serialize () const virtual
Returns serialized Message for a Context.
Returns
serialization result
Reimplemented in GT::GTL::NullContext.
Definition at line 127 of file context.cpp.
References GT::GTL::ValidableSymbol::addIndent(), knownObjects, and parentContext.
{
     stringstream result;
     bool firstElement = true;
     if (parentContext) {
         result << "// Ancestrial Context BEGIN"
                << ValidableSymbol::addIndent(parentContext->serialize()) << endl
                << "// Ancestrial Context END";
         firstElement = false;
     }
     for (const KnownObjects::value_type& knownObject : knownObjects) {
         static Identifier currentContext("context");
         if (knownObject.first == currentContext)
             continue;
         if (!firstElement)
             result << endl;
         result << "LET " << knownObject.first << " BE" << endl
                << ValidableSymbol::addIndent(knownObject.second->serialize()) << ';';
         firstElement = false;
     }
     return result.str();
 }
Message GT::GTL::Context::toString () const override virtual
Returns Message about Context.
Returns
Context's Message
Implements GT::Model::Root.
Reimplemented in GT::GTL::NullContext.
Definition at line 154 of file context.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), and knownObjects.
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     for (const KnownObjects::value_type& knownObject : knownObjects) {
         static Identifier currentContext("context");
         if (knownObject.first == currentContext)
             continue;
         IdentifierPtr name  = createIdentifierPtr(knownObject.first);
         MessagePtr    value = createMessagePtr(knownObject.second->toString());
         resultBuilder->addResult(name, value);
     }
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
map<Identifier, ParamPtr> GT::GTL::Context::knownObjects private
Registerd Objects.
Definition at line 65 of file context.hpp.
Referenced by getKnownObjects(), getNumber(), getObject(), getParam(), hasRegistered(), registerParam(), serialize(), and toString().
ContextPtr GT::GTL::Context::parentContext private
Possible parent Context.
Definition at line 60 of file context.hpp.
Referenced by getKnownObjects(), getNumber(), getObject(), getParam(), hasRegistered(), and serialize().
The documentation for this class was generated from the following files:
include/gt/gtl/context.hpp
src/gt/gtl/context.cpp