Game Theory Tools (full documentation): GT::GTL::ExecutionStatementDriver Class Reference
GT::GTL::ExecutionStatementDriver Class Reference final
Implementation used for handling statements via ExecutionDriver.
#include <execution_statement_driver.hpp>
Public Member Functions
ExecutionStatementDriver (Driver *parentDriver, Context *context)
Initiates ExecutionStatementDriver with its parent.
virtual bool executeDefinition (const DefinitionPtr *definition) override
Executes Definition saving Object under defined name.
virtual bool executeQuery (const QueryPtr *query) override
Executes Query saving Object under defined name.
virtual DefinitionPtr * createDefinition (const InputLocation &inputLocation, const IdentifierPtr *identifier, const ObjectPtr *object) const override
Creates Definition saving Object under defined name.
virtual QueryPtr * createQuery (const InputLocation &inputLocation, const IdentifiersPtr *identifiers, const ObjectsPtr *objects, const ConditionsPtr *conditions) const override
Creates Query for given properties.
virtual Message toString () const override
ExecutionStatementDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
CheckingStatementDriver checkingStatementDriver
Driver for error handling.
Driver * driver
Implementation of a main Driver.
Context * context
Contains Context.
Detailed Description
Implementation used for handling statements via ExecutionDriver.
Performs actual execution of instructions for statements.
Author
Mateusz Kubuszok
See Also
ExecutionDriver
StatementDriver
Definition at line 42 of file execution_statement_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::ExecutionStatementDriver::ExecutionStatementDriver (Driver * parentDriver, Context * context)
Initiates ExecutionStatementDriver with its parent.
Parameters
parentDriver parent Driver
context Context data
Definition at line 35 of file execution_statement_driver.cpp.
   :
     checkingStatementDriver(parentDriver),
     driver(parentDriver),
     context(parentContext)
     {}
Member Function Documentation
DefinitionPtr * GT::GTL::ExecutionStatementDriver::createDefinition (const InputLocation & inputLocation, const IdentifierPtr * identifier, const ObjectPtr * object) const override virtual
Creates Definition saving Object under defined name.
Parameters
inputLocation input location of created Definition
identifier name of defined Object
object defined Object
Returns
Definition
Implements GT::GTL::StatementDriver.
Definition at line 77 of file execution_statement_driver.cpp.
References checkingStatementDriver, GT::GTL::CheckingStatementDriver::createDefinition(), and GT::GTL::ParamFactory::getInstance().
         {
     DefinitionPtr* errorCheck =
         checkingStatementDriver.createDefinition(inputLocation, identifierPtr, objectPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const IdentifierPtr& identifier = *identifierPtr;
     const ObjectPtr&     object     = *objectPtr;
     return new DefinitionPtr(
         setupLocation<Definition>(
             DefinitionPtr(new Definition(identifier, ParamFactory::getInstance().createParam(object))),
             inputLocation
         )
     );
 }
QueryPtr * GT::GTL::ExecutionStatementDriver::createQuery (const InputLocation & inputLocation, const IdentifiersPtr * identifiers, const ObjectsPtr * objects, const ConditionsPtr * conditions) const override virtual
Creates Query for given properties.
Parameters
inputLocation input location of created Definition
identifiers queried properties
objects queried Object
conditions Conditions
Returns
Query
Implements GT::GTL::StatementDriver.
Definition at line 99 of file execution_statement_driver.cpp.
References checkingStatementDriver, and GT::GTL::CheckingStatementDriver::createQuery().
         {
     QueryPtr* errorCheck =
         checkingStatementDriver.createQuery(inputLocation, identifiersPtr, objectsPtr, conditionsPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const IdentifiersPtr& identifiers = *identifiersPtr;
     const ObjectsPtr&     objects     = *objectsPtr;
     const ConditionsPtr&  conditions  = *conditionsPtr;
     return new QueryPtr(
         setupLocation<Query>(
             QueryPtr(new Query(identifiers, objects, conditions)),
             inputLocation
         )
     );
 }
bool GT::GTL::ExecutionStatementDriver::executeDefinition (const DefinitionPtr * definition) override virtual
Executes Definition saving Object under defined name.
Parameters
definition definition to execute
Implements GT::GTL::StatementDriver.
Definition at line 44 of file execution_statement_driver.cpp.
References GT::Model::ResultFactory::buildResult(), checkingStatementDriver, context, GT::createIdentifierPtr(), driver, GT::GTL::CheckingStatementDriver::executeDefinition(), GT::Model::ResultFactory::getInstance(), GT::GTL::Context::registerParam(), and GT::GTL::Driver::showResult().
   {
     if (!checkingStatementDriver.executeDefinition(definitionPtr))
         return false;
     context->registerParam(*definitionPtr);
     static IdentifierPtr name   = createIdentifierPtr("Result");
     static MessagePtr    value  = createIdentifierPtr("Param defined successfully");
     ResultPtr            result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     driver->showResult(result);
     return true;
 }
bool GT::GTL::ExecutionStatementDriver::executeQuery (const QueryPtr * query) override virtual
Executes Query saving Object under defined name.
Parameters
query query to execute
Implements GT::GTL::StatementDriver.
Definition at line 60 of file execution_statement_driver.cpp.
References checkingStatementDriver, context, GT::createMessage(), driver, GT::GTL::Query::execute(), GT::GTL::CheckingStatementDriver::executeQuery(), GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::Driver::showError(), and GT::GTL::Driver::showResult().
   {
     if (!checkingStatementDriver.executeQuery(queryPtr))
         return false;
     Query& query = **queryPtr;
     try {
         driver->showResult(query.execute(*context));
         return true;
     } catch (const exception& e) {
         driver->showError(*query.getInputLocation(), createMessage(e.what()));
         return false;
     }
 }
Message GT::GTL::ExecutionStatementDriver::toString () const override virtual
ExecutionStatementDriver's Message.
Returns
message
Implements GT::GTL::StatementDriver.
Definition at line 123 of file execution_statement_driver.cpp.
{
     return Message("ExecutionStatementDriver");
 }
Member Data Documentation
CheckingStatementDriver GT::GTL::ExecutionStatementDriver::checkingStatementDriver private
Driver for error handling.
Definition at line 46 of file execution_statement_driver.hpp.
Referenced by createDefinition(), createQuery(), executeDefinition(), and executeQuery().
Context* GT::GTL::ExecutionStatementDriver::context private
Contains Context.
Definition at line 54 of file execution_statement_driver.hpp.
Referenced by executeDefinition(), and executeQuery().
Driver* GT::GTL::ExecutionStatementDriver::driver private
Implementation of a main Driver.
Definition at line 50 of file execution_statement_driver.hpp.
Referenced by executeDefinition(), and executeQuery().
The documentation for this class was generated from the following files:
src/gt/gtl/execution_statement_driver.hpp
src/gt/gtl/execution_statement_driver.cpp