Game Theory Tools (full documentation): GT::Routines::PlayerChoiceCondition Class Reference
GT::Routines::PlayerChoiceCondition Class Reference final
Condition that configures Routine to allow only one choice from some Player.
#include <player_choice_condition.hpp>
Public Member Functions
PlayerChoiceCondition (const IdentifierPtr player, const IdentifierPtr strategy)
Initiates Condition with Player's name and chosen strategy.
virtual void configureRoutine (RoutineConfigPtr routineConfig) const override
Configureg given RoutineConfig.
virtual Message toString () const override
Returns Condition's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const IdentifierPtr player
Player's name.
const IdentifierPtr strategy
Chosen strategy.
Detailed Description
Condition that configures Routine to allow only one choice from some Player.
Author
Mateusz Kubuszok
See Also
SelectableStrategiesRoutine
Definition at line 39 of file player_choice_condition.hpp.
Constructor & Destructor Documentation
GT::Routines::PlayerChoiceCondition::PlayerChoiceCondition (const IdentifierPtr player, const IdentifierPtr strategy)
Initiates Condition with Player's name and chosen strategy.
Parameters
player Player that chooses strategy
strategy chosen strategy
Definition at line 35 of file player_choice_condition.cpp.
   :
     player(definedPlayer),
     strategy(definedStrategy)
     {}
Member Function Documentation
void GT::Routines::PlayerChoiceCondition::configureRoutine (RoutineConfigPtr routineConfig) const override virtual
Configureg given RoutineConfig.
Parameters
routineConfig RoutineConfig to set up
Exceptions
InvalidCondition thrown when Condition is invalid
Implements GT::Routines::Condition.
Definition at line 43 of file player_choice_condition.cpp.
References GT::Routines::ExceptionFactory::getInstance(), GT::Routines::ExceptionFactory::invalidCondition(), player, GT::Routines::PlayerChoiceRoutineConfig::requireChoiceExactly(), and strategy.
         {
     PlayerChoiceRoutineConfigPtr specificConfig =
         dynamic_pointer_cast<PlayerChoiceRoutineConfig>(routineConfig);
     if (!specificConfig)
         return;
     try {
         specificConfig->requireChoiceExactly(*player, *strategy);
     } catch (InvalidPlayerChoice& e) {
         throw ExceptionFactory::getInstance().invalidCondition(e);
     }
 }
Message GT::Routines::PlayerChoiceCondition::toString () const override virtual
Returns Condition's Message.
Returns
Condition's Message
Implements GT::Routines::Condition.
Definition at line 59 of file player_choice_condition.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), player, and strategy.
{
     MessagePtr strategyName = createMessagePtr(strategy);
     return ResultFactory::getInstance().buildResult()->addResult(player, strategyName).build()->getResult();
 }
Member Data Documentation
const IdentifierPtr GT::Routines::PlayerChoiceCondition::player private
Player's name.
Definition at line 43 of file player_choice_condition.hpp.
Referenced by configureRoutine(), and toString().
const IdentifierPtr GT::Routines::PlayerChoiceCondition::strategy private
Chosen strategy.
Definition at line 47 of file player_choice_condition.hpp.
Referenced by configureRoutine(), and toString().
The documentation for this class was generated from the following files:
src/gt/routines/player_choice_condition.hpp
src/gt/routines/player_choice_condition.cpp