Game Theory Tools (full documentation): GT::GTL::NullParam Class Reference
GT::GTL::NullParam Class Reference final
Null Param for handling invalid situations.
#include <param.hpp>
Public Member Functions
virtual const ObjectPtr getObject (const Context &) const override
Returns Object for Context.
virtual const ObjectPtr getObject (const Context &, VisitedIdentifiers &) const override
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &) const override
Returns Number for context.
virtual const NumberPtr getNumber (const Context &, VisitedIdentifiers &) const override
Returns Number for context.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns message about object.
Public Member Functions inherited from GT::GTL::Param
Param ()
Default constructor.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const override
Finds referred Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const override
Finds referred Objects' property for giver conditions and returns it as a Result.
virtual operator const Param & () const override
Explicit cast to Param type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual operator const Game & () const
Explicit cast to Game type.
virtual operator const Player & () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Public Types inherited from GT::GTL::Param
typedef set< Identifier > VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Protected Member Functions inherited from GT::GTL::Param
void checkVisitedIdentifiers (const VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Checks whether visited Identifiers contain current one.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Null Param for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 176 of file param.hpp.
Member Function Documentation
virtual const NumberPtr GT::GTL::NullParam::getNumber (const Context & context) const inline override virtual
Returns Number for context.
Parameters
context Context with values
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented from GT::GTL::Param.
Definition at line 191 of file param.hpp.
References GT::Model::NullFactory::createNumber(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumber();
     }
virtual const NumberPtr GT::GTL::NullParam::getNumber (const Context & context, VisitedIdentifiers & visitedIdentifiers) const inline override virtual
Returns Number for context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 197 of file param.hpp.
References GT::Model::NullFactory::createNumber(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumber();
     }
virtual const ObjectPtr GT::GTL::NullParam::getObject (const Context & context) const inline override virtual
Returns Object for Context.
Parameters
context Context with values
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented from GT::GTL::Param.
Definition at line 178 of file param.hpp.
References GT::GTL::NullFactory::createObject(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createObject();
     }
virtual const ObjectPtr GT::GTL::NullParam::getObject (const Context & context, VisitedIdentifiers & visitedIdentifiers) const inline override virtual
Returns Object for Context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 184 of file param.hpp.
References GT::GTL::NullFactory::createObject(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createObject();
     }
virtual bool GT::GTL::NullParam::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 204 of file param.hpp.
{
         return false;
     }
virtual Message GT::GTL::NullParam::toString () const inline override virtual
Returns message about object.
Returns
generic Message
Reimplemented from GT::GTL::Object.
Definition at line 208 of file param.hpp.
{
         return Message("NullParam");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/param.hpp