Game Theory Tools (full documentation): GT::GTL::IdentifierParam Class Reference
GT::GTL::IdentifierParam Class Reference final
Param containing reference to other Param.
#include <identifier_param.hpp>
Public Member Functions
IdentifierParam (const Identifier &id)
Initiates Param with Identifier.
const Identifier & getIdentifier () const
Returns Identifier.
virtual const ObjectPtr getObject (const Context &context, VisitedIdentifiers &visitedIdentifiers) const override
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &context, VisitedIdentifiers &visitedIdentifiers) const override
Returns Number for context.
virtual Message serialize () const override
Returns serialized Message for an IdentifierParam.
virtual Message toString () const override
IdentifierParam's Message.
Public Member Functions inherited from GT::GTL::Param
Param ()
Default constructor.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const override
Finds referred Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const override
Finds referred Objects' property for giver conditions and returns it as a Result.
virtual const ObjectPtr getObject (const Context &context) const
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &context) const
Returns Number for context.
virtual operator const Param & () const override
Explicit cast to Param type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual operator const Game & () const
Explicit cast to Game type.
virtual operator const Player & () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Identifier identifier
Identifier that this Param points to.
Additional Inherited Members
Public Types inherited from GT::GTL::Param
typedef set< Identifier > VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Param
void checkVisitedIdentifiers (const VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Checks whether visited Identifiers contain current one.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Param containing reference to other Param.
Author
Mateusz Kubuszok
See Also
Context
Param
ParamFactory
Definition at line 41 of file identifier_param.hpp.
Constructor & Destructor Documentation
GT::GTL::IdentifierParam::IdentifierParam (const Identifier & id) explicit
Initiates Param with Identifier.
Parameters
id identifier
Definition at line 31 of file identifier_param.cpp.
   :
     Param(),
     identifier(id)
     {}
Member Function Documentation
const Identifier & GT::GTL::IdentifierParam::getIdentifier () const
Returns Identifier.
Returns
Identifier
Definition at line 38 of file identifier_param.cpp.
References identifier.
{
     return identifier;
 }
const NumberPtr GT::GTL::IdentifierParam::getNumber (const Context & context, VisitedIdentifiers & visitedIdentifiers) const override virtual
Returns Number for context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 51 of file identifier_param.cpp.
References GT::GTL::Param::checkVisitedIdentifiers(), GT::GTL::Context::getParam(), and identifier.
         {
     checkVisitedIdentifiers(visitedIdentifiers, identifier);
     visitedIdentifiers.insert(identifier);
     return context.getParam(identifier)->getNumber(context, visitedIdentifiers);
 }
const ObjectPtr GT::GTL::IdentifierParam::getObject (const Context & context, VisitedIdentifiers & visitedIdentifiers) const override virtual
Returns Object for Context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 42 of file identifier_param.cpp.
References GT::GTL::Param::checkVisitedIdentifiers(), GT::GTL::Context::getParam(), and identifier.
         {
     checkVisitedIdentifiers(visitedIdentifiers, identifier);
     visitedIdentifiers.insert(identifier);
     return context.getParam(identifier)->getObject(context, visitedIdentifiers);
 }
Message GT::GTL::IdentifierParam::serialize () const override virtual
Returns serialized Message for an IdentifierParam.
Returns
serialization result
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 60 of file identifier_param.cpp.
References GT::createMessage(), and identifier.
{
     return createMessage(identifier);
 }
Message GT::GTL::IdentifierParam::toString () const override virtual
IdentifierParam's Message.
Returns
Message
Reimplemented from GT::GTL::Object.
Definition at line 64 of file identifier_param.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), and identifier.
{
     static const IdentifierPtr name  = createIdentifierPtr("IdentifierParam");
     MessagePtr                 value = createMessagePtr(identifier);
     return ResultFactory::getInstance().buildResult()->addResult(name, value).build()->getResult();
 }
Member Data Documentation
const Identifier GT::GTL::IdentifierParam::identifier private
Identifier that this Param points to.
Definition at line 45 of file identifier_param.hpp.
Referenced by getIdentifier(), getNumber(), getObject(), serialize(), and toString().
The documentation for this class was generated from the following files:
src/gt/gtl/identifier_param.hpp
src/gt/gtl/identifier_param.cpp