Game Theory Tools (full documentation): GT::Model::NullExtensiveData Class Reference
GT::Model::NullExtensiveData Class Reference final
Null ExtensiveData for handling invalid situations.
#include <extensive_data.hpp>
Public Member Functions
NullExtensiveData ()
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual const PlayerPtr getPlayerInTurn (const Positions &) const override
Returns Player that plays for given position.
virtual const PlayerPtr getPlayerInTurn (const PositionsPtr) const override
Returns Player that plays for given position.
virtual ExtensiveData & setPlayerInTurn (const Positions &, const PlayerPtr) override
Sets Player that plays for given position.
virtual ExtensiveData & setPlayerInTurn (const PositionsPtr, const PlayerPtr) override
Sets Player that plays for given position.
virtual const DataPiecePtr getPayoffs (const Positions &) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const PositionsPtr) const override
Returns DataPiece that gives access to payoffs.
virtual Data & setPayoffs (const Positions &, const NumbersPtr) override
Sets Positions to contains given payoffs.
virtual Data & setPayoffs (const PositionsPtr, const NumbersPtr) override
Sets Positions to contains given payoffs.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns ExtensiveData Message.
virtual const DataPiecePtr operator[] (const Positions &) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const PositionsPtr) const override
Returns DataPiece that gives access to payoffs.
Public Member Functions inherited from GT::Model::ExtensiveData
ExtensiveData (const PlayersPtr playersDefinitions)
Initiates Data with Players' definitions.
virtual const ExtensiveDataNodePtr getRoot () const
Returns root of ExtensiveData tree.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null ExtensiveData for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 215 of file extensive_data.hpp.
Constructor & Destructor Documentation
GT::Model::NullExtensiveData::NullExtensiveData () inline
Definition at line 217 of file extensive_data.hpp.
                         :
         ExtensiveData(NullFactory::getInstance().createPlayers())
         {}
Member Function Documentation
virtual const DataPiecePtr GT::Model::NullExtensiveData::getPayoffs (const Positions & positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 251 of file extensive_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullExtensiveData::getPayoffs (const PositionsPtr positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 257 of file extensive_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const PlayerPtr GT::Model::NullExtensiveData::getPlayerInTurn (const Positions & positions) const inline override virtual
Returns Player that plays for given position.
Parameters
positions Positions in payoff storage
Returns
Player that plays given position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 225 of file extensive_data.hpp.
References GT::Model::NullFactory::createPlayer(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createPlayer();
     }
virtual const PlayerPtr GT::Model::NullExtensiveData::getPlayerInTurn (const PositionsPtr positions) const inline override virtual
Returns Player that plays for given position.
Parameters
positions Positions in payoff storage
Returns
Player that plays given position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 231 of file extensive_data.hpp.
References GT::Model::NullFactory::createPlayer(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createPlayer();
     }
virtual const PlayersPtr GT::Model::NullExtensiveData::getPlayers () const inline override virtual
Returns Players' definitions.
Returns
Players' definitions
Reimplemented from GT::Model::ExtensiveData.
Definition at line 221 of file extensive_data.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual bool GT::Model::NullExtensiveData::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 277 of file extensive_data.hpp.
{
         return false;
     }
virtual const DataPiecePtr GT::Model::NullExtensiveData::operator[] (const Positions & positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 285 of file extensive_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullExtensiveData::operator[] (const PositionsPtr positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::ExtensiveData.
Definition at line 291 of file extensive_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual Data& GT::Model::NullExtensiveData::setPayoffs (const Positions & positions, const NumbersPtr numbers) inline override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Exceptions
InvalidCoordinate thrown when Positions does not specify all depths continously ("1", "2", ...) or some strategies do not match assigned for each turn Players
Reimplemented from GT::Model::ExtensiveData.
Definition at line 263 of file extensive_data.hpp.
                {
         return *this;
     }
virtual Data& GT::Model::NullExtensiveData::setPayoffs (const PositionsPtr positions, const NumbersPtr numbers) inline override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Exceptions
InvalidCoordinate thrown when Positions does not specify all depths continously ("1", "2", ...) or some strategies do not match assigned for each turn Players
Reimplemented from GT::Model::ExtensiveData.
Definition at line 270 of file extensive_data.hpp.
                {
         return *this;
     }
virtual ExtensiveData& GT::Model::NullExtensiveData::setPlayerInTurn (const Positions & positions, const PlayerPtr player) inline override virtual
Sets Player that plays for given position.
Parameters
positions Positions for which player Player
player Player that plays given position
Returns
reference ot itdelf for chaining
Reimplemented from GT::Model::ExtensiveData.
Definition at line 237 of file extensive_data.hpp.
                {
         return *this;
     }
virtual ExtensiveData& GT::Model::NullExtensiveData::setPlayerInTurn (const PositionsPtr positions, const PlayerPtr player) inline override virtual
Sets Player that plays for given position.
Parameters
positions Positions for which player Player
player Player that plays given position
Returns
reference ot itdelf for chaining
Reimplemented from GT::Model::ExtensiveData.
Definition at line 244 of file extensive_data.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullExtensiveData::toString () const inline override virtual
Returns ExtensiveData Message.
Returns
Message
Reimplemented from GT::Model::ExtensiveData.
Definition at line 281 of file extensive_data.hpp.
{
         return Message("NullExtensiveData");
     }
The documentation for this class was generated from the following file:
src/gt/model/extensive_data.hpp