Game Theory Tools (full documentation): GT::GTL::InformationSetRangeCondition Class Reference
GT::GTL::InformationSetRangeCondition Class Reference final
Condition used for selecting strategy for an information set.
#include <information_set_range_condition.hpp>
Public Member Functions
InformationSetRangeCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectsPtr strategies)
Initiates Condition with a Player's name and choice.
virtual Routines::ConditionPtr getCondition (const Context &context) const override
Returns Condition applicable to Routine.
virtual Message toString () const override
Returns Message about Condition.
Public Member Functions inherited from GT::GTL::Condition
virtual ~Condition ()
Default destructor.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const ObjectPtr player
Param with Player's name.
const ObjectPtr informationSet
Param with Player's information set.
const ObjectsPtr strategies
Param with Player's strategies.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Condition
Identifier getIdentifier (const Context &context, const ObjectPtr &object) const
Obtains Identifier from Object.
Detailed Description
Condition used for selecting strategy for an information set.
Author
Mateusz Kubuszok
Definition at line 37 of file information_set_range_condition.hpp.
Constructor & Destructor Documentation
GT::GTL::InformationSetRangeCondition::InformationSetRangeCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectsPtr strategies)
Initiates Condition with a Player's name and choice.
Parameters
player Param with Player's name
informationSet Param with Player's informationSet
strategies Param with Player's strategies
Definition at line 39 of file information_set_range_condition.cpp.
   :
     player(definedPlayer),
     informationSet(definedInformationSet),
     strategies(definedStrategies)
     {}
Member Function Documentation
Routines::ConditionPtr GT::GTL::InformationSetRangeCondition::getCondition (const Context & context) const override virtual
Returns Condition applicable to Routine.
Parameters
context Context
Returns
Condition applicable to Routine
Exceptions
InvalidType thrown when either player or strategy are not IdentifierParams
Implements GT::GTL::Condition.
Definition at line 49 of file information_set_range_condition.cpp.
References GT::createIdentifierPtr(), GT::createIdentifiersPtr(), GT::Routines::ConditionFactory::createInformationSetRangeCondition(), GT::GTL::Condition::getIdentifier(), GT::Routines::ConditionFactory::getInstance(), informationSet, player, and strategies.
         {
     const Identifier playerName         = getIdentifier(context, player);
     const Identifier informationSetName = getIdentifier(context, informationSet);
     Identifiers strategiesNames;
     for (const ObjectPtr& strategy : *strategies)
         strategiesNames.push_back( createIdentifierPtr(getIdentifier(context, strategy)) );
     return Routines::ConditionFactory::getInstance().createInformationSetRangeCondition(
         createIdentifierPtr(playerName),
         createIdentifierPtr(informationSetName),
         createIdentifiersPtr(strategiesNames)
     );
 }
Message GT::GTL::InformationSetRangeCondition::toString () const override virtual
Returns Message about Condition.
Returns
Condition's Message
Implements GT::GTL::Condition.
Definition at line 66 of file information_set_range_condition.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), informationSet, player, and strategies.
{
     static const IdentifierPtr playerName         = createIdentifierPtr("Player");
     static const IdentifierPtr informationSetName = createIdentifierPtr("Information Set");
     static const IdentifierPtr allowedName        = createIdentifierPtr("Allowed");
     ResultBuilderPtr strategiesValue = ResultFactory::getInstance().buildResult();
     for (Index i = 0; i < strategies->size(); i++) {
         strategiesValue->addResult(
             createIdentifierPtr(i+1),
             createMessagePtr(strategies->at(i)->toString())
         );
     }
     Message result = ResultFactory::getInstance().buildResult()
         ->addResult(playerName,         createMessagePtr(player->toString()))
          .addResult(informationSetName, createMessagePtr(informationSet->toString()))
          .addResult(allowedName,        createMessagePtr(strategiesValue->build()->getResult()))
          .build()->getResult();
     static const IdentifierPtr name  = createIdentifierPtr("Condition");
     MessagePtr                 value = createMessagePtr(result);
     return ResultFactory::getInstance().buildResult()->addResult(name, value).build()->getResult();
 }
Member Data Documentation
const ObjectPtr GT::GTL::InformationSetRangeCondition::informationSet private
Param with Player's information set.
Definition at line 45 of file information_set_range_condition.hpp.
Referenced by getCondition(), and toString().
const ObjectPtr GT::GTL::InformationSetRangeCondition::player private
Param with Player's name.
Definition at line 41 of file information_set_range_condition.hpp.
Referenced by getCondition(), and toString().
const ObjectsPtr GT::GTL::InformationSetRangeCondition::strategies private
Param with Player's strategies.
Definition at line 49 of file information_set_range_condition.hpp.
Referenced by getCondition(), and toString().
The documentation for this class was generated from the following files:
src/gt/gtl/information_set_range_condition.hpp
src/gt/gtl/information_set_range_condition.cpp