Game Theory Tools (full documentation): GT::GTL::ParamFactory Class Reference
GT::GTL::ParamFactory Class Reference final
Used for creation of Params that may differs in behaviour.
#include <param_factory.hpp>
Public Member Functions
ParamPtr createParam (const Identifier &identifier) const
Creates Param by identifier attatched to it.
ParamPtr createParam (const IdentifierPtr identifier) const
Creates Param by identifier attatched to it.
ParamPtr createParam (const Number &number) const
Creates Param by value contained by it.
ParamPtr createParam (const NumberPtr number) const
Creates Param by value contained by it.
ParamPtr createParam (const ObjectPtr object) const
Creates Param by value contained by it.
Static Public Member Functions
static ParamFactory & getInstance ()
Returns the instance of a ParamFactory.
Private Member Functions
ParamFactory ()
Private constructor.
ParamFactory (const ParamFactory &paramFactory)
Private copy constructor.
~ParamFactory ()
Private destructor.
Detailed Description
Used for creation of Params that may differs in behaviour.
Author
Mateusz Kubuszok
Definition at line 37 of file param_factory.hpp.
Constructor & Destructor Documentation
GT::GTL::ParamFactory::ParamFactory () private
Private constructor.
Definition at line 75 of file param_factory.cpp.
 {}
GT::GTL::ParamFactory::ParamFactory (const ParamFactory & paramFactory) private
Private copy constructor.
GT::GTL::ParamFactory::~ParamFactory () private
Private destructor.
Definition at line 77 of file param_factory.cpp.
 {}
Member Function Documentation
ParamPtr GT::GTL::ParamFactory::createParam (const Identifier & identifier) const
Creates Param by identifier attatched to it.
Parameters
identifier identifier of a Param
Returns
Param instance
Definition at line 41 of file param_factory.cpp.
         {
     return ParamPtr(new IdentifierParam(identifier));
 }
ParamPtr GT::GTL::ParamFactory::createParam (const IdentifierPtr identifier) const
Creates Param by identifier attatched to it.
Parameters
identifier identifier of a Param
Returns
Param instance
Definition at line 47 of file param_factory.cpp.
         {
     return ParamPtr(new IdentifierParam(*identifier));
 }
ParamPtr GT::GTL::ParamFactory::createParam (const Number & number) const
Creates Param by value contained by it.
Parameters
number value of a Param
Returns
Param instance
Definition at line 53 of file param_factory.cpp.
         {
     NumberPtr value(new Number(number));
     return ParamPtr(new NumberParam(value));
 }
ParamPtr GT::GTL::ParamFactory::createParam (const NumberPtr number) const
Creates Param by value contained by it.
Parameters
number value of a Param
Returns
Param instance
Definition at line 60 of file param_factory.cpp.
         {
     return ParamPtr(new NumberParam(number));
 }
ParamPtr GT::GTL::ParamFactory::createParam (const ObjectPtr object) const
Creates Param by value contained by it.
Parameters
object value of a Param
Returns
Param instance
Definition at line 66 of file param_factory.cpp.
         {
     const Param& param = *object;
     return param ? dynamic_pointer_cast<Param>(object) : ParamPtr(new ObjectParam(object));
 }
ParamFactory & GT::GTL::ParamFactory::getInstance () static
Returns the instance of a ParamFactory.
Returns
ParamFactory instance
Definition at line 34 of file param_factory.cpp.
Referenced by GT::GTL::Context::Context(), GT::GTL::ExecutionStatementDriver::createDefinition(), and GT::GTL::ExecutionValueDriver::get().
{
     static ParamFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/gtl/param_factory.hpp
src/gt/gtl/param_factory.cpp