Game Theory Tools (full documentation): GT::Model::ExtensiveGameBuilder Class Reference
GT::Model::ExtensiveGameBuilder Class Reference final
Builder used for creating ExtensiveGame.
#include <extensive_game_builder.hpp>
Public Member Functions
ExtensiveGameBuilder ()
Defalt constructor.
virtual GamePtr build () const override
Returns set up Game.
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual DataBuilder & setPlayers (const PlayersPtr newPlayers) override
Sets Players' definitions.
virtual DataBuilder & addNextPositions (const PositionsPtr positions) override
Specifies next Positions.
virtual DataBuilder & setPayoffs (const NumbersPtr params) override
Sets payoffs values.
virtual DataBuilderPtr clone () const override
Returns copy of itsef with shared content and frozen values of already set Positions.
virtual GameBuilderPtr cloneBuilder () const override
Returns new copy of this GameBuilder's type.
virtual DataBuilderPtr dataBuilder () const override
Returns Same's DataBuilder.
virtual Message toString () const override
ExtensiveGameBuilder Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
ExtensiveDataBuilderPtr extensiveDataBuilder
Game's DataBuilder.
Detailed Description
Builder used for creating ExtensiveGame.
Games in this form has all payoffs defined in nodes of a game tree. Each node of that tree has assigned Player. As such each SubCoordinates is mapped to strategy of the same Player.
Author
Mateusz Kubuszok
See Also
ExtensiveGame
ExtensiveDataBuilder
Definition at line 43 of file extensive_game_builder.hpp.
Constructor & Destructor Documentation
GT::Model::ExtensiveGameBuilder::ExtensiveGameBuilder ()
Defalt constructor.
Definition at line 35 of file extensive_game_builder.cpp.
Referenced by cloneBuilder().
                                            :
     extensiveDataBuilder(new ExtensiveDataBuilder())
     {}
Member Function Documentation
DataBuilder & GT::Model::ExtensiveGameBuilder::addNextPositions (const PositionsPtr positions) override virtual
Specifies next Positions.
Parameters
positions next Positions to specify
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 50 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
   {
     extensiveDataBuilder->addNextPositions(positions);
     return *this;
 }
GamePtr GT::Model::ExtensiveGameBuilder::build () const override virtual
Returns set up Game.
Returns
built Game
Implements GT::Model::GameBuilder.
Definition at line 77 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
{
     return GamePtr(
         new ExtensiveGame(
             extensiveDataBuilder->getPlayers(),
             extensiveDataBuilder->build()
         )
     );
 }
DataBuilderPtr GT::Model::ExtensiveGameBuilder::clone () const override virtual
Returns copy of itsef with shared content and frozen values of already set Positions.
Returns
copy with frozem Positions and content common to parent
Implements GT::Model::DataBuilder.
Definition at line 64 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
{
     return extensiveDataBuilder->clone();
 }
GameBuilderPtr GT::Model::ExtensiveGameBuilder::cloneBuilder () const override virtual
Returns new copy of this GameBuilder's type.
Returns
GameBuilder
Implements GT::Model::GameBuilder.
Definition at line 68 of file extensive_game_builder.cpp.
References ExtensiveGameBuilder().
{
     return GameBuilderPtr(new ExtensiveGameBuilder());
 }
DataBuilderPtr GT::Model::ExtensiveGameBuilder::dataBuilder () const override virtual
Returns Same's DataBuilder.
Returns
DataBuilder
Implements GT::Model::GameBuilder.
Definition at line 72 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
Referenced by toString().
{
     return dynamic_pointer_cast<DataBuilder>(extensiveDataBuilder);
 }
const PlayersPtr GT::Model::ExtensiveGameBuilder::getPlayers () const override virtual
Returns Players' definitions.
Returns
Players' definitions
Implements GT::Model::GameBuilder.
Definition at line 39 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
{
     return extensiveDataBuilder->getPlayers();
 }
DataBuilder & GT::Model::ExtensiveGameBuilder::setPayoffs (const NumbersPtr params) override virtual
Sets payoffs values.
Parameters
params values of payoffs
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 57 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
   {
     extensiveDataBuilder->setPayoffs(params);
     return *this;
 }
DataBuilder & GT::Model::ExtensiveGameBuilder::setPlayers (const PlayersPtr newPlayers) override virtual
Sets Players' definitions.
Parameters
newPlayers Players' definitions
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 43 of file extensive_game_builder.cpp.
References extensiveDataBuilder.
   {
     extensiveDataBuilder->setPlayers(players);
     return *this;
 }
Message GT::Model::ExtensiveGameBuilder::toString () const override virtual
ExtensiveGameBuilder Message.
Returns
Message
Implements GT::Model::DataBuilder.
Definition at line 86 of file extensive_game_builder.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), dataBuilder(), and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name    = createIdentifierPtr("Current Extensive Game");
     const MessagePtr           message = createMessagePtr(dataBuilder()->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, message).build()->getResult();
 }
Member Data Documentation
ExtensiveDataBuilderPtr GT::Model::ExtensiveGameBuilder::extensiveDataBuilder private
Game's DataBuilder.
Definition at line 47 of file extensive_game_builder.hpp.
Referenced by addNextPositions(), build(), clone(), dataBuilder(), getPlayers(), setPayoffs(), and setPlayers().
The documentation for this class was generated from the following files:
src/gt/model/extensive_game_builder.hpp
src/gt/model/extensive_game_builder.cpp