Game Theory Tools (full documentation): GT::GTL::ErrorObject Class Reference
GT::GTL::ErrorObject Class Reference final
Error Object for handling invalid situations.
#include <object.hpp>
Public Member Functions
ErrorObject (const Message errorMessage)
virtual bool respondsTo (const Identifier &) const override
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &) const override
Returns property's description.
virtual ResultPtr findProperty (const Context &, const Identifier &) const override
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &, const Identifier &, const Conditions &) const override
Finds Objects' property for giver Conditions and returns it as a Result.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns message about object.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual const Game & toGame () const
Explicit cast to Game type.
virtual const Param & toParam () const
Explicit cast to Param type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Message message
Error message.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Error Object for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 272 of file object.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorObject::ErrorObject (const Message errorMessage) inline
Definition at line 279 of file object.hpp.
       :
         message(errorMessage)
         {}
Member Function Documentation
virtual ResultPtr GT::GTL::ErrorObject::describeProperty (const Identifier & propertyName) const inline override virtual
Returns property's description.
Parameters
propertyName property's name
Returns
property's description
Exceptions
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 291 of file object.hpp.
References GT::GTL::NullFactory::createResult(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::GTL::ErrorObject::findProperty (const Context & context, const Identifier & propertyName) const inline override virtual
Finds Objects' property and returns it as a Result.
Parameters
context Context with values
propertyName property's name
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 297 of file object.hpp.
References GT::GTL::NullFactory::createResult(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::GTL::ErrorObject::findPropertyWithConditions (const Context & context, const Identifier & propertyName, const Conditions & conditions) const inline override virtual
Finds Objects' property for giver Conditions and returns it as a Result.
Parameters
context Context with values
propertyName property's name
conditions Conditions to consider
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 304 of file object.hpp.
References GT::GTL::NullFactory::createResult(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createResult();
     }
virtual bool GT::GTL::ErrorObject::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 312 of file object.hpp.
{
         return false;
     }
virtual bool GT::GTL::ErrorObject::respondsTo (const Identifier & propertyName) const inline override virtual
Whether Object responds to some property.
Parameters
propertyName property's name
Returns
true if Object responds to such property
Reimplemented from GT::GTL::Object.
Definition at line 285 of file object.hpp.
                      {
         return false;
     }
virtual Message GT::GTL::ErrorObject::toString () const inline override virtual
Returns message about object.
Returns
generic Message
Reimplemented from GT::GTL::Object.
Definition at line 316 of file object.hpp.
References message.
{
         return message;
     }
Member Data Documentation
const Message GT::GTL::ErrorObject::message private
Error message.
Definition at line 276 of file object.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/object.hpp