Game Theory Tools (full documentation): GT::GTL::NullGameDriver Class Reference
GT::GTL::NullGameDriver Class Reference
Null GameDriver for handling invalid situations.
#include <game_driver.hpp>
Public Member Functions
NullGameDriver ()
virtual GamePtr * createStrategic (const InputLocation &inputLocation, const DetailsPtr *) const override
Create Strategic Game.
virtual GamePtr * createExtensive (const InputLocation &inputLocation, const DetailsPtr *) const override
Create Extensive Game.
virtual DetailsPtr * createDetails (const InputLocation &inputLocation, const ObjectsPtr *, const CoordinatesPtr *) const override
Create Details.
virtual PlayerPtr * createPlayer (const InputLocation &inputLocation, const IdentifierPtr *, const IdentifiersPtr *) const override
Create Player.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
GameDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null GameDriver for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 107 of file game_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::NullGameDriver::NullGameDriver () inline
Definition at line 109 of file game_driver.hpp.
                      :
         GameDriver()
         {}
Member Function Documentation
virtual DetailsPtr* GT::GTL::NullGameDriver::createDetails (const InputLocation & inputLocation, const ObjectsPtr * players, const CoordinatesPtr * data) const inline override virtual
Create Details.
Parameters
inputLocation input location of created Details
players declared Players
data declared Coordinates
Returns
Details
Implements GT::GTL::GameDriver.
Definition at line 137 of file game_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new DetailsPtr(
             setupLocation<Details>(
                 NullFactory::getInstance().createDetails(),
                 inputLocation
             )
         );
     }
virtual GamePtr* GT::GTL::NullGameDriver::createExtensive (const InputLocation & inputLocation, const DetailsPtr * details) const inline override virtual
Create Extensive Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 125 of file game_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new GamePtr(
             setupLocation<Game>(
                 NullFactory::getInstance().createGame(),
                 inputLocation
             )
         );
     }
virtual PlayerPtr* GT::GTL::NullGameDriver::createPlayer (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifiersPtr * strategies) const inline override virtual
Create Player.
Parameters
inputLocation input location of created Player
player Player's name
strategies strategies
Returns
Player
Implements GT::GTL::GameDriver.
Definition at line 150 of file game_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new PlayerPtr(
             setupLocation<Player>(
                 NullFactory::getInstance().createPlayer(),
                 inputLocation
             )
         );
     }
virtual GamePtr* GT::GTL::NullGameDriver::createStrategic (const InputLocation & inputLocation, const DetailsPtr * details) const inline override virtual
Create Strategic Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 113 of file game_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new GamePtr(
             setupLocation<Game>(
                 NullFactory::getInstance().createGame(),
                 inputLocation
             )
         );
     }
virtual bool GT::GTL::NullGameDriver::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 163 of file game_driver.hpp.
{
         return false;
     }
virtual Message GT::GTL::NullGameDriver::toString () const inline override virtual
GameDriver's Message.
Returns
message
Implements GT::GTL::GameDriver.
Definition at line 167 of file game_driver.hpp.
{
         return Message("NullGameDriver");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/game_driver.hpp