Game Theory Tools (full documentation): GT::Routines::NullFactory Class Reference
GT::Routines::NullFactory Class Reference final
Used for creation of Null instances for Routines classes.
#include <null_factory.hpp>
Public Member Functions
ConditionPtr createCondition () const
Creates NullCondition.
ConditionsPtr createConditions () const
Creates NullConditions.
RoutinePtr createRoutine () const
Creates NullRoutine.
RoutinesPtr createRoutines () const
Creates NullRoutines.
Static Public Member Functions
static NullFactory & getInstance ()
Returns the instance of a NullFactory.
Private Member Functions
NullFactory ()=default
Default constructor hidden from programmers.
NullFactory (const NullFactory &nullFactory)=delete
Default copy constructor hidden from programmers.
~NullFactory ()=default
Default destructor hidden from programmers.
Detailed Description
Used for creation of Null instances for Routines classes.
Author
Mateusz Kubuszok
Definition at line 37 of file null_factory.hpp.
Constructor & Destructor Documentation
GT::Routines::NullFactory::NullFactory () private default
Default constructor hidden from programmers.
GT::Routines::NullFactory::NullFactory (const NullFactory & nullFactory) private delete
Default copy constructor hidden from programmers.
Parameters
nullFactory object to copy
GT::Routines::NullFactory::~NullFactory () private default
Default destructor hidden from programmers.
Member Function Documentation
ConditionPtr GT::Routines::NullFactory::createCondition () const
Creates NullCondition.
Returns
NullCondition
Definition at line 36 of file null_factory.cpp.
Referenced by GT::GTL::NullCondition::getCondition(), and GT::GTL::ErrorCondition::getCondition().
{
     return ConditionPtr(new NullCondition());
 }
ConditionsPtr GT::Routines::NullFactory::createConditions () const
Creates NullConditions.
Returns
NullConditions
Definition at line 40 of file null_factory.cpp.
{
     return ConditionsPtr(new Conditions());
 }
RoutinePtr GT::Routines::NullFactory::createRoutine () const
Creates NullRoutine.
Returns
NullRoutine
Definition at line 44 of file null_factory.cpp.
{
     return RoutinePtr(new NullRoutine());
 }
RoutinesPtr GT::Routines::NullFactory::createRoutines () const
Creates NullRoutines.
Returns
NullRoutines
Definition at line 48 of file null_factory.cpp.
{
     return RoutinesPtr(new Routines());
 }
NullFactory & GT::Routines::NullFactory::getInstance () static
Returns the instance of a NullFactory.
Returns
NullFactory instance
Definition at line 31 of file null_factory.cpp.
Referenced by GT::GTL::NullCondition::getCondition(), and GT::GTL::ErrorCondition::getCondition().
{
     static NullFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/routines/null_factory.hpp
src/gt/routines/null_factory.cpp