Game Theory Tools (full documentation): GT::GTL::CheckingConditionDriver Class Reference
GT::GTL::CheckingConditionDriver Class Reference final
Implementation used for handling Conditions via CheckingDriver.
#include <checking_condition_driver.hpp>
Public Member Functions
virtual ConditionPtr * informationSetChoosed (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *informationSetPtr, const ObjectPtr *strategyPtr) const override
Create condition for Player choosing strategy in information set.
virtual ConditionPtr * informationSetWithin (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *informationSetPtr, const ObjectsPtr *strategiesPtr) const override
Create condition for Player limiting allowed strategies in information set.
virtual ConditionPtr * playerChoosed (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *strategyPtr) const override
Create condition for Player choosing strategy.
virtual ConditionPtr * playerWithin (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectsPtr *strategiesPtr) const override
Create condition for Player limiting allowed strategies.
virtual Message toString () const override
CheckingConditionDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
bool isPlayerOrParam (const Object &object) const
Whether Object is Player or Param.
bool hasIdentifier (const Object &object) const
Whether Object stores Identifier.
Detailed Description
Implementation used for handling Conditions via CheckingDriver.
Performs only syntax/type checking on Conditions' tokens.
Author
Mateusz Kubuszok
See Also
CheckingDriver
ConditionDriver
Definition at line 42 of file checking_condition_driver.hpp.
Member Function Documentation
bool GT::GTL::CheckingConditionDriver::hasIdentifier (const Object & object) const private
Whether Object stores Identifier.
Parameters
object Object to check
Returns
true if Object stores Identifier
Definition at line 239 of file checking_condition_driver.cpp.
References GT::GTL::Param::toParam().
Referenced by informationSetChoosed(), informationSetWithin(), playerChoosed(), and playerWithin().
         {
     const Param& param = object.toParam();
     return param;
 }
ConditionPtr * GT::GTL::CheckingConditionDriver::informationSetChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectPtr * strategyPtr) const override virtual
Create condition for Player choosing strategy in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 31 of file checking_condition_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), hasIdentifier(), isPlayerOrParam(), and GT::GTL::Object::toString().
Referenced by GT::GTL::ExecutionConditionDriver::informationSetChoosed().
         {
     const Object& playerObject         = **playerPtr;
     const Object& informationSetObject = **informationSetPtr;
     const Object& strategyObject       = **strategyPtr;
     if (!isPlayerOrParam(playerObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() + "Object does not define a Player: " + playerObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *playerObject.getInputLocation()
             )
         );
     }
     if (!hasIdentifier(informationSetObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Object does not define a Param with information set: " + informationSetObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *informationSetObject.getInputLocation()
             )
         );
     }
     if (!hasIdentifier(strategyObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Object does not define a Param with strategy: " + strategyObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *strategyObject.getInputLocation()
             )
         );
     }
     return new ConditionPtr(
         setupLocation<Condition>(
             NullFactory::getInstance().createCondition(),
             inputLocation
         )
     );
 }
ConditionPtr * GT::GTL::CheckingConditionDriver::informationSetWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectsPtr * strategiesPtr) const override virtual
Create condition for Player limiting allowed strategies in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 84 of file checking_condition_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), hasIdentifier(), isPlayerOrParam(), and GT::GTL::Object::toString().
Referenced by GT::GTL::ExecutionConditionDriver::informationSetWithin().
         {
     const Object&  playerObject         = **playerPtr;
     const Object&  informationSetObject = **informationSetPtr;
     const Objects& strategiesObjects    = **strategiesPtr;
     if (!isPlayerOrParam(playerObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() + "Object does not define a Player: " + playerObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *playerObject.getInputLocation()
             )
         );
     }
     if (!hasIdentifier(informationSetObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Object does not define a Param with information set: " + informationSetObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *informationSetObject.getInputLocation()
             )
         );
     }
     for (const ObjectPtr& strategy : strategiesObjects) {
         const Object& strategyObject = *strategy;
         if (!hasIdentifier(strategyObject)) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Object does not define a Param with strategy: " + strategyObject.toString();
             return new ConditionPtr(
                 setupLocation<Condition>(
                     ErrorFactory::getInstance().createCondition(errorMessage),
                     *strategyObject.getInputLocation()
                 )
             );
         }
     }
     return new ConditionPtr(
         setupLocation<Condition>(
             NullFactory::getInstance().createCondition(),
             inputLocation
         )
     );
 }
bool GT::GTL::CheckingConditionDriver::isPlayerOrParam (const Object & object) const private
Whether Object is Player or Param.
Parameters
object Object to check
Returns
true if Object is either Object or Param
Definition at line 227 of file checking_condition_driver.cpp.
References GT::GTL::Param::toParam(), and GT::GTL::Player::toPlayer().
Referenced by informationSetChoosed(), informationSetWithin(), playerChoosed(), and playerWithin().
         {
     if (!object)
         return false;
     const Player& player = object.toPlayer();
     const Param&  param  = object.toParam();
     return (player || param);
 }
ConditionPtr * GT::GTL::CheckingConditionDriver::playerChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * strategyPtr) const override virtual
Create condition for Player choosing strategy.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 140 of file checking_condition_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), hasIdentifier(), isPlayerOrParam(), and GT::GTL::Object::toString().
Referenced by GT::GTL::ExecutionConditionDriver::playerChoosed().
         {
     const Object& playerObject   = **playerPtr;
     const Object& strategyObject = **strategyPtr;
     if (!isPlayerOrParam(playerObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() + "Object does not define a Player: " + playerObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *playerObject.getInputLocation()
             )
         );
     }
     if (!hasIdentifier(strategyObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Object does not define a Param with strategy: " + strategyObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *strategyObject.getInputLocation()
             )
         );
     }
     return new ConditionPtr(
         setupLocation<Condition>(
             NullFactory::getInstance().createCondition(),
             inputLocation
         )
     );
 }
ConditionPtr * GT::GTL::CheckingConditionDriver::playerWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectsPtr * strategiesPtr) const override virtual
Create condition for Player limiting allowed strategies.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 179 of file checking_condition_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), hasIdentifier(), isPlayerOrParam(), and GT::GTL::Object::toString().
Referenced by GT::GTL::ExecutionConditionDriver::playerWithin().
         {
     const Object&  playerObject      = **playerPtr;
     const Objects& strategiesObjects = **strategiesPtr;
     if (!isPlayerOrParam(playerObject)) {
         // TODO: create MessageFactory
         Message errorMessage = Message() + "Object does not define a Player: " + playerObject.toString();
         return new ConditionPtr(
             setupLocation<Condition>(
                 ErrorFactory::getInstance().createCondition(errorMessage),
                 *playerObject.getInputLocation()
             )
         );
     }
     for (const ObjectPtr& strategy : strategiesObjects) {
         const Object& strategyObject = *strategy;
         if (!hasIdentifier(strategyObject)) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Object does not define a Param with strategy: " + strategyObject.toString();
             return new ConditionPtr(
                 setupLocation<Condition>(
                     ErrorFactory::getInstance().createCondition(errorMessage),
                     *strategyObject.getInputLocation()
                 )
             );
         }
     }
     return new ConditionPtr(
         setupLocation<Condition>(
             NullFactory::getInstance().createCondition(),
             inputLocation
         )
     );
 }
Message GT::GTL::CheckingConditionDriver::toString () const override virtual
CheckingConditionDriver's Message.
Returns
Message
Implements GT::GTL::ConditionDriver.
Definition at line 221 of file checking_condition_driver.cpp.
{
     return Message("CheckingConditionDriver");
 }
The documentation for this class was generated from the following files:
src/gt/gtl/checking_condition_driver.hpp
src/gt/gtl/checking_condition_driver.cpp