Game Theory Tools (full documentation): GT::GTL::ErrorParam Class Reference
GT::GTL::ErrorParam Class Reference final
Error Param for handling invalid situations.
#include <param.hpp>
Public Member Functions
ErrorParam (const Message errorMessage)
virtual const ObjectPtr getObject (const Context &) const override
Returns Object for Context.
virtual const ObjectPtr getObject (const Context &, VisitedIdentifiers &) const override
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &) const override
Returns Number for context.
virtual const NumberPtr getNumber (const Context &, VisitedIdentifiers &) const override
Returns Number for context.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns message about object.
Public Member Functions inherited from GT::GTL::Param
Param ()
Default constructor.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const override
Finds referred Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const override
Finds referred Objects' property for giver conditions and returns it as a Result.
virtual operator const Param & () const override
Explicit cast to Param type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual operator const Game & () const
Explicit cast to Game type.
virtual operator const Player & () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Message message
Error message.
Additional Inherited Members
Public Types inherited from GT::GTL::Param
typedef set< Identifier > VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Param
void checkVisitedIdentifiers (const VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Checks whether visited Identifiers contain current one.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Error Param for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 221 of file param.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorParam::ErrorParam (const Message errorMessage) inline
Definition at line 228 of file param.hpp.
       :
         message(errorMessage)
         {}
Member Function Documentation
virtual const NumberPtr GT::GTL::ErrorParam::getNumber (const Context & context) const inline override virtual
Returns Number for context.
Parameters
context Context with values
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented from GT::GTL::Param.
Definition at line 247 of file param.hpp.
References GT::Model::NullFactory::createNumber(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumber();
     }
virtual const NumberPtr GT::GTL::ErrorParam::getNumber (const Context & context, VisitedIdentifiers & visitedIdentifiers) const inline override virtual
Returns Number for context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 253 of file param.hpp.
References GT::Model::NullFactory::createNumber(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumber();
     }
virtual const ObjectPtr GT::GTL::ErrorParam::getObject (const Context & context) const inline override virtual
Returns Object for Context.
Parameters
context Context with values
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented from GT::GTL::Param.
Definition at line 234 of file param.hpp.
References GT::GTL::NullFactory::createObject(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createObject();
     }
virtual const ObjectPtr GT::GTL::ErrorParam::getObject (const Context & context, VisitedIdentifiers & visitedIdentifiers) const inline override virtual
Returns Object for Context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Implements GT::GTL::Param.
Definition at line 240 of file param.hpp.
References GT::GTL::NullFactory::createObject(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createObject();
     }
virtual bool GT::GTL::ErrorParam::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 260 of file param.hpp.
{
         return false;
     }
virtual Message GT::GTL::ErrorParam::toString () const inline override virtual
Returns message about object.
Returns
generic Message
Reimplemented from GT::GTL::Object.
Definition at line 264 of file param.hpp.
References message.
{
         return message;
     }
Member Data Documentation
const Message GT::GTL::ErrorParam::message private
Error message.
Definition at line 225 of file param.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/param.hpp