Game Theory Tools (full documentation): GT::Routines::InformationSetChoiceRoutineConfig Class Reference
GT::Routines::InformationSetChoiceRoutineConfig Class Reference abstract
Contains information about available choices for each information set.
#include <information_set_choice_routine_config.hpp>
Public Member Functions
InformationSetChoiceRoutineConfig (const ExtensiveDataNodePtr extensiveGameRoot)
Initiates config with ExtensiveData's tree root.
InformationSetChoiceRoutineConfig & requireChoiceExactly (const Identifier &player, const Identifier &informationSet, const Identifier &chosenStrategy)
Trims availabe choices for information set for just one.
InformationSetChoiceRoutineConfig & requireChoiceWithin (const Identifier &player, const Identifier &informationSet, const Identifiers &allowedStrategies)
Trims availabe choices for information set to passed ones.
const Identifiers & getAvailableStrategies (const Identifier &player, const Identifier &informationSet) const
Returns available choices for given Player and information set.
virtual bool isValid () const override=0
Whether current configuration is valid.
Public Member Functions inherited from GT::Routines::RoutineConfig
virtual Message toString () const override=0
Returns RoutineConfig's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier,
Identifiers > AvailableForSets
Contains information about strategies available for each set.
typedef map< Identifier,
AvailableForSets > AvailableForPlayersAndSets
Contains information about strategies/information sets available for each Player.
Private Attributes
AvailableForPlayersAndSets availableForPlayersAndSets
Available strategies for information sets of each Player.
Detailed Description
Contains information about available choices for each information set.
Author
Mateusz Kubuszok
See Also
InformationSetChoiceCondition
InformationSetRangeCondition
Definition at line 47 of file information_set_choice_routine_config.hpp.
Member Typedef Documentation
typedef map<Identifier, AvailableForSets> GT::Routines::InformationSetChoiceRoutineConfig::AvailableForPlayersAndSets private
Contains information about strategies/information sets available for each Player.
Definition at line 56 of file information_set_choice_routine_config.hpp.
typedef map<Identifier, Identifiers> GT::Routines::InformationSetChoiceRoutineConfig::AvailableForSets private
Contains information about strategies available for each set.
Definition at line 51 of file information_set_choice_routine_config.hpp.
Constructor & Destructor Documentation
GT::Routines::InformationSetChoiceRoutineConfig::InformationSetChoiceRoutineConfig (const ExtensiveDataNodePtr extensiveGameRoot) explicit
Initiates config with ExtensiveData's tree root.
Parameters
extensiveGameRoot root of Data tree
Definition at line 38 of file information_set_choice_routine_config.cpp.
References availableForPlayersAndSets.
   :
     availableForPlayersAndSets()
 {
     const ExtensiveGamePositionsHelper positionsHelper(extensiveGameRoot);
     const IdentifiersPtr possiblePlayers = positionsHelper.getPossiblePlayers();
     for (const IdentifierPtr& playerPtr : *possiblePlayers) {
         const Identifier& player = *playerPtr;
         AvailableForSets     availableForSets;
         const IdentifiersPtr informationSets = positionsHelper.getPossibleInformationSetsForPlayer(player);
         for (const IdentifierPtr& informationSetPtr : *informationSets) {
             const Identifier& informationSet = *informationSetPtr;
             Identifiers choicesForSet(
                 *positionsHelper.getInformationSetForPlayer(player, informationSet).getChoices()
             );
             availableForSets.insert( AvailableForSets::value_type(informationSet, choicesForSet) );
         }
         availableForPlayersAndSets.insert( AvailableForPlayersAndSets::value_type(player, availableForSets) );
     }
 }
Member Function Documentation
const Identifiers & GT::Routines::InformationSetChoiceRoutineConfig::getAvailableStrategies (const Identifier & player, const Identifier & informationSet) const
Returns available choices for given Player and information set.
Parameters
player Player's name
informationSet information set's name
Returns
available strategies
Exceptions
InvalidPlayerChoice thrown if Player's or information set's name is invalid
Definition at line 118 of file information_set_choice_routine_config.cpp.
References availableForPlayersAndSets, GT::Routines::ExceptionFactory::getInstance(), GT::Routines::ExceptionFactory::informationSetNotFound(), and GT::Routines::ExceptionFactory::playerNotFound().
Referenced by GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen(), requireChoiceExactly(), and requireChoiceWithin().
         {
     if (!availableForPlayersAndSets.count(player))
         throw ExceptionFactory::getInstance().playerNotFound(player);
     const AvailableForSets& informationSets = availableForPlayersAndSets.at(player);
     if (!informationSets.count(informationSet))
         throw ExceptionFactory::getInstance().informationSetNotFound(player, informationSet);
     return informationSets.at(informationSet);
 }
bool GT::Routines::InformationSetChoiceRoutineConfig::isValid () const override pure virtual
Whether current configuration is valid.
Returns
true if current configuration is valid
Implements GT::Routines::RoutineConfig.
Implemented in GT::Routines::ExtensivePureEquilibriumRoutineConfig.
Definition at line 132 of file information_set_choice_routine_config.cpp.
References availableForPlayersAndSets.
Referenced by GT::Routines::ExtensivePureEquilibriumRoutineConfig::isValid().
{
     for (const AvailableForSets availableForSets : availableForPlayersAndSets | map_values)
         for (const Identifiers strategies : availableForSets | map_values)
             if (strategies.empty())
                 return false;
     return true;
 }
InformationSetChoiceRoutineConfig & GT::Routines::InformationSetChoiceRoutineConfig::requireChoiceExactly (const Identifier & player, const Identifier & informationSet, const Identifier & chosenStrategy)
Trims availabe choices for information set for just one.
Parameters
player Player's name
informationSet information set's name
chosenStrategy chosen strategy
Returns
reference to itself for chainging
Exceptions
InvalidPlayerChoice thrown if Player's or information set's name is invalid
Definition at line 65 of file information_set_choice_routine_config.cpp.
References getAvailableStrategies().
Referenced by GT::Routines::InformationSetChoiceCondition::configureRoutine().
   {
     Identifiers& availableStrategies =
         const_cast<Identifiers&>(getAvailableStrategies(player, informationSet));
     // removes all strategies not equal to the chosen
     availableStrategies.erase(
         remove_if(
             availableStrategies.begin(),
             availableStrategies.end(),
             [chosenStrategy](const IdentifierPtr& checkedStrategy) {
                 return (*checkedStrategy) != chosenStrategy;
             }
         )
     );
     return *this;
 }
InformationSetChoiceRoutineConfig & GT::Routines::InformationSetChoiceRoutineConfig::requireChoiceWithin (const Identifier & player, const Identifier & informationSet, const Identifiers & allowedStrategies)
Trims availabe choices for information set to passed ones.
Parameters
player Player's name
informationSet information set's name
allowedStrategies allowed strategies
Returns
reference to itself for chainging
Exceptions
InvalidPlayerChoice thrown if Player's or information set's name is invalid
Definition at line 87 of file information_set_choice_routine_config.cpp.
References getAvailableStrategies().
Referenced by GT::Routines::InformationSetRangeCondition::configureRoutine().
   {
     Identifiers& availableStrategies =
         const_cast<Identifiers&>(getAvailableStrategies(player, informationSet));
     // removes all not allowed
     availableStrategies.erase(
         remove_if(
             availableStrategies.begin(),
             availableStrategies.end(),
             [allowedStrategies](const IdentifierPtr& checkedStrategy) {
                 // check if such strategy is NOT present among allowedStrategies and thus can be removed
                 bool result = allowedStrategies.empty() || allowedStrategies.end() == find_if(
                     allowedStrategies.begin(),
                     allowedStrategies.end(),
                     [checkedStrategy](const IdentifierPtr& allowedStrategy) {
                         return *checkedStrategy == *allowedStrategy;
                     }
                 );
                 return result;
             }
         ),
         availableStrategies.end()
     );
     return *this;
 }
Member Data Documentation
AvailableForPlayersAndSets GT::Routines::InformationSetChoiceRoutineConfig::availableForPlayersAndSets private
Available strategies for information sets of each Player.
Definition at line 61 of file information_set_choice_routine_config.hpp.
Referenced by getAvailableStrategies(), InformationSetChoiceRoutineConfig(), and isValid().
The documentation for this class was generated from the following files:
src/gt/routines/information_set_choice_routine_config.hpp
src/gt/routines/information_set_choice_routine_config.cpp