language:       cpp
before_install:
              - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
              - sudo add-apt-repository ppa:boost-latest/ppa -y
              - sudo apt-get update -qq
install:
              - if [ "$CXX" = "g++" ]; then
              -   sudo apt-get install gcc-4.8 g++-4.8
              -   export CXX="g++-4.8" CC="gcc-4.8"
              -   sudo apt-get install libboost1.48-dev libboost-program-options1.48-dev libboost-program-options1.48.0 libboost-test1.48-dev libboost-test1.48.0
              - fi
              - if [ "$CXX" = "clang++" ]; then
              -   sudo apt-get install libboost1.54-dev libboost-program-options1.54-dev libboost-program-options1.54.0 libboost-test1.54-dev libboost-test1.54.0
              - fi
              - sudo apt-get install flex bison libgmp-dev glpk scons valgrind
compiler:
              - gcc
              - clang
script:       - scons -Q buildExecutables --implicit-deps-unchanged --jobs 4
              - valgrind --leak-check=full --error-exitcode=1 bin/ModelsTests
              - valgrind --leak-check=full --error-exitcode=1 bin/RoutinesTests
              - valgrind --leak-check=full --error-exitcode=1 bin/GTLTests
              - valgrind --leak-check=full --error-exitcode=1 bin/ProgramsTests
              - valgrind --leak-check=full --error-exitcode=1 bin/gtl_program -i examples/strategic_form_game.gtl
              - valgrind --leak-check=full --error-exitcode=1 bin/gtl_program -i examples/extensive_form_game.gtl
              - valgrind --leak-check=full --error-exitcode=1 bin/gtl_program -i examples/properties_querying.gtl
branches:
  except:       gh-pages
notifications:
  email:
    on_success: change
    on_failure: always
