Game Theory Tools (full documentation): GT::GTL::NullGame Class Reference
GT::GTL::NullGame Class Reference final
Null Game for handling invalid situations.
#include <game.hpp>
Public Member Functions
NullGame ()
virtual ResultPtr pureEquilibrium (const Context &, const Conditions &) const override
Search pure Nash equilibrium for given conditions.
virtual ResultPtr mixedEquilibrium (const Context &, const Conditions &) const override
Search mixed Nash equilibrium for given conditions.
virtual ResultPtr behaviorEquilibrium (const Context &, const Conditions &) const override
Search behavior Nash equilibrium for given conditions.
virtual const IdentifierPtr getGameType () const override
Returns game type name.
virtual Message serialize () const override
Returns serialized Message for a Game.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message about Game.
Public Member Functions inherited from GT::GTL::Game
Game (const Model::GamePtr game)
Initiates Object with Game model.
Game (const Model::GamePtr game, const IdentifierPtr gameType)
Initiates Object with Game model.
virtual const Game & toGame () const override
Explicit cast to Game type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const
Finds Objects' property for giver Conditions and returns it as a Result.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual const Param & toParam () const
Explicit cast to Param type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Null Game for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 146 of file game.hpp.
Constructor & Destructor Documentation
GT::GTL::NullGame::NullGame () inline
Definition at line 148 of file game.hpp.
                :
         Game(Model::NullFactory::getInstance().createGame())
         {}
Member Function Documentation
virtual ResultPtr GT::GTL::NullGame::behaviorEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search behavior Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 166 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual const IdentifierPtr GT::GTL::NullGame::getGameType () const inline override virtual
Returns game type name.
Game type used during game definition: EXTENSIVE, STRATEGIC.
Returns
game type Identifier
Reimplemented from GT::GTL::Game.
Definition at line 173 of file game.hpp.
References GT::createIdentifierPtr().
{
         return createIdentifierPtr("NULL");
     }
virtual bool GT::GTL::NullGame::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 181 of file game.hpp.
{
         return false;
     }
virtual ResultPtr GT::GTL::NullGame::mixedEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search mixed Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 159 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::GTL::NullGame::pureEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search pure Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 152 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual Message GT::GTL::NullGame::serialize () const inline override virtual
Returns serialized Message for a Game.
Returns
serialization result
Reimplemented from GT::GTL::Game.
Definition at line 177 of file game.hpp.
References GT::createMessage().
{
         return createMessage("NULL GAME");
     }
virtual Message GT::GTL::NullGame::toString () const inline override virtual
Returns Message about Game.
Returns
Game's state
Reimplemented from GT::GTL::Game.
Definition at line 185 of file game.hpp.
{
         return Message("NullGame");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/game.hpp