Game Theory Tools (full documentation): GT::GTL::Scanner Class Reference
GT::GTL::Scanner Class Reference
Scans for tokens declared by Parser class in given InputStream.
#include <scanner.hpp>
Public Member Functions
Scanner (InputStream *inputStream)
Initiates Scanner with input stream that serves as data source.
bool isInteractive () const
Whether scanner is currently interactive.
void setInteractive (bool isInteractive)
Set whether scanner should be interactive or not.
virtual int lex (Parser::semantic_type *newlval, Parser::location_type &newlocation)
Scans for next token.
Private Member Functions
int lex ()
Actual lexer/scanner function.
Private Attributes
Parser::semantic_type * lval
Field used during token scanning - contains actual value of parsed chain.
Detailed Description
Scans for tokens declared by Parser class in given InputStream.
Its content is generated by Flex (Lex?) from scanner.yy class. Acts as a more convinient wrapper for GTLFlexLexer.
Author
Mateusz Kubuszok
See Also
Parser
::GTLFlexLexer
Definition at line 65 of file scanner.hpp.
Constructor & Destructor Documentation
GT::GTL::Scanner::Scanner (InputStream * inputStream) explicit
Initiates Scanner with input stream that serves as data source.
Parameters
inputStream input stream initiating Scanner
Definition at line 2259 of file scanner.cpp.
   :
     GTLFlexLexer(inputStream),
     lval(nullptr)
     {}
Member Function Documentation
bool GT::GTL::Scanner::isInteractive () const
Whether scanner is currently interactive.
Returns
true if current buffer is set and it's interactive
Definition at line 2266 of file scanner.cpp.
References YY_CURRENT_BUFFER.
{
     return YY_CURRENT_BUFFER && YY_CURRENT_BUFFER->yy_is_interactive;
 }
int GT::GTL::Scanner::lex (Parser::semantic_type * newlval, Parser::location_type & newlocation) virtual
Scans for next token.
Parameters
newlval initiates next scanning with value
newlocation location to fill with positions
Returns
returns number of next token
Definition at line 2278 of file scanner.cpp.
References GT::GTL::location::begin, GT::GTL::position::columns(), GT::GTL::location::end, lex(), GT::GTL::position::lines(), and lval.
Referenced by yylex().
   {
     lval = newlval;
     Index firstLine   = yylineno;
     Index firstColumn = 1; // TODO
     int result = lex();
     Index lastLine   = yylineno;
     Index lastColumn = 1; // TODO
     newlocation.begin.lines(firstLine-1);
     newlocation.begin.columns(firstColumn-1);
     newlocation.end.lines(lastLine-1);
     newlocation.end.columns(lastColumn-1);
     return result;
 }
int GT::GTL::Scanner::lex () private
Actual lexer/scanner function.
Uses source defined by the constructor. Its body is generated from scanner.yy file by Flex with YY_DECL macroinstruction.
Returns
value used for communicating with Parser
Referenced by lex().
void GT::GTL::Scanner::setInteractive (bool isInteractive)
Set whether scanner should be interactive or not.
Interactive scanner behaves better (?) in a console but is slower than non-interactive one.
Parameters
isInteractive true if scanner should be interactive
Definition at line 2270 of file scanner.cpp.
References yy_set_interactive.
   {
     yy_set_interactive(isNowInteractive);
 }
Member Data Documentation
Parser::semantic_type* GT::GTL::Scanner::lval private
Field used during token scanning - contains actual value of parsed chain.
Definition at line 69 of file scanner.hpp.
Referenced by lex().
The documentation for this class was generated from the following files:
include/gt/gtl/scanner.hpp
src/gt/gtl/scanner.cpp