Game Theory Tools (full documentation): GT::Model::StrategicGame Class Reference
GT::Model::StrategicGame Class Reference final
Defnies StrategicGame.
#include <strategic_game.hpp>
Public Member Functions
StrategicGame (const PlayersPtr newPlayers, const StrategicDataPtr newData)
Initiates Game with Players and Data.
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual const DataAccessorPtr getData () const override
Returns Game's Data.
virtual Message toString () const override
Returns StrategicGame's Message.
Public Member Functions inherited from GT::Model::Game
virtual bool isEqual (const Root &root) const override
Defines equality relation.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const PlayersPtr players
Players.
const StrategicDataPtr data
Game's Data.
Detailed Description
Defnies StrategicGame.
Games in this form should have all coordinates filled with payoffs. Since all Players and their strategies are known beforehand, positions can also be hashed to Indexes with StrategicGamePositionsHelper.
Author
Mateusz Kubuszok
See Also
StrategicData
StrategicGamePositionsHelper
Definition at line 43 of file strategic_game.hpp.
Constructor & Destructor Documentation
GT::Model::StrategicGame::StrategicGame (const PlayersPtr newPlayers, const StrategicDataPtr newData)
Initiates Game with Players and Data.
Parameters
newPlayers Players' definitions
newData Data for Game
Definition at line 31 of file strategic_game.cpp.
   :
     players(newPlayers),
     data(newData)
     {}
Member Function Documentation
const DataAccessorPtr GT::Model::StrategicGame::getData () const override virtual
Returns Game's Data.
Returns
Game's Data
Implements GT::Model::Game.
Definition at line 43 of file strategic_game.cpp.
References data.
{
     return DataAccessorPtr(new StrategicDataAccessor(data));
 }
const PlayersPtr GT::Model::StrategicGame::getPlayers () const override virtual
Returns Players' definitions.
Returns
Players' denifitions
Implements GT::Model::Game.
Definition at line 39 of file strategic_game.cpp.
References players.
{
     return players;
 }
Message GT::Model::StrategicGame::toString () const override virtual
Returns StrategicGame's Message.
Returns
Message
Implements GT::Model::Game.
Definition at line 47 of file strategic_game.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), data, and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name      = createIdentifierPtr("Strategic Game");
     const MessagePtr           subresult = createMessagePtr(data->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, subresult).build()->getResult();
 }
Member Data Documentation
const StrategicDataPtr GT::Model::StrategicGame::data private
Game's Data.
Definition at line 51 of file strategic_game.hpp.
Referenced by getData(), and toString().
const PlayersPtr GT::Model::StrategicGame::players private
Players.
Definition at line 47 of file strategic_game.hpp.
Referenced by getPlayers().
The documentation for this class was generated from the following files:
src/gt/model/strategic_game.hpp
src/gt/model/strategic_game.cpp