Game Theory Tools (full documentation): GT::Routines::SelectableStrategiesRoutine Class Reference
GT::Routines::SelectableStrategiesRoutine Class Reference
Interface used to setup available Players.
#include <selectable_strategies_routine.hpp>
Public Member Functions
SelectableStrategiesRoutine (const PlayersPtr players)
Initiates Routine with available Players.
const PlayersPtr getAvailablePlayers () const
Obtains list of currently available Players.
IdentifiersPtr getAvailableStrategiesForPlayer (const Identifier &player) const
Returna available strategies for a Player.
void setAvailableStrategiesForPlayer (const Identifier &player, IdentifiersPtr strategies)
Sets available strategies for given Players.
Public Member Functions inherited from GT::Routines::Routine
virtual ResultPtr findResultFor (const GamePtr game, const ConditionsPtr conditions) const =0
Calculates Result for given Game and Conditions.
virtual Message toString () const override=0
Returns Routine's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier,
IdentifiersPtr > AvailableStrategies
Map containing available strategies.
Private Attributes
const PlayersPtr players
Available Players.
AvailableStrategies availableStrategies
Available strategies.
Detailed Description
Interface used to setup available Players.
Author
Mateusz Kubuszok
See Also
Routine
Definition at line 43 of file selectable_strategies_routine.hpp.
Member Typedef Documentation
typedef map<Identifier, IdentifiersPtr> GT::Routines::SelectableStrategiesRoutine::AvailableStrategies private
Map containing available strategies.
Definition at line 47 of file selectable_strategies_routine.hpp.
Constructor & Destructor Documentation
GT::Routines::SelectableStrategiesRoutine::SelectableStrategiesRoutine (const PlayersPtr players) explicit
Initiates Routine with available Players.
Parameters
players Players definitions
Definition at line 31 of file selectable_strategies_routine.cpp.
References availableStrategies, and players.
   :
     players(definedPlayers),
     availableStrategies()
 {
     for (const Players::value_type& playerPair : *players) {
         const Identifier   playerName = playerPair.first;
         const Identifiers& strategies = *playerPair.second->getStrategies();
         IdentifiersPtr availableStrategiesForPlayer(new Identifiers(strategies));
         availableStrategies.insert( AvailableStrategies::value_type(
             playerName,
             availableStrategiesForPlayer
         ) );
     }
 }
Member Function Documentation
const PlayersPtr GT::Routines::SelectableStrategiesRoutine::getAvailablePlayers () const
Obtains list of currently available Players.
Returns
available Players
Definition at line 50 of file selectable_strategies_routine.cpp.
References players.
{
     return players;
 }
IdentifiersPtr GT::Routines::SelectableStrategiesRoutine::getAvailableStrategiesForPlayer (const Identifier & player) const
Returna available strategies for a Player.
Parameters
player Player for which strategies are obtaines
Returns
currently available strategies
Definition at line 54 of file selectable_strategies_routine.cpp.
References availableStrategies, GT::Routines::ExceptionFactory::getInstance(), and GT::Routines::ExceptionFactory::playerNotFound().
Referenced by GT::Routines::PlayerChoiceCondition::configureRoutine().
         {
     if (!availableStrategies.count(player))
         throw ExceptionFactory::getInstance().playerNotFound(player);
     return availableStrategies.at(player);
 }
void GT::Routines::SelectableStrategiesRoutine::setAvailableStrategiesForPlayer (const Identifier & player, IdentifiersPtr strategies)
Sets available strategies for given Players.
Parameters
player Player for which strategies are set up
strategies avialable strategies for Player
Definition at line 63 of file selectable_strategies_routine.cpp.
References availableStrategies, GT::Routines::ExceptionFactory::getInstance(), and GT::Routines::ExceptionFactory::playerNotFound().
   {
     if (!availableStrategies.count(player))
         throw ExceptionFactory::getInstance().playerNotFound(player);
     availableStrategies[player] = strategies;
 }
Member Data Documentation
AvailableStrategies GT::Routines::SelectableStrategiesRoutine::availableStrategies private
Available strategies.
Definition at line 57 of file selectable_strategies_routine.hpp.
Referenced by getAvailableStrategiesForPlayer(), SelectableStrategiesRoutine(), and setAvailableStrategiesForPlayer().
const PlayersPtr GT::Routines::SelectableStrategiesRoutine::players private
Available Players.
Definition at line 52 of file selectable_strategies_routine.hpp.
Referenced by getAvailablePlayers(), and SelectableStrategiesRoutine().
The documentation for this class was generated from the following files:
src/gt/routines/selectable_strategies_routine.hpp
src/gt/routines/selectable_strategies_routine.cpp