Game Theory Tools (full documentation): GT::GTL::Game Class Reference
GT::GTL::Game Class Reference
Defines Game.
#include <game.hpp>
Public Member Functions
Game (const Model::GamePtr game)
Initiates Object with Game model.
Game (const Model::GamePtr game, const IdentifierPtr gameType)
Initiates Object with Game model.
virtual ResultPtr pureEquilibrium (const Context &context, const Conditions &conditions) const
Search pure Nash equilibrium for given conditions.
virtual ResultPtr mixedEquilibrium (const Context &context, const Conditions &conditions) const
Search mixed Nash equilibrium for given conditions.
virtual ResultPtr behaviorEquilibrium (const Context &context, const Conditions &conditions) const
Search behavior Nash equilibrium for given conditions.
virtual const IdentifierPtr getGameType () const
Returns game type name.
virtual Message serialize () const override
Returns serialized Message for a Game.
virtual Message toString () const override
Returns Message about Game.
virtual const Game & toGame () const override
Explicit cast to Game type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const
Finds Objects' property for giver Conditions and returns it as a Result.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual const Param & toParam () const
Explicit cast to Param type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Model::GamePtr game
Model Game implementation.
const IdentifierPtr gameType
Game type.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Defines Game.
Game Object can be later used to Query it or to store it into Context for later use.
Author
Mateusz Kubuszok
See Also
GameDriver
Parser
Definition at line 42 of file game.hpp.
Constructor & Destructor Documentation
GT::GTL::Game::Game (const Model::GamePtr game) explicit
Initiates Object with Game model.
Parameters
game Model Game implementation
Definition at line 39 of file game.cpp.
References GT::GTL::Object::registerProperty().
   :
     Object(createIdentifier("Game")),
     game(gameImplementation),
     gameType(createIdentifierPtr(""))
 {
     registerProperty(
         Identifier("pure_equilibrium"),     ObjectPropertyPtr(new GamePureEquilibriumProperty(this))
     );
     registerProperty(
         Identifier("mixed_equilibrium"),    ObjectPropertyPtr(new GameMixedEquilibriumProperty(this))
     );
     registerProperty(
         Identifier("behavior_equilibrium"), ObjectPropertyPtr(new GameBehaviorEquilibriumProperty(this))
     );
 }
GT::GTL::Game::Game (const Model::GamePtr game, const IdentifierPtr gameType)
Initiates Object with Game model.
Parameters
game Model Game implementation
gameType type of Game: "STRATEGIC" or "EXTENSIVE"
Definition at line 57 of file game.cpp.
References GT::GTL::Object::registerProperty().
   :
     Object(createIdentifier("Game")),
     game(gameImplementation),
     gameType(gameTypeName)
 {
     registerProperty(
         Identifier("pure_equilibrium"),     ObjectPropertyPtr(new GamePureEquilibriumProperty(this))
     );
     registerProperty(
         Identifier("mixed_equilibrium"),    ObjectPropertyPtr(new GameMixedEquilibriumProperty(this))
     );
     registerProperty(
         Identifier("behavior_equilibrium"), ObjectPropertyPtr(new GameBehaviorEquilibriumProperty(this))
     );
 }
Member Function Documentation
ResultPtr GT::GTL::Game::behaviorEquilibrium (const Context & context, const Conditions & conditions) const virtual
Search behavior Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 104 of file game.cpp.
References GT::Routines::RoutineFactory::behaviourStrategyEquilibriumFindingRoutineFor(), game, and GT::Routines::RoutineFactory::getInstance().
Referenced by GT::GTL::GameBehaviorEquilibriumProperty::findForConditions().
         {
     Routines::RoutinePtr routine =
         Routines::RoutineFactory::getInstance().behaviourStrategyEquilibriumFindingRoutineFor(game);
     Routines::ConditionsPtr routineConditions(new Routines::Conditions());
     for (const ConditionPtr& condition : conditions)
         routineConditions->push_back(condition->getCondition(context));
     return routine->findResultFor(game, routineConditions);
 }
const IdentifierPtr GT::GTL::Game::getGameType () const virtual
Returns game type name.
Game type used during game definition: EXTENSIVE, STRATEGIC.
Returns
game type Identifier
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 118 of file game.cpp.
References gameType.
{
     return gameType;
 }
ResultPtr GT::GTL::Game::mixedEquilibrium (const Context & context, const Conditions & conditions) const virtual
Search mixed Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 90 of file game.cpp.
References game, GT::Routines::RoutineFactory::getInstance(), and GT::Routines::RoutineFactory::mixedStrategyEquilibriumFindingRoutineFor().
Referenced by GT::GTL::GameMixedEquilibriumProperty::findForConditions().
         {
     Routines::RoutinePtr routine =
         Routines::RoutineFactory::getInstance().mixedStrategyEquilibriumFindingRoutineFor(game);
     Routines::ConditionsPtr routineConditions(new Routines::Conditions());
     for (const ConditionPtr& condition : conditions)
         routineConditions->push_back(condition->getCondition(context));
     return routine->findResultFor(game, routineConditions);
 }
ResultPtr GT::GTL::Game::pureEquilibrium (const Context & context, const Conditions & conditions) const virtual
Search pure Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 76 of file game.cpp.
References game, GT::Routines::RoutineFactory::getInstance(), and GT::Routines::RoutineFactory::pureStrategyEquilibriumFindingRoutineFor().
Referenced by GT::GTL::GamePureEquilibriumProperty::findForConditions().
         {
     Routines::RoutinePtr routine =
         Routines::RoutineFactory::getInstance().pureStrategyEquilibriumFindingRoutineFor(game);
     Routines::ConditionsPtr routineConditions(new Routines::Conditions());
     for (const ConditionPtr& condition : conditions)
         routineConditions->push_back(condition->getCondition(context));
     return routine->findResultFor(game, routineConditions);
 }
Message GT::GTL::Game::serialize () const override virtual
Returns serialized Message for a Game.
Returns
serialization result
Reimplemented from GT::GTL::ValidableSymbol.
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 122 of file game.cpp.
References GT::GTL::ValidableSymbol::addIndent(), game, gameType, and GT::GTL::LazyGameProxy::getPlayersParams().
{
     stringstream result;
     if (!gameType->empty())
         result << *gameType << ' ';
     result << "GAME WITH\n";
     const shared_ptr<LazyGameProxy> lazyGame = dynamic_pointer_cast<LazyGameProxy>(game);
     if (lazyGame) {
         const ObjectsPtr players = lazyGame->getPlayersParams();
         if (players->size()) {
             stringstream subresult;
             bool firstElement = true;
             for (const ObjectPtr& player : *players) {
                 if (!firstElement)
                     subresult << ',' << endl;
                 subresult << player->serialize();
                 firstElement = false;
             }
             result << addIndent(subresult.str()) << endl;
         }
         result << "SUCH AS" << endl;
         stringstream subresult;
         bool firstElement = true;
         for (const CoordinatePtr& coordinate : *lazyGame->getCoordinates()) {
             if (!firstElement)
                 subresult << ',' << endl;
             subresult << coordinate->serialize();
             firstElement = false;
         }
         result << addIndent(subresult.str()) << endl;
     } else
         result << addIndent("!! CANNOT RECOVER DATA !!") << endl;
     result << "END";
     return result.str();
 }
const Game & GT::GTL::Game::toGame () const override virtual
Explicit cast to Game type.
Returns
Game
Reimplemented from GT::GTL::Object.
Definition at line 170 of file game.cpp.
{
     return *this;
 }
Message GT::GTL::Game::toString () const override virtual
Returns Message about Game.
Returns
Game's state
Reimplemented from GT::GTL::Object.
Reimplemented in GT::GTL::ErrorGame, and GT::GTL::NullGame.
Definition at line 166 of file game.cpp.
References game.
{
     return game->toString();
 }
Member Data Documentation
const Model::GamePtr GT::GTL::Game::game private
Model Game implementation.
Definition at line 46 of file game.hpp.
Referenced by behaviorEquilibrium(), mixedEquilibrium(), pureEquilibrium(), serialize(), and toString().
const IdentifierPtr GT::GTL::Game::gameType private
Game type.
Definition at line 51 of file game.hpp.
Referenced by getGameType(), and serialize().
The documentation for this class was generated from the following files:
include/gt/gtl/game.hpp
src/gt/gtl/game.cpp