Game Theory Tools (public API): GT Namespace Reference
GT Namespace Reference
Contains classes and modules related to Nash equilibria calculation.
Namespaces
GTL
Contains classes related to parsing text input as a GTL language.
Model
Contains classes related to storing GT data.
Program
Contains classes related to creating GTL executable.
Routines
Contains classes related to calculating Nash equilibria for given Models.
Typedefs
typedef unsigned int Index
Position in array or storage.
typedef istream InputStream
Input stream alias.
typedef ostream OutputStream
Output stream alias.
typedef string Message
Alias for string used as messages.
typedef shared_ptr< Message > MessagePtr
Smart pointer to Message.
typedef vector< MessagePtr > Messages
Vector of Messages.
typedef shared_ptr< Messages > MessagesPtr
Smart pointer to Messages.
typedef string Identifier
Alias for string used as identifiers.
typedef shared_ptr< Identifier > IdentifierPtr
Smart pointer to Identifier.
typedef vector< IdentifierPtr > Identifiers
Vector of Identifiers.
typedef shared_ptr< Identifiers > IdentifiersPtr
Smart pointer to Identifiers.
typedef mpf_class Number
Alias for multiple precision float class.
typedef shared_ptr< Number > NumberPtr
Smart pointer to Number.
typedef vector< NumberPtr > Numbers
Vector of Numbers.
typedef shared_ptr< Numbers > NumbersPtr
Smart pointer to Numbers.
typedef map< Identifier,
Identifier > Positions
Map of dimension-position pairs.
typedef shared_ptr< Positions > PositionsPtr
Smart pointer to Positions.
Functions
bool operator== (Messages &messages1, Messages &messages2)
Check if Messages are equal.
bool operator!= (Messages &messages1, Messages &messages2)
Check if Messages are different.
bool operator== (Identifiers &identifier1, Identifiers &identifier2)
Check if Identifiers are equal.
bool operator!= (Identifiers &identifier1, Identifiers &identifier2)
Check if Identifiers are different.
bool operator== (Numbers &numbers1, Numbers &numbers2)
Check if Numbers are equal.
bool operator!= (Numbers &numbers1, Numbers &numbers2)
Check if Numbers are different.
bool operator== (Positions &positions1, Positions &positions2)
Check if Positions are equal.
bool operator!= (Positions &positions1, Positions &positions2)
Check if Positions are different.
Message createMessage (Index message)
Creates Message.
Message createMessage (double message)
Creates Message.
Message createMessage (const char *message)
Creates Message.
Message createMessage (string message)
Creates Message.
Message createMessage (shared_ptr< string > message)
Creates Message.
Message createMessage (Number number)
Creates Message.
Message createMessage (NumberPtr number)
Creates Message.
MessagePtr createMessagePtr (Index message)
Creates Message.
MessagePtr createMessagePtr (double message)
Creates Message.
MessagePtr createMessagePtr (const char *message)
Creates Message.
MessagePtr createMessagePtr (string message)
Creates Message.
MessagePtr createMessagePtr (shared_ptr< string > message)
Creates Message.
MessagePtr createMessagePtr (Number number)
Creates Message.
MessagePtr createMessagePtr (NumberPtr number)
Creates Messages.
Messages createMessages ()
Creates Messages.
MessagesPtr createMessagesPtr ()
Creates Messages.
MessagesPtr createMessagesPtr (Messages messages)
Creates Message.
Identifier createIdentifier (Index identifier)
Creates Identifier.
Identifier createIdentifier (const char *identifier)
Creates Identifier.
Identifier createIdentifier (string identifier)
Creates Identifier.
Identifier createIdentifier (shared_ptr< string > identifier)
Creates Identifier.
IdentifierPtr createIdentifierPtr (Index identifier)
Creates Identifier.
IdentifierPtr createIdentifierPtr (const char *identifier)
Creates Identifier.
IdentifierPtr createIdentifierPtr (string identifier)
Creates Identifier.
IdentifierPtr createIdentifierPtr (shared_ptr< string > identifier)
Creates Identifier.
Identifiers createIdentifiers ()
Creates Identifiers.
IdentifiersPtr createIdentifiersPtr ()
Creates Identifier.
IdentifiersPtr createIdentifiersPtr (Identifiers identifiers)
Creates Identifiers.
Number createNumber (int number)
Creates Number.
Number createNumber (float number)
Creates Number.
Number createNumber (double number)
Creates Number.
Number createNumber (string number)
Creates Number.
Number createNumber (shared_ptr< string > number)
Creates Number.
Number createNumber (Number number)
Creates Number.
Number createNumber (NumberPtr number)
Creates Number.
NumberPtr createNumberPtr (int number)
Creates Number.
NumberPtr createNumberPtr (float number)
Creates Number.
NumberPtr createNumberPtr (double number)
Creates Number.
NumberPtr createNumberPtr (string number)
Creates Number.
NumberPtr createNumberPtr (shared_ptr< string > number)
Creates Number.
NumberPtr createNumberPtr (Number number)
Creates Number.
NumberPtr createNumberPtr (NumberPtr number)
Creates Number.
Numbers createNumbers ()
Creates Numbers.
NumbersPtr createNumbersPtr ()
Creates Numbers.
NumbersPtr createNumbersPtr (Numbers numbers)
Creates Numbers.
Positions createPositions ()
Creates Positions.
PositionsPtr createPositionsPtr ()
Creates Positions.
Detailed Description
Contains classes and modules related to Nash equilibria calculation.
GT namespace itself creates some aliases used in nested namespaces responsible for specific tasks. This helps the project to have consistent names and coventions.
Typedef Documentation
typedef string GT::Identifier
Alias for string used as identifiers.
Definition at line 77 of file common.hpp.
typedef shared_ptr<Identifier> GT::IdentifierPtr
Smart pointer to Identifier.
Definition at line 78 of file common.hpp.
typedef vector<IdentifierPtr> GT::Identifiers
Vector of Identifiers.
Definition at line 79 of file common.hpp.
typedef shared_ptr<Identifiers> GT::IdentifiersPtr
Smart pointer to Identifiers.
Definition at line 80 of file common.hpp.
typedef unsigned int GT::Index
Position in array or storage.
Definition at line 67 of file common.hpp.
typedef istream GT::InputStream
Input stream alias.
Definition at line 71 of file common.hpp.
typedef string GT::Message
Alias for string used as messages.
Definition at line 73 of file common.hpp.
typedef shared_ptr<Message> GT::MessagePtr
Smart pointer to Message.
Definition at line 74 of file common.hpp.
typedef vector<MessagePtr> GT::Messages
Vector of Messages.
Definition at line 75 of file common.hpp.
typedef shared_ptr<Messages> GT::MessagesPtr
Smart pointer to Messages.
Definition at line 76 of file common.hpp.
typedef mpf_class GT::Number
Alias for multiple precision float class.
Definition at line 81 of file common.hpp.
typedef shared_ptr<Number> GT::NumberPtr
Smart pointer to Number.
Definition at line 82 of file common.hpp.
typedef vector<NumberPtr> GT::Numbers
Vector of Numbers.
Definition at line 83 of file common.hpp.
typedef shared_ptr<Numbers> GT::NumbersPtr
Smart pointer to Numbers.
Definition at line 84 of file common.hpp.
typedef ostream GT::OutputStream
Output stream alias.
Definition at line 72 of file common.hpp.
typedef map<Identifier, Identifier> GT::Positions
Map of dimension-position pairs.
Definition at line 85 of file common.hpp.
typedef shared_ptr<Positions> GT::PositionsPtr
Smart pointer to Positions.
Definition at line 86 of file common.hpp.
Function Documentation
Identifier GT::createIdentifier (Index identifier)
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Identifier GT::createIdentifier (const char * identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 78 of file helpers.hpp.
Identifier GT::createIdentifier (string identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 84 of file helpers.hpp.
Identifier GT::createIdentifier (shared_ptr< string > identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 90 of file helpers.hpp.
IdentifierPtr GT::createIdentifierPtr (Index identifier)
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Referenced by GT::GTL::NullGame::getGameType(), and GT::GTL::ErrorGame::getGameType().
IdentifierPtr GT::createIdentifierPtr (const char * identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 96 of file helpers.hpp.
IdentifierPtr GT::createIdentifierPtr (string identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 102 of file helpers.hpp.
IdentifierPtr GT::createIdentifierPtr (shared_ptr< string > identifier) inline
Creates Identifier.
Parameters
identifier source to turn into Identifier
Returns
Identifier
Definition at line 108 of file helpers.hpp.
Identifiers GT::createIdentifiers () inline
Creates Identifiers.
Returns
Identifiers
Definition at line 114 of file helpers.hpp.
IdentifiersPtr GT::createIdentifiersPtr () inline
Creates Identifier.
Returns
Identifier
Definition at line 118 of file helpers.hpp.
IdentifiersPtr GT::createIdentifiersPtr (Identifiers identifiers) inline
Creates Identifiers.
Parameters
identifiers source to turn into Identifiers
Returns
Identifiers
Definition at line 122 of file helpers.hpp.
Message GT::createMessage (Index message)
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Referenced by GT::GTL::NullGame::serialize(), and GT::GTL::ErrorGame::serialize().
Message GT::createMessage (double message)
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Message GT::createMessage (const char * message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 26 of file helpers.hpp.
Message GT::createMessage (string message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 32 of file helpers.hpp.
Message GT::createMessage (shared_ptr< string > message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 38 of file helpers.hpp.
Message GT::createMessage (Number number)
Creates Message.
Parameters
number source to turn into Message
Returns
Message
Message GT::createMessage (NumberPtr number)
Creates Message.
Parameters
number source to turn into Message
Returns
Message
MessagePtr GT::createMessagePtr (Index message)
Creates Message.
Parameters
message source to turn into Message
Returns
Message
MessagePtr GT::createMessagePtr (double message)
Creates Message.
Parameters
message source to turn into Message
Returns
Message
MessagePtr GT::createMessagePtr (const char * message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 44 of file helpers.hpp.
MessagePtr GT::createMessagePtr (string message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 50 of file helpers.hpp.
MessagePtr GT::createMessagePtr (shared_ptr< string > message) inline
Creates Message.
Parameters
message source to turn into Message
Returns
Message
Definition at line 56 of file helpers.hpp.
MessagePtr GT::createMessagePtr (Number number)
Creates Message.
Parameters
number source to turn into Message
Returns
Message
MessagePtr GT::createMessagePtr (NumberPtr number)
Creates Messages.
Parameters
number source to turn into Message
Returns
Message
Messages GT::createMessages () inline
Creates Messages.
Returns
Message
Definition at line 62 of file helpers.hpp.
MessagesPtr GT::createMessagesPtr () inline
Creates Messages.
Returns
Message
Definition at line 66 of file helpers.hpp.
MessagesPtr GT::createMessagesPtr (Messages messages) inline
Creates Message.
Parameters
messages source to turn into Message
Returns
Messages
Definition at line 70 of file helpers.hpp.
Number GT::createNumber (int number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 130 of file helpers.hpp.
Number GT::createNumber (float number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 136 of file helpers.hpp.
Number GT::createNumber (double number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 142 of file helpers.hpp.
Number GT::createNumber (string number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 148 of file helpers.hpp.
Number GT::createNumber (shared_ptr< string > number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 154 of file helpers.hpp.
Number GT::createNumber (Number number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 160 of file helpers.hpp.
Number GT::createNumber (NumberPtr number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 166 of file helpers.hpp.
NumberPtr GT::createNumberPtr (int number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 172 of file helpers.hpp.
NumberPtr GT::createNumberPtr (float number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 178 of file helpers.hpp.
NumberPtr GT::createNumberPtr (double number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 184 of file helpers.hpp.
NumberPtr GT::createNumberPtr (string number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 190 of file helpers.hpp.
NumberPtr GT::createNumberPtr (shared_ptr< string > number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 196 of file helpers.hpp.
NumberPtr GT::createNumberPtr (Number number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 202 of file helpers.hpp.
NumberPtr GT::createNumberPtr (NumberPtr number) inline
Creates Number.
Parameters
number source to turn into Number
Returns
Number
Definition at line 208 of file helpers.hpp.
Numbers GT::createNumbers () inline
Creates Numbers.
Returns
Numbers
Definition at line 214 of file helpers.hpp.
NumbersPtr GT::createNumbersPtr () inline
Creates Numbers.
Returns
Numbers
Definition at line 218 of file helpers.hpp.
NumbersPtr GT::createNumbersPtr (Numbers numbers) inline
Creates Numbers.
Parameters
numbers source to turn into Numbers
Returns
Numbers
Definition at line 222 of file helpers.hpp.
Positions GT::createPositions () inline
Creates Positions.
Returns
Positions
Definition at line 230 of file helpers.hpp.
PositionsPtr GT::createPositionsPtr () inline
Creates Positions.
Returns
Positions
Definition at line 234 of file helpers.hpp.
bool GT::operator!= (Messages & messages1, Messages & messages2)
Check if Messages are different.
Parameters
messages1 first Messages vector
messages2 second Messages vector
Returns
true if vectors have different content
bool GT::operator!= (Identifiers & identifier1, Identifiers & identifier2)
Check if Identifiers are different.
Parameters
identifier1 first Identifiers vector
identifier2 second Identifiers vector
Returns
true if vectors have different content
bool GT::operator!= (Numbers & numbers1, Numbers & numbers2)
Check if Numbers are different.
Parameters
numbers1 first Numbers vector
numbers2 second Numbers vector
Returns
true if vectors have different content
bool GT::operator!= (Positions & positions1, Positions & positions2)
Check if Positions are different.
Parameters
positions1 first Positions vector
positions2 second Positions vector
Returns
true if vectors have different content
bool GT::operator== (Messages & messages1, Messages & messages2)
Check if Messages are equal.
Parameters
messages1 first Messages vector
messages2 second Messages vector
Returns
true if vectors have equal content
bool GT::operator== (Identifiers & identifier1, Identifiers & identifier2)
Check if Identifiers are equal.
Parameters
identifier1 first Identifiers vector
identifier2 second Identifiers vector
Returns
true if vectors have equal content
bool GT::operator== (Numbers & numbers1, Numbers & numbers2)
Check if Numbers are equal.
Parameters
numbers1 first Numbers vector
numbers2 second Numbers vector
Returns
true if vectors have equal content
bool GT::operator== (Positions & positions1, Positions & positions2)
Check if Positions are equal.
Parameters
positions1 first Positions vector
positions2 second Positions vector
Returns
true if vectors have equal content