Game Theory Tools (full documentation): GT::Model::ExtensiveDataNode Class Reference
GT::Model::ExtensiveDataNode Class Reference
Creates tree containing whole ExtensiveData content.
#include <extensive_data_node.hpp>
Public Member Functions
ExtensiveDataNode ()
Tree's root's constructor.
virtual const ExtensiveDataNode & getParent () const
Returns parent of this Node (Null object for Root).
virtual const ExtensiveDataNodes & getChildren () const
Returns children of this Node (empty for leaf).
virtual const PlayerPtr getPlayer () const
Returns Player of a current Node.
virtual const PlayerPtr getPlayer (const Positions &positions) const
Returns Player for a given Positions.
virtual ExtensiveDataNode & setPlayer (const PlayerPtr player)
Sets Player of a current Node.
virtual ExtensiveDataNode & setPlayer (const Positions &positions, const PlayerPtr player)
Sets Player of a current Node.
virtual const NumbersPtr getPayoffs (const Positions &positions) const
Returns Payoff values.
virtual ExtensiveDataNode & setPayoffs (const Positions &positions, const NumbersPtr values)
Sets Payoff values.
virtual IdentifiersPtr getChoices () const
Returns available choices.
virtual bool hasChoice (const Identifier &strategy) const
Returns whether such choice is available.
virtual const ExtensiveDataNode & getNodeForChoice (const Identifier &strategy) const
Returns node for given choice.
virtual bool isLeaf () const
Returns whether the node is a leaf.
virtual Message toString () const override
ExtensiveDataNode's Message.
virtual Message toString (const ExtensiveGamePositionsHelper &positionsHelper) const
ExtensiveDataNode's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Protected Member Functions
ExtensiveDataNode (ExtensiveDataNode *parent, Index depth)
Child Node constructor.
ExtensiveDataNode (ExtensiveDataNode *parent, NumbersPtr values)
Leaf Node constructor.
Private Types
typedef boost::intrusive_ptr
< ExtensiveDataNode > ExtensiveDataNodeInnerPtr
Pointer deleting only NullExtensiveDataNode objects (roots' mock parents).
Private Member Functions
bool isPositionOfCurrentNodePlayer (const Positions &positions) const
Whether passed Positions of a Platyer point to a current Node.
bool checkPositions (const Positions &positions) const
Whether Positions contains choice for current Node.
bool checkPlayerPositions (const Positions &positions) const
Whether Positions contains NEXT choice.
Private Attributes
ExtensiveDataNodeInnerPtr parent
Parent of this node.
PlayerPtr player
Player which strategis are allowed in this Node.
NumbersPtr payoff
Payoff values.
ExtensiveDataNodesPtr nodes
Children of this node (choices).
Index depthValue
Current depth's value.
Identifier depthName
Current depth's name.
Friends
void intrusive_ptr_add_ref (ExtensiveDataNode *parent)
Reference incrementation for ExtensiveDataNodeInnerPtr.
void intrusive_ptr_release (ExtensiveDataNode *parent)
Reference release for ExtensiveDataNodeInnerPtr.
Detailed Description
Creates tree containing whole ExtensiveData content.
Author
Mateusz Kubuszok
See Also
ExtensiveData
Definition at line 39 of file extensive_data_node.hpp.
Member Typedef Documentation
typedef boost::intrusive_ptr<ExtensiveDataNode> GT::Model::ExtensiveDataNode::ExtensiveDataNodeInnerPtr private
Pointer deleting only NullExtensiveDataNode objects (roots' mock parents).
Definition at line 43 of file extensive_data_node.hpp.
Constructor & Destructor Documentation
GT::Model::ExtensiveDataNode::ExtensiveDataNode ()
Tree's root's constructor.
Definition at line 49 of file extensive_data_node.cpp.
Referenced by setPayoffs(), and setPlayer().
                                      :
     parent(new NullExtensiveDataNode()),
     player(NullFactory::getInstance().createPlayer()),
     payoff(new Numbers()),
     nodes(new ExtensiveDataNodes()),
     depthValue(1),
     depthName(createIdentifier(1))
     {}
GT::Model::ExtensiveDataNode::ExtensiveDataNode (ExtensiveDataNode * parent, Index depth) protected
Child Node constructor.
Parameters
parent parent of thisNode
depth depth of a created Node
Definition at line 248 of file extensive_data_node.cpp.
   :
     parent(definedParent),
     player(NullFactory::getInstance().createPlayer()),
     payoff(new Numbers()),
     nodes(new ExtensiveDataNodes()),
     depthValue(currentDepth),
     depthName(createIdentifier(currentDepth))
     {}
GT::Model::ExtensiveDataNode::ExtensiveDataNode (ExtensiveDataNode * parent, NumbersPtr values) protected
Leaf Node constructor.
Parameters
parent parent of thisNode
values Payoff values
Definition at line 260 of file extensive_data_node.cpp.
   :
     parent(definedParent),
     player(NullFactory::getInstance().createPlayer()),
     payoff(values),
     nodes(new ExtensiveDataNodes()),
     depthValue(0),
     depthName("")
     {}
Member Function Documentation
bool GT::Model::ExtensiveDataNode::checkPlayerPositions (const Positions & positions) const private
Whether Positions contains NEXT choice.
Parameters
positions Positions of sought Player
Returns
true if Positions are empty or contains some choice for this depth
Definition at line 286 of file extensive_data_node.cpp.
References depthName.
Referenced by getPlayer(), and setPlayer().
         {
     return positions.empty() || positions.count(depthName);
 }
bool GT::Model::ExtensiveDataNode::checkPositions (const Positions & positions) const private
Whether Positions contains choice for current Node.
Parameters
positions Positions of sought Payoff
Returns
true if Positions contains strategy for current depth that is available in this node
Definition at line 280 of file extensive_data_node.cpp.
References depthName, and nodes.
Referenced by getPayoffs().
         {
     return positions.count(depthName) && nodes->count(positions.at(depthName));
 }
const ExtensiveDataNodes & GT::Model::ExtensiveDataNode::getChildren () const virtual
Returns children of this Node (empty for leaf).
Returns
children Nodes
Definition at line 62 of file extensive_data_node.cpp.
References nodes.
{
     return *nodes;
 }
IdentifiersPtr GT::Model::ExtensiveDataNode::getChoices () const virtual
Returns available choices.
Returns
choices
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 159 of file extensive_data_node.cpp.
References GT::createIdentifierPtr(), GT::createIdentifiersPtr(), and nodes.
{
     IdentifiersPtr choices = createIdentifiersPtr();
     for (Identifier choice : *nodes | map_keys)
         choices->push_back( createIdentifierPtr(choice) );
     return choices;
 }
const ExtensiveDataNode & GT::Model::ExtensiveDataNode::getNodeForChoice (const Identifier & strategy) const virtual
Returns node for given choice.
Parameters
strategy choice to obtain
Returns
node for choice
Exceptions
InvalidStrategy thrown if such strategy isn't available choice
Definition at line 178 of file extensive_data_node.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidStrategy(), and nodes.
         {
     if (!nodes->count(strategy))
         throw ExceptionFactory::getInstance().invalidStrategy(strategy);
     return *nodes->at(strategy);
 }
const ExtensiveDataNode & GT::Model::ExtensiveDataNode::getParent () const virtual
Returns parent of this Node (Null object for Root).
Returns
parent Node
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 58 of file extensive_data_node.cpp.
References parent.
{
     return *parent;
 }
const NumbersPtr GT::Model::ExtensiveDataNode::getPayoffs (const Positions & positions) const virtual
Returns Payoff values.
Parameters
positions Positions of a sought Payoff
Returns
values of Payoffs
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 120 of file extensive_data_node.cpp.
References checkPositions(), depthName, depthValue, GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), nodes, and payoff.
         {
     if (depthValue == 0)
         return payoff;
     if (!checkPositions(positions))
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(positions);
     const Identifier& strategy = positions.at(depthName);
     return (*nodes)[strategy]->getPayoffs(positions);
 }
const PlayerPtr GT::Model::ExtensiveDataNode::getPlayer () const virtual
Returns Player of a current Node.
Returns
Player of this Node
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 66 of file extensive_data_node.cpp.
References player.
{
     return player;
 }
const PlayerPtr GT::Model::ExtensiveDataNode::getPlayer (const Positions & positions) const virtual
Returns Player for a given Positions.
Parameters
positions Positions of a sought Player
Returns
Player of this Node
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 70 of file extensive_data_node.cpp.
References checkPlayerPositions(), GT::Model::NullFactory::createPlayer(), depthName, GT::Model::NullFactory::getInstance(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), isPositionOfCurrentNodePlayer(), nodes, and player.
         {
     if (isPositionOfCurrentNodePlayer(positions))
         return player;
     if (!checkPlayerPositions(positions))
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(positions);
     const Identifier& strategy = positions.at(depthName);
     if (nodes->count(strategy))
         return (*nodes)[strategy]->getPlayer(positions);
     return NullFactory::getInstance().createPlayer();
 }
bool GT::Model::ExtensiveDataNode::hasChoice (const Identifier & strategy) const virtual
Returns whether such choice is available.
Parameters
strategy choice to check
Returns
true if choice is available
Definition at line 168 of file extensive_data_node.cpp.
References nodes.
         {
     return nodes->count(strategy);
 }
bool GT::Model::ExtensiveDataNode::isLeaf () const virtual
Returns whether the node is a leaf.
Returns
true if the node is a leaf
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 174 of file extensive_data_node.cpp.
References nodes.
{
     return nodes->empty();
 }
bool GT::Model::ExtensiveDataNode::isPositionOfCurrentNodePlayer (const Positions & positions) const private
Whether passed Positions of a Platyer point to a current Node.
Parameters
positions Positions of sought Player
Returns
true if Positions point to a Player in this Node
Definition at line 274 of file extensive_data_node.cpp.
References depthValue.
Referenced by getPlayer(), and setPlayer().
         {
     return depthValue == positions.size()+1;
 }
ExtensiveDataNode & GT::Model::ExtensiveDataNode::setPayoffs (const Positions & positions, const NumbersPtr values) virtual
Sets Payoff values.
Parameters
positions Positions of a set Payoff
values Payoff value
Returns
reference to itself for chaining
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 133 of file extensive_data_node.cpp.
References GT::Model::ExceptionFactory::coordinatesAlreadySet(), depthName, depthValue, ExtensiveDataNode(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), and nodes.
   {
     if (!positions.count(depthName))
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(positions);
     const Identifier& strategy = positions.at(depthName);
     if (!nodes->count(strategy)) {
         ExtensiveDataNodePtr node;
         if (depthValue == positions.size())
             node = ExtensiveDataNodePtr(new ExtensiveDataNode(this, values));
         else {
             node = ExtensiveDataNodePtr(new ExtensiveDataNode(this, depthValue+1));
             node->setPayoffs(positions, values);
         }
         nodes->insert( ExtensiveDataNodes::value_type(strategy, node) );
     } else if (depthValue != positions.size())
         (*nodes)[strategy]->setPayoffs(positions, values);
     else
         throw ExceptionFactory::getInstance().coordinatesAlreadySet(positions);
     return *this;
 }
ExtensiveDataNode & GT::Model::ExtensiveDataNode::setPlayer (const PlayerPtr player) virtual
Sets Player of a current Node.
Parameters
player Player of this Node
Returns
reference to itself for chaining
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 86 of file extensive_data_node.cpp.
References player.
Referenced by setPlayer().
   {
     player = newPlayer;
     return *this;
 }
ExtensiveDataNode & GT::Model::ExtensiveDataNode::setPlayer (const Positions & positions, const PlayerPtr player) virtual
Sets Player of a current Node.
Parameters
positions Positions of a set Player
player Player of this Node
Returns
reference to itself for chaining
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 93 of file extensive_data_node.cpp.
References checkPlayerPositions(), GT::Model::ExceptionFactory::coordinatesAlreadySet(), depthName, depthValue, ExtensiveDataNode(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), isPositionOfCurrentNodePlayer(), nodes, player, and setPlayer().
   {
     if (isPositionOfCurrentNodePlayer(positions)) {
         if (player->isNotNull() && player != newPlayer)
             throw ExceptionFactory::getInstance().coordinatesAlreadySet(positions);
         setPlayer(newPlayer);
     }
     else if (!checkPlayerPositions(positions))
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(positions);
     else {
         const Identifier& strategy = positions.at(depthName);
         if (!nodes->count(strategy)) {
             ExtensiveDataNodePtr node(new ExtensiveDataNode(this, depthValue+1));
             nodes->insert( ExtensiveDataNodes::value_type(strategy, node) );
         }
         (*nodes)[strategy]->setPlayer(positions, newPlayer);
     }
     return *this;
 }
Message GT::Model::ExtensiveDataNode::toString () const override virtual
ExtensiveDataNode's Message.
Returns
Message
Implements GT::Model::Root.
Reimplemented in GT::Model::NullExtensiveDataNode.
Definition at line 187 of file extensive_data_node.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), depthValue, GT::Model::ResultFactory::getInstance(), nodes, payoff, and player.
{
     static const IdentifierPtr    valueName     = createIdentifierPtr("Value");
     ResultBuilderPtr              resultBuilder = ResultFactory::getInstance().buildResult();
     if (depthValue == 0)
         for (NumberPtr& number : (*payoff)) {
             MessagePtr result = createMessagePtr(number);
             resultBuilder->addResult(valueName, result);
         }
     else {
         static const IdentifierPtr playerName  = createIdentifierPtr("Player");
         const MessagePtr           playerValue = createMessagePtr(player->toString());
         resultBuilder->addResult(playerName, playerValue);
         for (ExtensiveDataNodes::value_type& node : (*nodes)) {
             IdentifierPtr nodeName = createIdentifierPtr(node.first);
             MessagePtr    result   = createMessagePtr(node.second->toString());
             resultBuilder->addResult(nodeName, result);
         }
     }
     return resultBuilder->build()->getResult();
 }
Message GT::Model::ExtensiveDataNode::toString (const ExtensiveGamePositionsHelper & positionsHelper) const virtual
ExtensiveDataNode's Message.
Parameters
positionsHelper ExtensiveGamePositionsHelper that will define information sets.
Returns
Message
Definition at line 211 of file extensive_data_node.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), depthValue, GT::Model::ExtensiveGamePositionsHelper::getInformationSetsForPlayer(), GT::Model::ResultFactory::getInstance(), nodes, payoff, and player.
         {
     static const IdentifierPtr valueName     = createIdentifierPtr("Value");
     ResultBuilderPtr           resultBuilder = ResultFactory::getInstance().buildResult();
     if (depthValue == 0)
         for (NumberPtr& number : (*payoff)) {
             MessagePtr result = createMessagePtr(number);
             resultBuilder->addResult(valueName, result);
         }
     else {
         static const IdentifierPtr playerName  = createIdentifierPtr("Player");
         const MessagePtr           playerValue = createMessagePtr(player->toString());
         resultBuilder->addResult(playerName, playerValue);
         static const IdentifierPtr setName  = createIdentifierPtr("Information Set");
         try {
             const MessagePtr           setValue = createMessagePtr(
                 positionsHelper.getInformationSetsForPlayer(*player->getName())
                                .right.at(const_cast<GT::Model::ExtensiveDataNode* const>(this))
             );
             resultBuilder->addResult(setName, setValue);
         } catch (...) {}
         for (ExtensiveDataNodes::value_type& node : (*nodes)) {
             IdentifierPtr nodeName = createIdentifierPtr(node.first);
             MessagePtr    result   = createMessagePtr(node.second->toString(positionsHelper));
             resultBuilder->addResult(nodeName, result);
         }
     }
     return resultBuilder->build()->getResult();
 }
Friends And Related Function Documentation
void intrusive_ptr_add_ref (ExtensiveDataNode * parent) friend
Reference incrementation for ExtensiveDataNodeInnerPtr.
Definition at line 32 of file extensive_data_node.cpp.
   {}
void intrusive_ptr_release (ExtensiveDataNode * parent) friend
Reference release for ExtensiveDataNodeInnerPtr.
Definition at line 36 of file extensive_data_node.cpp.
   {
     // NullExtensiveDataNode has its parent set to nullptr to avoid cycle - need to null check first
     if (parent && parent->isNull())
         delete parent;
 }
Member Data Documentation
Identifier GT::Model::ExtensiveDataNode::depthName private
Current depth's name.
Definition at line 80 of file extensive_data_node.hpp.
Referenced by checkPlayerPositions(), checkPositions(), getPayoffs(), getPlayer(), setPayoffs(), and setPlayer().
Index GT::Model::ExtensiveDataNode::depthValue private
Current depth's value.
Definition at line 76 of file extensive_data_node.hpp.
Referenced by getPayoffs(), isPositionOfCurrentNodePlayer(), setPayoffs(), setPlayer(), and toString().
ExtensiveDataNodesPtr GT::Model::ExtensiveDataNode::nodes private
Children of this node (choices).
Definition at line 72 of file extensive_data_node.hpp.
Referenced by checkPositions(), getChildren(), getChoices(), getNodeForChoice(), getPayoffs(), getPlayer(), hasChoice(), isLeaf(), setPayoffs(), setPlayer(), and toString().
ExtensiveDataNodeInnerPtr GT::Model::ExtensiveDataNode::parent private
Parent of this node.
Definition at line 60 of file extensive_data_node.hpp.
Referenced by getParent().
NumbersPtr GT::Model::ExtensiveDataNode::payoff private
Payoff values.
Definition at line 68 of file extensive_data_node.hpp.
Referenced by getPayoffs(), and toString().
PlayerPtr GT::Model::ExtensiveDataNode::player private
Player which strategis are allowed in this Node.
Definition at line 64 of file extensive_data_node.hpp.
Referenced by getPlayer(), setPlayer(), and toString().
The documentation for this class was generated from the following files:
src/gt/model/extensive_data_node.hpp
src/gt/model/extensive_data_node.cpp