Game Theory Tools (full documentation): GT::GTL::NullDefinition Class Reference
GT::GTL::NullDefinition Class Reference final
Null Definition for handling invalid situations.
#include <definition.hpp>
Public Member Functions
NullDefinition ()
virtual const IdentifierPtr getName () const override
Returns name of the property.
virtual const ParamPtr getValue () const override
Returns value of the property.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message about Definition.
Public Member Functions inherited from GT::GTL::Definition
Definition (const IdentifierPtr definedName, const ParamPtr definedValue)
Constructor for name and value.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Null Definition for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 97 of file definition.hpp.
Constructor & Destructor Documentation
GT::GTL::NullDefinition::NullDefinition () inline
Definition at line 99 of file definition.hpp.
                      :
         Definition(
             Model::NullFactory::getInstance().createIdentifier(),
             NullFactory::getInstance().createParam()
         )
         {}
Member Function Documentation
virtual const IdentifierPtr GT::GTL::NullDefinition::getName () const inline override virtual
Returns name of the property.
Returns
value of the property
Reimplemented from GT::GTL::Definition.
Definition at line 106 of file definition.hpp.
References GT::Model::NullFactory::createIdentifier(), and GT::Model::NullFactory::getInstance().
{
         return Model::NullFactory::getInstance().createIdentifier();
     }
virtual const ParamPtr GT::GTL::NullDefinition::getValue () const inline override virtual
Returns value of the property.
Returns
value of the property
Reimplemented from GT::GTL::Definition.
Definition at line 110 of file definition.hpp.
References GT::GTL::NullFactory::createParam(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createParam();
     }
virtual bool GT::GTL::NullDefinition::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 114 of file definition.hpp.
{
         return false;
     }
virtual Message GT::GTL::NullDefinition::toString () const inline override virtual
Returns Message about Definition.
Returns
Definition's Message
Reimplemented from GT::GTL::Definition.
Definition at line 118 of file definition.hpp.
{
         return Message("NullDefinition");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/definition.hpp