Game Theory Tools (public API): GT::GTL::ErrorDetails Class Reference
GT::GTL::ErrorDetails Class Reference final
Error Details for handling invalid situations.
#include <details.hpp>
Public Member Functions
ErrorDetails (const Message errorMessage)
virtual const CoordinatesPtr getCoordinates () const override
Returns Coordinates with data.
virtual const ObjectsPtr getPlayers () const override
Returns Players definitions.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns Message about Game details.
Public Member Functions inherited from GT::GTL::Details
Details (const ObjectsPtr playersDetails, const CoordinatesPtr coordinatesDetails)
Constructor for Players with data.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Message message
Error message.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Error Details for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 129 of file details.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorDetails::ErrorDetails (const Message errorMessage) inline
Definition at line 136 of file details.hpp.
       :
         Details(
             NullFactory::getInstance().createObjects(),
             NullFactory::getInstance().createCoordinates()
         ),
         message(errorMessage)
         {}
Member Function Documentation
virtual const CoordinatesPtr GT::GTL::ErrorDetails::getCoordinates () const inline override virtual
Returns Coordinates with data.
Returns
Coordinates wit data
Reimplemented from GT::GTL::Details.
Definition at line 146 of file details.hpp.
References GT::GTL::NullFactory::createCoordinates(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createCoordinates();
     }
virtual const ObjectsPtr GT::GTL::ErrorDetails::getPlayers () const inline override virtual
Returns Players definitions.
Returns
Players definitions
Reimplemented from GT::GTL::Details.
Definition at line 150 of file details.hpp.
References GT::GTL::NullFactory::createObjects(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createObjects();
     }
virtual bool GT::GTL::ErrorDetails::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 154 of file details.hpp.
{
         return false;
     }
virtual Message GT::GTL::ErrorDetails::toString () const inline override virtual
Returns Message about Game details.
Returns
Game Details Message
Reimplemented from GT::GTL::Details.
Definition at line 158 of file details.hpp.
References message.
{
         return message;
     }
Member Data Documentation
const Message GT::GTL::ErrorDetails::message private
Error message.
Definition at line 133 of file details.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/details.hpp