Game Theory Tools (full documentation): GT::GTL::NullObject Class Reference
GT::GTL::NullObject Class Reference final
Null Object for handling invalid situations.
#include <object.hpp>
Public Member Functions
virtual bool respondsTo (const Identifier &) const override
Whether Object responds to some property.
virtual ResultPtr findProperty (const Context &, const Identifier &) const override
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &, const Identifier &, const Conditions &) const override
Finds Objects' property for giver Conditions and returns it as a Result.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns message about object.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual operator const Game & () const
Explicit cast to Game type.
virtual operator const Param & () const
Explicit cast to Param type.
virtual operator const Player & () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Null Object for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 215 of file object.hpp.
Member Function Documentation
virtual ResultPtr GT::GTL::NullObject::findProperty (const Context & context, const Identifier & propertyName) const inline override virtual
Finds Objects' property and returns it as a Result.
Parameters
context Context with values
propertyName property's name
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 223 of file object.hpp.
References GT::GTL::NullFactory::createResult(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::GTL::NullObject::findPropertyWithConditions (const Context & context, const Identifier & propertyName, const Conditions & conditions) const inline override virtual
Finds Objects' property for giver Conditions and returns it as a Result.
Parameters
context Context with values
propertyName property's name
conditions Conditions to consider
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 230 of file object.hpp.
References GT::GTL::NullFactory::createResult(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createResult();
     }
virtual bool GT::GTL::NullObject::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 238 of file object.hpp.
{
         return false;
     }
virtual bool GT::GTL::NullObject::respondsTo (const Identifier & propertyName) const inline override virtual
Whether Object responds to some property.
Parameters
propertyName property's name
Returns
true if Object responds to such property
Reimplemented from GT::GTL::Object.
Definition at line 217 of file object.hpp.
                      {
         return false;
     }
virtual Message GT::GTL::NullObject::toString () const inline override virtual
Returns message about object.
Returns
generic Message
Reimplemented from GT::GTL::Object.
Definition at line 242 of file object.hpp.
{
         return Message("NullObject");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/object.hpp