Game Theory Tools (full documentation): GT::Routines::ConditionFactory Class Reference
GT::Routines::ConditionFactory Class Reference final
Used for creation of Null instances for Routines classes.
#include <condition_factory.hpp>
Public Member Functions
ConditionPtr createInformationSetChoiceCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifierPtr strategy) const
Creates Condition of information set's choice.
ConditionPtr createInformationSetRangeCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifiersPtr strategies) const
Creates Condition of information set's allowed range.
ConditionPtr createPlayerChoiceCondition (const IdentifierPtr player, const IdentifierPtr strategy) const
Creates Condition of Player's choice.
ConditionPtr createPlayerRangeCondition (const IdentifierPtr player, const IdentifiersPtr strategies) const
Creates Condition of Player's allowed strategies.
Static Public Member Functions
static ConditionFactory & getInstance ()
Returns the instance of a ConditionFactory.
Private Member Functions
ConditionFactory ()=default
Default constructor hidden from programmers.
ConditionFactory (const ConditionFactory &conditionFactory)=delete
Default copy constructor hidden from programmers.
~ConditionFactory ()=default
Default destructor hidden from programmers.
Detailed Description
Used for creation of Null instances for Routines classes.
Author
Mateusz Kubuszok
Definition at line 37 of file condition_factory.hpp.
Constructor & Destructor Documentation
GT::Routines::ConditionFactory::ConditionFactory () private default
Default constructor hidden from programmers.
GT::Routines::ConditionFactory::ConditionFactory (const ConditionFactory & conditionFactory) private delete
Default copy constructor hidden from programmers.
Parameters
conditionFactory object to copy
GT::Routines::ConditionFactory::~ConditionFactory () private default
Default destructor hidden from programmers.
Member Function Documentation
ConditionPtr GT::Routines::ConditionFactory::createInformationSetChoiceCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifierPtr strategy) const
Creates Condition of information set's choice.
Parameters
player Player's name
informationSet information set's name
strategy chosen strategy
Returns
Condition
Definition at line 36 of file condition_factory.cpp.
Referenced by GT::GTL::InformationSetChoiceCondition::getCondition().
         {
     return ConditionPtr( new InformationSetChoiceCondition(player, informationSet, strategy) );
 }
ConditionPtr GT::Routines::ConditionFactory::createInformationSetRangeCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifiersPtr strategies) const
Creates Condition of information set's allowed range.
Parameters
player Player's name
informationSet information set's name
strategies allowed strategies
Returns
Condition
Definition at line 44 of file condition_factory.cpp.
Referenced by GT::GTL::InformationSetRangeCondition::getCondition().
         {
     return ConditionPtr( new InformationSetRangeCondition(player, informationSet, strategies) );
 }
ConditionPtr GT::Routines::ConditionFactory::createPlayerChoiceCondition (const IdentifierPtr player, const IdentifierPtr strategy) const
Creates Condition of Player's choice.
Parameters
player Player's name
strategy chosen strategy
Returns
Condition
Definition at line 52 of file condition_factory.cpp.
Referenced by GT::GTL::PlayerChoiceCondition::getCondition().
         {
     return ConditionPtr( new PlayerChoiceCondition(player, strategy) );
 }
ConditionPtr GT::Routines::ConditionFactory::createPlayerRangeCondition (const IdentifierPtr player, const IdentifiersPtr strategies) const
Creates Condition of Player's allowed strategies.
Parameters
player Player's name
strategies allowed strategies
Returns
Condition
Definition at line 59 of file condition_factory.cpp.
Referenced by GT::GTL::PlayerRangeCondition::getCondition().
         {
     return ConditionPtr( new PlayerRangeCondition(player, strategies) );
 }
ConditionFactory & GT::Routines::ConditionFactory::getInstance () static
Returns the instance of a ConditionFactory.
Returns
ConditionFactory instance
Definition at line 31 of file condition_factory.cpp.
Referenced by GT::GTL::PlayerChoiceCondition::getCondition(), GT::GTL::PlayerRangeCondition::getCondition(), GT::GTL::InformationSetChoiceCondition::getCondition(), and GT::GTL::InformationSetRangeCondition::getCondition().
{
     static ConditionFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/routines/condition_factory.hpp
src/gt/routines/condition_factory.cpp