Game Theory Tools (full documentation): GT::GTL::NullCoordinateDriver Class Reference
GT::GTL::NullCoordinateDriver Class Reference
Null CoordinateDriver for handling invalid situations.
#include <coordinate_driver.hpp>
Public Member Functions
NullCoordinateDriver ()
virtual CoordinatePtr * create (const InputLocation &inputLocation, const IdentifierPtr *, const IdentifierPtr *) const override
Creates coordinate.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *, const CoordinatesPtr *) const override
Fills Coordinate with subcoordinates.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *, const ParamsPtr *) const override
Fills Coordinate with Params.
virtual CoordinatePtr * merge (const InputLocation &inputLocation, const CoordinatePtr *, const CoordinatePtr *) const override
Merge two coordinates into one.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
CoordinateDriver message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null CoordinateDriver for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 111 of file coordinate_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::NullCoordinateDriver::NullCoordinateDriver () inline
Definition at line 113 of file coordinate_driver.hpp.
                            :
         CoordinateDriver()
         {}
Member Function Documentation
virtual CoordinatePtr* GT::GTL::NullCoordinateDriver::create (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifierPtr * strategy) const inline override virtual
Creates coordinate.
Parameters
inputLocation input location of created Coordinate
player dimension (Player)
strategy position (strategy)
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 117 of file coordinate_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 NullFactory::getInstance().createCoordinate(),
                 inputLocation
             )
         );
     }
virtual CoordinatePtr* GT::GTL::NullCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const CoordinatesPtr * data) const inline override virtual
Fills Coordinate with subcoordinates.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 130 of file coordinate_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 NullFactory::getInstance().createCoordinate(),
                 inputLocation
             )
         );
     }
virtual CoordinatePtr* GT::GTL::NullCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const ParamsPtr * data) const inline override virtual
Fills Coordinate with Params.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 143 of file coordinate_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 NullFactory::getInstance().createCoordinate(),
                 inputLocation
             )
         );
     }
virtual bool GT::GTL::NullCoordinateDriver::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 169 of file coordinate_driver.hpp.
{
         return false;
     }
virtual CoordinatePtr* GT::GTL::NullCoordinateDriver::merge (const InputLocation & inputLocation, const CoordinatePtr * coordinate1, const CoordinatePtr * coordinate2) const inline override virtual
Merge two coordinates into one.
Parameters
inputLocation input location of created Condition
coordinate1 first Coorinate
coordinate2 second Coorinate
Returns
merged Coordinates
Implements GT::GTL::CoordinateDriver.
Definition at line 156 of file coordinate_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 NullFactory::getInstance().createCoordinate(),
                 inputLocation
             )
         );
     }
virtual Message GT::GTL::NullCoordinateDriver::toString () const inline override virtual
CoordinateDriver message.
Returns
message
Implements GT::GTL::CoordinateDriver.
Definition at line 173 of file coordinate_driver.hpp.
{
         return Message("NullCoordinateDriver");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/coordinate_driver.hpp