Game Theory Tools (full documentation): GT::GTL::NullFactory Class Reference
GT::GTL::NullFactory Class Reference final
Used for creation of Null instances for GTL classes.
#include <null_factory.hpp>
Public Member Functions
ConditionPtr createCondition () const
Creates NullCondition.
ConditionsPtr createConditions () const
Creates NullConditions.
ContextPtr createContext () const
Creates NullContext.
CoordinatePtr createCoordinate () const
Creates NullCoordinate.
CoordinatesPtr createCoordinates () const
Creates NullCoordinates.
DefinitionPtr createDefinition () const
Creates NullDefinition.
DetailsPtr createDetails () const
Creates NullDetails.
GamePtr createGame () const
Creates NullGame.
ObjectPtr createObject () const
Creates NullObject.
ObjectsPtr createObjects () const
Creates NullObjects.
ParamPtr createParam () const
Creates NullParam.
ParamsPtr createParams () const
Creates NullParams.
PlayerPtr createPlayer () const
Creates NullPlayer.
PositionsPtr createPositions () const
Creates NullPositions.
ResultPtr createResult () const
Creates NullResult.
QueryPtr createQuery () const
Creates NullQuery.
DriverPtr createDriver () const
Creates NullDriver.
ConditionDriverPtr createConditionDriver () const
Creates NullConditionDriver.
CoordinateDriverPtr createCoordinateDriver () const
Creates NullCoordinateDriver.
GameDriverPtr createGameDriver () const
Creates NullGameDriver.
ValueDriverPtr createValueDriver () const
Creates NullValueDriver.
StatementDriverPtr createStatementDriver () const
Creates NullStatementDriver.
CollectionsDriverPtr< Coordinate > createCoordinatesDriver () const
Creates NullCollectionsDriver<Coordinate>.
CollectionsDriverPtr< Condition > createConditionsDriver () const
Creates NullCollectionsDriver<Condition>.
CollectionsDriverPtr< Identifier > createIdentifiersDriver () const
Creates NullCollectionsDriver<Identifier>.
CollectionsDriverPtr< Object > createObjectsDriver () const
Creates NullCollectionsDriver<Object>.
CollectionsDriverPtr< Param > createParamsDriver () const
Creates NullCollectionsDriver<Param>.
InputLocationPtr createInputLocation () const
Creates null InputLocation.
Static Public Member Functions
static NullFactory & getInstance ()
Returns the instance of a NullFactory.
Private Member Functions
NullFactory ()=default
Default constructor hidden from programmers.
NullFactory (const NullFactory &nullFactory)=delete
Default copy constructor hidden from programmers.
~NullFactory ()=default
Default destructor hidden from programmers.
Detailed Description
Used for creation of Null instances for GTL classes.
Author
Mateusz Kubuszok
Definition at line 37 of file null_factory.hpp.
Constructor & Destructor Documentation
GT::GTL::NullFactory::NullFactory () private default
Default constructor hidden from programmers.
GT::GTL::NullFactory::NullFactory (const NullFactory & nullFactory) private delete
Default copy constructor hidden from programmers.
Parameters
nullFactory object to copy
GT::GTL::NullFactory::~NullFactory () private default
Default destructor hidden from programmers.
Member Function Documentation
ConditionPtr GT::GTL::NullFactory::createCondition () const
Creates NullCondition.
Returns
NullCondition
Definition at line 36 of file null_factory.cpp.
{
     return ConditionPtr(new NullCondition());
 }
ConditionDriverPtr GT::GTL::NullFactory::createConditionDriver () const
Creates NullConditionDriver.
Returns
NullConditionDriver
Definition at line 104 of file null_factory.cpp.
{
     return ConditionDriverPtr(new NullConditionDriver());
 }
ConditionsPtr GT::GTL::NullFactory::createConditions () const
Creates NullConditions.
Returns
NullConditions
Definition at line 40 of file null_factory.cpp.
Referenced by GT::GTL::Object::findProperty().
{
     return ConditionsPtr(new Conditions());
 }
CollectionsDriverPtr< Condition > GT::GTL::NullFactory::createConditionsDriver () const
Creates NullCollectionsDriver<Condition>.
Returns
NullCollectionsDriver<Condition>
Definition at line 128 of file null_factory.cpp.
{
     return CollectionsDriverPtr<Condition>(new NullCollectionsDriver<Condition>());
 }
ContextPtr GT::GTL::NullFactory::createContext () const
Creates NullContext.
Returns
NullContext
Definition at line 44 of file null_factory.cpp.
{
     return ContextPtr(new NullContext());
 }
CoordinatePtr GT::GTL::NullFactory::createCoordinate () const
Creates NullCoordinate.
Returns
NullCoordinate
Definition at line 48 of file null_factory.cpp.
{
     return CoordinatePtr(new NullCoordinate());
 }
CoordinateDriverPtr GT::GTL::NullFactory::createCoordinateDriver () const
Creates NullCoordinateDriver.
Returns
NullCooridnateDriver
Definition at line 108 of file null_factory.cpp.
{
     return CoordinateDriverPtr(new NullCoordinateDriver());
 }
CoordinatesPtr GT::GTL::NullFactory::createCoordinates () const
Creates NullCoordinates.
Returns
NullCoordinates
Definition at line 52 of file null_factory.cpp.
Referenced by GT::GTL::NullDetails::getCoordinates(), GT::GTL::ErrorDetails::getCoordinates(), GT::GTL::NullCoordinate::getSubCoordinates(), and GT::GTL::ErrorCoordinate::getSubCoordinates().
{
     return CoordinatesPtr(new Coordinates());
 }
CollectionsDriverPtr< Coordinate > GT::GTL::NullFactory::createCoordinatesDriver () const
Creates NullCollectionsDriver<Coordinate>.
Returns
NullCollectionsDriver<Coordinate>
Definition at line 124 of file null_factory.cpp.
{
     return CollectionsDriverPtr<Coordinate>(new NullCollectionsDriver<Coordinate>());
 }
DefinitionPtr GT::GTL::NullFactory::createDefinition () const
Creates NullDefinition.
Returns
NullDefinition
Definition at line 56 of file null_factory.cpp.
{
     return DefinitionPtr(new NullDefinition());
 }
DetailsPtr GT::GTL::NullFactory::createDetails () const
Creates NullDetails.
Returns
NullDetails
Definition at line 60 of file null_factory.cpp.
{
     return DetailsPtr(new NullDetails());
 }
DriverPtr GT::GTL::NullFactory::createDriver () const
Creates NullDriver.
Returns
NullDriver
Definition at line 100 of file null_factory.cpp.
{
     return DriverPtr(new NullDriver());
 }
GamePtr GT::GTL::NullFactory::createGame () const
Creates NullGame.
Returns
NullGame
Definition at line 64 of file null_factory.cpp.
{
     return GamePtr(new NullGame());
 }
GameDriverPtr GT::GTL::NullFactory::createGameDriver () const
Creates NullGameDriver.
Returns
NullGameDriver
Definition at line 112 of file null_factory.cpp.
{
     return GameDriverPtr(new NullGameDriver());
 }
CollectionsDriverPtr< Identifier > GT::GTL::NullFactory::createIdentifiersDriver () const
Creates NullCollectionsDriver<Identifier>.
Returns
NullCollectionsDriver<Identifier>
Definition at line 132 of file null_factory.cpp.
{
     return CollectionsDriverPtr<Identifier>(new NullCollectionsDriver<Identifier>());
 }
InputLocationPtr GT::GTL::NullFactory::createInputLocation () const
Creates null InputLocation.
Returns
InputLocation
Definition at line 144 of file null_factory.cpp.
{
     return InputLocationPtr(new InputLocation());
 }
ObjectPtr GT::GTL::NullFactory::createObject () const
Creates NullObject.
Returns
NullObject
Definition at line 68 of file null_factory.cpp.
Referenced by GT::GTL::NullParam::getObject(), GT::GTL::ErrorParam::getObject(), and GT::GTL::NullContext::getObject().
{
     return ObjectPtr(new NullObject());
 }
ObjectsPtr GT::GTL::NullFactory::createObjects () const
Creates NullObjects.
Returns
NullObjects
Definition at line 72 of file null_factory.cpp.
Referenced by GT::GTL::NullDetails::getPlayers(), and GT::GTL::ErrorDetails::getPlayers().
{
     return ObjectsPtr(new Objects());
 }
CollectionsDriverPtr< Object > GT::GTL::NullFactory::createObjectsDriver () const
Creates NullCollectionsDriver<Object>.
Returns
NullCollectionsDriver<Object>
Definition at line 136 of file null_factory.cpp.
{
     return CollectionsDriverPtr<Object>(new NullCollectionsDriver<Object>());
 }
ParamPtr GT::GTL::NullFactory::createParam () const
Creates NullParam.
Returns
NullParam
Definition at line 76 of file null_factory.cpp.
Referenced by GT::GTL::NullContext::getParam(), GT::GTL::NullDefinition::getValue(), and GT::GTL::ErrorDefinition::getValue().
{
     return ParamPtr(new NullParam());
 }
ParamsPtr GT::GTL::NullFactory::createParams () const
Creates NullParams.
Returns
NullParams
Definition at line 80 of file null_factory.cpp.
Referenced by GT::GTL::NullCoordinate::getParams(), and GT::GTL::ErrorCoordinate::getParams().
{
     return ParamsPtr(new Params());
 }
CollectionsDriverPtr< Param > GT::GTL::NullFactory::createParamsDriver () const
Creates NullCollectionsDriver<Param>.
Returns
NullCollectionsDriver<Param>
Definition at line 140 of file null_factory.cpp.
{
     return CollectionsDriverPtr<Param>(new NullCollectionsDriver<Param>());
 }
PlayerPtr GT::GTL::NullFactory::createPlayer () const
Creates NullPlayer.
Returns
NullPlayer
Definition at line 84 of file null_factory.cpp.
{
     return PlayerPtr(new NullPlayer());
 }
PositionsPtr GT::GTL::NullFactory::createPositions () const
Creates NullPositions.
Returns
NullPositions
Definition at line 88 of file null_factory.cpp.
Referenced by GT::GTL::NullCoordinate::getPositions(), and GT::GTL::ErrorCoordinate::getPositions().
{
     return PositionsPtr(new Positions());
 }
QueryPtr GT::GTL::NullFactory::createQuery () const
Creates NullQuery.
Returns
NullQuery
Definition at line 96 of file null_factory.cpp.
{
     return QueryPtr(new NullQuery());
 }
ResultPtr GT::GTL::NullFactory::createResult () const
Creates NullResult.
Returns
NullResult
Definition at line 92 of file null_factory.cpp.
Referenced by GT::GTL::NullObject::describeProperty(), GT::GTL::ErrorObject::describeProperty(), GT::GTL::NullQuery::execute(), GT::GTL::ErrorQuery::execute(), GT::GTL::NullObject::findProperty(), GT::GTL::ErrorObject::findProperty(), GT::GTL::NullObject::findPropertyWithConditions(), and GT::GTL::ErrorObject::findPropertyWithConditions().
{
     return ResultPtr(new NullResult());
 }
StatementDriverPtr GT::GTL::NullFactory::createStatementDriver () const
Creates NullStatementDriver.
Returns
NullStatementDriver
Definition at line 120 of file null_factory.cpp.
{
     return StatementDriverPtr(new NullStatementDriver());
 }
ValueDriverPtr GT::GTL::NullFactory::createValueDriver () const
Creates NullValueDriver.
Returns
NullValueDriver
Definition at line 116 of file null_factory.cpp.
{
     return ValueDriverPtr(new NullValueDriver());
 }
NullFactory & GT::GTL::NullFactory::getInstance () static
Returns the instance of a NullFactory.
Returns
NullFactory instance
Definition at line 31 of file null_factory.cpp.
Referenced by GT::GTL::CheckingCoordinateDriver::create(), GT::GTL::NullCoordinateDriver::create(), GT::GTL::CheckingStatementDriver::createDefinition(), GT::GTL::NullStatementDriver::createDefinition(), GT::GTL::CheckingGameDriver::createDetails(), GT::GTL::NullGameDriver::createDetails(), GT::GTL::CheckingGameDriver::createExtensive(), GT::GTL::NullGameDriver::createExtensive(), GT::GTL::CheckingGameDriver::createPlayer(), GT::GTL::NullGameDriver::createPlayer(), GT::GTL::CheckingStatementDriver::createQuery(), GT::GTL::NullStatementDriver::createQuery(), GT::GTL::CheckingGameDriver::createStrategic(), GT::GTL::NullGameDriver::createStrategic(), GT::GTL::NullObject::describeProperty(), GT::GTL::ErrorObject::describeProperty(), GT::GTL::NullQuery::execute(), GT::GTL::ErrorQuery::execute(), GT::GTL::CheckingCoordinateDriver::fillWithData(), GT::GTL::NullCoordinateDriver::fillWithData(), GT::GTL::Object::findProperty(), GT::GTL::NullObject::findProperty(), GT::GTL::ErrorObject::findProperty(), GT::GTL::NullObject::findPropertyWithConditions(), GT::GTL::ErrorObject::findPropertyWithConditions(), GT::GTL::CheckingValueDriver::get(), GT::GTL::NullValueDriver::get(), GT::GTL::NullDetails::getCoordinates(), GT::GTL::ErrorDetails::getCoordinates(), GT::GTL::NullParam::getObject(), GT::GTL::ErrorParam::getObject(), GT::GTL::NullContext::getObject(), GT::GTL::NullContext::getParam(), GT::GTL::NullCoordinate::getParams(), GT::GTL::ErrorCoordinate::getParams(), GT::GTL::NullDetails::getPlayers(), GT::GTL::ErrorDetails::getPlayers(), GT::GTL::NullCoordinate::getPositions(), GT::GTL::ErrorCoordinate::getPositions(), GT::GTL::NullCoordinate::getSubCoordinates(), GT::GTL::ErrorCoordinate::getSubCoordinates(), GT::GTL::NullDefinition::getValue(), GT::GTL::ErrorDefinition::getValue(), GT::GTL::CheckingConditionDriver::informationSetChoosed(), GT::GTL::NullConditionDriver::informationSetChoosed(), GT::GTL::CheckingConditionDriver::informationSetWithin(), GT::GTL::NullConditionDriver::informationSetWithin(), GT::GTL::CheckingCoordinateDriver::merge(), GT::GTL::NullCoordinateDriver::merge(), GT::GTL::CheckingConditionDriver::playerChoosed(), GT::GTL::NullConditionDriver::playerChoosed(), GT::GTL::CheckingConditionDriver::playerWithin(), GT::GTL::NullConditionDriver::playerWithin(), and GT::GTL::NullValueDriver::toObject().
{
     static NullFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/gtl/null_factory.hpp
src/gt/gtl/null_factory.cpp