Game Theory Tools (public API): GT::GTL::ErrorCoordinate Class Reference
GT::GTL::ErrorCoordinate Class Reference final
Error Coordinate for handling invalid situations.
#include <coordinate.hpp>
Public Member Functions
ErrorCoordinate (Message errorMessage)
virtual Coordinate & addParam (const ParamPtr) override
Adds Param to the list.
virtual Coordinate & addParams (const ParamsPtr) override
Adds Params to the list.
virtual Coordinate & addPosition (const IdentifierPtr, const IdentifierPtr) override
Add Position to known Coordinates.
virtual Coordinate & addSubCoordinate (const CoordinatePtr) override
Adds SubCoordinate.
virtual Coordinate & addSubCoordinates (const CoordinatesPtr) override
Adds SubCoordinates.
virtual const ParamsPtr getParams () const override
Obtains Params.
virtual const PositionsPtr getPositions () const override
Obtains Positions.
virtual const CoordinatesPtr getSubCoordinates () const override
Obtain SubCoordinates.
virtual void fillDataBuilder (const Context &, DataBuilderPtr &) const
Fill DataBuilder with its data.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns Coordinate Message.
Public Member Functions inherited from GT::GTL::Coordinate
Coordinate ()
Default constructor.
Coordinate (const IdentifierPtr player, const IdentifierPtr strategy)
Constructor for initial strategies.
virtual Message serialize () const override
Returns serialized Message for a Coordinate.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
Message message
Error message.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Error Coordinate for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 290 of file coordinate.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorCoordinate::ErrorCoordinate (Message errorMessage) inline
Definition at line 297 of file coordinate.hpp.
       :
         message(errorMessage)
         {}
Member Function Documentation
virtual Coordinate& GT::GTL::ErrorCoordinate::addParam (const ParamPtr param) inline override virtual
Adds Param to the list.
Parameters
param single Param
Returns
reference to itself
Reimplemented from GT::GTL::Coordinate.
Definition at line 303 of file coordinate.hpp.
                {
         return *this;
     }
virtual Coordinate& GT::GTL::ErrorCoordinate::addParams (const ParamsPtr params) inline override virtual
Adds Params to the list.
Parameters
params Params' vector
Returns
reference to itself
Reimplemented from GT::GTL::Coordinate.
Definition at line 309 of file coordinate.hpp.
                {
         return *this;
     }
virtual Coordinate& GT::GTL::ErrorCoordinate::addPosition (const IdentifierPtr player, const IdentifierPtr strategy) inline override virtual
Add Position to known Coordinates.
Parameters
player player (dimension)
strategy strategy (position on dimension)
Returns
reference to itself
Reimplemented from GT::GTL::Coordinate.
Definition at line 315 of file coordinate.hpp.
                {
         return *this;
     }
virtual Coordinate& GT::GTL::ErrorCoordinate::addSubCoordinate (const CoordinatePtr subCoordinate) inline override virtual
Adds SubCoordinate.
Parameters
subCoordinate SubCoordinate
Returns
reference to itself
Reimplemented from GT::GTL::Coordinate.
Definition at line 322 of file coordinate.hpp.
                {
         return *this;
     }
virtual Coordinate& GT::GTL::ErrorCoordinate::addSubCoordinates (const CoordinatesPtr subCoordinates) inline override virtual
Adds SubCoordinates.
Parameters
subCoordinates SubCoordinate
Returns
reference to itself
Reimplemented from GT::GTL::Coordinate.
Definition at line 328 of file coordinate.hpp.
                {
         return *this;
     }
virtual void GT::GTL::ErrorCoordinate::fillDataBuilder (const Context & context, DataBuilderPtr & dataBuilder) const inline virtual
Fill DataBuilder with its data.
Parameters
context Context with params
dataBuilder DataBuilder to fill
Exceptions
CyclicIdentifiers thrown when some Identfiers create the cycle
InvalidContentRequest thrown when some Param does not contain Number
NotDefinedParam thrown when some Param cannot find value inside Context
IllegalInnerState thrown when some of positions are already set
InvalidCoordinate thrown when some of values are not valid strategies names
IllegalInnerState thrown when attempting to set params when not all coordinates are known
Reimplemented from GT::GTL::Coordinate.
Definition at line 346 of file coordinate.hpp.
             {}
virtual const ParamsPtr GT::GTL::ErrorCoordinate::getParams () const inline override virtual
Obtains Params.
Returns
Params
Reimplemented from GT::GTL::Coordinate.
Definition at line 334 of file coordinate.hpp.
References GT::GTL::NullFactory::createParams(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createParams();
     }
virtual const PositionsPtr GT::GTL::ErrorCoordinate::getPositions () const inline override virtual
Obtains Positions.
Returns
Positions
Reimplemented from GT::GTL::Coordinate.
Definition at line 338 of file coordinate.hpp.
References GT::GTL::NullFactory::createPositions(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPositions();
     }
virtual const CoordinatesPtr GT::GTL::ErrorCoordinate::getSubCoordinates () const inline override virtual
Obtain SubCoordinates.
Returns
SubCoordinates
Reimplemented from GT::GTL::Coordinate.
Definition at line 342 of file coordinate.hpp.
References GT::GTL::NullFactory::createCoordinates(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createCoordinates();
     }
virtual bool GT::GTL::ErrorCoordinate::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 351 of file coordinate.hpp.
{
         return false;
     }
virtual Message GT::GTL::ErrorCoordinate::toString () const inline override virtual
Returns Coordinate Message.
Returns
Message
Reimplemented from GT::GTL::Coordinate.
Definition at line 355 of file coordinate.hpp.
References message.
{
         return message;
     }
Member Data Documentation
Message GT::GTL::ErrorCoordinate::message private
Error message.
Definition at line 294 of file coordinate.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/coordinate.hpp