Game Theory Tools (full documentation): GT::GTL::ConditionFactory Class Reference
GT::GTL::ConditionFactory Class Reference final
Used for creation of Conditions for GT model.
#include <condition_factory.hpp>
Public Member Functions
ConditionPtr createInformationSetChoiceCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectPtr strategy) const
Creates Condition for a Player choosing strategy beforehand.
ConditionPtr createInformationSetRangeCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectsPtr strategies) const
Creates Condition for a Player limiting strategies beforehand.
ConditionPtr createPlayerChoiceCondition (const ObjectPtr player, const ObjectPtr strategy) const
Creates Condition for a Player choosing strategy beforehand.
ConditionPtr createPlayerRangeCondition (const ObjectPtr player, const ObjectsPtr strategies) const
Creates Condition for a Player limiting strategies beforehand.
Static Public Member Functions
static ConditionFactory & getInstance ()
Returns the instance of a ResultFactory.
Private Member Functions
ConditionFactory ()
Default constructor hidden from programmers.
ConditionFactory (const ConditionFactory &conditionFactory)
Default copy constructor hidden from programmers.
~ConditionFactory ()
Default destructor hidden from programmers.
Detailed Description
Used for creation of Conditions for GT model.
Author
Mateusz Kubuszok
Definition at line 37 of file condition_factory.hpp.
Constructor & Destructor Documentation
GT::GTL::ConditionFactory::ConditionFactory () private
Default constructor hidden from programmers.
Definition at line 77 of file condition_factory.cpp.
 {}
GT::GTL::ConditionFactory::ConditionFactory (const ConditionFactory & conditionFactory) private
Default copy constructor hidden from programmers.
Parameters
conditionFactory object to copy
GT::GTL::ConditionFactory::~ConditionFactory () private
Default destructor hidden from programmers.
Definition at line 79 of file condition_factory.cpp.
 {}
Member Function Documentation
ConditionPtr GT::GTL::ConditionFactory::createInformationSetChoiceCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectPtr strategy) const
Creates Condition for a Player choosing strategy beforehand.
Parameters
player player Object
informationSet information set Object
strategy strategy Object
Returns
Condition for a Player
Definition at line 37 of file condition_factory.cpp.
         {
     return ConditionPtr(
         new InformationSetChoiceCondition(player, informationSet, strategy)
     );
 }
ConditionPtr GT::GTL::ConditionFactory::createInformationSetRangeCondition (const ObjectPtr player, const ObjectPtr informationSet, const ObjectsPtr strategies) const
Creates Condition for a Player limiting strategies beforehand.
Parameters
player player Object
informationSet information set Object
strategies strategies Objects
Returns
Condition for a Player
Definition at line 47 of file condition_factory.cpp.
         {
     return ConditionPtr(
         new InformationSetRangeCondition(player, informationSet, strategies)
     );
 }
ConditionPtr GT::GTL::ConditionFactory::createPlayerChoiceCondition (const ObjectPtr player, const ObjectPtr strategy) const
Creates Condition for a Player choosing strategy beforehand.
Parameters
player player Object
strategy strategy Object
Returns
Condition for a Player
Definition at line 57 of file condition_factory.cpp.
         {
     return ConditionPtr(
         new PlayerChoiceCondition(player, strategy)
     );
 }
ConditionPtr GT::GTL::ConditionFactory::createPlayerRangeCondition (const ObjectPtr player, const ObjectsPtr strategies) const
Creates Condition for a Player limiting strategies beforehand.
Parameters
player player Object
strategies strategies Objects
Returns
Condition for a Player
Definition at line 66 of file condition_factory.cpp.
         {
     return ConditionPtr(
         new PlayerRangeCondition(player, strategies)
     );
 }
ConditionFactory & GT::GTL::ConditionFactory::getInstance () static
Returns the instance of a ResultFactory.
Returns
ConditionFactory instance
Definition at line 30 of file condition_factory.cpp.
Referenced by GT::GTL::ExecutionConditionDriver::informationSetChoosed(), GT::GTL::ExecutionConditionDriver::informationSetWithin(), GT::GTL::ExecutionConditionDriver::playerChoosed(), and GT::GTL::ExecutionConditionDriver::playerWithin().
{
     static ConditionFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/gtl/condition_factory.hpp
src/gt/gtl/condition_factory.cpp