Game Theory Tools (full documentation): GT::Model::Root Class Reference
GT::Model::Root Class Reference abstract
Basic interface of many classes used in the project.
#include <root.hpp>
Public Member Functions
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
virtual Message toString () const =0
Returns Message about an Object allowing its debuging.
Friends
bool operator== (const Root &root1, const Root &root2)
Syntax sugar for Root::isEqual(const Root&) method.
bool operator!= (const Root &root1, const Root &root2)
Syntax sugar for !Root#isEqual(const Root&) method.
OutputStream & operator<< (OutputStream &stream, const Root &root)
Syntax sugar for toString() method.
Detailed Description
Basic interface of many classes used in the project.
Author
Mateusz Kubuszok
Definition at line 37 of file root.hpp.
Constructor & Destructor Documentation
GT::Model::Root::~Root () virtual
Default destructor.
Definition at line 31 of file root.cpp.
 {}
Member Function Documentation
bool GT::Model::Root::isEqual (const Root & root) const virtual
Defines equality relation.
Parameters
root another root to compare
Returns
true if roots are equal
Reimplemented in GT::Model::Player, GT::Model::Result, and GT::Model::Game.
Definition at line 33 of file root.cpp.
Referenced by GT::Model::operator!=(), and GT::Model::operator==().
         {
     return this == &root;
 }
bool GT::Model::Root::isNotNull () const virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented in GT::Model::NullExtensiveDataNode, GT::Model::NullExtensiveData, GT::GTL::NullCoordinate, GT::Model::NullStrategicData, GT::GTL::NullDriver, GT::GTL::NullObject, GT::Model::NullPlayer, GT::GTL::NullContext, GT::GTL::NullParam, GT::GTL::NullConditionDriver, GT::GTL::NullValueDriver, GT::Model::NullData, GT::GTL::NullCoordinateDriver, GT::GTL::NullGameDriver, GT::GTL::NullStatementDriver, GT::GTL::NullCollectionsDriver< Content >, GT::GTL::NullGame, GT::Model::NullResultBuilder, GT::Model::NullDataBuilder, GT::Model::NullGameBuilder, GT::Model::NullDataAccessor, GT::Model::NullResult, GT::Model::NullGame, GT::GTL::NullQuery, GT::Model::NullDataPiece, GT::GTL::NullDefinition, GT::GTL::NullDetails, GT::GTL::NullCondition, GT::GTL::NullPlayer, GT::Routines::NullRoutine, and GT::Routines::NullCondition.
Definition at line 39 of file root.cpp.
Referenced by isNull().
{
     return true;
 }
bool GT::Model::Root::isNull () const
Wheter Root is a null Object (null guardian).
Returns
true if object is a null object
Definition at line 43 of file root.cpp.
References isNotNull().
Referenced by GT::Model::ExtensiveDataNode::~ExtensiveDataNode().
{
     return !isNotNull();
 }
virtual Message GT::Model::Root::toString () const pure virtual
Returns Message about an Object allowing its debuging.
Also used by Models and Routines to render Results.
Returns
Root's Message
Implemented in GT::GTL::ErrorCoordinate, GT::Model::NullExtensiveDataNode, GT::GTL::ErrorObject, GT::Model::NullExtensiveData, GT::GTL::NullCoordinate, GT::GTL::ErrorParam, GT::Model::NullStrategicData, GT::GTL::NullDriver, GT::GTL::NullObject, GT::GTL::ExecutionDriver, GT::Model::NullPlayer, GT::GTL::NullContext, GT::GTL::NullParam, GT::GTL::CheckingDriver, GT::GTL::ErrorGame, GT::Model::StrategicData, GT::GTL::Coordinate, GT::Model::ExtensiveDataNode, GT::Model::StrategicGamePositionsHelper, GT::Model::ExtensiveData, GT::GTL::NullConditionDriver, GT::GTL::NullValueDriver, GT::Model::NullData, GT::GTL::NullCoordinateDriver, GT::GTL::NullGameDriver, GT::GTL::ErrorQuery, GT::GTL::Context, GT::GTL::ErrorDefinition, GT::GTL::ErrorDetails, GT::GTL::NullStatementDriver, GT::GTL::Object, GT::GTL::NullCollectionsDriver< Content >, GT::GTL::ErrorCondition, GT::GTL::Driver, GT::GTL::NullGame, GT::Model::NullResultBuilder, GT::Model::StrategicDataAccessor, GT::Model::NullDataBuilder, GT::Model::NullGameBuilder, GT::Model::Player, GT::Model::StrategicDataBuilder, GT::Model::NullDataAccessor, GT::Model::NullResult, GT::GTL::ErrorPlayer, GT::Model::ExtensiveGamePositionsHelper, GT::Model::NullGame, GT::Model::ExtensiveDataBuilder, GT::GTL::ExecutionConditionDriver, GT::Model::ExtensiveDataAccessor, GT::GTL::ExecutionGameDriver, GT::Model::ExtensiveGameBuilder, GT::Model::StrategicGameBuilder, GT::GTL::NullQuery, GT::GTL::CheckingConditionDriver, GT::GTL::ExecutionCoordinateDriver, GT::GTL::ExecutionStatementDriver, GT::GTL::ExecutionValueDriver, GT::Model::AbstractResultBuilder, GT::Model::NullDataPiece, GT::GTL::CheckingCoordinateDriver, GT::GTL::NullDefinition, GT::Routines::ExtensivePureStrategyPath, GT::GTL::CheckingValueDriver, GT::GTL::NullDetails, GT::GTL::CheckingGameDriver, GT::GTL::NullCondition, GT::GTL::CheckingStatementDriver, GT::GTL::CollectionsDriver< Content >, GT::Model::Data, GT::GTL::CollectionsDriver< GT::GTL::GT::GTL::Condition >, GT::GTL::CollectionsDriver< GT::Identifier >, GT::GTL::CollectionsDriver< GT::GTL::GT::GTL::Coordinate >, GT::GTL::CollectionsDriver< GT::GTL::GT::GTL::Object >, GT::GTL::CollectionsDriver< GT::GTL::GT::GTL::Param >, GT::GTL::ConditionDriver, GT::Model::DataBuilder, GT::GTL::CoordinateDriver, GT::GTL::LazyGameProxy, GT::GTL::ValueDriver, GT::GTL::StatementDriver, GT::GTL::IdentifierParam, GT::GTL::Game, GT::GTL::GameDriver, GT::GTL::NullPlayer, GT::GTL::Query, GT::Model::DataPiece, GT::GTL::NumberParam, GT::GTL::ObjectParam, GT::Model::ExtensiveGame, GT::GTL::Definition, GT::GTL::Details, GT::Routines::NullRoutine, GT::Model::StrategicGame, GT::Routines::InformationSetChoiceCondition, GT::Routines::InformationSetRangeCondition, GT::GTL::InformationSetChoiceCondition, GT::GTL::InformationSetRangeCondition, GT::Model::PlainDataPiece, GT::Model::DataAccessor, GT::Routines::NullCondition, GT::Routines::PlayerChoiceCondition, GT::Routines::PlayerRangeCondition, GT::GTL::Condition, GT::GTL::PlayerChoiceCondition, GT::GTL::PlayerRangeCondition, GT::Model::Result, GT::Routines::ExtensivePureEquilibriumRoutine, GT::Routines::NullRoutineConfig, GT::Model::Game, GT::Routines::StrategicPureEquilibriumRoutine, GT::GTL::Player, GT::Routines::ExtensivePureEquilibriumRoutineConfig, GT::Routines::StrategicPureEquilibriumRoutineConfig, GT::Routines::Routine, GT::Routines::NotYetImplementedRoutine, GT::Routines::PropertyUndefinedRoutine, GT::Routines::Condition, and GT::Routines::RoutineConfig.
Referenced by GT::Model::operator<<(), GT::GTL::CheckingDriver::showError(), and GT::GTL::suberrorMessage().
Friends And Related Function Documentation
bool operator!= (const Root & root1, const Root & root2) friend
Syntax sugar for !Root#isEqual(const Root&) method.
Parameters
root1 first Root to compare
root2 second Root to compare
Returns
true if Root are not equal
Definition at line 58 of file root.cpp.
   {
     return !root1.isEqual(root2);
 }
OutputStream& operator<< (OutputStream & stream, const Root & root) friend
Syntax sugar for toString() method.
Parameters
stream stream to concatenate
root Root to concatenate
Returns
stream for chaining
Definition at line 65 of file root.cpp.
   {
     return stream << root.toString();
 }
bool operator== (const Root & root1, const Root & root2) friend
Syntax sugar for Root::isEqual(const Root&) method.
Parameters
root1 first Root to compare
root2 second Root to compare
Returns
true if Root are equal
Definition at line 51 of file root.cpp.
   {
     return root1.isEqual(root2);
 }
The documentation for this class was generated from the following files:
include/gt/model/root.hpp
src/gt/model/root.cpp