Game Theory Tools (full documentation): GT::GTL::NullDetails Class Reference
GT::GTL::NullDetails Class Reference final
Null Details for handling invalid situations.
#include <details.hpp>
Public Member Functions
NullDetails ()
virtual const CoordinatesPtr getCoordinates () const override
Returns Coordinates with data.
virtual const ObjectsPtr getPlayers () const override
Returns Players definitions.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message about Game details.
Public Member Functions inherited from GT::GTL::Details
Details (const ObjectsPtr playersDetails, const CoordinatesPtr coordinatesDetails)
Constructor for Players with data.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Null Details for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 95 of file details.hpp.
Constructor & Destructor Documentation
GT::GTL::NullDetails::NullDetails () inline
Definition at line 97 of file details.hpp.
                   :
         Details(
             NullFactory::getInstance().createObjects(),
             NullFactory::getInstance().createCoordinates()
         )
         {}
Member Function Documentation
virtual const CoordinatesPtr GT::GTL::NullDetails::getCoordinates () const inline override virtual
Returns Coordinates with data.
Returns
Coordinates wit data
Reimplemented from GT::GTL::Details.
Definition at line 104 of file details.hpp.
References GT::GTL::NullFactory::createCoordinates(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createCoordinates();
     }
virtual const ObjectsPtr GT::GTL::NullDetails::getPlayers () const inline override virtual
Returns Players definitions.
Returns
Players definitions
Reimplemented from GT::GTL::Details.
Definition at line 108 of file details.hpp.
References GT::GTL::NullFactory::createObjects(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createObjects();
     }
virtual bool GT::GTL::NullDetails::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 112 of file details.hpp.
{
         return false;
     }
virtual Message GT::GTL::NullDetails::toString () const inline override virtual
Returns Message about Game details.
Returns
Game Details Message
Reimplemented from GT::GTL::Details.
Definition at line 116 of file details.hpp.
{
         return Message("NullDetails");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/details.hpp