Game Theory Tools (full documentation): GT::GTL::Object Class Reference
GT::GTL::Object Class Reference
Root of all Objects used as a data in parsed by GTL.
#include <object.hpp>
Public Member Functions
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const
Finds Objects' property for giver Conditions and returns it as a Result.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual Message toString () const override
Returns message about object.
virtual const Game & toGame () const
Explicit cast to Game type.
virtual const Param & toParam () const
Explicit cast to Param type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Protected Member Functions
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Private Attributes
ObjectPropertyMap registeredProperties
Map containing ObjectProperties bound to their name.
const IdentifierPtr typeName
Object's type name.
Static Private Attributes
static const GamePtr noGame = ErrorFactory::getInstance().createGame("This Object is not a Game")
Returned when Object cannot be casted to Game.
static const ParamPtr noParam = ErrorFactory::getInstance().createParam("This Object is not a Param")
Returned when Object cannot be casted to Param.
static const PlayerPtr noPlayer = ErrorFactory::getInstance().createPlayer("This Object is not a Player")
Returned when Object cannot be casted to Player.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Root of all Objects used as a data in parsed by GTL.
Common ancestor of all types of data (besides Numbers) that can be used within language.
Author
Mateusz Kubuszok
See Also
Param
Context
Parser
Definition at line 43 of file object.hpp.
Constructor & Destructor Documentation
GT::GTL::Object::Object ()
Default constructor.
Definition at line 42 of file object.cpp.
References registerProperty().
                :
     Root(),
     registeredProperties(),
     typeName(createIdentifierPtr("Object"))
 {
     registerProperty(Identifier("properties"), ObjectPropertyPtr(new ObjectKnownProperties(this)));
     registerProperty(Identifier("type"),       ObjectPropertyPtr(new ObjectTypeProperty(this)));
 }
GT::GTL::Object::Object (const Identifier type) explicit
Constructor initiated with Object's type.
Parameters
type Object's type
Definition at line 51 of file object.cpp.
References registerProperty().
   :
     Root(),
     registeredProperties(),
     typeName(createIdentifierPtr(type))
 {
     registerProperty(Identifier("properties"), ObjectPropertyPtr(new ObjectKnownProperties(this)));
     registerProperty(Identifier("type"),       ObjectPropertyPtr(new ObjectTypeProperty(this)));
 }
GT::GTL::Object::~Object () virtual
Object's destructor.
Removes the properties' register.
Definition at line 62 of file object.cpp.
 {}
Member Function Documentation
ResultPtr GT::GTL::Object::describeProperty (const Identifier & propertyName) const virtual
Returns property's description.
Parameters
propertyName property's name
Returns
property's description
Exceptions
InvalidProperty thrown when property is not available for an Object
Reimplemented in GT::GTL::ErrorObject, and GT::GTL::NullObject.
Definition at line 70 of file object.cpp.
References getProperty().
Referenced by GT::GTL::ObjectKnownProperties::findForConditions().
         {
     return getProperty(propertyName)->getDescription();
 }
ResultPtr GT::GTL::Object::findProperty (const Context & context, const Identifier & propertyName) const virtual
Finds Objects' property and returns it as a Result.
Parameters
context Context with values
propertyName property's name
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented in GT::GTL::ErrorObject, GT::GTL::NullObject, and GT::GTL::Param.
Definition at line 76 of file object.cpp.
References GT::GTL::NullFactory::createConditions(), findPropertyWithConditions(), and GT::GTL::NullFactory::getInstance().
Referenced by GT::GTL::Param::findProperty().
         {
     ConditionsPtr noConditions = NullFactory::getInstance().createConditions();
     return findPropertyWithConditions(context, propertyName, *noConditions);
 }
ResultPtr GT::GTL::Object::findPropertyWithConditions (const Context & context, const Identifier & propertyName, const Conditions & conditions) const virtual
Finds Objects' property for giver Conditions and returns it as a Result.
Parameters
context Context with values
propertyName property's name
conditions Conditions to consider
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented in GT::GTL::ErrorObject, GT::GTL::NullObject, and GT::GTL::Param.
Definition at line 84 of file object.cpp.
References getProperty().
Referenced by findProperty(), and GT::GTL::Param::findPropertyWithConditions().
         {
     return getProperty(propertyName)->findForConditions(context, conditions);
 }
const ObjectPropertyPtr GT::GTL::Object::getProperty (const Identifier & propertyName) const protected
Obtains ObjectProperty by name under which it was registered.
Parameters
propertyName name of a required property
Returns
required ObjectProperty
Exceptions
InvalidProperty thrown when property is not available for an Object
Definition at line 129 of file object.cpp.
References GT::GTL::ExceptionFactory::getInstance(), GT::GTL::ExceptionFactory::invalidObjectProperty(), and registeredProperties.
Referenced by describeProperty(), and findPropertyWithConditions().
         {
     if (registeredProperties.count(propertyName))
         return registeredProperties.at(propertyName);
     throw ExceptionFactory::getInstance().invalidObjectProperty(propertyName);
 }
bool GT::GTL::Object::isPropertyRegistered (const Identifier & propertyName) const protected
Whether property is registered or not.
Parameters
propertyName name of a checked property
Returns
true if property is registered
Definition at line 123 of file object.cpp.
References registeredProperties.
Referenced by respondsTo().
         {
     return registeredProperties.count(propertyName);
 }
IdentifiersPtr GT::GTL::Object::listProperties () const virtual
Returns list of available properties.
Returns
properties list
Definition at line 92 of file object.cpp.
References GT::createIdentifierPtr(), GT::createIdentifiersPtr(), and registeredProperties.
{
     IdentifiersPtr properties = createIdentifiersPtr();
     for (Identifier property : registeredProperties | map_keys)
         properties->push_back( createIdentifierPtr(property) );
     return properties;
 }
void GT::GTL::Object::registerProperty (const Identifier propertyName, const ObjectPropertyPtr property) protected
Registers property together with its name.
Parameters
propertyName property's name
property property instance
Definition at line 137 of file object.cpp.
References registeredProperties.
Referenced by GT::GTL::CurrentContext::CurrentContext(), GT::GTL::Game::Game(), Object(), GT::GTL::Param::Param(), and GT::GTL::Player::Player().
   {
     registeredProperties.insert( ObjectPropertyMap::value_type(propertyName, property) );
 }
bool GT::GTL::Object::respondsTo (const Identifier & propertyName) const virtual
Whether Object responds to some property.
Parameters
propertyName property's name
Returns
true if Object responds to such property
Reimplemented in GT::GTL::ErrorObject, and GT::GTL::NullObject.
Definition at line 64 of file object.cpp.
References isPropertyRegistered().
         {
     return isPropertyRegistered(propertyName);
 }
const Game & GT::GTL::Object::toGame () const virtual
Explicit cast to Game type.
Returns
Game
Reimplemented in GT::GTL::Game.
Definition at line 109 of file object.cpp.
References noGame.
{
     return *noGame;
 }
const Param & GT::GTL::Object::toParam () const virtual
Explicit cast to Param type.
Returns
Param
Reimplemented in GT::GTL::Param.
Definition at line 113 of file object.cpp.
References noParam.
Referenced by GT::GTL::CheckingGameDriver::createDetails().
{
     return *noParam;
 }
const Player & GT::GTL::Object::toPlayer () const virtual
Explicit cast to Player type.
Returns
Player
Reimplemented in GT::GTL::Player.
Definition at line 117 of file object.cpp.
References noPlayer.
Referenced by GT::GTL::CheckingGameDriver::createDetails().
{
     return *noPlayer;
 }
Message GT::GTL::Object::toString () const override virtual
Returns message about object.
Returns
generic Message
Implements GT::Model::Root.
Reimplemented in GT::GTL::ErrorObject, GT::GTL::ErrorParam, GT::GTL::NullObject, GT::GTL::ErrorGame, GT::GTL::NullParam, GT::GTL::NullGame, GT::GTL::ErrorPlayer, GT::GTL::Game, GT::GTL::IdentifierParam, GT::GTL::NullPlayer, GT::GTL::NumberParam, GT::GTL::ObjectParam, and GT::GTL::Player.
Definition at line 105 of file object.cpp.
References GT::createMessage(), and typeName.
Referenced by GT::GTL::CheckingCoordinateDriver::fillWithData(), GT::GTL::ParamValueProperty::findForConditions(), GT::GTL::CheckingConditionDriver::informationSetChoosed(), GT::GTL::CheckingConditionDriver::informationSetWithin(), GT::GTL::CheckingConditionDriver::playerChoosed(), and GT::GTL::CheckingConditionDriver::playerWithin().
{
     return createMessage(typeName);
 }
const IdentifierPtr GT::GTL::Object::type () const virtual
Returns type of an Object.
Returns
type name
Definition at line 101 of file object.cpp.
References typeName.
Referenced by GT::GTL::ObjectTypeProperty::findForConditions().
{
     return typeName;
 }
Member Data Documentation
const GamePtr GT::GTL::Object::noGame = ErrorFactory::getInstance().createGame("This Object is not a Game") static private
Returned when Object cannot be casted to Game.
Definition at line 47 of file object.hpp.
Referenced by toGame().
const ParamPtr GT::GTL::Object::noParam = ErrorFactory::getInstance().createParam("This Object is not a Param") static private
Returned when Object cannot be casted to Param.
Definition at line 52 of file object.hpp.
Referenced by toParam().
const PlayerPtr GT::GTL::Object::noPlayer = ErrorFactory::getInstance().createPlayer("This Object is not a Player") static private
Returned when Object cannot be casted to Player.
Definition at line 57 of file object.hpp.
Referenced by toPlayer().
ObjectPropertyMap GT::GTL::Object::registeredProperties private
Map containing ObjectProperties bound to their name.
Definition at line 62 of file object.hpp.
Referenced by getProperty(), isPropertyRegistered(), listProperties(), and registerProperty().
const IdentifierPtr GT::GTL::Object::typeName private
Object's type name.
Definition at line 67 of file object.hpp.
Referenced by toString(), and type().
The documentation for this class was generated from the following files:
include/gt/gtl/object.hpp
src/gt/gtl/object.cpp