Game Theory Tools (full documentation): GT::Model::StrategicGameBuilder Class Reference
GT::Model::StrategicGameBuilder Class Reference final
Builder used for creating StrategicGame.
#include <strategic_game_builder.hpp>
Public Member Functions
StrategicGameBuilder ()
Default constructor.
virtual GamePtr build () const override
Returns set up Game.
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual DataBuilder & setPlayers (PlayersPtr newPlayers) override
Sets Players' definitions.
virtual DataBuilder & addNextPositions (PositionsPtr positions) override
Specifies next Positions.
virtual DataBuilder & setPayoffs (NumbersPtr params) override
Sets payoffs values.
virtual DataBuilderPtr clone () const override
Returns copy of itsef with shared content and frozen values of already set Positions.
virtual GameBuilderPtr cloneBuilder () const override
Returns new copy of this GameBuilder's type.
virtual DataBuilderPtr dataBuilder () const override
Returns Same's DataBuilder.
virtual Message toString () const override
StrategicGameBuilder Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
StrategicDataBuilderPtr strategicDataBuilder
Game's DataBuilder.
Detailed Description
Builder used for creating StrategicGame.
Games in this form should have all coordinates filled with payoffs. Since all Players and their strategies are known beforehand, positions can also be hashed to Indexes with PositionsHelper.
Author
Mateusz Kubuszok
See Also
StrategicGame
StrategicDataBuilder
Definition at line 43 of file strategic_game_builder.hpp.
Constructor & Destructor Documentation
GT::Model::StrategicGameBuilder::StrategicGameBuilder ()
Default constructor.
Definition at line 35 of file strategic_game_builder.cpp.
Referenced by cloneBuilder().
                                            :
     strategicDataBuilder(new StrategicDataBuilder())
     {}
Member Function Documentation
DataBuilder & GT::Model::StrategicGameBuilder::addNextPositions (PositionsPtr positions) override virtual
Specifies next Positions.
Parameters
positions next Positions to specify
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 50 of file strategic_game_builder.cpp.
References strategicDataBuilder.
   {
     strategicDataBuilder->addNextPositions(positions);
     return *this;
 }
GamePtr GT::Model::StrategicGameBuilder::build () const override virtual
Returns set up Game.
Returns
built Game
Implements GT::Model::GameBuilder.
Definition at line 76 of file strategic_game_builder.cpp.
References strategicDataBuilder.
{
     return GamePtr(
         new StrategicGame(
             strategicDataBuilder->getPlayers(),
             strategicDataBuilder->build()
         )
     );
 }
DataBuilderPtr GT::Model::StrategicGameBuilder::clone () const override virtual
Returns copy of itsef with shared content and frozen values of already set Positions.
Returns
copy with frozem Positions and content common to parent
Implements GT::Model::DataBuilder.
Definition at line 64 of file strategic_game_builder.cpp.
References strategicDataBuilder.
{
     return strategicDataBuilder->clone();
 }
GameBuilderPtr GT::Model::StrategicGameBuilder::cloneBuilder () const override virtual
Returns new copy of this GameBuilder's type.
Returns
GameBuilder
Implements GT::Model::GameBuilder.
Definition at line 68 of file strategic_game_builder.cpp.
References StrategicGameBuilder().
{
     return GameBuilderPtr(new StrategicGameBuilder());
 }
DataBuilderPtr GT::Model::StrategicGameBuilder::dataBuilder () const override virtual
Returns Same's DataBuilder.
Returns
DataBuilder
Implements GT::Model::GameBuilder.
Definition at line 72 of file strategic_game_builder.cpp.
References strategicDataBuilder.
Referenced by toString().
{
     return dynamic_pointer_cast<DataBuilder>(strategicDataBuilder);
 }
const PlayersPtr GT::Model::StrategicGameBuilder::getPlayers () const override virtual
Returns Players' definitions.
Returns
Players' definitions
Implements GT::Model::GameBuilder.
Definition at line 39 of file strategic_game_builder.cpp.
References strategicDataBuilder.
{
     return strategicDataBuilder->getPlayers();
 }
DataBuilder & GT::Model::StrategicGameBuilder::setPayoffs (NumbersPtr params) override virtual
Sets payoffs values.
Parameters
params values of payoffs
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 57 of file strategic_game_builder.cpp.
References strategicDataBuilder.
   {
     strategicDataBuilder->setPayoffs(params);
     return *this;
 }
DataBuilder & GT::Model::StrategicGameBuilder::setPlayers (PlayersPtr newPlayers) override virtual
Sets Players' definitions.
Parameters
newPlayers Players' definitions
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 43 of file strategic_game_builder.cpp.
References strategicDataBuilder.
   {
     strategicDataBuilder->setPlayers(players);
     return *this;
 }
Message GT::Model::StrategicGameBuilder::toString () const override virtual
StrategicGameBuilder Message.
Returns
Message
Implements GT::Model::DataBuilder.
Definition at line 85 of file strategic_game_builder.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), dataBuilder(), and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name    = createIdentifierPtr("Current Strategic Game");
     const MessagePtr           message = createMessagePtr(dataBuilder()->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, message).build()->getResult();
 }
Member Data Documentation
StrategicDataBuilderPtr GT::Model::StrategicGameBuilder::strategicDataBuilder private
Game's DataBuilder.
Definition at line 47 of file strategic_game_builder.hpp.
Referenced by addNextPositions(), build(), clone(), dataBuilder(), getPlayers(), setPayoffs(), and setPlayers().
The documentation for this class was generated from the following files:
src/gt/model/strategic_game_builder.hpp
src/gt/model/strategic_game_builder.cpp