Game Theory Tools (full documentation): GT::Routines::MatrixMixedEquilibriumRoutine Class Reference
GT::Routines::MatrixMixedEquilibriumRoutine Class Reference final
Routune returning mixed strategy equilibrium for 0-sum Strategic Game with 2 Players.
#include <matrix_mixed_equilibrium_routine.hpp>
Public Member Functions
virtual ResultPtr findResultFor (const GamePtr game, const ConditionsPtr conditions) const override
Returns mixed strategy equilibrium for Strategic Game with 2 Players when game is 0-sum type.
virtual Message toString () const override
Returns Routine's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
LPProblemPtr initializeProblem (const Players &players) const
Initializes GLPK's problem (LPProblem structure) with variables declarations.
void fillUpProblem (LPProblem *problem, const StrategicDataAccessor &data, const StrategicGamePositionsHelper &positionsHelper) const
Fills ProblemPtr instance with values.
ResultPtr solveProblem (LPProblem *problem, const StrategicDataAccessor &data, const StrategicGamePositionsHelper &positionsHelper) const
Returns solution for the passed Problem.
Detailed Description
Routune returning mixed strategy equilibrium for 0-sum Strategic Game with 2 Players.
Author
Mateusz Kubuszok
See Also
Condition
Definition at line 39 of file matrix_mixed_equilibrium_routine.hpp.
Member Function Documentation
void GT::Routines::MatrixMixedEquilibriumRoutine::fillUpProblem (LPProblem * problem, const StrategicDataAccessor & data, const StrategicGamePositionsHelper & positionsHelper) const private
Fills ProblemPtr instance with values.
Parameters
problem instance of a LPProblem that needs to have its values filled
data contains data with Payoff values
positionsHelper helper used to calculate positions in StrategicDataAccessor
Definition at line 101 of file matrix_mixed_equilibrium_routine.cpp.
References GT::createNumber(), GT::Model::Player::getName(), and GT::Model::Player::getStrategyOrdinal().
Referenced by findResultFor().
         {
     const Player&     player1     = *( positionsHelper.getPlayers()->begin()->second );
     const Player&     player2     = *( (++positionsHelper.getPlayers()->begin())->second );
     const Identifier& player1Name = *( player1.getName() );
     const Identifier& player2Name = *( player2.getName() );
     const Index       upperBound  = positionsHelper.getUpperBound();
     // LP problem definition does not allow negative values - we shift by const to make all non-negative
     // value will be calculated manually in
     // #solveProblem(LPProblem*,const StrategicDataAccessor&,const StrategicGamePositionsHelper&)const
     // so we don't need to pass shift between methods
     Number payoffShift = createNumber(0.0);
     for (Index k = 0; k < upperBound; k++) {
         const NumberPtr& payoff = data[k]->getPayoff(player1Name);
         if (*payoff < payoffShift)
             payoffShift = *payoff;
     }
     vector<int>     player1Strategies(upperBound+1);
     vector<int>     player2Strategies(upperBound+1);
     vector<double>  payoff(upperBound+1);
     for (Index k = 0; k < upperBound; k++) {
         const PositionsPtr positions       = positionsHelper.retrievePositions(k);
         const Identifier&  player1Strategy = positions->at(player1Name);
         const Identifier&  player2Strategy = positions->at(player2Name);
         // change 0-indexing used in Model to 1-indexing used in GLPK
         const Index        player1Ordinal  = player1.getStrategyOrdinal(player1Strategy) + 1;
         const Index        player2Ordinal  = player2.getStrategyOrdinal(player2Strategy) + 1;
         // shift value by calculated constans to ensure non-negativity
         const Number       shiftedPayoff   = (*data[positions]->getPayoff(player1Name)) - payoffShift;
         const double       player1Payoff   = shiftedPayoff.get_d();
         // GLPK uses 1 indeksing also in data arrays
         player1Strategies[k+1] = player1Ordinal;
         player2Strategies[k+1] = player2Ordinal;
         payoff[k+1]            = player1Payoff; // figure out GMP with GLPK
     }
     // vectors uses contignous memory - &x[0] "transforms" it into a C-style array
     glp_load_matrix(problem, upperBound, &player1Strategies[0], &player2Strategies[0], &payoff[0]);
 }
ResultPtr GT::Routines::MatrixMixedEquilibriumRoutine::findResultFor (const GamePtr game, const ConditionsPtr conditions) const override virtual
Returns mixed strategy equilibrium for Strategic Game with 2 Players when game is 0-sum type.
Routine uses linear programming to solve the problem. It's a typical 0-sum strategic game solution where primal solution is (distribution of Player 2 strategies) * cost function value and dual solution is (distribution of Player 1 strategies) * cost function value.
Parameters
game Game definition
conditions Conditions for this Routine
Returns
Result for fiven Game and Conditions
Exceptions
InvalidCondition thrown when some Condition is invalid or when Conditions application leads to an invalid RoutineConfig or no result
InvalidGameType thrown when Game's type doesn't match Routine's one
Implements GT::Routines::Routine.
Definition at line 45 of file matrix_mixed_equilibrium_routine.cpp.
References fillUpProblem(), GT::Routines::ExceptionFactory::getInstance(), initializeProblem(), GT::Routines::ExceptionFactory::invalidGameType(), and solveProblem().
         {
     const StrategicDataAccessorPtr data    = dynamic_pointer_cast<StrategicDataAccessor>(game->getData());
     const Players&                 players = *data->getPlayers();
     if (!data || players.size() != 2) {
         static Identifier strategicGameName("0-sum Strategic Game with 2 players");
         throw ExceptionFactory::getInstance().invalidGameType(strategicGameName);
     }
     const StrategicGamePositionsHelper positionsHelper(data->getPlayers());
     LPProblemPtr                       problemPtr  = initializeProblem(players);
     LPProblem*                         problem     = problemPtr.get();
     fillUpProblem(problem, *data, positionsHelper);
     return solveProblem(problem, *data, positionsHelper);
 }
LPProblemPtr GT::Routines::MatrixMixedEquilibriumRoutine::initializeProblem (const Players & players) const private
Initializes GLPK's problem (LPProblem structure) with variables declarations.
Parameters
players Players used to initialize problem
Returns
initalized problem
Definition at line 71 of file matrix_mixed_equilibrium_routine.cpp.
References GT::Routines::createLPProblem(), GT::Model::Player::getStrategies(), GT::Model::Player::getStrategiesNumber(), and GT::Model::Player::getStrategyOrdinal().
Referenced by findResultFor().
         {
     const Player& player1 = *( players.begin()->second );
     const Player& player2 = *( (++players.begin())->second );
     LPProblemPtr problemPtr = createLPProblem();
     LPProblem*   problem(problemPtr.get());
     glp_set_prob_name( problem, "2 player 0-sum strategic form game" );
     glp_set_obj_dir(   problem, GLP_MAX );
     glp_add_cols(problem, player2.getStrategiesNumber());
     for (const IdentifierPtr& player2Strategy : *player2.getStrategies()) {
         int j = player2.getStrategyOrdinal(*player2Strategy) + 1;
         glp_set_col_name(problem, j, player2Strategy->c_str());
         glp_set_col_bnds(problem, j, GLP_LO, 0.0, 0.0);
         glp_set_obj_coef(problem, j, 1.0);
     }
     glp_add_rows(problem, player1.getStrategiesNumber());
     for (const IdentifierPtr& player1Strategy : *player1.getStrategies()) {
         int i = player1.getStrategyOrdinal(*player1Strategy) + 1;
         glp_set_row_name(problem, i, player1Strategy->c_str());
         glp_set_row_bnds(problem, i, GLP_UP, 0.0, 1.0);
     }
     return problemPtr;
 }
ResultPtr GT::Routines::MatrixMixedEquilibriumRoutine::solveProblem (LPProblem * problem, const StrategicDataAccessor & data, const StrategicGamePositionsHelper & positionsHelper) const private
Returns solution for the passed Problem.
Parameters
problem instance of a LPProblem to solve
data contains data with Payoff values
positionsHelper helper used to calculate positions in StrategicDataAccessor
Returns
resuls
Definition at line 148 of file matrix_mixed_equilibrium_routine.cpp.
References GT::Model::ResultFactory::buildResult(), GT::Model::ResultFactory::constResult(), GT::createIdentifierPtr(), GT::createIdentifiersPtr(), GT::createMessagePtr(), GT::createMessagesPtr(), GT::Model::ResultFactory::getInstance(), GT::Model::Player::getName(), GT::Model::Player::getStrategies(), and GT::Model::Player::getStrategyOrdinal().
Referenced by findResultFor().
         {
     typedef map<Identifier, double> DistributionMap;
     glp_smcp parm;
     glp_init_smcp(&parm);
     parm.msg_lev = GLP_MSG_OFF;
     if (glp_simplex(problem, &parm) != 0 ||
         glp_get_prim_stat(problem) != GLP_FEAS || glp_get_dual_stat(problem) != GLP_FEAS) {
         // TODO: create MessageFactory
         return ResultFactory::getInstance().constResult(Message("Failed to calculate the solution"));
     }
     double distributionFactor = glp_get_obj_val(problem);
     const Player&     player1       = *( positionsHelper.getPlayers()->begin()->second );
     const Identifier& player1Name   = *( player1.getName() );
     DistributionMap   player1Distribution;
     for (const IdentifierPtr& strategy : *player1.getStrategies()) {
         // change 0-indexing used in Model to 1-indexing used in GLPK
         Index strategyOrdinal = player1.getStrategyOrdinal(*strategy) + 1;
         double probability    = glp_get_row_dual(problem, strategyOrdinal) / distributionFactor;
         player1Distribution.insert( DistributionMap::value_type(*strategy, probability) );
     }
     const Player&     player2     = *( (++positionsHelper.getPlayers()->begin())->second );
     const Identifier& player2Name = *( player2.getName() );
     DistributionMap   player2Distribution;
     for (const IdentifierPtr& strategy : *player2.getStrategies()) {
         // change 0-indexing used in Model to 1-indexing used in GLPK
         Index strategyOrdinal = player2.getStrategyOrdinal(*strategy) + 1;
         double probability    = glp_get_col_prim(problem, strategyOrdinal) / distributionFactor;
         player2Distribution.insert( DistributionMap::value_type(*strategy, probability) );
     }
     double player1Payoff = 0.0;
     for (const IdentifierPtr& player1Strategy : *player1.getStrategies()) {
         for (const IdentifierPtr& player2Strategy : *player2.getStrategies()) {
             Positions positions;
             positions.insert( Positions::value_type(player1Name, *player1Strategy) );
             positions.insert( Positions::value_type(player2Name, *player2Strategy) );
             player1Payoff += data[positions]->getPayoff(player1Name)->get_d() *
                              player1Distribution[*player1Strategy] *
                              player2Distribution[*player2Strategy];
         }
     }
     double player2Payoff = -player1Payoff;
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     ResultBuilderPtr player1DistributionResult = ResultFactory::getInstance().buildResult();
     for (const IdentifierPtr& player1Strategy : *player1.getStrategies()) {
         const MessagePtr& probability  = createMessagePtr(player1Distribution[*player1Strategy]);
         player1DistributionResult->addResult( player1Strategy, probability );
     }
     ResultBuilderPtr player2DistributionResult = ResultFactory::getInstance().buildResult();
     for (const IdentifierPtr& player2Strategy : *player2.getStrategies()) {
         const MessagePtr& probability  = createMessagePtr(player2Distribution[*player2Strategy]);
         player2DistributionResult->addResult( player2Strategy, probability );
     }
     ResultBuilderPtr mixedStrategiesResult = ResultFactory::getInstance().buildResult();
     mixedStrategiesResult->addResult(
         player1.getName(),
         createMessagePtr( player1DistributionResult->build()->getResult() )
     );
     mixedStrategiesResult->addResult(
         player2.getName(),
         createMessagePtr( player2DistributionResult->build()->getResult() )
     );
     const MessagePtr mixedStrategies = createMessagePtr(mixedStrategiesResult->build()->getResult());
     static const IdentifierPtr mixedStrategiesName = createIdentifierPtr("Mixed Strategies");
     resultBuilder->addResult( mixedStrategiesName, mixedStrategies );
     static const IdentifierPtr payoffName = createIdentifierPtr("Payoff");
     ResultBuilderPtr payoffResult = ResultFactory::getInstance().buildResult();
     IdentifiersPtr   headers      = createIdentifiersPtr();
     headers->push_back( player1.getName() );
     headers->push_back( player2.getName() );
     payoffResult->setHeaders( headers );
     MessagesPtr payoffs = createMessagesPtr();
     payoffs->push_back( createMessagePtr(player1Payoff) );
     payoffs->push_back( createMessagePtr(player2Payoff) );
     payoffResult->addRecord( payoffName, payoffs );
     resultBuilder->addResult( payoffName, createMessagePtr(payoffResult->build()->getResult()) );
     return resultBuilder->build();
 }
Message GT::Routines::MatrixMixedEquilibriumRoutine::toString () const override virtual
Returns Routine's Message.
Returns
Routine's Message
Implements GT::Routines::Routine.
Definition at line 65 of file matrix_mixed_equilibrium_routine.cpp.
{
     return Message("MatrixMixedEquilibriumRoutine");
 }
The documentation for this class was generated from the following files:
src/gt/routines/matrix_mixed_equilibrium_routine.hpp
src/gt/routines/matrix_mixed_equilibrium_routine.cpp