Game Theory Tools (full documentation): GT::Model::AbstractResultBuilder Class Reference
GT::Model::AbstractResultBuilder Class Reference abstract
Common base class of all actual implemetations used in Model.
#include <abstract_result_builder.hpp>
Public Member Functions
AbstractResultBuilder (const Message indentation)
Constructor initiating class with indentation.
virtual ResultBuilder & setHeaders (const IdentifiersPtr &propertiesNames) override
Sets headers used for displaying records.
virtual ResultBuilder & addRecord (const IdentifierPtr &name, const MessagesPtr &propertiesValues) override
Adds record to displayed Result.
virtual ResultBuilder & addResult (const IdentifierPtr &name, const MessagePtr &result) override
Adds single named subresult.
virtual ResultPtr build () const =0
Build Result.
virtual ResultPtr buildRaw () const =0
Build raw Result - one that can be inserted into other results.
virtual Message toString () const override
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Protected Types
typedef std::pair
< IdentifierPtr, MessagesPtr > PartialResult
Type containing name-properties pair.
typedef
boost::container::vector
< PartialResult > PartialResults
Type containing name to properties mapping.
typedef std::pair
< IdentifierPtr, MessagePtr > SubResult
Type containing name-subresult pair.
typedef
boost::container::vector
< SubResult > SubResults
Type containing name to subresult mapping.
Protected Member Functions
void checkPropertyToResultMatching () const
Check whether all records has the same size as headers.
Message addIndent (const Message content) const
Adds indent to the beginning of each line of passes content.
Protected Attributes
IdentifiersPtr propertiesNames
Names of properties.
PartialResults partialResults
Values of declared properties.
SubResults subResults
SubResults.
Message indent
Indent used.
Detailed Description
Common base class of all actual implemetations used in Model.
Implements ResultBuilder interface.
Author
Mateusz Kubuszok
See Also
ResultBuilder
Definition at line 41 of file abstract_result_builder.hpp.
Member Typedef Documentation
typedef std::pair<IdentifierPtr, MessagesPtr> GT::Model::AbstractResultBuilder::PartialResult protected
Type containing name-properties pair.
Definition at line 127 of file abstract_result_builder.hpp.
typedef boost::container::vector<PartialResult> GT::Model::AbstractResultBuilder::PartialResults protected
Type containing name to properties mapping.
Definition at line 131 of file abstract_result_builder.hpp.
typedef std::pair<IdentifierPtr, MessagePtr> GT::Model::AbstractResultBuilder::SubResult protected
Type containing name-subresult pair.
Definition at line 135 of file abstract_result_builder.hpp.
typedef boost::container::vector<SubResult> GT::Model::AbstractResultBuilder::SubResults protected
Type containing name to subresult mapping.
Definition at line 139 of file abstract_result_builder.hpp.
Constructor & Destructor Documentation
GT::Model::AbstractResultBuilder::AbstractResultBuilder (const Message indentation) explicit
Constructor initiating class with indentation.
Parameters
indentation sequence used for indentation
Definition at line 39 of file abstract_result_builder.cpp.
   :
     propertiesNames(new Identifiers()),
     partialResults(),
     subResults(),
     indent(indentation)
     {}
Member Function Documentation
Message GT::Model::AbstractResultBuilder::addIndent (const Message content) const protected
Adds indent to the beginning of each line of passes content.
Parameters
content content that should be indented
Returns
indented content
Definition at line 93 of file abstract_result_builder.cpp.
References indent.
Referenced by GT::Model::JSONResultBuilder::build(), and GT::Model::PlainResultBuilder::buildRaw().
         {
     // do not use boost::container::vector here - it causes memory access violation with split function
     std::vector<Message> lines;
     split(lines, content, is_any_of("\n"));
     bool firstElement = true;
     stringstream result;
     for (Message& line : lines)
         if (!line.empty() && line != "\n") {
             if (!firstElement)
                 result  << endl;
             result << indent << line;
             firstElement = false;
         }
     return result.str();
 }
ResultBuilder & GT::Model::AbstractResultBuilder::addRecord (const IdentifierPtr & name, const MessagesPtr & propertiesValues) override virtual
Adds record to displayed Result.
Results size must match headers size.
Parameters
name name of added record
propertiesValues properties that should be displayed
Returns
refernce to self for chaining
See Also
setHeaders(const IdentifiersPtr&)
Implements GT::Model::ResultBuilder.
Definition at line 55 of file abstract_result_builder.cpp.
References partialResults.
   {
     partialResults.push_back( PartialResults::value_type(name, propertiesValues) );
     return *this;
 }
ResultBuilder & GT::Model::AbstractResultBuilder::addResult (const IdentifierPtr & name, const MessagePtr & result) override virtual
Adds single named subresult.
Parameters
name name subresult is build
result subresult
Returns
reference for itself for chaining
Implements GT::Model::ResultBuilder.
Definition at line 63 of file abstract_result_builder.cpp.
References subResults.
   {
     subResults.push_back( SubResults::value_type(name, result) );
     return *this;
 }
virtual ResultPtr GT::Model::AbstractResultBuilder::build () const pure virtual
Build Result.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages of any Object does not match properties' one
See Also
buildRaw()
Implements GT::Model::ResultBuilder.
Implemented in GT::Model::JSONResultBuilder, GT::Model::PlainResultBuilder, and GT::Model::XMLResultBuilder.
Referenced by toString().
virtual ResultPtr GT::Model::AbstractResultBuilder::buildRaw () const pure virtual
Build raw Result - one that can be inserted into other results.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages of any Object does not match properties' one
See Also
build()
Implements GT::Model::ResultBuilder.
Implemented in GT::Model::JSONResultBuilder, GT::Model::PlainResultBuilder, and GT::Model::XMLResultBuilder.
void GT::Model::AbstractResultBuilder::checkPropertyToResultMatching () const protected
Check whether all records has the same size as headers.
Exceptions
IllegalInnerState thrown when some record does not match headers size
Definition at line 81 of file abstract_result_builder.cpp.
References GT::Model::ExceptionFactory::getInstance(), partialResults, GT::Model::ExceptionFactory::propertiesAndResultsDontMatchInSize(), and propertiesNames.
Referenced by GT::Model::JSONResultBuilder::buildRaw(), GT::Model::XMLResultBuilder::buildRaw(), and GT::Model::PlainResultBuilder::buildRaw().
{
     Index propertiesSize = propertiesNames->size();
     for (const PartialResult& partialResult : partialResults) {
         MessagesPtr checkedProperties = partialResult.second;
         if (checkedProperties->size() != propertiesSize)
             throw ExceptionFactory::getInstance().propertiesAndResultsDontMatchInSize(
                 propertiesSize,
                 checkedProperties->size()
             );
     }
 }
ResultBuilder & GT::Model::AbstractResultBuilder::setHeaders (const IdentifiersPtr & propertiesNames) override virtual
Sets headers used for displaying records.
Size of headers must match size of each record.
Parameters
propertiesNames headers' names that will be used in a Result
Returns
refernce to self for chaining
See Also
addRecord(const IdentifierPtr&, const MessagesPtr&)
Implements GT::Model::ResultBuilder.
Definition at line 48 of file abstract_result_builder.cpp.
References propertiesNames.
   {
     propertiesNames = newPropertiesNames;
     return *this;
 }
Message GT::Model::AbstractResultBuilder::toString () const override virtual
Displays what would be build or error message that would be thrown.
Returns
current result or error message
See Also
build()
Implements GT::Model::Root.
Definition at line 71 of file abstract_result_builder.cpp.
References build().
{
     try {
         return build()->getResult();
     } catch (const IllegalInnerState& e) {
         return Message(e.what());
     }
 }
Member Data Documentation
Message GT::Model::AbstractResultBuilder::indent protected
Indent used.
Definition at line 156 of file abstract_result_builder.hpp.
Referenced by addIndent(), GT::Model::PlainResultBuilder::buildRaw(), and GT::Model::JSONResultBuilder::buildRaw().
PartialResults GT::Model::AbstractResultBuilder::partialResults protected
Values of declared properties.
Definition at line 148 of file abstract_result_builder.hpp.
Referenced by addRecord(), GT::Model::XMLResultBuilder::buildRaw(), GT::Model::PlainResultBuilder::buildRaw(), GT::Model::JSONResultBuilder::buildRaw(), and checkPropertyToResultMatching().
IdentifiersPtr GT::Model::AbstractResultBuilder::propertiesNames protected
Names of properties.
Definition at line 144 of file abstract_result_builder.hpp.
Referenced by GT::Model::JSONResultBuilder::buildRaw(), GT::Model::XMLResultBuilder::buildRaw(), GT::Model::PlainResultBuilder::buildRaw(), checkPropertyToResultMatching(), and setHeaders().
SubResults GT::Model::AbstractResultBuilder::subResults protected
SubResults.
Definition at line 152 of file abstract_result_builder.hpp.
Referenced by addResult(), GT::Model::PlainResultBuilder::buildRaw(), and GT::Model::JSONResultBuilder::buildRaw().
The documentation for this class was generated from the following files:
src/gt/model/abstract_result_builder.hpp
src/gt/model/abstract_result_builder.cpp