Game Theory Tools (full documentation): GT::GTL::ErrorFactory Class Reference
GT::GTL::ErrorFactory Class Reference final
Used for creation of Error instances for GTL classes.
#include <error_factory.hpp>
Public Member Functions
ConditionPtr createCondition (const Message errorMessage) const
Creates ErrorCondition.
CoordinatePtr createCoordinate (const Message errorMessage) const
Creates ErrorCoordinate.
DefinitionPtr createDefinition (const Message errorMessage) const
Creates ErrorDefinition.
DetailsPtr createDetails (const Message errorMessage) const
Creates ErrorDetails.
GamePtr createGame (const Message errorMessage) const
Creates ErrorGame.
ObjectPtr createObject (const Message errorMessage) const
Creates ErrorObject.
ParamPtr createParam (const Message errorMessage) const
Creates ErrorParam.
PlayerPtr createPlayer (const Message errorMessage) const
Creates ErrorPlayer.
QueryPtr createQuery (const Message errorMessage) const
Creates ErrorQuery.
Static Public Member Functions
static ErrorFactory & getInstance ()
Returns the instance of a ErrorFactory.
Private Member Functions
ErrorFactory ()
Default constructor hidden from programmers.
ErrorFactory (const ErrorFactory &errorFactory)
Default copy constructor hidden from programmers.
~ErrorFactory ()
Default destructor hidden from programmers.
Detailed Description
Used for creation of Error instances for GTL classes.
Author
Mateusz Kubuszok
Definition at line 37 of file error_factory.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorFactory::ErrorFactory () private
Default constructor hidden from programmers.
Definition at line 93 of file error_factory.cpp.
 {}
GT::GTL::ErrorFactory::ErrorFactory (const ErrorFactory & errorFactory) private
Default copy constructor hidden from programmers.
Parameters
errorFactory object to copy
GT::GTL::ErrorFactory::~ErrorFactory () private
Default destructor hidden from programmers.
Definition at line 95 of file error_factory.cpp.
 {}
Member Function Documentation
ConditionPtr GT::GTL::ErrorFactory::createCondition (const Message errorMessage) const
Creates ErrorCondition.
Parameters
errorMessage message describing error
Returns
ErrorCondition
Definition at line 37 of file error_factory.cpp.
         {
     return ConditionPtr(new ErrorCondition(errorMessage));
 }
CoordinatePtr GT::GTL::ErrorFactory::createCoordinate (const Message errorMessage) const
Creates ErrorCoordinate.
Parameters
errorMessage message describing error
Returns
ErrorCoordinate
Definition at line 43 of file error_factory.cpp.
         {
     return CoordinatePtr(new ErrorCoordinate(errorMessage));
 }
DefinitionPtr GT::GTL::ErrorFactory::createDefinition (const Message errorMessage) const
Creates ErrorDefinition.
Parameters
errorMessage message describing error
Returns
ErrorDefinition
Definition at line 49 of file error_factory.cpp.
         {
     return DefinitionPtr(new ErrorDefinition(errorMessage));
 }
DetailsPtr GT::GTL::ErrorFactory::createDetails (const Message errorMessage) const
Creates ErrorDetails.
Parameters
errorMessage message describing error
Returns
ErrorDetails
Definition at line 55 of file error_factory.cpp.
         {
     return DetailsPtr(new ErrorDetails(errorMessage));
 }
GamePtr GT::GTL::ErrorFactory::createGame (const Message errorMessage) const
Creates ErrorGame.
Parameters
errorMessage message describing error
Returns
ErrorGame
Definition at line 61 of file error_factory.cpp.
         {
     return GamePtr(new ErrorGame(errorMessage));
 }
ObjectPtr GT::GTL::ErrorFactory::createObject (const Message errorMessage) const
Creates ErrorObject.
Parameters
errorMessage message describing error
Returns
ErrorObject
Definition at line 67 of file error_factory.cpp.
         {
     return ObjectPtr(new ErrorObject(errorMessage));
 }
ParamPtr GT::GTL::ErrorFactory::createParam (const Message errorMessage) const
Creates ErrorParam.
Parameters
errorMessage message describing error
Returns
ErrorParam
Definition at line 73 of file error_factory.cpp.
         {
     return ParamPtr(new ErrorParam(errorMessage));
 }
PlayerPtr GT::GTL::ErrorFactory::createPlayer (const Message errorMessage) const
Creates ErrorPlayer.
Parameters
errorMessage message describing error
Returns
ErrorPlayer
Definition at line 79 of file error_factory.cpp.
         {
     return PlayerPtr(new ErrorPlayer(errorMessage));
 }
QueryPtr GT::GTL::ErrorFactory::createQuery (const Message errorMessage) const
Creates ErrorQuery.
Parameters
errorMessage message describing error
Returns
ErrorQuery
Definition at line 85 of file error_factory.cpp.
         {
     return QueryPtr(new ErrorQuery(errorMessage));
 }
ErrorFactory & GT::GTL::ErrorFactory::getInstance () static
Returns the instance of a ErrorFactory.
Returns
ErrorFactory instance
Definition at line 30 of file error_factory.cpp.
Referenced by GT::GTL::CheckingStatementDriver::createDefinition(), GT::GTL::CheckingGameDriver::createDetails(), GT::GTL::CheckingGameDriver::createExtensive(), GT::GTL::CheckingStatementDriver::createQuery(), GT::GTL::CheckingGameDriver::createStrategic(), GT::GTL::CheckingCoordinateDriver::fillWithData(), GT::GTL::CheckingConditionDriver::informationSetChoosed(), GT::GTL::CheckingConditionDriver::informationSetWithin(), GT::GTL::CheckingCoordinateDriver::merge(), GT::GTL::CheckingConditionDriver::playerChoosed(), and GT::GTL::CheckingConditionDriver::playerWithin().
{
     static ErrorFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/gtl/error_factory.hpp
src/gt/gtl/error_factory.cpp