Game Theory Tools (full documentation): GT::Model::NullPlayer Class Reference
GT::Model::NullPlayer Class Reference final
Null Player for handling invalid situations.
#include <player.hpp>
Public Member Functions
NullPlayer ()
virtual const IdentifierPtr getName () const override
Returns name ot the Player.
virtual const IdentifiersPtr getStrategies () const override
Returns Player's strategies.
virtual Index getStrategiesNumber () const override
Returns number of strategies.
virtual Index getStrategyOrdinal (const Identifier &) const override
Returns ordinal of a strategy with given Identifier.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message with Player's name and strategies.
Public Member Functions inherited from GT::Model::Player
Player (const IdentifierPtr playerName, const IdentifiersPtr playerStrategies)
Constructor of the Player.
virtual bool hasStrategy (const Identifier &strategy) const
Returns whether strategy with such name exists.
virtual bool isEqual (const Root &root) const override
Defines equality relation.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null Player for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 184 of file player.hpp.
Constructor & Destructor Documentation
GT::Model::NullPlayer::NullPlayer () inline
Definition at line 186 of file player.hpp.
                  :
         Player(
             NullFactory::getInstance().createIdentifier(),
             NullFactory::getInstance().createIdentifiers()
         )
         {}
Member Function Documentation
virtual const IdentifierPtr GT::Model::NullPlayer::getName () const inline override virtual
Returns name ot the Player.
Returns
Player's name
Reimplemented from GT::Model::Player.
Definition at line 193 of file player.hpp.
References GT::Model::NullFactory::createIdentifier(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createIdentifier();
     }
virtual const IdentifiersPtr GT::Model::NullPlayer::getStrategies () const inline override virtual
Returns Player's strategies.
Returns
Player's strategies
Reimplemented from GT::Model::Player.
Definition at line 197 of file player.hpp.
References GT::Model::NullFactory::createIdentifiers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createIdentifiers();
     }
virtual Index GT::Model::NullPlayer::getStrategiesNumber () const inline override virtual
Returns number of strategies.
Returns
number of strategies
Reimplemented from GT::Model::Player.
Definition at line 201 of file player.hpp.
{
         return 0;
     }
virtual Index GT::Model::NullPlayer::getStrategyOrdinal (const Identifier & strategy) const inline override virtual
Returns ordinal of a strategy with given Identifier.
Parameters
strategy strategy name
Returns
ordinal of strategy with given Identifier
Exceptions
InvalidCoordinate thrown if Player has no such strategy
Reimplemented from GT::Model::Player.
Definition at line 205 of file player.hpp.
                      {
         return 0;
     }
virtual bool GT::Model::NullPlayer::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 211 of file player.hpp.
{
         return false;
     }
virtual Message GT::Model::NullPlayer::toString () const inline override virtual
Returns Message with Player's name and strategies.
Returns
Player's name and strategies
Reimplemented from GT::Model::Player.
Definition at line 215 of file player.hpp.
{
         return Message("NullPlayer");
     }
The documentation for this class was generated from the following file:
include/gt/model/player.hpp