Game Theory Tools (full documentation): GT::GTL::Details Class Reference
GT::GTL::Details Class Reference
Contains Coordinates as well as defined Players.
#include <details.hpp>
Public Member Functions
Details (const ObjectsPtr playersDetails, const CoordinatesPtr coordinatesDetails)
Constructor for Players with data.
virtual const CoordinatesPtr getCoordinates () const
Returns Coordinates with data.
virtual const ObjectsPtr getPlayers () const
Returns Players definitions.
virtual Message toString () const override
Returns Message about Game details.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const ObjectsPtr players
Players' collection.
const CoordinatesPtr coordinates
Coordinates' collection.
Detailed Description
Contains Coordinates as well as defined Players.
Contains information about Players and Coordinates that will be used to build data.
Author
Mateusz Kubuszok
See Also
GameDriver
Parser
Definition at line 42 of file details.hpp.
Constructor & Destructor Documentation
GT::GTL::Details::Details (const ObjectsPtr playersDetails, const CoordinatesPtr coordinatesDetails)
Constructor for Players with data.
Parameters
playersDetails declared players
coordinatesDetails declared data
Definition at line 31 of file details.cpp.
   :
     players(playersDetails),
     coordinates(coordinatesDetails)
     {}
Member Function Documentation
const CoordinatesPtr GT::GTL::Details::getCoordinates () const virtual
Returns Coordinates with data.
Returns
Coordinates wit data
Reimplemented in GT::GTL::ErrorDetails, and GT::GTL::NullDetails.
Definition at line 39 of file details.cpp.
References coordinates.
Referenced by GT::GTL::ExecutionGameDriver::createGameWithBuilder().
{
     return coordinates;
 }
const ObjectsPtr GT::GTL::Details::getPlayers () const virtual
Returns Players definitions.
Returns
Players definitions
Reimplemented in GT::GTL::ErrorDetails, and GT::GTL::NullDetails.
Definition at line 43 of file details.cpp.
References players.
Referenced by GT::GTL::ExecutionGameDriver::createGameWithBuilder().
{
     return players;
 }
Message GT::GTL::Details::toString () const override virtual
Returns Message about Game details.
Returns
Game Details Message
Implements GT::Model::Root.
Reimplemented in GT::GTL::ErrorDetails, and GT::GTL::NullDetails.
Definition at line 47 of file details.cpp.
References GT::Model::ResultFactory::buildResult(), coordinates, GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), and players.
Referenced by GT::GTL::CheckingGameDriver::createExtensive(), and GT::GTL::CheckingGameDriver::createStrategic().
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     static const IdentifierPtr playersName = createIdentifierPtr("Players");
     static const IdentifierPtr playerName  = createIdentifierPtr("Player");
     ResultBuilderPtr playersResultBuilder  = ResultFactory::getInstance().buildResult();
     for (const ObjectPtr& player : *players) {
         MessagePtr playerValue = createMessagePtr(player->toString());
         playersResultBuilder->addResult(playerName, playerValue);
     }
     MessagePtr playersValue = createMessagePtr(playersResultBuilder->build()->getResult());
     resultBuilder->addResult(playersName, playersValue);
     static const IdentifierPtr coordinatesName = createIdentifierPtr("Coordinates");
     static const IdentifierPtr coordinateName  = createIdentifierPtr("Coordinate");
     ResultBuilderPtr coordinatesResultBuilder  = ResultFactory::getInstance().buildResult();
     for (const CoordinatePtr& coordinate : *coordinates) {
         MessagePtr coordinateValue = createMessagePtr(coordinate->toString());
         coordinatesResultBuilder->addResult(coordinateName, coordinateValue);
     }
     MessagePtr coordinatesValue = createMessagePtr(coordinatesResultBuilder->build()->getResult());
     resultBuilder->addResult(coordinatesName, coordinatesValue);
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
const CoordinatesPtr GT::GTL::Details::coordinates private
Coordinates' collection.
Definition at line 51 of file details.hpp.
Referenced by getCoordinates(), and toString().
const ObjectsPtr GT::GTL::Details::players private
Players' collection.
Definition at line 46 of file details.hpp.
Referenced by getPlayers(), and toString().
The documentation for this class was generated from the following files:
include/gt/gtl/details.hpp
src/gt/gtl/details.cpp