Game Theory Tools (full documentation): GT::Model::PlainDataPiece Class Reference
GT::Model::PlainDataPiece Class Reference final
Used to store values at lowest level.
#include <plain_data_piece.hpp>
Public Member Functions
PlainDataPiece (const PlayersPtr players, const NumbersPtr params)
Constructor initiated with Players and params definitions.
virtual const NumberPtr & getPayoff (const Identifier &playerName) const override
Returns Player's payoff by its name.
virtual Message toString () const override
Returns PlainDataPiece's Message.
Public Member Functions inherited from GT::Model::DataPiece
const NumberPtr & getPayoff (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
const NumberPtr & operator[] (const Identifier &playerName) const
Returns Player's payoff by its name.
const NumberPtr & operator[] (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
StrategicGamePositionsHelper positionsHelper
StrategicGamePositionsHelper used to properly locate Index in storage.
NumbersPtr numbers
Values of payoff.
Detailed Description
Used to store values at lowest level.
Implements DataPiece interface.
Author
Mateusz Kubuszok
See Also
DataPiece
Data
DataAccessor
Definition at line 43 of file plain_data_piece.hpp.
Constructor & Destructor Documentation
GT::Model::PlainDataPiece::PlainDataPiece (const PlayersPtr players, const NumbersPtr params)
Constructor initiated with Players and params definitions.
Parameters
players Players definitions
params params definitions
Definition at line 35 of file plain_data_piece.cpp.
   :
     positionsHelper(players),
     numbers(params)
     {}
Member Function Documentation
const NumberPtr & GT::Model::PlainDataPiece::getPayoff (const Identifier & playerName) const override virtual
Returns Player's payoff by its name.
Parameters
playerName name of Player for which payoff is required
Returns
value of a payoff
Exceptions
InvalidCoordinate thrown when player name is not known
Implements GT::Model::DataPiece.
Definition at line 43 of file plain_data_piece.cpp.
References GT::Model::StrategicGamePositionsHelper::calculatePlayer(), GT::Model::StrategicGamePositionsHelper::checkPlayer(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidPlayer(), numbers, and positionsHelper.
         {
     if (!positionsHelper.checkPlayer(playerName))
         throw ExceptionFactory::getInstance().invalidPlayer(playerName);
     return (*numbers)[positionsHelper.calculatePlayer(playerName)];
 }
Message GT::Model::PlainDataPiece::toString () const override virtual
Returns PlainDataPiece's Message.
Returns
Message
Implements GT::Model::DataPiece.
Definition at line 51 of file plain_data_piece.cpp.
References GT::Model::ResultFactory::buildResult(), GT::Model::StrategicGamePositionsHelper::calculatePlayer(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), GT::Model::StrategicGamePositionsHelper::getPlayers(), numbers, and positionsHelper.
{
     static const IdentifierPtr  name = createIdentifierPtr("Payoff");
     const IdentifiersPtr        players(new Identifiers());
     const MessagesPtr           values(new Messages());
     for (Identifier playerName : (*positionsHelper.getPlayers()) | map_keys) {
         players->push_back( createIdentifierPtr(playerName) );
         values->push_back( createMessagePtr((*numbers)[positionsHelper.calculatePlayer(playerName)]) );
     }
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     resultBuilder->setHeaders(players).addRecord( name, values );
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
NumbersPtr GT::Model::PlainDataPiece::numbers private
Values of payoff.
Definition at line 51 of file plain_data_piece.hpp.
Referenced by getPayoff(), and toString().
StrategicGamePositionsHelper GT::Model::PlainDataPiece::positionsHelper private
StrategicGamePositionsHelper used to properly locate Index in storage.
Definition at line 47 of file plain_data_piece.hpp.
Referenced by getPayoff(), and toString().
The documentation for this class was generated from the following files:
src/gt/model/plain_data_piece.hpp
src/gt/model/plain_data_piece.cpp