Game Theory Tools (full documentation): GT::Model::StrategicDataBuilder Class Reference
GT::Model::StrategicDataBuilder Class Reference final
Builder used for creating StrategicGame's Data.
#include <strategic_data_builder.hpp>
Public Member Functions
StrategicDataBuilder ()
Defalt constructor.
StrategicDataPtr build () const
Returns set up Data.
const PlayersPtr getPlayers () const
Returns Players' definitions.
virtual DataBuilder & setPlayers (const PlayersPtr newPlayers) override
Sets Players' definitions.
virtual DataBuilder & addNextPositions (const PositionsPtr positions) override
Specifies next Positions.
virtual DataBuilder & setPayoffs (const NumbersPtr params) override
Sets payoffs values.
virtual DataBuilderPtr clone () const override
Returns copy of itsef with shared content and frozen values of already set Positions.
virtual Message toString () const override
StrategicDataBuilder Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier, bool > KnownPositions
Type containing information whether some player-strategy pair is already known.
Private Attributes
StrategicDataPtr data
Actual data.
PlayersPtr players
Players.
Positions currentPositions
Currently known Positions.
KnownPositions currentlyKnownPositions
Information which Positions are already known.
Detailed Description
Builder used for creating StrategicGame's Data.
Games in this form should have all coordinates filled with payoffs. Since all Players and their strategies are known beforehand, positions can also be hashed to Indexes with StrategicGamePositionsHelper.
Author
Mateusz Kubuszok
See Also
StrategicData
StrategicGamePositionsHelper
Definition at line 48 of file strategic_data_builder.hpp.
Member Typedef Documentation
typedef map<Identifier, bool> GT::Model::StrategicDataBuilder::KnownPositions private
Type containing information whether some player-strategy pair is already known.
Definition at line 52 of file strategic_data_builder.hpp.
Constructor & Destructor Documentation
GT::Model::StrategicDataBuilder::StrategicDataBuilder ()
Defalt constructor.
Definition at line 35 of file strategic_data_builder.cpp.
Referenced by clone().
                                            :
     data(InnerNullFactory::getInstance().createStrategicData()),
     players(NullFactory::getInstance().createPlayers()),
     currentPositions(),
     currentlyKnownPositions()
     {}
Member Function Documentation
DataBuilder & GT::Model::StrategicDataBuilder::addNextPositions (const PositionsPtr positions) override virtual
Specifies next Positions.
Parameters
positions next Positions to specify
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 62 of file strategic_data_builder.cpp.
References GT::Model::ExceptionFactory::coordinatesAlreadySet(), currentlyKnownPositions, currentPositions, GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), and players.
   {
     for (Positions::value_type& position : (*positions)) {
         if (currentlyKnownPositions.count(position.first) && currentlyKnownPositions[position.first])
             throw ExceptionFactory::getInstance().coordinatesAlreadySet(*positions);
         if (!(*players)[position.first]->hasStrategy(position.second))
             throw ExceptionFactory::getInstance().invalidCoordinateFormat(*positions);
     }
     for (Positions::value_type& position : (*positions)) {
         currentPositions.insert( position );
         currentlyKnownPositions.insert( KnownPositions::value_type(position.first, true) );
     }
     return *this;
 }
StrategicDataPtr GT::Model::StrategicDataBuilder::build () const
Returns set up Data.
Returns
built Data
Definition at line 42 of file strategic_data_builder.cpp.
References data.
{
     return data;
 }
DataBuilderPtr GT::Model::StrategicDataBuilder::clone () const override virtual
Returns copy of itsef with shared content and frozen values of already set Positions.
Returns
copy with frozem Positions and content common to parent
Implements GT::Model::DataBuilder.
Definition at line 92 of file strategic_data_builder.cpp.
References StrategicDataBuilder().
{
     return DataBuilderPtr(new StrategicDataBuilder(*this));
 }
const PlayersPtr GT::Model::StrategicDataBuilder::getPlayers () const
Returns Players' definitions.
Returns
Players' definitions
Definition at line 46 of file strategic_data_builder.cpp.
References players.
{
     return players;
 }
DataBuilder & GT::Model::StrategicDataBuilder::setPayoffs (const NumbersPtr params) override virtual
Sets payoffs values.
Parameters
params values of payoffs
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 80 of file strategic_data_builder.cpp.
References currentlyKnownPositions, currentPositions, data, GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::incompleteCoordinates(), and players.
   {
     for (Identifier player : (*players) | map_keys)
         if (!currentlyKnownPositions.count(player) || !currentlyKnownPositions[player])
             throw ExceptionFactory::getInstance().incompleteCoordinates();
     data->setPayoffs(currentPositions, params);
     return *this;
 }
DataBuilder & GT::Model::StrategicDataBuilder::setPlayers (const PlayersPtr newPlayers) override virtual
Sets Players' definitions.
Parameters
newPlayers Players' definitions
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 50 of file strategic_data_builder.cpp.
References data, GT::Model::ExceptionFactory::getInstance(), players, and GT::Model::ExceptionFactory::playersAlreadySet().
   {
     if (data->isNotNull())
         throw ExceptionFactory::getInstance().playersAlreadySet();
     data    = StrategicDataPtr(new StrategicData(newPlayers));
     players = newPlayers;
     return *this;
 }
Message GT::Model::StrategicDataBuilder::toString () const override virtual
StrategicDataBuilder Message.
Returns
Message
Implements GT::Model::DataBuilder.
Definition at line 96 of file strategic_data_builder.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), data, and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name    = createIdentifierPtr("Current Data");
     const MessagePtr           message = createMessagePtr(data->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, message).build()->getResult();
 }
Member Data Documentation
KnownPositions GT::Model::StrategicDataBuilder::currentlyKnownPositions private
Information which Positions are already known.
Definition at line 71 of file strategic_data_builder.hpp.
Referenced by addNextPositions(), and setPayoffs().
Positions GT::Model::StrategicDataBuilder::currentPositions private
Currently known Positions.
Definition at line 67 of file strategic_data_builder.hpp.
Referenced by addNextPositions(), and setPayoffs().
StrategicDataPtr GT::Model::StrategicDataBuilder::data private
Actual data.
Definition at line 57 of file strategic_data_builder.hpp.
Referenced by build(), setPayoffs(), setPlayers(), and toString().
PlayersPtr GT::Model::StrategicDataBuilder::players private
Players.
Definition at line 62 of file strategic_data_builder.hpp.
Referenced by addNextPositions(), getPlayers(), setPayoffs(), and setPlayers().
The documentation for this class was generated from the following files:
src/gt/model/strategic_data_builder.hpp
src/gt/model/strategic_data_builder.cpp