Game Theory Tools (full documentation): GT::GTL::LazyGameProxy Class Reference
GT::GTL::LazyGameProxy Class Reference final
Makes Game act in functional manner by building it from scratch each time some property is required.
#include <lazy_game_proxy.hpp>
Public Member Functions
LazyGameProxy (const GameBuilderPtr gameBuilder, const ObjectsPtr players, const CoordinatesPtr coordinates, const Context *context)
Initiates lazy proxy with data required to instantiate Game.
const CoordinatesPtr getCoordinates () const
Grants access to Coordinates used to build Game on request.
const ObjectsPtr getPlayersParams () const
Grants access to Players' Params used to build Game on request.
virtual const Model::PlayersPtr getPlayers () const override
Returns Game's Players.
virtual const DataAccessorPtr getData () const override
Grants access to Data specific to a Game.
virtual Message toString () const override
Game's Message.
Public Member Functions inherited from GT::Model::Game
virtual bool isEqual (const Root &root) const override
Defines equality relation.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
const Model::GamePtr accessGame () const
Create temporary instance of Game.
Private Attributes
const GameBuilderPtr gameBuilder
Actual Game's builder.
const ObjectsPtr players
Players.
const CoordinatesPtr coordinates
Coordinates to setup data.
const Context * context
Context.
Detailed Description
Makes Game act in functional manner by building it from scratch each time some property is required.
Author
Mateusz Kubuszok
See Also
Model::Game
Model::GameBuilder
Coordinate
Context
Definition at line 47 of file lazy_game_proxy.hpp.
Constructor & Destructor Documentation
GT::GTL::LazyGameProxy::LazyGameProxy (const GameBuilderPtr gameBuilder, const ObjectsPtr players, const CoordinatesPtr coordinates, const Context * context)
Initiates lazy proxy with data required to instantiate Game.
Parameters
gameBuilder builder that will create Game
players Players definitions
coordinates Cooridnates with payoff
context actual Context
Definition at line 40 of file lazy_game_proxy.cpp.
   :
     gameBuilder(definedGameBuilder),
     players(definedPlayers),
     coordinates(definedCoordinates),
     context(definedContext)
     {}
Member Function Documentation
const Model::GamePtr GT::GTL::LazyGameProxy::accessGame () const private
Create temporary instance of Game.
Returns
Games instance
Definition at line 74 of file lazy_game_proxy.cpp.
References context, coordinates, GT::createIdentifier(), gameBuilder, GT::GTL::ExceptionFactory::getInstance(), GT::Model::Player::getName(), GT::GTL::Param::getObject(), GT::GTL::ExceptionFactory::invalidObjectType(), players, GT::GTL::Param::toParam(), and GT::GTL::Player::toPlayer().
Referenced by getData(), getPlayers(), and toString().
{
     GameBuilderPtr currentGameBuilder = gameBuilder->cloneBuilder();
     PlayersPtr modelPlayers(new Players());
     for (const ObjectPtr& objectPtr : *players) {
         const Player& player = objectPtr->toPlayer();
         const Param&  param  = objectPtr->toParam();
         if (player) {
             const PlayerPtr playerPtr = dynamic_pointer_cast<Player>(objectPtr);
             if (playerPtr) {
                 modelPlayers->insert(
                     Players::value_type(
                         *player.getName(),
                         dynamic_pointer_cast<Model::Player>(playerPtr)
                     )
                 );
                 continue;
             }
         }
         if (param) {
             const ObjectPtr referredObject = param.getObject(*context);
             const Player&   referredPlayer = referredObject->toPlayer();
             if (referredPlayer) {
                 PlayerPtr playerPtr = dynamic_pointer_cast<Player>(objectPtr);
                 modelPlayers->insert(
                     Players::value_type(
                         *referredPlayer.getName(),
                         dynamic_pointer_cast<Model::Player>(referredObject)
                     )
                 );
                 continue;
             }
         }
         static const Identifier typeName = createIdentifier("Player");
         throw ExceptionFactory::getInstance().invalidObjectType(typeName);
     }
     currentGameBuilder->dataBuilder()->setPlayers(modelPlayers);
     for (const CoordinatePtr& coordinate : *coordinates) {
         DataBuilderPtr builderForCoordinate = currentGameBuilder->clone();
         coordinate->fillDataBuilder(*context, builderForCoordinate);
     }
     return currentGameBuilder->build();
 }
const CoordinatesPtr GT::GTL::LazyGameProxy::getCoordinates () const
Grants access to Coordinates used to build Game on request.
Returns
Coordinates stored inside proxy
Definition at line 52 of file lazy_game_proxy.cpp.
References coordinates.
{
     return coordinates;
 }
const Model::DataAccessorPtr GT::GTL::LazyGameProxy::getData () const override virtual
Grants access to Data specific to a Game.
Returns
DataAccessor returns DataAccessor specific for a Game
Implements GT::Model::Game.
Definition at line 64 of file lazy_game_proxy.cpp.
References accessGame().
{
     return accessGame()->getData();
 }
const PlayersPtr GT::GTL::LazyGameProxy::getPlayers () const override virtual
Returns Game's Players.
Returns
Players
Implements GT::Model::Game.
Definition at line 60 of file lazy_game_proxy.cpp.
References accessGame().
{
     return accessGame()->getPlayers();
 }
const ObjectsPtr GT::GTL::LazyGameProxy::getPlayersParams () const
Grants access to Players' Params used to build Game on request.
Returns
Objects stored inside proxy
Definition at line 56 of file lazy_game_proxy.cpp.
References players.
Referenced by GT::GTL::Game::serialize().
{
     return players;
 }
Message GT::GTL::LazyGameProxy::toString () const override virtual
Game's Message.
Returns
message
Implements GT::Model::Game.
Definition at line 68 of file lazy_game_proxy.cpp.
References accessGame().
{
     return accessGame()->toString();
 }
Member Data Documentation
const Context* GT::GTL::LazyGameProxy::context private
Context.
Definition at line 63 of file lazy_game_proxy.hpp.
Referenced by accessGame().
const CoordinatesPtr GT::GTL::LazyGameProxy::coordinates private
Coordinates to setup data.
Definition at line 59 of file lazy_game_proxy.hpp.
Referenced by accessGame(), and getCoordinates().
const GameBuilderPtr GT::GTL::LazyGameProxy::gameBuilder private
Actual Game's builder.
Definition at line 51 of file lazy_game_proxy.hpp.
Referenced by accessGame().
const ObjectsPtr GT::GTL::LazyGameProxy::players private
Players.
Definition at line 55 of file lazy_game_proxy.hpp.
Referenced by accessGame(), and getPlayersParams().
The documentation for this class was generated from the following files:
src/gt/gtl/lazy_game_proxy.hpp
src/gt/gtl/lazy_game_proxy.cpp