Game Theory Tools (full documentation): GT::Program::ProgramController Class Reference
GT::Program::ProgramController Class Reference final
Sets up Parser and runs it.
#include <program_controller.hpp>
Public Member Functions
ProgramController ()
Initiates controller with default settings.
virtual ~ProgramController ()
Default destructor - frees resources if necessary.
ProgramController & setCheckingOnly ()
Sets used driver to Checking Driver.
ProgramController & setCheckingAndExecution ()
Sets used driver to Execution Driver.
ProgramController & setDebugLevel (int debugLevel)
Sets debug level.
ProgramController & setDefaultInputStream ()
Sets used input stream to standard input stream.
ProgramController & setInputStream (const string filename)
Sets used input stream to file input stream.
ProgramController & setInputStream (InputStream *inputStream, bool shouldBeFreed, bool isInteractive)
Sets used input stream to given input stream.
ProgramController & setDefaultOutputStream ()
Sets used output stream to standard output stream.
ProgramController & setOutputStream (const string filename)
Sets used output stream to file output stream.
ProgramController & setOutputStream (OutputStream *outputStream, bool shouldBeFreed)
Sets used output stream to given output stream.
ProgramController & setDefaultErrorStream ()
Sets used error stream to standard error stream.
ProgramController & setErrorStream (const string filename)
Sets used error stream to file output stream.
ProgramController & setErrorStream (OutputStream *errorStream, bool shouldBeFreed)
Sets used error stream to given error stream.
ProgramController & setResultBuilderMode (const ResultBuilderMode resultBuilderMode)
Defines type of returned result (output).
ProgramController & setResultIndentationMode (const ResultIndentationMode resultIndentationMode)
Defines type of used indentation (output).
int run () const
Executes Parser as a program.
Private Attributes
int debugLevel
Debug level - if its different to 0 parser messages are shown.
bool shouldExecute
Whether ExcutionDriver should be used instead of CheckingDriver.
InputStream * inputStream
Pointer to input stream.
OutputStream * outputStream
Pointer to output stream.
OutputStream * errorStream
Pointer to error stream.
bool isInteractiveInput
Whether input stream is interactive (read from std input).
bool shouldFreeInputStream
Whether input stream need to be released after usage.
bool shouldFreeOutputStream
Whether output stream need to be released after usage.
bool shouldFreeErrorStream
Whether error stream need to be released after usage.
ResultBuilderMode resultBuilderMode
Contains current Builder Mode setting.
ResultIndentationMode resultIndentationMode
Contains current Indentation Mode setting.
Detailed Description
Sets up Parser and runs it.
Author
Mateusz Kubuszok
See Also
GTL::Parser
Definition at line 46 of file program_controller.hpp.
Constructor & Destructor Documentation
GT::Program::ProgramController::ProgramController ()
Initiates controller with default settings.
By default stream are set to standard ones (without freeing), debug level is set to 0 and driver executes input.
Definition at line 49 of file program_controller.cpp.
                                      :
     debugLevel(0),
     shouldExecute(true),
     inputStream(&cin),
     outputStream(&cout),
     errorStream(&cerr),
     isInteractiveInput(true),
     shouldFreeInputStream(false),
     shouldFreeOutputStream(false),
     shouldFreeErrorStream(false),
     resultBuilderMode(ResultBuilderMode::PLAIN),
     resultIndentationMode(ResultIndentationMode::TABS)
     {}
GT::Program::ProgramController::~ProgramController () virtual
Default destructor - frees resources if necessary.
Definition at line 63 of file program_controller.cpp.
References errorStream, inputStream, outputStream, shouldFreeErrorStream, shouldFreeInputStream, and shouldFreeOutputStream.
{
     if (inputStream != nullptr && shouldFreeInputStream)
         delete inputStream;
     if (outputStream != nullptr && shouldFreeOutputStream)
         delete outputStream;
     if (errorStream != nullptr && shouldFreeErrorStream)
         delete errorStream;
 }
Member Function Documentation
int GT::Program::ProgramController::run () const
Executes Parser as a program.
Returns
0 of no error occurred, number of errors otherwise
Definition at line 182 of file program_controller.cpp.
References debugLevel, errorStream, inputStream, isInteractiveInput, outputStream, resultBuilderMode, resultIndentationMode, and shouldExecute.
Referenced by main().
{
     ResultFactory::getInstance()
         .setBuilderMode(resultBuilderMode)
         .setIndentationMode(resultIndentationMode);
     DriverPtr driver(
         shouldExecute ?
         DriverFactory::getInstance().createExecutionDriver(outputStream, errorStream) :
         DriverFactory::getInstance().createCheckingDriver(errorStream)
     );
     Scanner scanner(inputStream);
     scanner.setInteractive(isInteractiveInput);
     Parser  parser(scanner, *driver);
     parser.set_debug_level(debugLevel);
     return parser.parse();
 }
ProgramController & GT::Program::ProgramController::setCheckingAndExecution ()
Sets used driver to Execution Driver.
Returns
reference to itself for chaining
Definition at line 79 of file program_controller.cpp.
References shouldExecute.
{
     shouldExecute = true;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setCheckingOnly ()
Sets used driver to Checking Driver.
Returns
reference to itself for chaining
Definition at line 74 of file program_controller.cpp.
References shouldExecute.
{
     shouldExecute = false;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setDebugLevel (int debugLevel)
Sets debug level.
Parameters
debugLevel new debug level
Returns
reference to itself for chaining
Definition at line 84 of file program_controller.cpp.
References debugLevel.
Referenced by main().
   {
     debugLevel = newDebugLevel;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setDefaultErrorStream ()
Sets used error stream to standard error stream.
Returns
reference to itself for chaining
Definition at line 143 of file program_controller.cpp.
References setErrorStream().
Referenced by main().
{
     return setErrorStream(&cerr, false);
 }
ProgramController & GT::Program::ProgramController::setDefaultInputStream ()
Sets used input stream to standard input stream.
Returns
reference to itself for chaining
Definition at line 91 of file program_controller.cpp.
References setInputStream().
Referenced by main().
{
     return setInputStream(&cin, false, true);
 }
ProgramController & GT::Program::ProgramController::setDefaultOutputStream ()
Sets used output stream to standard output stream.
Returns
reference to itself for chaining
Definition at line 118 of file program_controller.cpp.
References setOutputStream().
Referenced by main().
{
     return setOutputStream(&cout, false);
 }
ProgramController & GT::Program::ProgramController::setErrorStream (const string filename)
Sets used error stream to file output stream.
Parameters
filename name of file to write
Returns
reference to itself for chaining
Definition at line 147 of file program_controller.cpp.
Referenced by main(), and setDefaultErrorStream().
   {
     ofstream* newErrorStream = new ofstream();
     newErrorStream->open(filename); // TODO error checking
     return setErrorStream(newErrorStream, true);
 }
ProgramController & GT::Program::ProgramController::setErrorStream (OutputStream * errorStream, bool shouldBeFreed)
Sets used error stream to given error stream.
Parameters
errorStream name of new error stream
shouldBeFreed whether resource should be freed after usage
Returns
reference to itself for chaining
Definition at line 155 of file program_controller.cpp.
References errorStream, and shouldFreeErrorStream.
   {
     if (errorStream != nullptr && shouldFreeErrorStream)
         delete errorStream;
     errorStream           = newErrorStream;
     shouldFreeErrorStream = shouldFreeStream;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setInputStream (const string filename)
Sets used input stream to file input stream.
Parameters
filename name of file to read
Returns
reference to itself for chaining
Definition at line 95 of file program_controller.cpp.
Referenced by main(), and setDefaultInputStream().
   {
     ifstream* newInputStream = new ifstream();
     newInputStream->open(filename); // TODO error checking
     return setInputStream(newInputStream, true, false);
 }
ProgramController & GT::Program::ProgramController::setInputStream (InputStream * inputStream, bool shouldBeFreed, bool isInteractive)
Sets used input stream to given input stream.
Parameters
inputStream name of new input stream
shouldBeFreed whether resource should be freed after usage
isInteractive whether input should be treated as interactive
Returns
reference to itself for chaining
Definition at line 103 of file program_controller.cpp.
References inputStream, isInteractiveInput, and shouldFreeInputStream.
   {
     if (inputStream != nullptr && shouldFreeInputStream)
         delete inputStream;
     inputStream           = newInputStream;
     shouldFreeInputStream = shouldFreeStream;
     isInteractiveInput    = isInteractive;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setOutputStream (const string filename)
Sets used output stream to file output stream.
Parameters
filename name of file to write
Returns
reference to itself for chaining
Definition at line 122 of file program_controller.cpp.
Referenced by main(), and setDefaultOutputStream().
   {
     ofstream* newOutputStream = new ofstream();
     newOutputStream->open(filename); // TODO error checking
     return setOutputStream(newOutputStream, true);
 }
ProgramController & GT::Program::ProgramController::setOutputStream (OutputStream * outputStream, bool shouldBeFreed)
Sets used output stream to given output stream.
Parameters
outputStream name of new output stream
shouldBeFreed whether resource should be freed after usage
Returns
reference to itself for chaining
Definition at line 130 of file program_controller.cpp.
References outputStream, and shouldFreeOutputStream.
   {
     if (outputStream != nullptr && shouldFreeOutputStream)
         delete outputStream;
     outputStream           = newOutputStream;
     shouldFreeOutputStream = shouldFreeStream;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setResultBuilderMode (const ResultBuilderMode resultBuilderMode)
Defines type of returned result (output).
Parameters
resultBuilderMode new builder mode
Returns
reference to itself for chaining
Definition at line 168 of file program_controller.cpp.
References resultBuilderMode.
Referenced by main().
   {
     resultBuilderMode = newResultBuilderMode;
     return *this;
 }
ProgramController & GT::Program::ProgramController::setResultIndentationMode (const ResultIndentationMode resultIndentationMode)
Defines type of used indentation (output).
Parameters
resultIndentationMode new indentation mode
Returns
reference to itself for chaining
Definition at line 175 of file program_controller.cpp.
References resultIndentationMode.
Referenced by main().
   {
     resultIndentationMode = newResultIndentationMode;
     return *this;
 }
Member Data Documentation
int GT::Program::ProgramController::debugLevel private
Debug level - if its different to 0 parser messages are shown.
Definition at line 50 of file program_controller.hpp.
Referenced by run(), and setDebugLevel().
OutputStream* GT::Program::ProgramController::errorStream private
Pointer to error stream.
Definition at line 67 of file program_controller.hpp.
Referenced by run(), setErrorStream(), and ~ProgramController().
InputStream* GT::Program::ProgramController::inputStream private
Pointer to input stream.
Definition at line 59 of file program_controller.hpp.
Referenced by run(), setInputStream(), and ~ProgramController().
bool GT::Program::ProgramController::isInteractiveInput private
Whether input stream is interactive (read from std input).
Definition at line 72 of file program_controller.hpp.
Referenced by run(), and setInputStream().
OutputStream* GT::Program::ProgramController::outputStream private
Pointer to output stream.
Definition at line 63 of file program_controller.hpp.
Referenced by run(), setOutputStream(), and ~ProgramController().
ResultBuilderMode GT::Program::ProgramController::resultBuilderMode private
Contains current Builder Mode setting.
Definition at line 90 of file program_controller.hpp.
Referenced by run(), and setResultBuilderMode().
ResultIndentationMode GT::Program::ProgramController::resultIndentationMode private
Contains current Indentation Mode setting.
Definition at line 95 of file program_controller.hpp.
Referenced by run(), and setResultIndentationMode().
bool GT::Program::ProgramController::shouldExecute private
Whether ExcutionDriver should be used instead of CheckingDriver.
Definition at line 54 of file program_controller.hpp.
Referenced by run(), setCheckingAndExecution(), and setCheckingOnly().
bool GT::Program::ProgramController::shouldFreeErrorStream private
Whether error stream need to be released after usage.
Definition at line 85 of file program_controller.hpp.
Referenced by setErrorStream(), and ~ProgramController().
bool GT::Program::ProgramController::shouldFreeInputStream private
Whether input stream need to be released after usage.
Definition at line 77 of file program_controller.hpp.
Referenced by setInputStream(), and ~ProgramController().
bool GT::Program::ProgramController::shouldFreeOutputStream private
Whether output stream need to be released after usage.
Definition at line 81 of file program_controller.hpp.
Referenced by setOutputStream(), and ~ProgramController().
The documentation for this class was generated from the following files:
include/gt/program/program_controller.hpp
src/gt/program/program_controller.cpp