Game Theory Tools (full documentation): GT::Model::ExtensiveDataAccessor Class Reference
GT::Model::ExtensiveDataAccessor Class Reference final
Allows to access data specific for Game in a tree form.
#include <extensive_data_accessor.hpp>
Public Member Functions
ExtensiveDataAccessor (const ExtensiveDataPtr gameData)
Initiates accessor with a ExtensiveData.
virtual const ExtensiveDataNodePtr getRoot () const
Returns root of ExtensiveData tree.
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual const DataPiecePtr getPayoffs (const PositionsPtr positions) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const Positions &positions) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const Positions &positions) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const PositionsPtr positions) const override
Returns DataPiece that gives access to payoffs.
virtual Message toString () const override
Returns ExtensiveDataAccessor Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const ExtensiveDataPtr data
Actual data.
Detailed Description
Allows to access data specific for Game in a tree form.
Games in this form has all payoffs defined in nodes of a game tree. Each node of that tree has assigned Player. As such each SubCoordinates is mapped to strategy of the same Player.
Author
Mateusz Kubuszok
See Also
DataAccessor
Data
DataPiece
ExtensiveData
ExtensiveDataPiece
ExtensiveDataBuilder
Definition at line 47 of file extensive_data_accessor.hpp.
Constructor & Destructor Documentation
GT::Model::ExtensiveDataAccessor::ExtensiveDataAccessor (const ExtensiveDataPtr gameData) explicit
Initiates accessor with a ExtensiveData.
Parameters
gameData ExtensiveData
Definition at line 31 of file extensive_data_accessor.cpp.
   :
     data(strategicData)
     {}
Member Function Documentation
const DataPiecePtr GT::Model::ExtensiveDataAccessor::getPayoffs (const PositionsPtr positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::DataAccessor.
Definition at line 45 of file extensive_data_accessor.cpp.
References data.
         {
     return data->getPayoffs(positions);
 }
const DataPiecePtr GT::Model::ExtensiveDataAccessor::getPayoffs (const Positions & positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::DataAccessor.
Definition at line 51 of file extensive_data_accessor.cpp.
References data.
         {
     return data->getPayoffs(positions);
 }
const PlayersPtr GT::Model::ExtensiveDataAccessor::getPlayers () const override virtual
Returns Players' definitions.
Returns
Players' definitions
Implements GT::Model::DataAccessor.
Definition at line 41 of file extensive_data_accessor.cpp.
References data.
{
     return data->getPlayers();
 }
const ExtensiveDataNodePtr GT::Model::ExtensiveDataAccessor::getRoot () const virtual
Returns root of ExtensiveData tree.
Returns
root
Definition at line 37 of file extensive_data_accessor.cpp.
References data.
{
     return data->getRoot();
 }
const DataPiecePtr GT::Model::ExtensiveDataAccessor::operator[] (const Positions & positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::DataAccessor.
Definition at line 63 of file extensive_data_accessor.cpp.
References data.
         {
     return (*data)[positions];
 }
const DataPiecePtr GT::Model::ExtensiveDataAccessor::operator[] (const PositionsPtr positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::DataAccessor.
Definition at line 69 of file extensive_data_accessor.cpp.
References data.
         {
     return (*data)[positions];
 }
Message GT::Model::ExtensiveDataAccessor::toString () const override virtual
Returns ExtensiveDataAccessor Message.
Returns
Message
Implements GT::Model::DataAccessor.
Definition at line 57 of file extensive_data_accessor.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), data, and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name      = createIdentifierPtr("Extensive Data Accessor");
     const MessagePtr           subresult = createMessagePtr(data->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, subresult).build()->getResult();
 }
Member Data Documentation
const ExtensiveDataPtr GT::Model::ExtensiveDataAccessor::data private
Actual data.
Definition at line 51 of file extensive_data_accessor.hpp.
Referenced by getPayoffs(), getPlayers(), getRoot(), operator[](), and toString().
The documentation for this class was generated from the following files:
src/gt/model/extensive_data_accessor.hpp
src/gt/model/extensive_data_accessor.cpp