Game Theory Tools (public API): GT::GTL::NullConditionDriver Class Reference
GT::GTL::NullConditionDriver Class Reference final
Null ConditionDriver for handling invalid situations.
#include <condition_driver.hpp>
Public Member Functions
NullConditionDriver ()
virtual ConditionPtr * informationSetChoosed (const InputLocation &inputLocation, const ObjectPtr *, const ObjectPtr *, const ObjectPtr *) const override
Create condition for Player choosing strategy in information set.
virtual ConditionPtr * informationSetWithin (const InputLocation &inputLocation, const ObjectPtr *, const ObjectPtr *, const ObjectsPtr *) const override
Create condition for Player limiting allowed strategies in information set.
virtual ConditionPtr * playerChoosed (const InputLocation &inputLocation, const ObjectPtr *, const ObjectPtr *) const override
Create condition for Player choosing strategy.
virtual ConditionPtr * playerWithin (const InputLocation &inputLocation, const ObjectPtr *, const ObjectsPtr *) const override
Create condition for Player limiting allowed strategies.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
ConditionDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null ConditionDriver for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 115 of file condition_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::NullConditionDriver::NullConditionDriver () inline
Definition at line 117 of file condition_driver.hpp.
                           :
         Root(),
         ConditionDriver()
         {}
Member Function Documentation
virtual ConditionPtr* GT::GTL::NullConditionDriver::informationSetChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectPtr * strategyPtr) const inline override virtual
Create condition for Player choosing strategy in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 122 of file condition_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ConditionPtr(
             setupLocation<Condition>(
                 NullFactory::getInstance().createCondition(),
                 inputLocation
             )
         );
     }
virtual ConditionPtr* GT::GTL::NullConditionDriver::informationSetWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectsPtr * strategiesPtr) const inline override virtual
Create condition for Player limiting allowed strategies in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 136 of file condition_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ConditionPtr(
             setupLocation<Condition>(
                 NullFactory::getInstance().createCondition(),
                 inputLocation
             )
         );
     }
virtual bool GT::GTL::NullConditionDriver::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 176 of file condition_driver.hpp.
{
         return false;
     }
virtual ConditionPtr* GT::GTL::NullConditionDriver::playerChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * strategyPtr) const inline override virtual
Create condition for Player choosing strategy.
Parameters
inputLocation input location of created Condition
playerPtr Player's name
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 150 of file condition_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ConditionPtr(
             setupLocation<Condition>(
                 NullFactory::getInstance().createCondition(),
                 inputLocation
             )
         );
     }
virtual ConditionPtr* GT::GTL::NullConditionDriver::playerWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectsPtr * strategiesPtr) const inline override virtual
Create condition for Player limiting allowed strategies.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 163 of file condition_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ConditionPtr(
             setupLocation<Condition>(
                 NullFactory::getInstance().createCondition(),
                 inputLocation
             )
         );
     }
virtual Message GT::GTL::NullConditionDriver::toString () const inline override virtual
ConditionDriver's Message.
Returns
message
Implements GT::GTL::ConditionDriver.
Definition at line 180 of file condition_driver.hpp.
{
         return Message("NullConditionDriver");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/condition_driver.hpp