Game Theory Tools (full documentation): GT::Routines::PlayerChoiceRoutineConfig Class Reference
GT::Routines::PlayerChoiceRoutineConfig Class Reference abstract
Contains information about available choices for each Player.
#include <player_choice_routine_config.hpp>
Public Member Functions
PlayerChoiceRoutineConfig (const PlayersPtr players)
Initiates config with Players definitions.
PlayerChoiceRoutineConfig & requireChoiceExactly (const Identifier &player, const Identifier &chosenStrategy)
Trims availabe choices for Player for just one.
PlayerChoiceRoutineConfig & requireChoiceWithin (const Identifier &player, const Identifiers &allowedStrategies)
Trims availabe choices for Player to passed ones.
const Identifiers & getAvailableStrategies (const Identifier &player) const
Returns available choices for given Player.
virtual bool isValid () const override=0
Whether current configuration is valid.
Public Member Functions inherited from GT::Routines::RoutineConfig
virtual Message toString () const override=0
Returns RoutineConfig's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier,
Identifiers > AvailableForPlayers
Contains information about strategies available for each Player.
Private Attributes
AvailableForPlayers availableForPlayers
Available strategies for each Player.
Detailed Description
Contains information about available choices for each Player.
Author
Mateusz Kubuszok
See Also
PlayerChoiceCondition
Definition at line 45 of file player_choice_routine_config.hpp.
Member Typedef Documentation
typedef map<Identifier, Identifiers> GT::Routines::PlayerChoiceRoutineConfig::AvailableForPlayers private
Contains information about strategies available for each Player.
Definition at line 49 of file player_choice_routine_config.hpp.
Constructor & Destructor Documentation
GT::Routines::PlayerChoiceRoutineConfig::PlayerChoiceRoutineConfig (const PlayersPtr players) explicit
Initiates config with Players definitions.
Parameters
players Players definitions
Definition at line 39 of file player_choice_routine_config.cpp.
References availableForPlayers.
   :
     availableForPlayers()
 {
     for (const Identifier player : *players | map_keys)
         availableForPlayers.insert(
             AvailableForPlayers::value_type( player, Identifiers(*players->at(player)->getStrategies()) )
         );
 }
Member Function Documentation
const Identifiers & GT::Routines::PlayerChoiceRoutineConfig::getAvailableStrategies (const Identifier & player) const
Returns available choices for given Player.
Parameters
player Player's name
Returns
available strategies
Exceptions
InvalidPlayerChoice thrown if Player's name is invalid
Definition at line 99 of file player_choice_routine_config.cpp.
References availableForPlayers, GT::Routines::ExceptionFactory::getInstance(), and GT::Routines::ExceptionFactory::playerNotFound().
Referenced by GT::Routines::StrategicPureEquilibriumRoutine::arePositionsAllowed(), requireChoiceExactly(), and requireChoiceWithin().
         {
     if (!availableForPlayers.count(player))
         throw ExceptionFactory::getInstance().playerNotFound(player);
     return availableForPlayers.at(player);
 }
bool GT::Routines::PlayerChoiceRoutineConfig::isValid () const override pure virtual
Whether current configuration is valid.
Returns
true if current configuration is valid
Implements GT::Routines::RoutineConfig.
Implemented in GT::Routines::StrategicPureEquilibriumRoutineConfig.
Definition at line 108 of file player_choice_routine_config.cpp.
References availableForPlayers.
Referenced by GT::Routines::StrategicPureEquilibriumRoutineConfig::isValid().
{
     for (const Identifiers strategies : availableForPlayers | map_values)
             if (strategies.empty())
                 return false;
     return true;
 }
PlayerChoiceRoutineConfig & GT::Routines::PlayerChoiceRoutineConfig::requireChoiceExactly (const Identifier & player, const Identifier & chosenStrategy)
Trims availabe choices for Player for just one.
Parameters
player Player's name
chosenStrategy chosen strategy
Returns
reference to itself for chainging
Exceptions
InvalidPlayerChoice thrown if Player's or information set's name is invalid
Definition at line 50 of file player_choice_routine_config.cpp.
References getAvailableStrategies().
Referenced by GT::Routines::PlayerChoiceCondition::configureRoutine().
   {
     Identifiers& availableStrategies = const_cast<Identifiers&>(getAvailableStrategies(player));
     // removes all strategies not equal to the chosen
     availableStrategies.erase(
         remove_if(
             availableStrategies.begin(),
             availableStrategies.end(),
             [chosenStrategy](const IdentifierPtr& checkedStrategy) {
                 return (*checkedStrategy) != chosenStrategy;
             }
         )
     );
     return *this;
 }
PlayerChoiceRoutineConfig & GT::Routines::PlayerChoiceRoutineConfig::requireChoiceWithin (const Identifier & player, const Identifiers & allowedStrategies)
Trims availabe choices for Player to passed ones.
Parameters
player Player's name
allowedStrategies allowed strategies
Returns
reference to itself for chainging
Exceptions
InvalidPlayerChoice thrown if Player's or information set's name is invalid
Definition at line 70 of file player_choice_routine_config.cpp.
References getAvailableStrategies().
Referenced by GT::Routines::PlayerRangeCondition::configureRoutine().
   {
     Identifiers& availableStrategies = const_cast<Identifiers&>(getAvailableStrategies(player));
     // removes all not allowed
     availableStrategies.erase(
         remove_if(
             availableStrategies.begin(),
             availableStrategies.end(),
             [allowedStrategies](const IdentifierPtr& checkedStrategy) {
                 // check if such strategy is NOT present among allowedStrategies and thus can be removed
                 bool result = allowedStrategies.empty() || allowedStrategies.end() == find_if(
                     allowedStrategies.begin(),
                     allowedStrategies.end(),
                     [checkedStrategy](const IdentifierPtr& allowedStrategy) {
                         return *checkedStrategy == *allowedStrategy;
                     }
                 );
                 return result;
             }
         ),
         availableStrategies.end()
     );
     return *this;
 }
Member Data Documentation
AvailableForPlayers GT::Routines::PlayerChoiceRoutineConfig::availableForPlayers private
Available strategies for each Player.
Definition at line 54 of file player_choice_routine_config.hpp.
Referenced by getAvailableStrategies(), isValid(), and PlayerChoiceRoutineConfig().
The documentation for this class was generated from the following files:
src/gt/routines/player_choice_routine_config.hpp
src/gt/routines/player_choice_routine_config.cpp