Game Theory Tools (full documentation): GT::Model::Result Class Reference
GT::Model::Result Class Reference abstract
Root of all Results created by GTL Parser.
#include <result.hpp>
Public Member Functions
virtual ~Result ()
Default destructor.
virtual Message getResult () const =0
Returns Result in a form available to send on OutputStream.
virtual bool isEqual (const Root &root) const override
Defines equality relation.
virtual Message toString () const override
Return message with results.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Friends
bool operator== (const ResultPtr &result1, const ResultPtr &result2)
Syntax sugar for Result::isEqual(const Root&) method.
bool operator!= (const ResultPtr &result1, const ResultPtr &result2)
Syntax sugar for !Result#isEqual(const Root&) method.
OutputStream & operator<< (OutputStream &stream, const ResultPtr &result)
Syntax sugar for toString() method.
Detailed Description
Root of all Results created by GTL Parser.
Since all classes of GT (except factories, Numbers, Identifiers and Messages) extend this one, they are guaranteed to have Result::toSting() and Result::isEqual(const Root&) methods as well as Result#==(const ResultPtr&, const ResultPtr&), Result#!=(const ResultPtr&, const ResultPtr&) and Result#<<(OutputStream&, const ResultPtr&) operators overloaded.
Author
Mateusz Kubuszok
See Also
ResultBuilder
ResultFactory
Definition at line 45 of file result.hpp.
Constructor & Destructor Documentation
GT::Model::Result::~Result () virtual
Default destructor.
Definition at line 31 of file result.cpp.
 {}
Member Function Documentation
virtual Message GT::Model::Result::getResult () const pure virtual
Returns Result in a form available to send on OutputStream.
Returns
Message with Result
Implemented in GT::Model::NullResult, GT::Model::ConstResult, and GT::Model::EmptyResult.
Referenced by isEqual(), and toString().
bool GT::Model::Result::isEqual (const Root & root) const override virtual
Defines equality relation.
Parameters
root another root to compare
Returns
true if roots are equal
Reimplemented from GT::Model::Root.
Definition at line 33 of file result.cpp.
References getResult().
         {
     const Result* result = dynamic_cast<const Result*>(&root);
     if (!result)
         return false;
     if (result == this)
         return true;
     return getResult() == result->getResult();
 }
Message GT::Model::Result::toString () const override virtual
Return message with results.
Returns
Result as a Message
Implements GT::Model::Root.
Reimplemented in GT::Model::NullResult.
Definition at line 44 of file result.cpp.
References getResult().
{
     return getResult();
 }
Friends And Related Function Documentation
bool operator!= (const ResultPtr & result1, const ResultPtr & result2) friend
Syntax sugar for !Result#isEqual(const Root&) method.
Parameters
result1 first Result to compare
result2 second Result to compare
Returns
true if Results are not equal
Definition at line 59 of file result.cpp.
   {
     return (*result1) != (*result2);
 }
OutputStream& operator<< (OutputStream & stream, const ResultPtr & result) friend
Syntax sugar for toString() method.
Parameters
stream stream to concatenate
result Result to concatenate
Returns
stream for chaining
Definition at line 66 of file result.cpp.
   {
     return stream << result->toString();
 }
bool operator== (const ResultPtr & result1, const ResultPtr & result2) friend
Syntax sugar for Result::isEqual(const Root&) method.
Parameters
result1 first Result to compare
result2 second Result to compare
Returns
true if Results are equal
Definition at line 52 of file result.cpp.
   {
     return (*result1) == (*result2);
 }
The documentation for this class was generated from the following files:
include/gt/model/result.hpp
src/gt/model/result.cpp