Game Theory Tools (full documentation): GT::GTL::ExecutionGameDriver Class Reference
GT::GTL::ExecutionGameDriver Class Reference final
Implementation used for handling Games via ExecutionDriver.
#include <execution_game_driver.hpp>
Public Member Functions
ExecutionGameDriver (Context *context)
Initiates ExecutionGameDriver with its parent.
virtual GamePtr * createStrategic (const InputLocation &inputLocation, const DetailsPtr *details) const override
Create Strategic Game.
virtual GamePtr * createExtensive (const InputLocation &inputLocation, const DetailsPtr *details) const override
Create Extensive Game.
virtual DetailsPtr * createDetails (const InputLocation &inputLocation, const ObjectsPtr *players, const CoordinatesPtr *data) const override
Create Details.
virtual PlayerPtr * createPlayer (const InputLocation &inputLocation, const IdentifierPtr *player, const IdentifiersPtr *strategies) const override
Create Player.
virtual Message toString () const override
ExecutionGameDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
GamePtr * createGameWithBuilder (const InputLocation &inputLocation, const Details &details, const Model::GameBuilder &gameBuilder, const IdentifierPtr &gameType) const
Game building routine common for Strategic and Extensive form Games.
Private Attributes
CheckingGameDriver checkingGameDriver
Driver for error handling.
Context * context
Contains Context.
Detailed Description
Implementation used for handling Games via ExecutionDriver.
Performs actual execution of instructions for Games.
Author
Mateusz Kubuszok
See Also
ExecutionDriver
GameDriver
Definition at line 42 of file execution_game_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::ExecutionGameDriver::ExecutionGameDriver (Context * context) explicit
Initiates ExecutionGameDriver with its parent.
Parameters
context Context data
Definition at line 36 of file execution_game_driver.cpp.
   :
     checkingGameDriver(),
     context(contextPtr)
     {}
Member Function Documentation
DetailsPtr * GT::GTL::ExecutionGameDriver::createDetails (const InputLocation & inputLocation, const ObjectsPtr * players, const CoordinatesPtr * data) const override virtual
Create Details.
Parameters
inputLocation input location of created Details
players declared Players
data declared Coordinates
Returns
Details
Implements GT::GTL::GameDriver.
Definition at line 77 of file execution_game_driver.cpp.
References checkingGameDriver, and GT::GTL::CheckingGameDriver::createDetails().
         {
     DetailsPtr* errorCheck = checkingGameDriver.createDetails(inputLocation, playersPtr, dataPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const ObjectsPtr&     objectPlayers = *playersPtr;
     const CoordinatesPtr& coordinates   = *dataPtr;
     return new DetailsPtr(
         setupLocation<Details>(
             DetailsPtr(new Details(objectPlayers, coordinates)),
             inputLocation
         )
     );
 }
GamePtr * GT::GTL::ExecutionGameDriver::createExtensive (const InputLocation & inputLocation, const DetailsPtr * details) const override virtual
Create Extensive Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 60 of file execution_game_driver.cpp.
References GT::Model::GameFactory::buildExtensiveGame(), checkingGameDriver, createGameWithBuilder(), GT::createIdentifierPtr(), GT::GTL::CheckingGameDriver::createStrategic(), and GT::Model::GameFactory::getInstance().
         {
     GamePtr* errorCheck = checkingGameDriver.createStrategic(inputLocation, detailsPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const Details&       details        = **detailsPtr;
     const GameBuilderPtr gameBuilderPtr = Model::GameFactory::getInstance().buildExtensiveGame();
     const GameBuilder&   gameBuilder    = *gameBuilderPtr;
     const IdentifierPtr  gameType       = createIdentifierPtr("EXTENSIVE");
     return createGameWithBuilder(inputLocation, details, gameBuilder, gameType);
 }
GamePtr * GT::GTL::ExecutionGameDriver::createGameWithBuilder (const InputLocation & inputLocation, const Details & details, const Model::GameBuilder & gameBuilder, const IdentifierPtr & gameType) const private
Game building routine common for Strategic and Extensive form Games.
Parameters
inputLocation input location of created Game
details Details built Game Details
gameBuilder GameBuilder specific for given Game
gameType Game type (STRATEGIC, EXTENSIVE)
Returns
Game instance (valid or not)
Definition at line 125 of file execution_game_driver.cpp.
References context, GT::GTL::Details::getCoordinates(), and GT::GTL::Details::getPlayers().
Referenced by createExtensive(), and createStrategic().
         {
     Model::GamePtr lazyGame(
         new LazyGameProxy(
             gameBuilder.cloneBuilder(),
             details.getPlayers(),
             details.getCoordinates(),
             context
         )
     );
     return new GamePtr(
        setupLocation<Game>(
             GamePtr(new Game(lazyGame, gameType)),
             inputLocation
         )
     );
 }
PlayerPtr * GT::GTL::ExecutionGameDriver::createPlayer (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifiersPtr * strategies) const override virtual
Create Player.
Parameters
inputLocation input location of created Player
player Player's name
strategies strategies
Returns
Player
Implements GT::GTL::GameDriver.
Definition at line 98 of file execution_game_driver.cpp.
References checkingGameDriver, and GT::GTL::CheckingGameDriver::createPlayer().
         {
     PlayerPtr* errorCheck = checkingGameDriver.createPlayer(inputLocation, playerPtr, strategiesPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const IdentifierPtr&  player     = *playerPtr;
     const IdentifiersPtr& strategies = *strategiesPtr;
     return new PlayerPtr(
         setupLocation<Player>(
             PlayerPtr(new Player(player, strategies)),
             inputLocation
         )
     );
 }
GamePtr * GT::GTL::ExecutionGameDriver::createStrategic (const InputLocation & inputLocation, const DetailsPtr * details) const override virtual
Create Strategic Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 43 of file execution_game_driver.cpp.
References GT::Model::GameFactory::buildStrategicGame(), checkingGameDriver, createGameWithBuilder(), GT::createIdentifierPtr(), GT::GTL::CheckingGameDriver::createStrategic(), and GT::Model::GameFactory::getInstance().
         {
     GamePtr* errorCheck = checkingGameDriver.createStrategic(inputLocation, detailsPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const Details&       details        = **detailsPtr;
     const GameBuilderPtr gameBuilderPtr = Model::GameFactory::getInstance().buildStrategicGame();
     const GameBuilder&   gameBuilder    = *gameBuilderPtr;
     const IdentifierPtr  gameType       = createIdentifierPtr("STRATEGIC");
     return createGameWithBuilder(inputLocation, details, gameBuilder, gameType);
 }
Message GT::GTL::ExecutionGameDriver::toString () const override virtual
ExecutionGameDriver's Message.
Returns
message
Implements GT::GTL::GameDriver.
Definition at line 119 of file execution_game_driver.cpp.
{
     return Message("ExecutionGameDriver");
 }
Member Data Documentation
CheckingGameDriver GT::GTL::ExecutionGameDriver::checkingGameDriver private
Driver for error handling.
Definition at line 46 of file execution_game_driver.hpp.
Referenced by createDetails(), createExtensive(), createPlayer(), and createStrategic().
Context* GT::GTL::ExecutionGameDriver::context private
Contains Context.
Definition at line 50 of file execution_game_driver.hpp.
Referenced by createGameWithBuilder().
The documentation for this class was generated from the following files:
src/gt/gtl/execution_game_driver.hpp
src/gt/gtl/execution_game_driver.cpp