Game Theory Tools (full documentation): GT::GTL::ObjectParam Class Reference
GT::GTL::ObjectParam Class Reference final
Param containing Object value.
#include <object_param.hpp>
Public Member Functions
ObjectParam (const ObjectPtr object)
Initiates Param with Object.
virtual const ObjectPtr getObject (const Context &context, VisitedIdentifiers &visitedIdentifiers) const override
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &context, VisitedIdentifiers &visitedIdentifiers) const override
Returns Number for context.
virtual Message serialize () const override
Returns serialized Message for a ObjectParam.
virtual Message toString () const override
ObjectParam's Message.
Public Member Functions inherited from GT::GTL::Param
Param ()
Default constructor.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const override
Finds referred Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const override
Finds referred Objects' property for giver conditions and returns it as a Result.
virtual const ObjectPtr getObject (const Context &context) const
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &context) const
Returns Number for context.
virtual const Param & toParam () const override
Explicit cast to Param type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual const Game & toGame () const
Explicit cast to Game type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const ObjectPtr value
Value stored by this Param.
Additional Inherited Members
Public Types inherited from GT::GTL::Param
typedef set< Identifier > VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Param
void checkVisitedIdentifiers (const VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Checks whether visited Identifiers contain current one.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Param containing Object value.
Author
Mateusz Kubuszok
See Also
Context
Param
ParamFactory
Definition at line 41 of file object_param.hpp.
Constructor & Destructor Documentation
GT::GTL::ObjectParam::ObjectParam (const ObjectPtr object) explicit
Initiates Param with Object.
Parameters
object Object
Definition at line 31 of file object_param.cpp.
   :
     Param(),
     value(object)
     {}
Member Function Documentation
const NumberPtr GT::GTL::ObjectParam::getNumber (const Context & context, VisitedIdentifiers & visitedIdentifiers) const override virtual
Returns Number for context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Number
Exceptions
InvalidContentRequest thrown always for this implementation
Implements GT::GTL::Param.
Definition at line 45 of file object_param.cpp.
References GT::GTL::ExceptionFactory::getInstance(), and GT::GTL::ExceptionFactory::requiredUnavailableNumberFromParam().
         {
     throw ExceptionFactory::getInstance().requiredUnavailableNumberFromParam();
 }
const ObjectPtr GT::GTL::ObjectParam::getObject (const Context & context, VisitedIdentifiers & visitedIdentifiers) const override virtual
Returns Object for Context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Object
Implements GT::GTL::Param.
Definition at line 38 of file object_param.cpp.
References value.
         {
     return value;
 }
Message GT::GTL::ObjectParam::serialize () const override virtual
Returns serialized Message for a ObjectParam.
Returns
serialization result
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 52 of file object_param.cpp.
References value.
{
     return value->serialize();
 }
Message GT::GTL::ObjectParam::toString () const override virtual
ObjectParam's Message.
Returns
Message
Reimplemented from GT::GTL::Object.
Definition at line 56 of file object_param.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), and value.
{
     static const IdentifierPtr name  = createIdentifierPtr("ObjectParam");
     MessagePtr                 val   = createMessagePtr(value->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, val).build()->getResult();
 }
Member Data Documentation
const ObjectPtr GT::GTL::ObjectParam::value private
Value stored by this Param.
Definition at line 45 of file object_param.hpp.
Referenced by getObject(), serialize(), and toString().
The documentation for this class was generated from the following files:
src/gt/gtl/object_param.hpp
src/gt/gtl/object_param.cpp