Game Theory Tools (full documentation): GT::Routines::RoutineFactory Class Reference
GT::Routines::RoutineFactory Class Reference final
Used for creation of Null instances for Routines classes.
#include <routine_factory.hpp>
Public Member Functions
RoutinePtr pureStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find pure-stratgy Nash eqilibrium.
RoutinePtr mixedStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find mixed-stratgy Nash eqilibrium.
RoutinePtr behaviourStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find behaiour-stratgy Nash eqilibrium.
Static Public Member Functions
static RoutineFactory & getInstance ()
Returns the instance of a RoutineFactory.
Private Member Functions
RoutineFactory ()
Default constructor hidden from programmers.
RoutineFactory (const RoutineFactory &routineFactory)
Default copy constructor hidden from programmers.
~RoutineFactory ()
Default destructor hidden from programmers.
Detailed Description
Used for creation of Null instances for Routines classes.
Author
Mateusz Kubuszok
Definition at line 37 of file routine_factory.hpp.
Constructor & Destructor Documentation
GT::Routines::RoutineFactory::RoutineFactory () private
Default constructor hidden from programmers.
Definition at line 97 of file routine_factory.cpp.
 {}
GT::Routines::RoutineFactory::RoutineFactory (const RoutineFactory & routineFactory) private
Default copy constructor hidden from programmers.
Parameters
routineFactory object to copy
GT::Routines::RoutineFactory::~RoutineFactory () private
Default destructor hidden from programmers.
Definition at line 99 of file routine_factory.cpp.
 {}
Member Function Documentation
RoutinePtr GT::Routines::RoutineFactory::behaviourStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find behaiour-stratgy Nash eqilibrium.
Parameters
game Game for which equilibrium should be sought
Returns
Routine finding Nash equilibria
Definition at line 79 of file routine_factory.cpp.
Referenced by GT::GTL::Game::behaviorEquilibrium().
         {
     DataAccessorPtr data = game->getData();
     shared_ptr<StrategicDataAccessor> strategicData( dynamic_pointer_cast<StrategicDataAccessor>(data) );
     if (strategicData)
         return RoutinePtr( new PropertyUndefinedRoutine() );
     // shared_ptr<ExtensiveDataAccessor> extensiveData( dynamic_pointer_cast<ExtensiveDataAccessor>(data) );
     // if (extensiveData)
     //     return RoutinePtr( new ExtensiveBehaviourEquilibriumRoutine(players) );
     return RoutinePtr(new NotYetImplementedRoutine());
 }
RoutineFactory & GT::Routines::RoutineFactory::getInstance () static
Returns the instance of a RoutineFactory.
Returns
RoutineFactory instance
Definition at line 40 of file routine_factory.cpp.
Referenced by GT::GTL::Game::behaviorEquilibrium(), GT::GTL::Game::mixedEquilibrium(), and GT::GTL::Game::pureEquilibrium().
{
     static RoutineFactory instance;
     return instance;
 }
RoutinePtr GT::Routines::RoutineFactory::mixedStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find mixed-stratgy Nash eqilibrium.
Parameters
game Game for which equilibrium should be sought
Returns
Routine finding Nash equilibria
Definition at line 63 of file routine_factory.cpp.
Referenced by GT::GTL::Game::mixedEquilibrium().
         {
     // DataAccessorPtr data = game->getData();
     // shared_ptr<StrategicDataAccessor> strategicData( dynamic_pointer_cast<StrategicDataAccessor>(data) );
     // if (strategicData)
     //     return RoutinePtr( new StrategicMixedEquilibriumRoutine() );
     // shared_ptr<ExtensiveDataAccessor> extensiveData( dynamic_pointer_cast<ExtensiveDataAccessor>(data) );
     // if (extensiveData)
     //     return RoutinePtr( new ExtensiveMixedEquilibriumRoutine() );
     return RoutinePtr(new NotYetImplementedRoutine());
 }
RoutinePtr GT::Routines::RoutineFactory::pureStrategyEquilibriumFindingRoutineFor (const GamePtr game) const
Creates Routine that find pure-stratgy Nash eqilibrium.
Parameters
game Game for which equilibrium should be sought
Returns
Routine finding Nash equilibria
Definition at line 47 of file routine_factory.cpp.
Referenced by GT::GTL::Game::pureEquilibrium().
         {
     DataAccessorPtr data = game->getData();
     shared_ptr<StrategicDataAccessor> strategicData( dynamic_pointer_cast<StrategicDataAccessor>(data) );
     if (strategicData)
         return RoutinePtr( new StrategicPureEquilibriumRoutine() );
     shared_ptr<ExtensiveDataAccessor> extensiveData( dynamic_pointer_cast<ExtensiveDataAccessor>(data) );
     if (extensiveData)
         return RoutinePtr( new ExtensivePureEquilibriumRoutine() );
     return RoutinePtr(new NotYetImplementedRoutine());
 }
The documentation for this class was generated from the following files:
include/gt/routines/routine_factory.hpp
src/gt/routines/routine_factory.cpp