Game Theory Tools (full documentation): GT::Model Namespace Reference
GT::Model Namespace Reference
Contains classes related to storing GT data.
Classes
class Data
Custom interface for all Data containers for Games.
class NullData
Null Data for handling invalid situations.
class DataAccessor
Custom interface for all Data accessing instances for Games.
class NullDataAccessor
Null DataAccessor for handling invalid situations.
class DataBuilder
Helper used to create data for Games.
class NullDataBuilder
Null DataBuilder for handling invalid situations.
class DataPiece
Interface for accessing Data coordinates for better access to values.
class NullDataPiece
Null DataPiece for handling invalid situations.
class IllegalInnerState
Intened to be thrown when inner state of an object is not allowed.
class InvalidCoordinate
Intened to be thrown when coordinates to some value are invalid.
class Game
Defines Game.
class NullGame
Null Game for handling invalid situations.
class GameBuilder
Helper used to create Games.
class NullGameBuilder
Null GameBuilder for handling invalid situations.
class GameFactory
Creates GameBuilders for required types of Games.
class NullFactory
Used for creation of Null instances for Model classes.
class Player
Defines Player.
class NullPlayer
Null Player for handling invalid situations.
class Result
Root of all Results created by GTL Parser.
class NullResult
Null Result for handling invalid situations.
class ResultBuilder
Builder used for creating Results displayed to user.
class NullResultBuilder
Null ResultBuilder for handling invalid situations.
class ResultFactory
Creates some simple Results as well as supplies builders for more complex of them.
class Root
Basic interface of many classes used in the project.
class AbstractResultBuilder
Common base class of all actual implemetations used in Model.
class ConstResult
Contains const Result Message.
class EmptyResult
Contains empty Message.
class ExceptionFactory
Used for creation of exceptions with predefined message format.
class ExtensiveData
Contins data specific for Game in a tree form.
class NullExtensiveData
Null ExtensiveData for handling invalid situations.
class ExtensiveDataAccessor
Allows to access data specific for Game in a tree form.
class ExtensiveDataBuilder
Builder used for creating ExtensiveGame's Data.
class ExtensiveDataNode
Creates tree containing whole ExtensiveData content.
class NullExtensiveDataNode
Null ExtensiveDriver for acting as a root's parent.
class ExtensiveGame
Defnies ExtensiveGame.
class ExtensiveGameBuilder
Builder used for creating ExtensiveGame.
class ExtensiveGamePositionsHelper
Helper used for calculating information sets for ExtensiveGames.
class InnerNullFactory
Used for creation of Null instances for Model inner classes.
class JSONResultBuilder
Builder used for creating Results displayed to user in JSON format.
class PlainDataPiece
Used to store values at lowest level.
class PlainResultBuilder
Builder used for creating Results displayed to user in plain user-friendly format.
class StrategicData
Contains data specific for Game in a strategic form.
class NullStrategicData
Null StrategicData for handling invalid situations.
class StrategicDataAccessor
Allows to access data specific for Game in a strategic form.
class StrategicDataBuilder
Builder used for creating StrategicGame's Data.
class StrategicGame
Defnies StrategicGame.
class StrategicGameBuilder
Builder used for creating StrategicGame.
class StrategicGamePositionsHelper
Helper used for calculating Positions into Index and the other way round.
class XMLResultBuilder
Builder used for creating Results displayed to user in XML format.
Typedefs
typedef shared_ptr< Player > PlayerPtr
Smart pointer to Player.
typedef map< Identifier,
PlayerPtr > Players
Map of Identifier-PlayerPtr pairs.
typedef shared_ptr< Players > PlayersPtr
Smart pointer to Players.
typedef shared_ptr< Data > DataPtr
Smart pointer to Data.
typedef shared_ptr< DataAccessor > DataAccessorPtr
Smart pointer to DataAccessor.
typedef shared_ptr< DataPiece > DataPiecePtr
Smart pointer to DataPiece.
typedef shared_ptr< DataBuilder > DataBuilderPtr
Smart pointer to DataBuilder.
typedef shared_ptr< Game > GamePtr
Smart pointer to Game.
typedef shared_ptr< GameBuilder > GameBuilderPtr
Smart pointer to GameBuilder.
typedef shared_ptr< Result > ResultPtr
Smart pointer to Result.
typedef shared_ptr< ResultBuilder > ResultBuilderPtr
Smart pointer to ResultBuilder.
typedef shared_ptr
< StrategicDataAccessor > StrategicDataAccessorPtr
typedef shared_ptr< StrategicData > StrategicDataPtr
typedef shared_ptr
< StrategicDataBuilder > StrategicDataBuilderPtr
typedef bimap< Identifier, Index > IdentifierMap
typedef map< Identifier,
IdentifierMap > StrategyMap
typedef shared_ptr
< ExtensiveDataNode > ExtensiveDataNodePtr
typedef map< Identifier,
ExtensiveDataNodePtr > ExtensiveDataNodes
typedef shared_ptr
< ExtensiveDataNodes > ExtensiveDataNodesPtr
typedef shared_ptr
< ExtensiveDataAccessor > ExtensiveDataAccessorPtr
typedef shared_ptr< ExtensiveData > ExtensiveDataPtr
typedef shared_ptr
< ExtensiveDataBuilder > ExtensiveDataBuilderPtr
typedef map< Identifier,
PlayerPtr > PlayersInTurns
typedef shared_ptr
< PlayersInTurns > PlayersInTurnsPtr
Enumerations
enum ResultBuilderMode { ResultBuilderMode::PLAIN, ResultBuilderMode::JSON, ResultBuilderMode::XML }
Used for configuring what kind of builders should be returned by ResultFactory.
enum ResultIndentationMode { ResultIndentationMode::TABS, ResultIndentationMode::SPACES, ResultIndentationMode::NONE }
Used for configuring whether builders returned by ResultFacotry should use indentation and how.
Functions
bool operator== (Players &players1, Players &players2)
Check if Players are equal.
bool operator!= (Players &players1, Players &players2)
Check if Players are different.
Players createPlayers ()
Creates Players.
PlayersPtr createPlayersPtr ()
Creates Players.
bool operator== (const GamePtr &game1, const GamePtr &game2)
bool operator!= (const GamePtr &game1, const GamePtr &game2)
OutputStream & operator<< (OutputStream &stream, const GamePtr &game)
bool operator== (const PlayerPtr &player1, const PlayerPtr &player2)
bool operator!= (const PlayerPtr &player1, const PlayerPtr &player2)
OutputStream & operator<< (OutputStream &stream, const PlayerPtr &player)
bool operator== (const ResultPtr &result1, const ResultPtr &result2)
bool operator!= (const ResultPtr &result1, const ResultPtr &result2)
OutputStream & operator<< (OutputStream &stream, const ResultPtr &result)
bool operator== (const Root &root1, const Root &root2)
bool operator!= (const Root &root1, const Root &root2)
OutputStream & operator<< (OutputStream &stream, const Root &root)
Detailed Description
Contains classes related to storing GT data.
It consists of Players, Games, Datas, DataAccessors and builders that help with creating models.
Typedef Documentation
typedef shared_ptr<DataAccessor> GT::Model::DataAccessorPtr
Smart pointer to DataAccessor.
Definition at line 83 of file common.hpp.
typedef shared_ptr<DataBuilder> GT::Model::DataBuilderPtr
Smart pointer to DataBuilder.
Definition at line 85 of file common.hpp.
typedef shared_ptr<DataPiece> GT::Model::DataPiecePtr
Smart pointer to DataPiece.
Definition at line 84 of file common.hpp.
typedef shared_ptr<Data> GT::Model::DataPtr
Smart pointer to Data.
Definition at line 82 of file common.hpp.
typedef shared_ptr<ExtensiveDataAccessor> GT::Model::ExtensiveDataAccessorPtr
Definition at line 96 of file inner_common.hpp.
typedef shared_ptr<ExtensiveDataBuilder> GT::Model::ExtensiveDataBuilderPtr
Definition at line 98 of file inner_common.hpp.
typedef shared_ptr<ExtensiveDataNode> GT::Model::ExtensiveDataNodePtr
Definition at line 93 of file inner_common.hpp.
typedef map<Identifier, ExtensiveDataNodePtr> GT::Model::ExtensiveDataNodes
Definition at line 94 of file inner_common.hpp.
typedef shared_ptr<ExtensiveDataNodes> GT::Model::ExtensiveDataNodesPtr
Definition at line 95 of file inner_common.hpp.
typedef shared_ptr<ExtensiveData> GT::Model::ExtensiveDataPtr
Definition at line 97 of file inner_common.hpp.
typedef shared_ptr<GameBuilder> GT::Model::GameBuilderPtr
Smart pointer to GameBuilder.
Definition at line 87 of file common.hpp.
typedef shared_ptr<Game> GT::Model::GamePtr
Smart pointer to Game.
Definition at line 86 of file common.hpp.
typedef bimap<Identifier, Index> GT::Model::IdentifierMap
Definition at line 90 of file inner_common.hpp.
typedef shared_ptr<Player> GT::Model::PlayerPtr
Smart pointer to Player.
Definition at line 75 of file common.hpp.
typedef map<Identifier, PlayerPtr> GT::Model::Players
Map of Identifier-PlayerPtr pairs.
Definition at line 80 of file common.hpp.
typedef map<Identifier, PlayerPtr> GT::Model::PlayersInTurns
Definition at line 100 of file inner_common.hpp.
typedef shared_ptr<PlayersInTurns> GT::Model::PlayersInTurnsPtr
Definition at line 101 of file inner_common.hpp.
typedef shared_ptr<Players> GT::Model::PlayersPtr
Smart pointer to Players.
Definition at line 81 of file common.hpp.
typedef shared_ptr<ResultBuilder> GT::Model::ResultBuilderPtr
Smart pointer to ResultBuilder.
Definition at line 89 of file common.hpp.
typedef shared_ptr<Result> GT::Model::ResultPtr
Smart pointer to Result.
Definition at line 88 of file common.hpp.
typedef shared_ptr<StrategicDataAccessor> GT::Model::StrategicDataAccessorPtr
Definition at line 82 of file inner_common.hpp.
typedef shared_ptr<StrategicDataBuilder> GT::Model::StrategicDataBuilderPtr
Definition at line 88 of file inner_common.hpp.
typedef shared_ptr<StrategicData> GT::Model::StrategicDataPtr
Definition at line 87 of file inner_common.hpp.
typedef map<Identifier, IdentifierMap> GT::Model::StrategyMap
Definition at line 91 of file inner_common.hpp.
Enumeration Type Documentation
enum GT::Model::ResultBuilderMode strong
Used for configuring what kind of builders should be returned by ResultFactory.
Author
Mateusz Kubuszok
Enumerator
PLAIN
JSON
XML
Definition at line 37 of file result_factory.hpp.
 { PLAIN, JSON, XML };
enum GT::Model::ResultIndentationMode strong
Used for configuring whether builders returned by ResultFacotry should use indentation and how.
Author
Mateusz Kubuszok
Enumerator
TABS
SPACES
NONE
Definition at line 45 of file result_factory.hpp.
 { TABS, SPACES, NONE };
Function Documentation
Players GT::Model::createPlayers () inline
Creates Players.
Returns
Players
Definition at line 27 of file helpers.hpp.
                 {
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////
PlayersPtr GT::Model::createPlayersPtr () inline
Creates Players.
Returns
Players
Definition at line 31 of file helpers.hpp.
bool GT::Model::operator!= (const GamePtr & game1, const GamePtr & game2)
Parameters
game1 first Game to compare
game2 second Game to compare
Returns
true if Games are not equal
Definition at line 57 of file game.cpp.
   {
     return (*game1) != (*game2);
 }
bool GT::Model::operator!= (const Root & root1, const Root & root2)
Parameters
root1 first Root to compare
root2 second Root to compare
Returns
true if Root are not equal
Definition at line 58 of file root.cpp.
References GT::Model::Root::isEqual().
   {
     return !root1.isEqual(root2);
 }
bool GT::Model::operator!= (const ResultPtr & result1, const ResultPtr & result2)
Parameters
result1 first Result to compare
result2 second Result to compare
Returns
true if Results are not equal
Definition at line 59 of file result.cpp.
   {
     return (*result1) != (*result2);
 }
bool GT::Model::operator!= (Players & players1, Players & players2)
Check if Players are different.
Parameters
players1 first Players vector
players2 second Players vector
Returns
true if vectors have different content
Definition at line 132 of file common.cpp.
   {
     return !(players1 == players2);
 }
bool GT::Model::operator!= (const PlayerPtr & player1, const PlayerPtr & player2)
Parameters
player1 first Player to compare
player2 second Player to compare
Returns
true if Players are not equal
Definition at line 112 of file player.cpp.
   {
     return (*player1) != (*player2);
 }
OutputStream& GT::Model::operator<< (OutputStream & stream, const GamePtr & game)
Parameters
stream stream to concatenate
game Game to concatenate
Returns
stream for chaining
Definition at line 64 of file game.cpp.
   {
     return stream << game->toString();
 }
OutputStream& GT::Model::operator<< (OutputStream & stream, const Root & root)
Parameters
stream stream to concatenate
root Root to concatenate
Returns
stream for chaining
Definition at line 65 of file root.cpp.
References GT::Model::Root::toString().
   {
     return stream << root.toString();
 }
OutputStream& GT::Model::operator<< (OutputStream & stream, const ResultPtr & result)
Parameters
stream stream to concatenate
result Result to concatenate
Returns
stream for chaining
Definition at line 66 of file result.cpp.
   {
     return stream << result->toString();
 }
OutputStream& GT::Model::operator<< (OutputStream & stream, const PlayerPtr & player)
Parameters
stream stream to concatenate
player Player to concatenate
Returns
stream for chaining
Definition at line 119 of file player.cpp.
   {
     return stream << player->toString();
 }
bool GT::Model::operator== (const GamePtr & game1, const GamePtr & game2)
Parameters
game1 first Game to compare
game2 second Game to compare
Returns
true if Games are equal
Definition at line 50 of file game.cpp.
   {
     return (*game1) == (*game2);
 }
bool GT::Model::operator== (const Root & root1, const Root & root2)
Parameters
root1 first Root to compare
root2 second Root to compare
Returns
true if Root are equal
Definition at line 51 of file root.cpp.
References GT::Model::Root::isEqual().
   {
     return root1.isEqual(root2);
 }
bool GT::Model::operator== (const ResultPtr & result1, const ResultPtr & result2)
Parameters
result1 first Result to compare
result2 second Result to compare
Returns
true if Results are equal
Definition at line 52 of file result.cpp.
   {
     return (*result1) == (*result2);
 }
bool GT::Model::operator== (Players & players1, Players & players2)
Check if Players are equal.
Parameters
players1 first Players vector
players2 second Players vector
Returns
true if vectors have equal content
Definition at line 119 of file common.cpp.
   {
     if (&players1 == &players2)
         return true;
     if (players1.size() != players2.size())
         return false;
     for (Identifier playerName : players1 | map_keys)
         if (!players2.count(playerName) || *players1[playerName] != *players2[playerName])
             return false;
     return true;
 }
bool GT::Model::operator== (const PlayerPtr & player1, const PlayerPtr & player2)
Parameters
player1 first Player to compare
player2 second Player to compare
Returns
true if Players are equal
Definition at line 105 of file player.cpp.
   {
     return (*player1) == (*player2);
 }