Game Theory Tools (full documentation): GT::Model::GameFactory Class Reference
GT::Model::GameFactory Class Reference final
Creates GameBuilders for required types of Games.
#include <game_factory.hpp>
Public Member Functions
GameBuilderPtr buildStrategicGame () const
Returns StrategicGame builder.
GameBuilderPtr buildExtensiveGame () const
Returns ExtensiveGame builder.
Static Public Member Functions
static GameFactory & getInstance ()
Returns the instance of a GameFactory.
Private Member Functions
GameFactory ()=default
Private constructor.
GameFactory (const GameFactory &gameFactory)=delete
Private copy constructor.
~GameFactory ()=default
Private destructor.
Detailed Description
Creates GameBuilders for required types of Games.
Author
Mateusz Kubuszok
Definition at line 37 of file game_factory.hpp.
Constructor & Destructor Documentation
GT::Model::GameFactory::GameFactory () private default
Private constructor.
GT::Model::GameFactory::GameFactory (const GameFactory & gameFactory) private delete
Private copy constructor.
GT::Model::GameFactory::~GameFactory () private default
Private destructor.
Member Function Documentation
GameBuilderPtr GT::Model::GameFactory::buildExtensiveGame () const
Returns ExtensiveGame builder.
ExtensiveGame builder requires that Players should be set at the very beginning. It required that at each node of tree only one Player is used. Different turns can have different Players. Otherwise InvalidCoordinate or IllegalInnerState exception is thrown.
Returns
Extensive Game builder
Definition at line 39 of file game_factory.cpp.
Referenced by GT::GTL::ExecutionGameDriver::createExtensive().
{
     return GameBuilderPtr(new ExtensiveGameBuilder());
 }
GameBuilderPtr GT::Model::GameFactory::buildStrategicGame () const
Returns StrategicGame builder.
StrategyGame builder requires that Players should be set at the very beginning. It also require that Each coordinate is set and its set exactly once. Otherwise InvalidCoordinate or IllegalInnerState exception is thrown.
Returns
Strategic Game builder
Definition at line 35 of file game_factory.cpp.
Referenced by GT::GTL::ExecutionGameDriver::createStrategic().
{
     return GameBuilderPtr(new StrategicGameBuilder());
 }
GameFactory & GT::Model::GameFactory::getInstance () static
Returns the instance of a GameFactory.
Returns
GameFactory instance
Definition at line 30 of file game_factory.cpp.
Referenced by GT::GTL::ExecutionGameDriver::createExtensive(), and GT::GTL::ExecutionGameDriver::createStrategic().
{
     static GameFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/model/game_factory.hpp
src/gt/model/game_factory.cpp