Game Theory Tools (full documentation): GT::Model::NullGame Class Reference
GT::Model::NullGame Class Reference final
Null Game for handling invalid situations.
#include <game.hpp>
Public Member Functions
virtual const PlayersPtr getPlayers () const override
Returns Game's Players.
virtual const DataAccessorPtr getData () const override
Grants access to Data specific to a Game.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Game's Message.
Public Member Functions inherited from GT::Model::Game
virtual bool isEqual (const Root &root) const override
Defines equality relation.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null Game for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 115 of file game.hpp.
Member Function Documentation
virtual const DataAccessorPtr GT::Model::NullGame::getData () const inline override virtual
Grants access to Data specific to a Game.
Returns
DataAccessor returns DataAccessor specific for a Game
Implements GT::Model::Game.
Definition at line 121 of file game.hpp.
References GT::Model::NullFactory::createDataAccessor(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createDataAccessor();
     }
virtual const PlayersPtr GT::Model::NullGame::getPlayers () const inline override virtual
Returns Game's Players.
Returns
Players
Implements GT::Model::Game.
Definition at line 117 of file game.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual bool GT::Model::NullGame::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 125 of file game.hpp.
{
         return false;
     }
virtual Message GT::Model::NullGame::toString () const inline override virtual
Game's Message.
Returns
Message
Implements GT::Model::Game.
Definition at line 129 of file game.hpp.
{
         return Message("NullGame");
     }
The documentation for this class was generated from the following file:
include/gt/model/game.hpp