Game Theory Tools (full documentation): GT::GTL::CheckingGameDriver Class Reference
GT::GTL::CheckingGameDriver Class Reference final
Implementation used for handling Games via CheckingDriver.
#include <checking_game_driver.hpp>
Public Member Functions
virtual GamePtr * createStrategic (const InputLocation &inputLocation, const DetailsPtr *details) const override
Create Strategic Game.
virtual GamePtr * createExtensive (const InputLocation &inputLocation, const DetailsPtr *details) const override
Create Extensive Game.
virtual DetailsPtr * createDetails (const InputLocation &inputLocation, const ObjectsPtr *players, const CoordinatesPtr *data) const override
Create Details.
virtual PlayerPtr * createPlayer (const InputLocation &inputLocation, const IdentifierPtr *player, const IdentifiersPtr *strategies) const override
Create Player.
virtual Message toString () const override
CheckingGameDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Implementation used for handling Games via CheckingDriver.
Performs only syntax/type checking on Games' tokens.
Author
Mateusz Kubuszok
See Also
CheckingDriver
GameDriver
Definition at line 42 of file checking_game_driver.hpp.
Member Function Documentation
DetailsPtr * GT::GTL::CheckingGameDriver::createDetails (const InputLocation & inputLocation, const ObjectsPtr * players, const CoordinatesPtr * data) const override virtual
Create Details.
Parameters
inputLocation input location of created Details
players declared Players
data declared Coordinates
Returns
Details
Implements GT::GTL::GameDriver.
Definition at line 83 of file checking_game_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), GT::GTL::Object::toParam(), GT::GTL::Object::toPlayer(), GT::GTL::Player::toString(), and GT::GTL::Coordinate::toString().
Referenced by GT::GTL::ExecutionGameDriver::createDetails().
         {
     const Objects&     objectPlayers = **playersPtr;
     const Coordinates& coordinates   = **dataPtr;
     for (const ObjectPtr& objectPlayerPtr : objectPlayers) {
         const Object& objectPlayer = *objectPlayerPtr;
         const Player& player       = objectPlayer.toPlayer();
         const Param&  param        = objectPlayer.toParam();
         if (!player && !param) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Invalid Player: " + player.toString();
             return new DetailsPtr(
                 setupLocation<Details>(
                     ErrorFactory::getInstance().createDetails(errorMessage),
                     *player.getInputLocation()
                 )
             );
         }
     }
     for (const CoordinatePtr& coordinatePtr : coordinates) {
         const Coordinate& coordinate = *coordinatePtr;
         if (!coordinate) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Invalid Data: " + coordinate.toString();
             return new DetailsPtr(
                 setupLocation<Details>(
                     ErrorFactory::getInstance().createDetails(errorMessage),
                     *coordinate.getInputLocation()
                 )
             );
         }
     }
     return new DetailsPtr(
         setupLocation<Details>(
             NullFactory::getInstance().createDetails(),
             inputLocation
         )
     );
 }
GamePtr * GT::GTL::CheckingGameDriver::createExtensive (const InputLocation & inputLocation, const DetailsPtr * details) const override virtual
Create Extensive Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 57 of file checking_game_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::NullFactory::getInstance(), GT::GTL::ErrorFactory::getInstance(), and GT::GTL::Details::toString().
         {
     const Details& details = **detailsPtr;
     if (!details) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Details: " + details.toString();
         return new GamePtr(
             setupLocation<Game>(
                 ErrorFactory::getInstance().createGame(errorMessage),
                 *details.getInputLocation()
             )
         );
     }
     return new GamePtr(
         setupLocation<Game>(
             NullFactory::getInstance().createGame(),
             inputLocation
         )
     );
 }
PlayerPtr * GT::GTL::CheckingGameDriver::createPlayer (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifiersPtr * strategies) const override virtual
Create Player.
Parameters
inputLocation input location of created Player
player Player's name
strategies strategies
Returns
Player
Implements GT::GTL::GameDriver.
Definition at line 131 of file checking_game_driver.cpp.
References GT::GTL::NullFactory::getInstance().
Referenced by GT::GTL::ExecutionGameDriver::createPlayer().
         {
     return new PlayerPtr(
         setupLocation<Player>(
             NullFactory::getInstance().createPlayer(),
             inputLocation
         )
     );
 }
GamePtr * GT::GTL::CheckingGameDriver::createStrategic (const InputLocation & inputLocation, const DetailsPtr * details) const override virtual
Create Strategic Game.
Parameters
inputLocation input location of created Game
details Details for game
Returns
Game
Implements GT::GTL::GameDriver.
Definition at line 31 of file checking_game_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::NullFactory::getInstance(), GT::GTL::ErrorFactory::getInstance(), and GT::GTL::Details::toString().
Referenced by GT::GTL::ExecutionGameDriver::createExtensive(), and GT::GTL::ExecutionGameDriver::createStrategic().
         {
     const Details& details = **detailsPtr;
     if (!details) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Details: " + details.toString();
         return new GamePtr(
             setupLocation<Game>(
                 ErrorFactory::getInstance().createGame(errorMessage),
                 *details.getInputLocation()
             )
         );
     }
     return new GamePtr(
         setupLocation<Game>(
             NullFactory::getInstance().createGame(),
             inputLocation
         )
     );
 }
Message GT::GTL::CheckingGameDriver::toString () const override virtual
CheckingGameDriver's Message.
Returns
message
Implements GT::GTL::GameDriver.
Definition at line 144 of file checking_game_driver.cpp.
{
     return Message("CheckingGameDriver");
 }
The documentation for this class was generated from the following files:
src/gt/gtl/checking_game_driver.hpp
src/gt/gtl/checking_game_driver.cpp