Game Theory Tools (full documentation): GT::GTL::ParamValueProperty Class Reference
GT::GTL::ParamValueProperty Class Reference final
Describes Param's value.
#include <param_value_property.hpp>
Public Member Functions
ParamValueProperty (const Param *describedParam)
Initiates ObjectProperty with Param it's describing.
virtual ResultPtr getDescription () const override
Returns ObjectProperty's description.
virtual ResultPtr findForConditions (const Context &context, const Conditions &conditions) const override
Finds Params's value.
Private Attributes
const Param * param
Described Param.
Detailed Description
Describes Param's value.
Author
Mateusz Kubuszok
See Also
Param
Definition at line 39 of file param_value_property.hpp.
Constructor & Destructor Documentation
GT::GTL::ParamValueProperty::ParamValueProperty (const Param * describedParam) explicit
Initiates ObjectProperty with Param it's describing.
Parameters
describedParam described Param
Definition at line 31 of file param_value_property.cpp.
   :
     param(describedParam)
     {}
Member Function Documentation
ResultPtr GT::GTL::ParamValueProperty::findForConditions (const Context & context, const Conditions & conditions) const override virtual
Finds Params's value.
Parameters
context Context with values
conditions Conditions to check
Returns
search Result
Implements GT::GTL::ObjectProperty.
Definition at line 43 of file param_value_property.cpp.
References GT::Model::ResultFactory::constResult(), GT::createMessage(), GT::Model::ResultFactory::getInstance(), GT::GTL::Param::getNumber(), GT::GTL::Param::getObject(), param, and GT::GTL::Object::toString().
         {
     Message content;
     try {
         content = param->getObject(context)->toString();
     } catch (const InvalidContentRequest&) {
         try {
             content = createMessage(param->getNumber(context));
         } catch (const InvalidContentRequest&) {
             content = param->toString();
         }
     }
     return ResultFactory::getInstance().constResult(content);
 }
ResultPtr GT::GTL::ParamValueProperty::getDescription () const override virtual
Returns ObjectProperty's description.
Returns
description
Implements GT::GTL::ObjectProperty.
Definition at line 37 of file param_value_property.cpp.
References GT::Model::ResultFactory::constResult(), and GT::Model::ResultFactory::getInstance().
{
     static Message description =
         "Shows value of a given Param";
     return ResultFactory::getInstance().constResult(description);
 }
Member Data Documentation
const Param* GT::GTL::ParamValueProperty::param private
Described Param.
Definition at line 43 of file param_value_property.hpp.
Referenced by findForConditions().
The documentation for this class was generated from the following files:
src/gt/gtl/param_value_property.hpp
src/gt/gtl/param_value_property.cpp