Game Theory Tools (full documentation): GT::Model::NullFactory Class Reference
GT::Model::NullFactory Class Reference final
Used for creation of Null instances for Model classes.
#include <null_factory.hpp>
Public Member Functions
IdentifierPtr createIdentifier () const
Creates null Identifier.
IdentifiersPtr createIdentifiers () const
Creates null Identifiers.
MessagePtr createMessage () const
Creates null Message.
MessagesPtr createMessages () const
Creates null Messages.
NumberPtr createNumber () const
Creates NullNumber.
NumbersPtr createNumbers () const
Creates Null Numbers.
PlayerPtr createPlayer () const
Creates NullPlayer.
PlayersPtr createPlayers () const
Creates NullPlayers.
DataPtr createData () const
Creates NullData.
DataAccessorPtr createDataAccessor () const
Creates NullDataAccessor.
DataPiecePtr createDataPiece () const
Creates NullDataPiece.
DataBuilderPtr createDataBuilder () const
Creates NullDataBuilder.
GamePtr createGame () const
Creates NullGame.
GameBuilderPtr createGameBuilder () const
Creates NullGameBuilder.
ResultPtr createResult () const
Creates NullResult.
ResultBuilderPtr createResultBuilder () const
Creates NullResultBuilder.
Static Public Member Functions
static NullFactory & getInstance ()
Returns the instance of a NullFactory.
Private Member Functions
NullFactory ()
Default constructor hidden from programmers.
NullFactory (const NullFactory &nullFactory)
Default copy constructor hidden from programmers.
~NullFactory ()
Default destructor hidden from programmers.
Detailed Description
Used for creation of Null instances for Model classes.
Author
Mateusz Kubuszok
Definition at line 37 of file null_factory.hpp.
Constructor & Destructor Documentation
GT::Model::NullFactory::NullFactory () private
Default constructor hidden from programmers.
Definition at line 103 of file null_factory.cpp.
 {}
GT::Model::NullFactory::NullFactory (const NullFactory & nullFactory) private
Default copy constructor hidden from programmers.
Parameters
nullFactory object to copy
GT::Model::NullFactory::~NullFactory () private
Default destructor hidden from programmers.
Definition at line 105 of file null_factory.cpp.
 {}
Member Function Documentation
DataPtr GT::Model::NullFactory::createData () const
Creates NullData.
Returns
NullData
Definition at line 69 of file null_factory.cpp.
{
     return DataPtr(new NullData());
 }
DataAccessorPtr GT::Model::NullFactory::createDataAccessor () const
Creates NullDataAccessor.
Returns
NullDataAccessor
Definition at line 73 of file null_factory.cpp.
Referenced by GT::Model::NullGame::getData().
{
     return DataAccessorPtr(new NullDataAccessor());
 }
DataBuilderPtr GT::Model::NullFactory::createDataBuilder () const
Creates NullDataBuilder.
Returns
NullDataBuilder
Definition at line 81 of file null_factory.cpp.
Referenced by GT::Model::NullGameBuilder::clone(), GT::Model::NullDataBuilder::clone(), and GT::Model::NullGameBuilder::dataBuilder().
{
     return DataBuilderPtr(new NullDataBuilder());
 }
DataPiecePtr GT::Model::NullFactory::createDataPiece () const
Creates NullDataPiece.
Returns
NullDataPiece
Definition at line 77 of file null_factory.cpp.
Referenced by GT::Model::NullDataAccessor::getPayoffs(), GT::Model::NullData::getPayoffs(), GT::Model::NullStrategicData::getPayoffs(), GT::Model::NullExtensiveData::getPayoffs(), GT::Model::NullDataAccessor::operator[](), GT::Model::NullData::operator[](), GT::Model::NullStrategicData::operator[](), and GT::Model::NullExtensiveData::operator[]().
{
     return DataPiecePtr(new NullDataPiece());
 }
GamePtr GT::Model::NullFactory::createGame () const
Creates NullGame.
Returns
NullGame
Definition at line 85 of file null_factory.cpp.
Referenced by GT::Model::NullGameBuilder::build().
{
     return GamePtr(new NullGame());
 }
GameBuilderPtr GT::Model::NullFactory::createGameBuilder () const
Creates NullGameBuilder.
Returns
NullGameBuilder
Definition at line 89 of file null_factory.cpp.
Referenced by GT::Model::NullGameBuilder::cloneBuilder().
{
     return GameBuilderPtr(new NullGameBuilder());
 }
IdentifierPtr GT::Model::NullFactory::createIdentifier () const
Creates null Identifier.
Returns
null Identifier
Definition at line 37 of file null_factory.cpp.
Referenced by GT::GTL::NullDefinition::getName(), GT::GTL::ErrorDefinition::getName(), and GT::Model::NullPlayer::getName().
{
     return IdentifierPtr(new Identifier("NullIdentifier"));
 }
IdentifiersPtr GT::Model::NullFactory::createIdentifiers () const
Creates null Identifiers.
Returns
null Identifiers
Definition at line 41 of file null_factory.cpp.
Referenced by GT::Model::NullExtensiveDataNode::getChoices(), and GT::Model::NullPlayer::getStrategies().
{
     return IdentifiersPtr(new Identifiers());
 }
MessagePtr GT::Model::NullFactory::createMessage () const
Creates null Message.
Returns
null Message
Definition at line 45 of file null_factory.cpp.
{
     return MessagePtr(new Message("NullMessage"));
 }
MessagesPtr GT::Model::NullFactory::createMessages () const
Creates null Messages.
Returns
null Messages
Definition at line 49 of file null_factory.cpp.
{
     return MessagesPtr(new Messages());
 }
NumberPtr GT::Model::NullFactory::createNumber () const
Creates NullNumber.
Returns
null Number
Definition at line 53 of file null_factory.cpp.
Referenced by GT::GTL::NullParam::getNumber(), GT::GTL::NullContext::getNumber(), and GT::GTL::ErrorParam::getNumber().
{
     return NumberPtr(new Number(0));
 }
NumbersPtr GT::Model::NullFactory::createNumbers () const
Creates Null Numbers.
Returns
null Numbers
Definition at line 57 of file null_factory.cpp.
Referenced by GT::Model::NullExtensiveDataNode::getPayoffs().
{
     return NumbersPtr(new Numbers());
 }
PlayerPtr GT::Model::NullFactory::createPlayer () const
Creates NullPlayer.
Returns
NullPlayer
Definition at line 61 of file null_factory.cpp.
Referenced by GT::Model::ExtensiveDataNode::getPlayer(), GT::Model::NullExtensiveDataNode::getPlayer(), and GT::Model::NullExtensiveData::getPlayerInTurn().
{
     return PlayerPtr(new NullPlayer());
 }
PlayersPtr GT::Model::NullFactory::createPlayers () const
Creates NullPlayers.
Returns
Player
Definition at line 65 of file null_factory.cpp.
Referenced by GT::Model::NullGameBuilder::getPlayers(), GT::Model::NullDataAccessor::getPlayers(), GT::Model::NullGame::getPlayers(), GT::Model::NullData::getPlayers(), GT::Model::NullStrategicData::getPlayers(), and GT::Model::NullExtensiveData::getPlayers().
{
     return PlayersPtr(new Players());
 }
ResultPtr GT::Model::NullFactory::createResult () const
Creates NullResult.
Returns
NullResult
Definition at line 93 of file null_factory.cpp.
Referenced by GT::GTL::NullGame::behaviorEquilibrium(), GT::GTL::ErrorGame::behaviorEquilibrium(), GT::Model::NullResultBuilder::build(), GT::Model::NullResultBuilder::buildRaw(), GT::Routines::NullRoutine::findResultFor(), GT::GTL::NullGame::mixedEquilibrium(), GT::GTL::ErrorGame::mixedEquilibrium(), GT::GTL::NullGame::pureEquilibrium(), and GT::GTL::ErrorGame::pureEquilibrium().
{
     return ResultPtr(new NullResult());
 }
ResultBuilderPtr GT::Model::NullFactory::createResultBuilder () const
Creates NullResultBuilder.
Returns
NullResultBuilder
Definition at line 97 of file null_factory.cpp.
{
     return ResultBuilderPtr(new NullResultBuilder());
 }
NullFactory & GT::Model::NullFactory::getInstance () static
Returns the instance of a NullFactory.
Returns
NullFactory instance
Definition at line 30 of file null_factory.cpp.
Referenced by GT::GTL::NullGame::behaviorEquilibrium(), GT::GTL::ErrorGame::behaviorEquilibrium(), GT::Model::NullGameBuilder::build(), GT::Model::NullResultBuilder::build(), GT::Model::NullResultBuilder::buildRaw(), GT::Model::NullGameBuilder::clone(), GT::Model::NullDataBuilder::clone(), GT::Model::NullGameBuilder::cloneBuilder(), GT::Model::NullGameBuilder::dataBuilder(), GT::Routines::NullRoutine::findResultFor(), GT::Model::NullExtensiveDataNode::getChoices(), GT::Model::NullGame::getData(), GT::GTL::NullDefinition::getName(), GT::GTL::ErrorDefinition::getName(), GT::Model::NullPlayer::getName(), GT::GTL::NullParam::getNumber(), GT::GTL::NullContext::getNumber(), GT::GTL::ErrorParam::getNumber(), GT::Model::NullDataAccessor::getPayoffs(), GT::Model::NullData::getPayoffs(), GT::Model::NullStrategicData::getPayoffs(), GT::Model::NullExtensiveData::getPayoffs(), GT::Model::NullExtensiveDataNode::getPayoffs(), GT::Model::ExtensiveDataNode::getPlayer(), GT::Model::NullExtensiveDataNode::getPlayer(), GT::Model::NullExtensiveData::getPlayerInTurn(), GT::Model::NullGameBuilder::getPlayers(), GT::Model::NullDataAccessor::getPlayers(), GT::Model::NullGame::getPlayers(), GT::Model::NullData::getPlayers(), GT::Model::NullStrategicData::getPlayers(), GT::Model::NullExtensiveData::getPlayers(), GT::Model::NullPlayer::getStrategies(), GT::GTL::NullGame::mixedEquilibrium(), GT::GTL::ErrorGame::mixedEquilibrium(), GT::Model::NullDataAccessor::operator[](), GT::Model::NullData::operator[](), GT::Model::NullStrategicData::operator[](), GT::Model::NullExtensiveData::operator[](), GT::GTL::NullGame::pureEquilibrium(), GT::GTL::ErrorGame::pureEquilibrium(), and GT::Model::StrategicData::StrategicData().
{
     static NullFactory instance;
     return instance;
 }
The documentation for this class was generated from the following files:
include/gt/model/null_factory.hpp
src/gt/model/null_factory.cpp