Game Theory Tools (public API): GT::Model::NullData Class Reference
GT::Model::NullData Class Reference final
Null Data for handling invalid situations.
#include <data.hpp>
Public Member Functions
virtual const PlayersPtr getPlayers () const override
Returns map of Players available in this DataAccessor.
virtual const DataPiecePtr getPayoffs (const Positions &) const override
Returns values handler for given coordiantes.
virtual const DataPiecePtr getPayoffs (const PositionsPtr) const override
Returns values handler for given coordiantes.
virtual Data & setPayoffs (const Positions &, const NumbersPtr) override
Sets values for given coordiantes.
virtual Data & setPayoffs (const PositionsPtr, const NumbersPtr) override
Sets values for given coordiantes.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Data's message.
virtual const DataPiecePtr operator[] (const Positions &) const override
Overrides operator[] allowing easy access to values via DataPiece interface.
virtual const DataPiecePtr operator[] (const PositionsPtr) const override
Overrides operator[] allowing easy access to values via DataPiece interface.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null Data for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 139 of file data.hpp.
Member Function Documentation
virtual const DataPiecePtr GT::Model::NullData::getPayoffs (const Positions & positions) const inline override virtual
Returns values handler for given coordiantes.
Parameters
positions coordinates in a Game
Returns
values of payoff
Exceptions
InvalidCoordinate thrown when coordinates are invalid
Implements GT::Model::Data.
Definition at line 145 of file data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                       {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullData::getPayoffs (const PositionsPtr positions) const inline override virtual
Returns values handler for given coordiantes.
Parameters
positions coordinates in a Game
Returns
values of payoff
Exceptions
InvalidCoordinate thrown when coordinates are invalid
Implements GT::Model::Data.
Definition at line 151 of file data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const PlayersPtr GT::Model::NullData::getPlayers () const inline override virtual
Returns map of Players available in this DataAccessor.
Returns
Players
Implements GT::Model::Data.
Definition at line 141 of file data.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual bool GT::Model::NullData::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 171 of file data.hpp.
{
         return false;
     }
virtual const DataPiecePtr GT::Model::NullData::operator[] (const Positions & positions) const inline override virtual
Overrides operator[] allowing easy access to values via DataPiece interface.
Parameters
positions coordinates
Returns
DataPiece object allowing access to concrete value
Exceptions
InvalidCoordinates thrown when positions coordinates are invalid
Implements GT::Model::Data.
Definition at line 179 of file data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullData::operator[] (const PositionsPtr positions) const inline override virtual
Overrides operator[] allowing easy access to values via DataPiece interface.
Parameters
positions coordinates
Returns
DataPiece object allowing access to concrete value
Exceptions
InvalidCoordinates thrown when positions coordinates are invalid
Implements GT::Model::Data.
Definition at line 185 of file data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual Data& GT::Model::NullData::setPayoffs (const Positions & positions, const NumbersPtr numbers) inline override virtual
Sets values for given coordiantes.
Parameters
positions coordinates in a Game
numbers payoff to set
Returns
reference to itself
Exceptions
InvalidCoordinate thrown when calculated coordinates are invalid
Implements GT::Model::Data.
Definition at line 157 of file data.hpp.
                {
         return *this;
     }
virtual Data& GT::Model::NullData::setPayoffs (const PositionsPtr positions, const NumbersPtr numbers) inline override virtual
Sets values for given coordiantes.
Parameters
positions coordinates in a Game
numbers payoff to set
Returns
reference to itself
Exceptions
InvalidCoordinate thrown when calculated coordinates are invalid
Implements GT::Model::Data.
Definition at line 164 of file data.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullData::toString () const inline override virtual
Returns Data's message.
Returns
message
Implements GT::Model::Data.
Definition at line 175 of file data.hpp.
{
         return Message("NullData");
     }
The documentation for this class was generated from the following file:
include/gt/model/data.hpp