Game Theory Tools (public API): GT::Model::NullResultBuilder Class Reference
GT::Model::NullResultBuilder Class Reference final
Null ResultBuilder for handling invalid situations.
#include <result_builder.hpp>
Public Member Functions
virtual ResultBuilder & setHeaders (const IdentifiersPtr &) override
Sets headers used for displaying records.
virtual ResultBuilder & addRecord (const IdentifierPtr &, const MessagesPtr &) override
Adds record to displayed Result.
virtual ResultBuilder & addResult (const IdentifierPtr &, const MessagePtr &) override
Adds single named subresult.
virtual ResultPtr build () const override
Build Result.
virtual ResultPtr buildRaw () const override
Build raw Result - one that can be inserted into other results.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message about an Object allowing its debuging.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null ResultBuilder for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 111 of file result_builder.hpp.
Member Function Documentation
virtual ResultBuilder& GT::Model::NullResultBuilder::addRecord (const IdentifierPtr & object, const MessagesPtr & results) inline override virtual
Adds record to displayed Result.
Results size must match headers size.
Parameters
object name of added record
results properties that should be displayed
Returns
reference to self for chaining
See Also
setHeaders(const IdentifiersPtr&)
Implements GT::Model::ResultBuilder.
Definition at line 119 of file result_builder.hpp.
                {
         return *this;
     }
virtual ResultBuilder& GT::Model::NullResultBuilder::addResult (const IdentifierPtr & name, const MessagePtr & result) inline override virtual
Adds single named subresult.
Parameters
name name of subresult
result subresult
Returns
reference for itself for chaining
Implements GT::Model::ResultBuilder.
Definition at line 126 of file result_builder.hpp.
                {
         return *this;
     }
virtual ResultPtr GT::Model::NullResultBuilder::build () const inline override virtual
Build Result.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages for any Object does not match number of properties
Implements GT::Model::ResultBuilder.
Definition at line 133 of file result_builder.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::Model::NullResultBuilder::buildRaw () const inline override virtual
Build raw Result - one that can be inserted into other results.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages for any Object does not match number of properties
Implements GT::Model::ResultBuilder.
Definition at line 137 of file result_builder.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createResult();
     }
virtual bool GT::Model::NullResultBuilder::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 141 of file result_builder.hpp.
{
         return false;
     }
virtual ResultBuilder& GT::Model::NullResultBuilder::setHeaders (const IdentifiersPtr & properties) inline override virtual
Sets headers used for displaying records.
Size of headers must match size of each record.
Parameters
properties headers' names that will be used in a Result
Returns
reference to self for chaining
See Also
addRecord(const IdentifierPtr&, const MessagesPtr&)
Implements GT::Model::ResultBuilder.
Definition at line 113 of file result_builder.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullResultBuilder::toString () const inline override virtual
Returns Message about an Object allowing its debuging.
Also used by Models and Routines to render Results.
Returns
Root's Message
Implements GT::Model::Root.
Definition at line 145 of file result_builder.hpp.
{
         return Message("NullResultBuilder");
     }
The documentation for this class was generated from the following file:
include/gt/model/result_builder.hpp