Game Theory Tools (full documentation): GT::Routines::ExtensivePureStrategyPath Class Reference
GT::Routines::ExtensivePureStrategyPath Class Reference final
Contains path to a payoff (with payoff).
#include <extensive_pure_strategy_path.hpp>
Public Types
typedef map< Identifier,
Positions > PlayersChoices
Contains choices for given Players.
Public Member Functions
ExtensivePureStrategyPath (const PlayersPtr players)
Initiates path with Players definitions.
ExtensivePureStrategyPath & addPlayerChoice (const Identifier &informationSet, const Identifier &player, const Identifier &strategy)
Adds older choice to the beginning of list.
const PlayersChoices & getPlayersChoices () const
Returns all players choices till now.
const DataPiecePtr getPayoff () const
Returns payoffs for path.
ExtensivePureStrategyPath & setPayoff (DataPiecePtr payoffs)
Sets payoff.
virtual Message toString () const
Returns ExtensivePureStrategyMessage message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const PlayersPtr players
Players definitions.
DataPiecePtr payoffs
Payoff.
map< Identifier, Positions > playersChoices
Contains choices for given Players.
Detailed Description
Contains path to a payoff (with payoff).
Author
Mateusz Kubuszok
Definition at line 43 of file extensive_pure_strategy_path.hpp.
Member Typedef Documentation
typedef map<Identifier, Positions> GT::Routines::ExtensivePureStrategyPath::PlayersChoices
Contains choices for given Players.
Definition at line 63 of file extensive_pure_strategy_path.hpp.
Constructor & Destructor Documentation
GT::Routines::ExtensivePureStrategyPath::ExtensivePureStrategyPath (const PlayersPtr players)
Initiates path with Players definitions.
Parameters
players Players definitions
Definition at line 35 of file extensive_pure_strategy_path.cpp.
References players, and playersChoices.
   :
     players(playersDefinitions),
     payoffs(Model::NullFactory::getInstance().createDataPiece()),
     playersChoices()
 {
     for (Players::value_type& player : *players)
         playersChoices.insert( PlayersChoices::value_type(player.first, Positions()) );
 }
Member Function Documentation
ExtensivePureStrategyPath & GT::Routines::ExtensivePureStrategyPath::addPlayerChoice (const Identifier & informationSet, const Identifier & player, const Identifier & strategy)
Adds older choice to the beginning of list.
Parameters
informationSet information set's name
player Player's name
strategy chosen strategy
Returns
reference for itself for chaining
Exceptions
InvalidPlayerChoice thrown when Player's name or chosen strategy is invalid
Definition at line 46 of file extensive_pure_strategy_path.cpp.
References GT::Routines::ExceptionFactory::getInstance(), GT::Routines::ExceptionFactory::playerNotFound(), players, playersChoices, and GT::Routines::ExceptionFactory::strategyNotFound().
Referenced by GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen().
   {
     if (!players->count(player) || !playersChoices.count(player))
         throw ExceptionFactory::getInstance().playerNotFound(player);
     if (!(*players)[player]->hasStrategy(strategy))
         throw ExceptionFactory::getInstance().strategyNotFound(player, strategy);
     playersChoices[player].insert( Positions::value_type( informationSet, strategy ) );
     return *this;
 }
const DataPiecePtr GT::Routines::ExtensivePureStrategyPath::getPayoff () const
Returns payoffs for path.
Returns
payoff
Definition at line 65 of file extensive_pure_strategy_path.cpp.
References payoffs.
{
     return payoffs;
 }
const ExtensivePureStrategyPath::PlayersChoices & GT::Routines::ExtensivePureStrategyPath::getPlayersChoices () const
Returns all players choices till now.
Returns
Players' choices
Definition at line 61 of file extensive_pure_strategy_path.cpp.
References playersChoices.
{
     return playersChoices;
 }
ExtensivePureStrategyPath & GT::Routines::ExtensivePureStrategyPath::setPayoff (DataPiecePtr payoffs)
Sets payoff.
Parameters
payoffs new payoffs
Returns
reference to itself for chaining
Definition at line 69 of file extensive_pure_strategy_path.cpp.
References payoffs.
   {
     payoffs = newPayoffs;
     return *this;
 }
Message GT::Routines::ExtensivePureStrategyPath::toString () const virtual
Returns ExtensivePureStrategyMessage message.
Returns
Message
Implements GT::Model::Root.
Definition at line 76 of file extensive_pure_strategy_path.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), payoffs, and playersChoices.
{
     static IdentifierPtr payoffName = createIdentifierPtr("Payoffs");
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     for (PlayersChoices::value_type playerChoices : playersChoices) {
         ResultBuilderPtr subResultBuilder = ResultFactory::getInstance().buildResult();
         for (Positions::value_type& choice : playerChoices.second)
             subResultBuilder->addResult( createIdentifierPtr(choice.first), createMessagePtr(choice.second) );
         resultBuilder->addResult(
             createIdentifierPtr(playerChoices.first),
             createMessagePtr(subResultBuilder->build()->getResult())
         );
     }
     resultBuilder->addResult(
         payoffName,
         createMessagePtr(payoffs->toString())
     );
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
DataPiecePtr GT::Routines::ExtensivePureStrategyPath::payoffs private
Payoff.
Definition at line 52 of file extensive_pure_strategy_path.hpp.
Referenced by getPayoff(), setPayoff(), and toString().
const PlayersPtr GT::Routines::ExtensivePureStrategyPath::players private
Players definitions.
Definition at line 47 of file extensive_pure_strategy_path.hpp.
Referenced by addPlayerChoice(), and ExtensivePureStrategyPath().
map<Identifier, Positions> GT::Routines::ExtensivePureStrategyPath::playersChoices private
Contains choices for given Players.
Definition at line 57 of file extensive_pure_strategy_path.hpp.
Referenced by addPlayerChoice(), ExtensivePureStrategyPath(), getPlayersChoices(), and toString().
The documentation for this class was generated from the following files:
src/gt/routines/extensive_pure_strategy_path.hpp
src/gt/routines/extensive_pure_strategy_path.cpp