Game Theory Tools (full documentation): GT::GTL::ErrorDefinition Class Reference
GT::GTL::ErrorDefinition Class Reference final
Error Definition for handling invalid situations.
#include <definition.hpp>
Public Member Functions
ErrorDefinition (Message errorMessage)
virtual const IdentifierPtr getName () const override
Returns name of the property.
virtual const ParamPtr getValue () const override
Returns value of the property.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns Message about Definition.
Public Member Functions inherited from GT::GTL::Definition
Definition (const IdentifierPtr definedName, const ParamPtr definedValue)
Constructor for name and value.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
Message message
Error message.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Error Definition for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 131 of file definition.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorDefinition::ErrorDefinition (Message errorMessage) inline
Definition at line 138 of file definition.hpp.
       :
         Definition(
             Model::NullFactory::getInstance().createIdentifier(),
             NullFactory::getInstance().createParam()
         ),
         message(errorMessage)
         {}
Member Function Documentation
virtual const IdentifierPtr GT::GTL::ErrorDefinition::getName () const inline override virtual
Returns name of the property.
Returns
value of the property
Reimplemented from GT::GTL::Definition.
Definition at line 148 of file definition.hpp.
References GT::Model::NullFactory::createIdentifier(), and GT::Model::NullFactory::getInstance().
{
         return Model::NullFactory::getInstance().createIdentifier();
     }
virtual const ParamPtr GT::GTL::ErrorDefinition::getValue () const inline override virtual
Returns value of the property.
Returns
value of the property
Reimplemented from GT::GTL::Definition.
Definition at line 152 of file definition.hpp.
References GT::GTL::NullFactory::createParam(), and GT::GTL::NullFactory::getInstance().
{
         return NullFactory::getInstance().createParam();
     }
virtual bool GT::GTL::ErrorDefinition::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 156 of file definition.hpp.
{
         return false;
     }
virtual Message GT::GTL::ErrorDefinition::toString () const inline override virtual
Returns Message about Definition.
Returns
Definition's Message
Reimplemented from GT::GTL::Definition.
Definition at line 160 of file definition.hpp.
References message.
{
         return message;
     }
Member Data Documentation
Message GT::GTL::ErrorDefinition::message private
Error message.
Definition at line 135 of file definition.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/definition.hpp