Game Theory Tools (full documentation): GT::GTL::ErrorGame Class Reference
GT::GTL::ErrorGame Class Reference final
Error Condition for handling invalid situations.
#include <game.hpp>
Public Member Functions
ErrorGame (const Message errorMessage)
virtual ResultPtr pureEquilibrium (const Context &, const Conditions &) const override
Search pure Nash equilibrium for given conditions.
virtual ResultPtr mixedEquilibrium (const Context &, const Conditions &) const override
Search mixed Nash equilibrium for given conditions.
virtual ResultPtr behaviorEquilibrium (const Context &, const Conditions &) const override
Search behavior Nash equilibrium for given conditions.
virtual const IdentifierPtr getGameType () const override
Returns game type name.
virtual Message serialize () const override
Returns serialized Message for a Game.
virtual bool isValid () const override
Returns whether Object is valid.
virtual Message toString () const override
Returns Message about Game.
Public Member Functions inherited from GT::GTL::Game
Game (const Model::GamePtr game)
Initiates Object with Game model.
Game (const Model::GamePtr game, const IdentifierPtr gameType)
Initiates Object with Game model.
virtual const Game & toGame () const override
Explicit cast to Game type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const
Finds Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const
Finds Objects' property for giver Conditions and returns it as a Result.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual const Param & toParam () const
Explicit cast to Param type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const Message message
Error message.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Detailed Description
Error Condition for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 198 of file game.hpp.
Constructor & Destructor Documentation
GT::GTL::ErrorGame::ErrorGame (const Message errorMessage) inline
Definition at line 205 of file game.hpp.
       :
         Game(Model::NullFactory::getInstance().createGame()),
         message(errorMessage)
         {}
Member Function Documentation
virtual ResultPtr GT::GTL::ErrorGame::behaviorEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search behavior Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 226 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual const IdentifierPtr GT::GTL::ErrorGame::getGameType () const inline override virtual
Returns game type name.
Game type used during game definition: EXTENSIVE, STRATEGIC.
Returns
game type Identifier
Reimplemented from GT::GTL::Game.
Definition at line 233 of file game.hpp.
References GT::createIdentifierPtr().
{
         return createIdentifierPtr("ERROR");
     }
virtual bool GT::GTL::ErrorGame::isValid () const inline override virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 241 of file game.hpp.
{
         return false;
     }
virtual ResultPtr GT::GTL::ErrorGame::mixedEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search mixed Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 219 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual ResultPtr GT::GTL::ErrorGame::pureEquilibrium (const Context & context, const Conditions & conditions) const inline override virtual
Search pure Nash equilibrium for given conditions.
Parameters
context context with definitions
conditions conditions for query
Reimplemented from GT::GTL::Game.
Definition at line 212 of file game.hpp.
References GT::Model::NullFactory::createResult(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createResult();
     }
virtual Message GT::GTL::ErrorGame::serialize () const inline override virtual
Returns serialized Message for a Game.
Returns
serialization result
Reimplemented from GT::GTL::Game.
Definition at line 237 of file game.hpp.
References GT::createMessage().
{
         return createMessage("ERROR GAME");
     }
virtual Message GT::GTL::ErrorGame::toString () const inline override virtual
Returns Message about Game.
Returns
Game's state
Reimplemented from GT::GTL::Game.
Definition at line 245 of file game.hpp.
References message.
{
         return message;
     }
Member Data Documentation
const Message GT::GTL::ErrorGame::message private
Error message.
Definition at line 202 of file game.hpp.
Referenced by toString().
The documentation for this class was generated from the following file:
include/gt/gtl/game.hpp