Game Theory Tools (full documentation): GT::Model::ExtensiveDataBuilder Class Reference
GT::Model::ExtensiveDataBuilder Class Reference final
Builder used for creating ExtensiveGame's Data.
#include <extensive_data_builder.hpp>
Public Member Functions
ExtensiveDataBuilder ()
Defalt constructor.
ExtensiveDataPtr build () const
Returns set up Data.
const PlayersPtr getPlayers () const
Returns Players' definitions.
virtual DataBuilder & setPlayers (const PlayersPtr newPlayers) override
Sets Players' definitions.
virtual DataBuilder & addNextPositions (const PositionsPtr positions) override
Specifies next Positions.
virtual DataBuilder & setPayoffs (const NumbersPtr params) override
Sets payoffs values.
virtual DataBuilderPtr clone () const override
Returns copy of itsef with shared content and frozen values of already set Positions.
virtual Message toString () const override
ExtensiveDataBuilder Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
ExtensiveDataPtr data
Actual data.
PlayersPtr players
Players.
Positions currentPositions
Current Positions that will be used to set params with setPayoffs(NumbersPtr).
Index depthValue
Current depth as numeric value.
Identifier depthName
Current depth as Identifier.
Detailed Description
Builder used for creating ExtensiveGame's Data.
Games in this form has all payoffs defined in nodes of a game tree. Each node of that tree has assigned Player. As such each SubCoordinates is mapped to strategy of the same Player.
Author
Mateusz Kubuszok
See Also
ExtensiveData
ExtensiveGame
Definition at line 43 of file extensive_data_builder.hpp.
Constructor & Destructor Documentation
GT::Model::ExtensiveDataBuilder::ExtensiveDataBuilder ()
Defalt constructor.
Definition at line 31 of file extensive_data_builder.cpp.
Referenced by clone().
                                            :
     data(InnerNullFactory::getInstance().createExtensiveData()),
     players(NullFactory::getInstance().createPlayers()),
     currentPositions(),
     depthValue(1),
     depthName(createIdentifier(1))
     {}
Member Function Documentation
DataBuilder & GT::Model::ExtensiveDataBuilder::addNextPositions (const PositionsPtr positions) override virtual
Specifies next Positions.
Parameters
positions next Positions to specify
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 59 of file extensive_data_builder.cpp.
References GT::createIdentifier(), currentPositions, data, depthName, depthValue, GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), GT::Model::ExceptionFactory::invalidExtensiveCoordinateFormat(), and players.
   {
     if (positions->size() != 1)
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(*positions);
     Identifier player   = positions->begin()->first;
     Identifier strategy = positions->begin()->second;
     PlayerPtr currentPlayer = data->getPlayerInTurn(currentPositions);
     if (currentPlayer->isNull()) {
         data->setPlayerInTurn(currentPositions, (*players)[player]);
         currentPlayer = (*players)[player];
     } else if ((*currentPlayer->getName()) != player)
         throw ExceptionFactory::getInstance().invalidExtensiveCoordinateFormat(*positions);
     currentPositions.insert( Positions::value_type(depthName, strategy) );
     depthName = createIdentifier(++depthValue);
     return *this;
 }
ExtensiveDataPtr GT::Model::ExtensiveDataBuilder::build () const
Returns set up Data.
Returns
built Data
Definition at line 39 of file extensive_data_builder.cpp.
References data.
{
     return data;
 }
DataBuilderPtr GT::Model::ExtensiveDataBuilder::clone () const override virtual
Returns copy of itsef with shared content and frozen values of already set Positions.
Returns
copy with frozem Positions and content common to parent
Implements GT::Model::DataBuilder.
Definition at line 89 of file extensive_data_builder.cpp.
References ExtensiveDataBuilder().
{
     return DataBuilderPtr(new ExtensiveDataBuilder(*this));
 }
const PlayersPtr GT::Model::ExtensiveDataBuilder::getPlayers () const
Returns Players' definitions.
Returns
Players' definitions
Definition at line 43 of file extensive_data_builder.cpp.
References players.
{
     return players;
 }
DataBuilder & GT::Model::ExtensiveDataBuilder::setPayoffs (const NumbersPtr params) override virtual
Sets payoffs values.
Parameters
params values of payoffs
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 82 of file extensive_data_builder.cpp.
References currentPositions, and data.
   {
     data->setPayoffs(currentPositions, params);
     return *this;
 }
DataBuilder & GT::Model::ExtensiveDataBuilder::setPlayers (const PlayersPtr newPlayers) override virtual
Sets Players' definitions.
Parameters
newPlayers Players' definitions
Returns
reference to itself for chanining
Implements GT::Model::DataBuilder.
Definition at line 47 of file extensive_data_builder.cpp.
References data, GT::Model::ExceptionFactory::getInstance(), players, and GT::Model::ExceptionFactory::playersAlreadySet().
   {
     if (data->isNotNull())
         throw ExceptionFactory::getInstance().playersAlreadySet();
     data    = ExtensiveDataPtr(new ExtensiveData(newPlayers));
     players = newPlayers;
     return *this;
 }
Message GT::Model::ExtensiveDataBuilder::toString () const override virtual
ExtensiveDataBuilder Message.
Returns
Message
Implements GT::Model::DataBuilder.
Definition at line 93 of file extensive_data_builder.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), data, and GT::Model::ResultFactory::getInstance().
{
     static const IdentifierPtr name    = createIdentifierPtr("Current Data");
     const MessagePtr           message = createMessagePtr(data->toString());
     return ResultFactory::getInstance().buildResult()->addResult(name, message).build()->getResult();
 }
Member Data Documentation
Positions GT::Model::ExtensiveDataBuilder::currentPositions private
Current Positions that will be used to set params with setPayoffs(NumbersPtr).
Definition at line 56 of file extensive_data_builder.hpp.
Referenced by addNextPositions(), and setPayoffs().
ExtensiveDataPtr GT::Model::ExtensiveDataBuilder::data private
Actual data.
Definition at line 47 of file extensive_data_builder.hpp.
Referenced by addNextPositions(), build(), setPayoffs(), setPlayers(), and toString().
Identifier GT::Model::ExtensiveDataBuilder::depthName private
Current depth as Identifier.
Definition at line 65 of file extensive_data_builder.hpp.
Referenced by addNextPositions().
Index GT::Model::ExtensiveDataBuilder::depthValue private
Current depth as numeric value.
Definition at line 61 of file extensive_data_builder.hpp.
Referenced by addNextPositions().
PlayersPtr GT::Model::ExtensiveDataBuilder::players private
Players.
Definition at line 52 of file extensive_data_builder.hpp.
Referenced by addNextPositions(), getPlayers(), and setPlayers().
The documentation for this class was generated from the following files:
src/gt/model/extensive_data_builder.hpp
src/gt/model/extensive_data_builder.cpp