Game Theory Tools (full documentation): GT::GTL::Parser Class Reference
GT::GTL::Parser Class Reference
A Bison parser.
#include <parser.hpp>
Classes
union semantic_type
Symbol semantic values.
struct token
Tokens.
Public Types
typedef location location_type
Symbol locations.
typedef token::yytokentype token_type
Token type.
typedef int debug_level_type
Type for debugging levels.
Public Member Functions
Parser (Scanner &scanner_yyarg, Driver &driver_yyarg)
Build a parser object.
virtual ~Parser ()
virtual int parse ()
std::ostream & debug_stream () const
The current debugging stream.
void set_debug_stream (std::ostream &)
Set the current debugging stream.
debug_level_type debug_level () const
The current debugging level.
void set_debug_level (debug_level_type l)
Set the current debugging level.
Private Types
typedef int state_type
State numbers.
typedef stack< state_type > state_stack_type
State stack type.
typedef stack< semantic_type > semantic_stack_type
Semantic value stack type.
typedef stack< location_type > location_stack_type
location stack type.
typedef unsigned char token_number_type
Internal symbol numbers.
typedef signed char rhs_number_type
A type to store symbol numbers and -1.
Private Member Functions
virtual void error (const location_type &loc, const std::string &msg)
Handles errors occuring during parsing.
virtual std::string yysyntax_error_ (int yystate, int tok)
virtual void yy_symbol_value_print_ (int yytype, const semantic_type *yyvaluep, const location_type *yylocationp)
Report a symbol value on the debug stream.
virtual void yy_symbol_print_ (int yytype, const semantic_type *yyvaluep, const location_type *yylocationp)
Report a symbol on the debug stream.
virtual void yy_reduce_print_ (int r)
Report on the debug stream that the rule r is going to be reduced.
virtual void yystack_print_ ()
Print the state stack on the debug stream.
token_number_type yytranslate_ (int t)
Convert a scanner token number t to a symbol number.
void yydestruct_ (const char *yymsg, int yytype, semantic_type *yyvaluep, location_type *yylocationp)
Reclaim the memory associated to a symbol.
void yypop_ (unsigned int n=1)
Pop n symbols the three stacks.
Static Private Member Functions
static bool yy_pact_value_is_default_ (int yyvalue)
static bool yy_table_value_is_error_ (int yyvalue)
static std::string yytnamerr_ (const char *n)
Convert the symbol name n to a form suitable for a diagnostic.
Private Attributes
state_stack_type yystate_stack_
The state stack.
semantic_stack_type yysemantic_stack_
The semantic value stack.
location_stack_type yylocation_stack_
The location stack.
int yydebug_
std::ostream * yycdebug_
Scanner & scanner
Driver & driver
Static Private Attributes
static const signed char yypact_ []
For a state, the index in yytable_ of its portion.
static const signed char yypact_ninf_ = -83
static const unsigned char yydefact_ []
static const signed char yypgoto_ []
static const signed char yydefgoto_ []
static const unsigned char yytable_ []
static const signed char yytable_ninf_ = -1
static const signed char yycheck_ []
static const unsigned char yystos_ []
For a state, its accessing symbol.
static const unsigned char yyr1_ []
For a rule, its LHS.
static const unsigned char yyr2_ []
For a rule, its RHS length.
static const char *const yytname_ []
For a symbol, its name in clear.
static const rhs_number_type yyrhs_ []
A `-1'-separated list of the rules' RHS.
static const unsigned char yyprhs_ []
For each rule, the index of the first RHS symbol in yyrhs_.
static const unsigned short int yyrline_ []
For each rule, its source line number.
static const unsigned short int yytoken_number_ []
For each scanner token number, its symbol number.
static const int yyeof_ = 0
static const int yylast_ = 105
static const int yynnts_ = 27
static const int yyempty_ = -2
static const int yyfinal_ = 24
static const int yyterror_ = 1
static const int yyerrcode_ = 256
static const int yyntokens_ = 31
static const unsigned int yyuser_token_number_max_ = 285
static const token_number_type yyundef_token_ = 2
Detailed Description
A Bison parser.
Definition at line 89 of file parser.hpp.
Member Typedef Documentation
typedef int GT::GTL::Parser::debug_level_type
Type for debugging levels.
Definition at line 182 of file parser.hpp.
typedef stack<location_type> GT::GTL::Parser::location_stack_type private
location stack type.
Definition at line 225 of file parser.hpp.
typedef location GT::GTL::Parser::location_type
Symbol locations.
Definition at line 126 of file parser.hpp.
typedef signed char GT::GTL::Parser::rhs_number_type private
A type to store symbol numbers and -1.
Definition at line 285 of file parser.hpp.
typedef stack<semantic_type> GT::GTL::Parser::semantic_stack_type private
Semantic value stack type.
Definition at line 223 of file parser.hpp.
typedef stack<state_type> GT::GTL::Parser::state_stack_type private
State stack type.
Definition at line 221 of file parser.hpp.
typedef int GT::GTL::Parser::state_type private
State numbers.
Definition at line 219 of file parser.hpp.
typedef unsigned char GT::GTL::Parser::token_number_type private
Internal symbol numbers.
Definition at line 243 of file parser.hpp.
typedef token::yytokentype GT::GTL::Parser::token_type
Token type.
Definition at line 165 of file parser.hpp.
Constructor & Destructor Documentation
GT::GTL::Parser::Parser (Scanner & scanner_yyarg, Driver & driver_yyarg)
Build a parser object.
Definition at line 223 of file parser.cpp.
     :
 #if YYDEBUG
       yydebug_ (false),
       yycdebug_ (&std::cerr),
 #endif
       scanner (scanner_yyarg),
       driver (driver_yyarg)
   {
   }
GT::GTL::Parser::~Parser () virtual
Definition at line 234 of file parser.cpp.
   {
   }
Member Function Documentation
debug_level_type GT::GTL::Parser::debug_level () const
The current debugging level.
std::ostream& GT::GTL::Parser::debug_stream () const
The current debugging stream.
void Parser::error (const location_type & loc, const std::string & message) private virtual
Handles errors occuring during parsing.
Report a syntax error.
Parameters
loc where the syntax error is found.
msg a description of the syntax error.
location location of error occurance
message error message
Definition at line 1604 of file parser.cpp.
References driver, and GT::GTL::Driver::showError().
Referenced by parse().
   {
     InputLocation errorLocation = location;
     driver.showError(errorLocation, message);
 }
int GT::GTL::Parser::parse () virtual
Parse.
Returns
0 iff parsing succeeded.
Lookahead and lookahead in internal form.
Semantic value of the lookahead.
Location of the lookahead.
The locations where the error started and ended.
$$.
$.
Definition at line 551 of file parser.cpp.
References CLEANUP, GT::GTL::Parser::semantic_type::condition, GT::GTL::Parser::semantic_type::conditions, GT::GTL::Parser::semantic_type::coordinate, GT::GTL::Parser::semantic_type::coordinates, GT::GTL::CoordinateDriver::create(), GT::GTL::StatementDriver::createDefinition(), GT::GTL::GameDriver::createDetails(), GT::GTL::GameDriver::createExtensive(), GT::GTL::GameDriver::createPlayer(), GT::GTL::StatementDriver::createQuery(), GT::GTL::GameDriver::createStrategic(), GT::GTL::Parser::semantic_type::definition, GT::GTL::Parser::semantic_type::details, driver, error(), GT::GTL::Driver::execute(), GT::GTL::StatementDriver::executeDefinition(), GT::GTL::StatementDriver::executeQuery(), GT::GTL::CoordinateDriver::fillWithData(), GT::GTL::Driver::forCondition(), GT::GTL::Driver::forConditions(), GT::GTL::Driver::forCoordinate(), GT::GTL::Driver::forCoordinates(), GT::GTL::Driver::forGame(), GT::GTL::Driver::forIdentifiers(), GT::GTL::Driver::forObjects(), GT::GTL::Driver::forParams(), GT::GTL::Driver::forStatement(), GT::GTL::Driver::forValue(), GT::GTL::Parser::semantic_type::game, GT::GTL::ValueDriver::get(), GT::GTL::Parser::semantic_type::identifier, GT::GTL::Parser::semantic_type::identifiers, GT::GTL::ConditionDriver::informationSetChoosed(), GT::GTL::ConditionDriver::informationSetWithin(), GT::GTL::Driver::load(), GT::GTL::CoordinateDriver::merge(), GT::GTL::Parser::semantic_type::object, GT::GTL::Parser::semantic_type::objects, GT::GTL::Parser::semantic_type::param, GT::GTL::Parser::semantic_type::params, GT::GTL::Parser::semantic_type::player, GT::GTL::ConditionDriver::playerChoosed(), GT::GTL::ConditionDriver::playerWithin(), GT::GTL::stack< T, S >::push(), GT::GTL::Parser::semantic_type::query, GT::GTL::Driver::save(), scanner, GT::GTL::Driver::showError(), string, GT::GTL::ValueDriver::toObject(), yy_pact_value_is_default_(), YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, yy_table_value_is_error_(), YYABORT, YYCDEBUG, yycheck_, yydefact_, yydefgoto_, yydestruct_(), yyempty_, yyeof_, yyfinal_, yylast_, yylex(), YYLLOC_DEFAULT, yylocation_stack_, yyntokens_, yypact_, yypgoto_, yypop_(), yyr1_, yyr2_, yysemantic_stack_, yystate_stack_, yystos_, yysyntax_error_(), yytable_, yyterror_, and yytranslate_().
   {
     /// Lookahead and lookahead in internal form.
     int yychar = yyempty_;
     int yytoken = 0;
     /* State.  */
     int yyn;
     int yylen = 0;
     int yystate = 0;
     /* Error handling.  */
     int yynerrs_ = 0;
     int yyerrstatus_ = 0;
     /// Semantic value of the lookahead.
     semantic_type yylval;
     /// Location of the lookahead.
     location_type yylloc;
     /// The locations where the error started and ended.
     location_type yyerror_range[3];
     /// $$.
     semantic_type yyval;
     /// @$.
     location_type yyloc;
     int yyresult;
     YYCDEBUG << "Starting parse" << std::endl;
     /* Initialize the stacks.  The initial state will be pushed in
        yynewstate, since the latter expects the semantical and the
        location values to have been already stored, initialize these
        stacks with a primary value.  */
     yystate_stack_ = state_stack_type (0);
     yysemantic_stack_ = semantic_stack_type (0);
     yylocation_stack_ = location_stack_type (0);
     yysemantic_stack_.push (yylval);
     yylocation_stack_.push (yylloc);
     /* New state.  */
   yynewstate:
     yystate_stack_.push (yystate);
     YYCDEBUG << "Entering state " << yystate << std::endl;
     /* Accept?  */
     if (yystate == yyfinal_)
       goto yyacceptlab;
     goto yybackup;
     /* Backup.  */
   yybackup:
     /* Try to take a decision without lookahead.  */
     yyn = yypact_[yystate];
     if (yy_pact_value_is_default_ (yyn))
       goto yydefault;
     /* Read a lookahead token.  */
     if (yychar == yyempty_)
       {
     YYCDEBUG << "Reading a token: ";
     yychar = yylex (&yylval, &yylloc, scanner, driver);
       }
     /* Convert token to internal form.  */
     if (yychar <= yyeof_)
       {
     yychar = yytoken = yyeof_;
     YYCDEBUG << "Now at end of input." << std::endl;
       }
     else
       {
     yytoken = yytranslate_ (yychar);
     YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
       }
     /* If the proper action on seeing token YYTOKEN is to reduce or to
        detect an error, take that action.  */
     yyn += yytoken;
     if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yytoken)
       goto yydefault;
     /* Reduce or error.  */
     yyn = yytable_[yyn];
     if (yyn <= 0)
       {
     if (yy_table_value_is_error_ (yyn))
       goto yyerrlab;
     yyn = -yyn;
     goto yyreduce;
       }
     /* Shift the lookahead token.  */
     YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
     /* Discard the token being shifted.  */
     yychar = yyempty_;
     yysemantic_stack_.push (yylval);
     yylocation_stack_.push (yylloc);
     /* Count tokens shifted since error; after three, turn off error
        status.  */
     if (yyerrstatus_)
       --yyerrstatus_;
     yystate = yyn;
     goto yynewstate;
   /*-----------------------------------------------------------.
   | yydefault -- do the default action for the current state.  |
   `-----------------------------------------------------------*/
   yydefault:
     yyn = yydefact_[yystate];
     if (yyn == 0)
       goto yyerrlab;
     goto yyreduce;
   /*-----------------------------.
   | yyreduce -- Do a reduction.  |
   `-----------------------------*/
   yyreduce:
     yylen = yyr2_[yyn];
     /* If YYLEN is nonzero, implement the default value of the action:
        `$$ = $1'.  Otherwise, use the top of the stack.
        Otherwise, the following line sets YYVAL to garbage.
        This behavior is undocumented and Bison
        users should not rely upon it.  */
     if (yylen)
       yyval = yysemantic_stack_[yylen - 1];
     else
       yyval = yysemantic_stack_[0];
     {
       slice<location_type, location_stack_type> slice (yylocation_stack_, yylen);
       YYLLOC_DEFAULT (yyloc, slice, yylen);
     }
     YY_REDUCE_PRINT (yyn);
     switch (yyn)
       {
       case 6:
 /* Line 690 of lalr1.cc  */
 #line 189 "f_n_b/parser.yy"
     { driver.execute((yylocation_stack_[(2) - (1)]), **(yysemantic_stack_[(2) - (1)].identifier)); CLEANUP((yysemantic_stack_[(2) - (1)].identifier)); }
     break;
   case 7:
 /* Line 690 of lalr1.cc  */
 #line 190 "f_n_b/parser.yy"
     { driver.load((yylocation_stack_[(2) - (1)]), **(yysemantic_stack_[(2) - (1)].identifier)); CLEANUP((yysemantic_stack_[(2) - (1)].identifier)); }
     break;
   case 8:
 /* Line 690 of lalr1.cc  */
 #line 191 "f_n_b/parser.yy"
     { driver.save((yylocation_stack_[(2) - (1)]), **(yysemantic_stack_[(2) - (1)].identifier)); CLEANUP((yysemantic_stack_[(2) - (1)].identifier)); }
     break;
   case 9:
 /* Line 690 of lalr1.cc  */
 #line 192 "f_n_b/parser.yy"
     { driver.forStatement().executeDefinition((yysemantic_stack_[(2) - (1)].definition)); CLEANUP((yysemantic_stack_[(2) - (1)].definition)); }
     break;
   case 10:
 /* Line 690 of lalr1.cc  */
 #line 193 "f_n_b/parser.yy"
     { driver.forStatement().executeQuery((yysemantic_stack_[(2) - (1)].query)); CLEANUP((yysemantic_stack_[(2) - (1)].query)); }
     break;
   case 12:
 /* Line 690 of lalr1.cc  */
 #line 198 "f_n_b/parser.yy"
     { (yyval.identifier) = (yysemantic_stack_[(2) - (2)].identifier); }
     break;
   case 13:
 /* Line 690 of lalr1.cc  */
 #line 202 "f_n_b/parser.yy"
     { (yyval.identifier) = (yysemantic_stack_[(2) - (2)].identifier); }
     break;
   case 14:
 /* Line 690 of lalr1.cc  */
 #line 206 "f_n_b/parser.yy"
     { (yyval.identifier) = (yysemantic_stack_[(3) - (3)].identifier); }
     break;
   case 15:
 /* Line 690 of lalr1.cc  */
 #line 210 "f_n_b/parser.yy"
     { (yyval.definition) = driver.forStatement().createDefinition((yylocation_stack_[(4) - (1)]), (yysemantic_stack_[(4) - (2)].identifier), (yysemantic_stack_[(4) - (4)].object));
                                    CLEANUP((yysemantic_stack_[(4) - (2)].identifier)); CLEANUP((yysemantic_stack_[(4) - (4)].object)); }
     break;
   case 16:
 /* Line 690 of lalr1.cc  */
 #line 215 "f_n_b/parser.yy"
     { (yyval.query) = driver.forStatement().createQuery((yylocation_stack_[(5) - (1)]), (yysemantic_stack_[(5) - (2)].identifiers), (yysemantic_stack_[(5) - (4)].objects), (yysemantic_stack_[(5) - (5)].conditions));
                                                   CLEANUP((yysemantic_stack_[(5) - (2)].identifiers)); CLEANUP((yysemantic_stack_[(5) - (4)].objects)); CLEANUP((yysemantic_stack_[(5) - (5)].conditions)); }
     break;
   case 17:
 /* Line 690 of lalr1.cc  */
 #line 222 "f_n_b/parser.yy"
     { (yyval.objects) = driver.forObjects().insert((yysemantic_stack_[(3) - (3)].object), (yysemantic_stack_[(3) - (1)].objects)); CLEANUP((yysemantic_stack_[(3) - (3)].object)); CLEANUP((yysemantic_stack_[(3) - (1)].objects)); }
     break;
   case 18:
 /* Line 690 of lalr1.cc  */
 #line 223 "f_n_b/parser.yy"
     { (yyval.objects) = driver.forObjects().create((yysemantic_stack_[(1) - (1)].object)); CLEANUP((yysemantic_stack_[(1) - (1)].object)); }
     break;
   case 19:
 /* Line 690 of lalr1.cc  */
 #line 227 "f_n_b/parser.yy"
     { (yyval.object) = driver.forValue().toObject((yysemantic_stack_[(1) - (1)].game)); CLEANUP((yysemantic_stack_[(1) - (1)].game)); }
     break;
   case 20:
 /* Line 690 of lalr1.cc  */
 #line 228 "f_n_b/parser.yy"
     { (yyval.object) = driver.forValue().toObject((yysemantic_stack_[(1) - (1)].player)); CLEANUP((yysemantic_stack_[(1) - (1)].player)); }
     break;
   case 21:
 /* Line 690 of lalr1.cc  */
 #line 229 "f_n_b/parser.yy"
     { (yyval.object) = driver.forValue().toObject((yysemantic_stack_[(1) - (1)].param)); CLEANUP((yysemantic_stack_[(1) - (1)].param)); }
     break;
   case 22:
 /* Line 690 of lalr1.cc  */
 #line 235 "f_n_b/parser.yy"
     { (yyval.game) = driver.forGame().createStrategic((yylocation_stack_[(4) - (1)]), (yysemantic_stack_[(4) - (3)].details)); CLEANUP((yysemantic_stack_[(4) - (3)].details)); }
     break;
   case 23:
 /* Line 690 of lalr1.cc  */
 #line 236 "f_n_b/parser.yy"
     { (yyval.game) = driver.forGame().createExtensive((yylocation_stack_[(4) - (1)]), (yysemantic_stack_[(4) - (3)].details)); CLEANUP((yysemantic_stack_[(4) - (3)].details)); }
     break;
   case 26:
 /* Line 690 of lalr1.cc  */
 #line 245 "f_n_b/parser.yy"
     { (yyval.details) = driver.forGame().createDetails((yylocation_stack_[(5) - (1)]), (yysemantic_stack_[(5) - (2)].objects), (yysemantic_stack_[(5) - (5)].coordinates)); CLEANUP((yysemantic_stack_[(5) - (2)].objects)); CLEANUP((yysemantic_stack_[(5) - (5)].coordinates)); }
     break;
   case 27:
 /* Line 690 of lalr1.cc  */
 #line 251 "f_n_b/parser.yy"
     { (yyval.player) = driver.forGame().createPlayer((yylocation_stack_[(5) - (1)]), (yysemantic_stack_[(5) - (2)].identifier), (yysemantic_stack_[(5) - (4)].identifiers));
                                                   CLEANUP((yysemantic_stack_[(5) - (2)].identifier)); CLEANUP((yysemantic_stack_[(5) - (4)].identifiers)); }
     break;
   case 28:
 /* Line 690 of lalr1.cc  */
 #line 258 "f_n_b/parser.yy"
     { (yyval.param) = driver.forValue().get((yylocation_stack_[(1) - (1)]), (yysemantic_stack_[(1) - (1)].identifier)); CLEANUP((yysemantic_stack_[(1) - (1)].identifier)); }
     break;
   case 29:
 /* Line 690 of lalr1.cc  */
 #line 259 "f_n_b/parser.yy"
     { (yyval.param) = driver.forValue().get((yylocation_stack_[(1) - (1)]), (yysemantic_stack_[(1) - (1)].number)); CLEANUP((yysemantic_stack_[(1) - (1)].number)); }
     break;
   case 30:
 /* Line 690 of lalr1.cc  */
 #line 263 "f_n_b/parser.yy"
     { (yyval.params) = driver.forParams().insert((yysemantic_stack_[(3) - (3)].param), (yysemantic_stack_[(3) - (1)].params)); CLEANUP((yysemantic_stack_[(3) - (3)].param)); CLEANUP((yysemantic_stack_[(3) - (1)].params)); }
     break;
   case 31:
 /* Line 690 of lalr1.cc  */
 #line 264 "f_n_b/parser.yy"
     { (yyval.params) = driver.forParams().create((yysemantic_stack_[(1) - (1)].param)); CLEANUP((yysemantic_stack_[(1) - (1)].param)); }
     break;
   case 32:
 /* Line 690 of lalr1.cc  */
 #line 270 "f_n_b/parser.yy"
     { (yyval.identifiers) = driver.forIdentifiers().insert((yysemantic_stack_[(3) - (3)].identifier), (yysemantic_stack_[(3) - (1)].identifiers)); CLEANUP((yysemantic_stack_[(3) - (3)].identifier)); CLEANUP((yysemantic_stack_[(3) - (1)].identifiers)); }
     break;
   case 33:
 /* Line 690 of lalr1.cc  */
 #line 271 "f_n_b/parser.yy"
     { (yyval.identifiers) = driver.forIdentifiers().create((yysemantic_stack_[(1) - (1)].identifier)); CLEANUP((yysemantic_stack_[(1) - (1)].identifier)); }
     break;
   case 34:
 /* Line 690 of lalr1.cc  */
 #line 277 "f_n_b/parser.yy"
     { (yyval.conditions) = (yysemantic_stack_[(1) - (1)].conditions); }
     break;
   case 35:
 /* Line 690 of lalr1.cc  */
 #line 278 "f_n_b/parser.yy"
     { (yyval.conditions) = driver.forConditions().empty(); }
     break;
   case 36:
 /* Line 690 of lalr1.cc  */
 #line 282 "f_n_b/parser.yy"
     { (yyval.conditions) = driver.forConditions().insert((yysemantic_stack_[(3) - (3)].condition), (yysemantic_stack_[(3) - (1)].conditions));
                                               CLEANUP((yysemantic_stack_[(3) - (3)].condition)); CLEANUP((yysemantic_stack_[(3) - (1)].conditions)); }
     break;
   case 37:
 /* Line 690 of lalr1.cc  */
 #line 284 "f_n_b/parser.yy"
     { (yyval.conditions) = driver.forConditions().create((yysemantic_stack_[(2) - (2)].condition));
                                               CLEANUP((yysemantic_stack_[(2) - (2)].condition)); }
     break;
   case 38:
 /* Line 690 of lalr1.cc  */
 #line 289 "f_n_b/parser.yy"
     { (yyval.condition) = driver.forCondition().playerChoosed((yylocation_stack_[(4) - (1)]), (yysemantic_stack_[(4) - (2)].object), (yysemantic_stack_[(4) - (4)].object));
                                       CLEANUP((yysemantic_stack_[(4) - (2)].object)); CLEANUP((yysemantic_stack_[(4) - (4)].object)); }
     break;
   case 39:
 /* Line 690 of lalr1.cc  */
 #line 291 "f_n_b/parser.yy"
     { (yyval.condition) = driver.forCondition().playerWithin((yylocation_stack_[(6) - (1)]), (yysemantic_stack_[(6) - (2)].object), (yysemantic_stack_[(6) - (5)].objects));
                                       CLEANUP((yysemantic_stack_[(6) - (2)].object)); CLEANUP((yysemantic_stack_[(6) - (5)].objects)); }
     break;
   case 40:
 /* Line 690 of lalr1.cc  */
 #line 293 "f_n_b/parser.yy"
     { (yyval.condition) = driver.forCondition().informationSetChoosed((yylocation_stack_[(6) - (1)]), (yysemantic_stack_[(6) - (2)].object), (yysemantic_stack_[(6) - (4)].object), (yysemantic_stack_[(6) - (6)].object));
                                       CLEANUP((yysemantic_stack_[(6) - (2)].object)); CLEANUP((yysemantic_stack_[(6) - (4)].object)); CLEANUP((yysemantic_stack_[(6) - (6)].object)); }
     break;
   case 41:
 /* Line 690 of lalr1.cc  */
 #line 295 "f_n_b/parser.yy"
     {(yyval.condition) = driver.forCondition().informationSetWithin((yylocation_stack_[(8) - (1)]),(yysemantic_stack_[(8) - (2)].object),(yysemantic_stack_[(8) - (4)].object),(yysemantic_stack_[(8) - (7)].objects));
                                       CLEANUP((yysemantic_stack_[(8) - (2)].object)); CLEANUP((yysemantic_stack_[(8) - (4)].object)); CLEANUP((yysemantic_stack_[(8) - (7)].objects)); }
     break;
   case 42:
 /* Line 690 of lalr1.cc  */
 #line 302 "f_n_b/parser.yy"
     { (yyval.coordinates) = (yysemantic_stack_[(1) - (1)].coordinates); }
     break;
   case 43:
 /* Line 690 of lalr1.cc  */
 #line 306 "f_n_b/parser.yy"
     { (yyval.coordinates) = driver.forCoordinates().insert((yysemantic_stack_[(3) - (3)].coordinate), (yysemantic_stack_[(3) - (1)].coordinates));
                                                 CLEANUP((yysemantic_stack_[(3) - (3)].coordinate)); CLEANUP((yysemantic_stack_[(3) - (1)].coordinates)); }
     break;
   case 44:
 /* Line 690 of lalr1.cc  */
 #line 308 "f_n_b/parser.yy"
     { (yyval.coordinates) = driver.forCoordinates().create((yysemantic_stack_[(1) - (1)].coordinate)); CLEANUP((yysemantic_stack_[(1) - (1)].coordinate)); }
     break;
   case 45:
 /* Line 690 of lalr1.cc  */
 #line 312 "f_n_b/parser.yy"
     { (yyval.coordinate) = driver.forCoordinate().fillWithData((yylocation_stack_[(5) - (1)]), (yysemantic_stack_[(5) - (2)].coordinate), (yysemantic_stack_[(5) - (4)].coordinates));
                                                        CLEANUP((yysemantic_stack_[(5) - (2)].coordinate)); CLEANUP((yysemantic_stack_[(5) - (4)].coordinates)); }
     break;
   case 46:
 /* Line 690 of lalr1.cc  */
 #line 314 "f_n_b/parser.yy"
     { (yyval.coordinate) = driver.forCoordinate().fillWithData((yylocation_stack_[(5) - (1)]), (yysemantic_stack_[(5) - (2)].coordinate), (yysemantic_stack_[(5) - (4)].params));
                                                        CLEANUP((yysemantic_stack_[(5) - (2)].coordinate)); CLEANUP((yysemantic_stack_[(5) - (4)].params)); }
     break;
   case 47:
 /* Line 690 of lalr1.cc  */
 #line 319 "f_n_b/parser.yy"
     { (yyval.coordinate) = driver.forCoordinate().merge((yylocation_stack_[(3) - (1)]), (yysemantic_stack_[(3) - (1)].coordinate), (yysemantic_stack_[(3) - (3)].coordinate)); CLEANUP((yysemantic_stack_[(3) - (1)].coordinate)); CLEANUP((yysemantic_stack_[(3) - (3)].coordinate)); }
     break;
   case 48:
 /* Line 690 of lalr1.cc  */
 #line 320 "f_n_b/parser.yy"
     { (yyval.coordinate) = (yysemantic_stack_[(1) - (1)].coordinate); }
     break;
   case 49:
 /* Line 690 of lalr1.cc  */
 #line 324 "f_n_b/parser.yy"
     { (yyval.coordinate) = driver.forCoordinate().create((yylocation_stack_[(3) - (1)]), (yysemantic_stack_[(3) - (1)].identifier), (yysemantic_stack_[(3) - (3)].identifier)); CLEANUP((yysemantic_stack_[(3) - (1)].identifier)); CLEANUP((yysemantic_stack_[(3) - (3)].identifier)); }
     break;
   case 51:
 /* Line 690 of lalr1.cc  */
 #line 331 "f_n_b/parser.yy"
     {
         // TODO: create MessageFactory
         std::string message = std::string() + "not recognized symbols: \"" + (**(yysemantic_stack_[(1) - (1)].identifier)) + "\"";
         driver.showError((yylocation_stack_[(1) - (1)]), message);
         CLEANUP((yysemantic_stack_[(1) - (1)].identifier));
     }
     break;
 /* Line 690 of lalr1.cc  */
 #line 1012 "src/gt/gtl/parser.cpp"
     default:
           break;
       }
     /* User semantic actions sometimes alter yychar, and that requires
        that yytoken be updated with the new translation.  We take the
        approach of translating immediately before every use of yytoken.
        One alternative is translating here after every semantic action,
        but that translation would be missed if the semantic action
        invokes YYABORT, YYACCEPT, or YYERROR immediately after altering
        yychar.  In the case of YYABORT or YYACCEPT, an incorrect
        destructor might then be invoked immediately.  In the case of
        YYERROR, subsequent parser actions might lead to an incorrect
        destructor call or verbose syntax error message before the
        lookahead is translated.  */
     YY_SYMBOL_PRINT ("-> $$ =", yyr1_[yyn], &yyval, &yyloc);
     yypop_ (yylen);
     yylen = 0;
     YY_STACK_PRINT ();
     yysemantic_stack_.push (yyval);
     yylocation_stack_.push (yyloc);
     /* Shift the result of the reduction.  */
     yyn = yyr1_[yyn];
     yystate = yypgoto_[yyn - yyntokens_] + yystate_stack_[0];
     if (0 <= yystate && yystate <= yylast_
     && yycheck_[yystate] == yystate_stack_[0])
       yystate = yytable_[yystate];
     else
       yystate = yydefgoto_[yyn - yyntokens_];
     goto yynewstate;
   /*------------------------------------.
   | yyerrlab -- here on detecting error |
   `------------------------------------*/
   yyerrlab:
     /* Make sure we have latest lookahead translation.  See comments at
        user semantic actions for why this is necessary.  */
     yytoken = yytranslate_ (yychar);
     /* If not already recovering from an error, report this error.  */
     if (!yyerrstatus_)
       {
     ++yynerrs_;
     if (yychar == yyempty_)
       yytoken = yyempty_;
     error (yylloc, yysyntax_error_ (yystate, yytoken));
       }
     yyerror_range[1] = yylloc;
     if (yyerrstatus_ == 3)
       {
     /* If just tried and failed to reuse lookahead token after an
      error, discard it.  */
     if (yychar <= yyeof_)
       {
       /* Return failure if at end of input.  */
       if (yychar == yyeof_)
         YYABORT;
       }
     else
       {
         yydestruct_ ("Error: discarding", yytoken, &yylval, &yylloc);
         yychar = yyempty_;
       }
       }
     /* Else will try to reuse lookahead token after shifting the error
        token.  */
     goto yyerrlab1;
   /*---------------------------------------------------.
   | yyerrorlab -- error raised explicitly by YYERROR.  |
   `---------------------------------------------------*/
   yyerrorlab:
     /* Pacify compilers like GCC when the user code never invokes
        YYERROR and the label yyerrorlab therefore never appears in user
        code.  */
     if (false)
       goto yyerrorlab;
     yyerror_range[1] = yylocation_stack_[yylen - 1];
     /* Do not reclaim the symbols of the rule which action triggered
        this YYERROR.  */
     yypop_ (yylen);
     yylen = 0;
     yystate = yystate_stack_[0];
     goto yyerrlab1;
   /*-------------------------------------------------------------.
   | yyerrlab1 -- common code for both syntax error and YYERROR.  |
   `-------------------------------------------------------------*/
   yyerrlab1:
     yyerrstatus_ = 3;   /* Each real token shifted decrements this.  */
     for (;;)
       {
     yyn = yypact_[yystate];
     if (!yy_pact_value_is_default_ (yyn))
     {
       yyn += yyterror_;
       if (0 <= yyn && yyn <= yylast_ && yycheck_[yyn] == yyterror_)
         {
           yyn = yytable_[yyn];
           if (0 < yyn)
         break;
         }
     }
     /* Pop the current state because it cannot handle the error token.  */
     if (yystate_stack_.height () == 1)
     YYABORT;
     yyerror_range[1] = yylocation_stack_[0];
     yydestruct_ ("Error: popping",
              yystos_[yystate],
              &yysemantic_stack_[0], &yylocation_stack_[0]);
     yypop_ ();
     yystate = yystate_stack_[0];
     YY_STACK_PRINT ();
       }
     yyerror_range[2] = yylloc;
     // Using YYLLOC is tempting, but would change the location of
     // the lookahead.  YYLOC is available though.
     YYLLOC_DEFAULT (yyloc, yyerror_range, 2);
     yysemantic_stack_.push (yylval);
     yylocation_stack_.push (yyloc);
     /* Shift the error token.  */
     YY_SYMBOL_PRINT ("Shifting", yystos_[yyn],
              &yysemantic_stack_[0], &yylocation_stack_[0]);
     yystate = yyn;
     goto yynewstate;
     /* Accept.  */
   yyacceptlab:
     yyresult = 0;
     goto yyreturn;
     /* Abort.  */
   yyabortlab:
     yyresult = 1;
     goto yyreturn;
   yyreturn:
     if (yychar != yyempty_)
       {
         /* Make sure we have latest lookahead translation.  See comments
            at user semantic actions for why this is necessary.  */
         yytoken = yytranslate_ (yychar);
         yydestruct_ ("Cleanup: discarding lookahead", yytoken, &yylval,
                      &yylloc);
       }
     /* Do not reclaim the symbols of the rule which action triggered
        this YYABORT or YYACCEPT.  */
     yypop_ (yylen);
     while (yystate_stack_.height () != 1)
       {
     yydestruct_ ("Cleanup: popping",
            yystos_[yystate_stack_[0]],
            &yysemantic_stack_[0],
            &yylocation_stack_[0]);
     yypop_ ();
       }
     return yyresult;
   }
void GT::GTL::Parser::set_debug_level (debug_level_type l)
Set the current debugging level.
void GT::GTL::Parser::set_debug_stream (std::ostream &)
Set the current debugging stream.
bool GT::GTL::Parser::yy_pact_value_is_default_ (int yyvalue) inline static private
Whether the given yypact_ value indicates a defaulted state.
Parameters
yyvalue the value to check
Definition at line 539 of file parser.cpp.
References yypact_ninf_.
Referenced by parse(), and yysyntax_error_().
   {
     return yyvalue == yypact_ninf_;
   }
virtual void GT::GTL::Parser::yy_reduce_print_ (int r) private virtual
Report on the debug stream that the rule r is going to be reduced.
virtual void GT::GTL::Parser::yy_symbol_print_ (int yytype, const semantic_type * yyvaluep, const location_type * yylocationp) private virtual
Report a symbol on the debug stream.
Parameters
yytype The token type.
yyvaluep Its semantic value.
yylocationp Its location.
virtual void GT::GTL::Parser::yy_symbol_value_print_ (int yytype, const semantic_type * yyvaluep, const location_type * yylocationp) private virtual
Report a symbol value on the debug stream.
Parameters
yytype The token type.
yyvaluep Its semantic value.
yylocationp Its location.
bool GT::GTL::Parser::yy_table_value_is_error_ (int yyvalue) inline static private
Whether the given yytable_ value indicates a syntax error.
Parameters
yyvalue the value to check
Definition at line 545 of file parser.cpp.
References yytable_ninf_.
Referenced by parse(), and yysyntax_error_().
   {
     return yyvalue == yytable_ninf_;
   }
void GT::GTL::Parser::yydestruct_ (const char * yymsg, int yytype, semantic_type * yyvaluep, location_type * yylocationp) inline private
Reclaim the memory associated to a symbol.
Parameters
yymsg Why this token is reclaimed.
yytype The symbol type.
yyvaluep Its semantic value.
yylocationp Its location.
Definition at line 270 of file parser.cpp.
References CLEANUP, GT::GTL::Parser::semantic_type::condition, GT::GTL::Parser::semantic_type::conditions, GT::GTL::Parser::semantic_type::coordinate, GT::GTL::Parser::semantic_type::coordinates, GT::GTL::Parser::semantic_type::definition, GT::GTL::Parser::semantic_type::details, GT::GTL::Parser::semantic_type::game, GT::GTL::Parser::semantic_type::identifier, GT::GTL::Parser::semantic_type::identifiers, GT::GTL::Parser::semantic_type::number, GT::GTL::Parser::semantic_type::object, GT::GTL::Parser::semantic_type::objects, GT::GTL::Parser::semantic_type::param, GT::GTL::Parser::semantic_type::params, GT::GTL::Parser::semantic_type::player, GT::GTL::Parser::semantic_type::query, YY_SYMBOL_PRINT, and YYUSE.
Referenced by parse().
   {
     YYUSE (yylocationp);
     YYUSE (yymsg);
     YYUSE (yyvaluep);
     YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
     switch (yytype)
       {
         case 28: /* "lexer_error" */
 /* Line 480 of lalr1.cc  */
 #line 152 "f_n_b/parser.yy"
     { if ((yyvaluep->identifier)) { CLEANUP((yyvaluep->identifier)); } };
 /* Line 480 of lalr1.cc  */
 #line 289 "src/gt/gtl/parser.cpp"
     break;
       case 29: /* "identifier" */
 /* Line 480 of lalr1.cc  */
 #line 152 "f_n_b/parser.yy"
     { if ((yyvaluep->identifier)) { CLEANUP((yyvaluep->identifier)); } };
 /* Line 480 of lalr1.cc  */
 #line 298 "src/gt/gtl/parser.cpp"
     break;
       case 30: /* "number" */
 /* Line 480 of lalr1.cc  */
 #line 154 "f_n_b/parser.yy"
     { if ((yyvaluep->number)) { CLEANUP((yyvaluep->number)); } };
 /* Line 480 of lalr1.cc  */
 #line 307 "src/gt/gtl/parser.cpp"
     break;
       case 35: /* "context_execute" */
 /* Line 480 of lalr1.cc  */
 #line 152 "f_n_b/parser.yy"
     { if ((yyvaluep->identifier)) { CLEANUP((yyvaluep->identifier)); } };
 /* Line 480 of lalr1.cc  */
 #line 316 "src/gt/gtl/parser.cpp"
     break;
       case 36: /* "context_load" */
 /* Line 480 of lalr1.cc  */
 #line 152 "f_n_b/parser.yy"
     { if ((yyvaluep->identifier)) { CLEANUP((yyvaluep->identifier)); } };
 /* Line 480 of lalr1.cc  */
 #line 325 "src/gt/gtl/parser.cpp"
     break;
       case 37: /* "context_save" */
 /* Line 480 of lalr1.cc  */
 #line 152 "f_n_b/parser.yy"
     { if ((yyvaluep->identifier)) { CLEANUP((yyvaluep->identifier)); } };
 /* Line 480 of lalr1.cc  */
 #line 334 "src/gt/gtl/parser.cpp"
     break;
       case 38: /* "definition" */
 /* Line 480 of lalr1.cc  */
 #line 159 "f_n_b/parser.yy"
     { if ((yyvaluep->definition)) { CLEANUP((yyvaluep->definition)); } };
 /* Line 480 of lalr1.cc  */
 #line 343 "src/gt/gtl/parser.cpp"
     break;
       case 39: /* "query" */
 /* Line 480 of lalr1.cc  */
 #line 162 "f_n_b/parser.yy"
     { if ((yyvaluep->query)) { CLEANUP((yyvaluep->query)); } };
 /* Line 480 of lalr1.cc  */
 #line 352 "src/gt/gtl/parser.cpp"
     break;
       case 40: /* "objects" */
 /* Line 480 of lalr1.cc  */
 #line 164 "f_n_b/parser.yy"
     { if ((yyvaluep->objects)) { CLEANUP((yyvaluep->objects)); } };
 /* Line 480 of lalr1.cc  */
 #line 361 "src/gt/gtl/parser.cpp"
     break;
       case 41: /* "object" */
 /* Line 480 of lalr1.cc  */
 #line 163 "f_n_b/parser.yy"
     { if ((yyvaluep->object)) { CLEANUP((yyvaluep->object)); } };
 /* Line 480 of lalr1.cc  */
 #line 370 "src/gt/gtl/parser.cpp"
     break;
       case 42: /* "game" */
 /* Line 480 of lalr1.cc  */
 #line 161 "f_n_b/parser.yy"
     { if ((yyvaluep->game)) { CLEANUP((yyvaluep->game)); } };
 /* Line 480 of lalr1.cc  */
 #line 379 "src/gt/gtl/parser.cpp"
     break;
       case 44: /* "details" */
 /* Line 480 of lalr1.cc  */
 #line 160 "f_n_b/parser.yy"
     { if ((yyvaluep->details)) { CLEANUP((yyvaluep->details)); } };
 /* Line 480 of lalr1.cc  */
 #line 388 "src/gt/gtl/parser.cpp"
     break;
       case 45: /* "player" */
 /* Line 480 of lalr1.cc  */
 #line 167 "f_n_b/parser.yy"
     { if ((yyvaluep->player)) { CLEANUP((yyvaluep->player)); } };
 /* Line 480 of lalr1.cc  */
 #line 397 "src/gt/gtl/parser.cpp"
     break;
       case 46: /* "param" */
 /* Line 480 of lalr1.cc  */
 #line 165 "f_n_b/parser.yy"
     { if ((yyvaluep->param)) { CLEANUP((yyvaluep->param)); } };
 /* Line 480 of lalr1.cc  */
 #line 406 "src/gt/gtl/parser.cpp"
     break;
       case 47: /* "params" */
 /* Line 480 of lalr1.cc  */
 #line 166 "f_n_b/parser.yy"
     { if ((yyvaluep->params)) { CLEANUP((yyvaluep->params)); } };
 /* Line 480 of lalr1.cc  */
 #line 415 "src/gt/gtl/parser.cpp"
     break;
       case 48: /* "identifiers" */
 /* Line 480 of lalr1.cc  */
 #line 153 "f_n_b/parser.yy"
     { if ((yyvaluep->identifiers)) { CLEANUP((yyvaluep->identifiers)); } };
 /* Line 480 of lalr1.cc  */
 #line 424 "src/gt/gtl/parser.cpp"
     break;
       case 49: /* "conditions" */
 /* Line 480 of lalr1.cc  */
 #line 156 "f_n_b/parser.yy"
     { if ((yyvaluep->conditions)) { CLEANUP((yyvaluep->conditions)); } };
 /* Line 480 of lalr1.cc  */
 #line 433 "src/gt/gtl/parser.cpp"
     break;
       case 50: /* "condition_collection" */
 /* Line 480 of lalr1.cc  */
 #line 156 "f_n_b/parser.yy"
     { if ((yyvaluep->conditions)) { CLEANUP((yyvaluep->conditions)); } };
 /* Line 480 of lalr1.cc  */
 #line 442 "src/gt/gtl/parser.cpp"
     break;
       case 51: /* "condition" */
 /* Line 480 of lalr1.cc  */
 #line 155 "f_n_b/parser.yy"
     { if ((yyvaluep->condition)) { CLEANUP((yyvaluep->condition)); } };
 /* Line 480 of lalr1.cc  */
 #line 451 "src/gt/gtl/parser.cpp"
     break;
       case 52: /* "data" */
 /* Line 480 of lalr1.cc  */
 #line 158 "f_n_b/parser.yy"
     { if ((yyvaluep->coordinates)) { CLEANUP((yyvaluep->coordinates)); } };
 /* Line 480 of lalr1.cc  */
 #line 460 "src/gt/gtl/parser.cpp"
     break;
       case 53: /* "data_coordinates" */
 /* Line 480 of lalr1.cc  */
 #line 158 "f_n_b/parser.yy"
     { if ((yyvaluep->coordinates)) { CLEANUP((yyvaluep->coordinates)); } };
 /* Line 480 of lalr1.cc  */
 #line 469 "src/gt/gtl/parser.cpp"
     break;
       case 54: /* "data_coordinate" */
 /* Line 480 of lalr1.cc  */
 #line 157 "f_n_b/parser.yy"
     { if ((yyvaluep->coordinate)) { CLEANUP((yyvaluep->coordinate)); } };
 /* Line 480 of lalr1.cc  */
 #line 478 "src/gt/gtl/parser.cpp"
     break;
       case 55: /* "coordinates" */
 /* Line 480 of lalr1.cc  */
 #line 157 "f_n_b/parser.yy"
     { if ((yyvaluep->coordinate)) { CLEANUP((yyvaluep->coordinate)); } };
 /* Line 480 of lalr1.cc  */
 #line 487 "src/gt/gtl/parser.cpp"
     break;
       case 56: /* "coordinate" */
 /* Line 480 of lalr1.cc  */
 #line 157 "f_n_b/parser.yy"
     { if ((yyvaluep->coordinate)) { CLEANUP((yyvaluep->coordinate)); } };
 /* Line 480 of lalr1.cc  */
 #line 496 "src/gt/gtl/parser.cpp"
     break;
     default:
       break;
       }
   }
void GT::GTL::Parser::yypop_ (unsigned int n = 1) inline private
Pop n symbols the three stacks.
Definition at line 504 of file parser.cpp.
References GT::GTL::stack< T, S >::pop(), yylocation_stack_, yysemantic_stack_, and yystate_stack_.
Referenced by parse().
   {
     yystate_stack_.pop (n);
     yysemantic_stack_.pop (n);
     yylocation_stack_.pop (n);
   }
virtual void GT::GTL::Parser::yystack_print_ () private virtual
Print the state stack on the debug stream.
std::string GT::GTL::Parser::yysyntax_error_ (int yystate, int tok) private virtual
Generate an error message.
Parameters
state the state where the error occurred.
tok the lookahead token.
Definition at line 1189 of file parser.cpp.
References string, YY_, yy_pact_value_is_default_(), yy_table_value_is_error_(), YYCASE_, yycheck_, yyempty_, yylast_, yyntokens_, yypact_, yytable_, yyterror_, yytname_, and yytnamerr_().
Referenced by parse().
   {
     std::string yyres;
     // Number of reported tokens (one for the "unexpected", one per
     // "expected").
     size_t yycount = 0;
     // Its maximum.
     enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
     // Arguments of yyformat.
     char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
     /* There are many possibilities here to consider:
        - If this state is a consistent state with a default action, then
          the only way this function was invoked is if the default action
          is an error action.  In that case, don't check for expected
          tokens because there are none.
        - The only way there can be no lookahead present (in yytoken) is
          if this state is a consistent state with a default action.
          Thus, detecting the absence of a lookahead is sufficient to
          determine that there is no unexpected or expected token to
          report.  In that case, just report a simple "syntax error".
        - Don't assume there isn't a lookahead just because this state is
          a consistent state with a default action.  There might have
          been a previous inconsistent state, consistent state with a
          non-default action, or user semantic action that manipulated
          yychar.
        - Of course, the expected token list depends on states to have
          correct lookahead information, and it depends on the parser not
          to perform extra reductions after fetching a lookahead from the
          scanner and before detecting a syntax error.  Thus, state
          merging (from LALR or IELR) and default reductions corrupt the
          expected token list.  However, the list is correct for
          canonical LR with one exception: it will still contain any
          token that will not be accepted due to an error action in a
          later state.
     */
     if (yytoken != yyempty_)
       {
         yyarg[yycount++] = yytname_[yytoken];
         int yyn = yypact_[yystate];
         if (!yy_pact_value_is_default_ (yyn))
           {
             /* Start YYX at -YYN if negative to avoid negative indexes in
                YYCHECK.  In other words, skip the first -YYN actions for
                this state because they are default actions.  */
             int yyxbegin = yyn < 0 ? -yyn : 0;
             /* Stay within bounds of both yycheck and yytname.  */
             int yychecklim = yylast_ - yyn + 1;
             int yyxend = yychecklim < yyntokens_ ? yychecklim : yyntokens_;
             for (int yyx = yyxbegin; yyx < yyxend; ++yyx)
               if (yycheck_[yyx + yyn] == yyx && yyx != yyterror_
                   && !yy_table_value_is_error_ (yytable_[yyx + yyn]))
                 {
                   if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                     {
                       yycount = 1;
                       break;
                     }
                   else
                     yyarg[yycount++] = yytname_[yyx];
                 }
           }
       }
     char const* yyformat = 0;
     switch (yycount)
       {
 #define YYCASE_(N, S)                         \
         case N:                               \
           yyformat = S;                       \
         break
         YYCASE_(0, YY_("syntax error"));
         YYCASE_(1, YY_("syntax error, unexpected %s"));
         YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
         YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
         YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
         YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
 #undef YYCASE_
       }
     // Argument number.
     size_t yyi = 0;
     for (char const* yyp = yyformat; *yyp; ++yyp)
       if (yyp[0] == '%' && yyp[1] == 's' && yyi < yycount)
         {
           yyres += yytnamerr_ (yyarg[yyi++]);
           ++yyp;
         }
       else
         yyres += *yyp;
     return yyres;
   }
std::string GT::GTL::Parser::yytnamerr_ (const char * n) static private
Convert the symbol name n to a form suitable for a diagnostic.
Definition at line 190 of file parser.cpp.
References string.
Referenced by yysyntax_error_().
   {
     if (*yystr == '"')
       {
         std::string yyr = "";
         char const *yyp = yystr;
         for (;;)
           switch (*++yyp)
             {
             case '\'':
             case ',':
               goto do_not_strip_quotes;
             case '\\':
               if (*++yyp != '\\')
                 goto do_not_strip_quotes;
               /* Fall through.  */
             default:
               yyr += *yyp;
               break;
             case '"':
               return yyr;
             }
       do_not_strip_quotes: ;
       }
     return yystr;
   }
Parser::token_number_type GT::GTL::Parser::yytranslate_ (int t) private
Convert a scanner token number t to a symbol number.
Definition at line 1531 of file parser.cpp.
References yyundef_token_, and yyuser_token_number_max_.
Referenced by parse().
   {
     static
     const token_number_type
     translate_table[] =
     {
            0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
        2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
        5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
       15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
       25,    26,    27,    28,    29,    30
     };
     if ((unsigned int) t <= yyuser_token_number_max_)
       return translate_table[t];
     else
       return yyundef_token_;
   }
Member Data Documentation
Driver& GT::GTL::Parser::driver private
Definition at line 335 of file parser.hpp.
Referenced by error(), and parse().
Scanner& GT::GTL::Parser::scanner private
Definition at line 334 of file parser.hpp.
Referenced by parse().
std::ostream* GT::GTL::Parser::yycdebug_ private
Definition at line 301 of file parser.hpp.
const signed char GT::GTL::Parser::yycheck_ static private
Initial value:
=
  {
        33,    56,     0,     1,    14,     3,     4,     5,    29,     7,
       0,     1,    94,     3,     4,     5,    26,     7,    13,    52,
      17,    19,    77,   105,    21,     9,    59,    11,    12,    19,
      28,    26,    25,    26,    23,    90,    22,    26,    28,    72,
       0,    74,    20,    29,    30,    29,    30,    29,    26,    16,
      17,    84,    23,    23,    21,    26,    26,    23,    23,     6,
      26,    26,     8,    22,    27,    29,    30,    29,    29,    27,
      27,    27,    27,    10,    10,    29,    29,    29,    13,     9,
      18,    26,    15,    22,    26,    29,    29,    10,    22,    58,
      22,    94,    -1,    24,    62,    89,    95,    -1,    -1,    50,
      -1,    -1,    -1,    -1,    -1,    55
  }
Definition at line 265 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
int GT::GTL::Parser::yydebug_ private
Definition at line 300 of file parser.hpp.
const unsigned char GT::GTL::Parser::yydefact_ static private
Initial value:
=
  {
         0,     3,    50,     0,     0,     0,     0,     0,    51,     0,
       0,     5,     0,     0,     0,     0,     0,    11,    12,    13,
       0,     0,    33,     0,     1,     2,     4,     6,     7,     8,
       9,    10,    14,     0,     0,     0,     0,     0,     0,    28,
      29,    15,    19,    20,    21,    35,    18,    32,     0,     0,
       0,     0,     0,    16,    34,     0,     0,    24,    24,     0,
      37,    17,     0,     0,     0,    25,    22,    23,     0,    36,
      27,     0,     0,     0,     0,     0,     0,     0,    38,     0,
      26,    42,    44,     0,     0,     0,     0,     0,    48,     0,
       0,    40,    39,     0,     0,     0,    43,     0,    49,    31,
       0,     0,    47,    41,    46,     0,    45,    30
  }
For a state, default reduction number. Unlessyytable_ specifies something else to do. Zero means the default is an error.
Definition at line 252 of file parser.hpp.
Referenced by parse().
const signed char GT::GTL::Parser::yydefgoto_ static private
Initial value:
=
  {
        -1,     9,    10,    11,    12,    13,    14,    15,    16,    45,
      46,    42,    66,    57,    43,    44,   100,    23,    53,    54,
      60,    80,    81,    82,    87,    88,    17
  }
Definition at line 255 of file parser.hpp.
Referenced by parse().
const int GT::GTL::Parser::yyempty_ = -2 static private
Definition at line 325 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
const int GT::GTL::Parser::yyeof_ = 0 static private
Definition at line 321 of file parser.hpp.
Referenced by parse().
const int GT::GTL::Parser::yyerrcode_ = 256 static private
Definition at line 328 of file parser.hpp.
const int GT::GTL::Parser::yyfinal_ = 24 static private
Definition at line 326 of file parser.hpp.
Referenced by parse().
const int GT::GTL::Parser::yylast_ = 105 static private
Definition at line 323 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
location_stack_type GT::GTL::Parser::yylocation_stack_ private
The location stack.
Definition at line 232 of file parser.hpp.
Referenced by parse(), and yypop_().
const int GT::GTL::Parser::yynnts_ = 27 static private
Definition at line 324 of file parser.hpp.
const int GT::GTL::Parser::yyntokens_ = 31 static private
Definition at line 329 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
const signed char GT::GTL::Parser::yypact_ static private
Initial value:
=
  {
         2,   -83,   -83,   -21,    18,    53,    38,    39,   -83,    40,
      10,   -83,    37,    42,    43,    44,    45,   -83,   -83,   -83,
      46,    54,   -83,    22,   -83,   -83,   -83,   -83,   -83,   -83,
     -83,   -83,   -83,    16,    16,    47,    48,    63,    64,   -83,
     -83,   -83,   -83,   -83,   -83,     5,   -83,   -83,    41,    65,
      65,    70,    16,   -83,    55,    39,    16,    62,    62,    16,
     -83,   -83,    70,    11,   -10,   -83,   -83,   -83,    33,   -83,
     -83,    67,    16,    61,    16,    66,     3,    16,   -83,    56,
     -83,    58,   -83,    68,    16,    29,    69,     7,   -83,    66,
      16,   -83,   -83,    57,    14,    56,   -83,    30,   -83,   -83,
      34,    35,   -83,   -83,   -83,    36,   -83,   -83
  }
For a state, the index in yytable_ of its portion.
Definition at line 246 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
const signed char GT::GTL::Parser::yypact_ninf_ = -83 static private
Definition at line 247 of file parser.hpp.
Referenced by yy_pact_value_is_default_().
const signed char GT::GTL::Parser::yypgoto_ static private
Initial value:
=
  {
       -83,   -83,   -83,    77,   -83,   -83,   -83,   -83,   -83,   -55,
     -33,   -83,    31,    49,   -83,   -82,   -83,    50,   -83,   -83,
      32,   -83,    -3,     6,   -83,     1,   -83
  }
Definition at line 254 of file parser.hpp.
Referenced by parse().
const unsigned char GT::GTL::Parser::yyprhs_[] static private
For each rule, the index of the first RHS symbol in yyrhs_.
Definition at line 289 of file parser.hpp.
const unsigned char GT::GTL::Parser::yyr1_ static private
Initial value:
=
  {
         0,    31,    32,    32,    33,    33,    34,    34,    34,    34,
      34,    34,    35,    36,    37,    38,    39,    40,    40,    41,
      41,    41,    42,    42,    43,    43,    44,    45,    46,    46,
      47,    47,    48,    48,    49,    49,    50,    50,    51,    51,
      51,    51,    52,    53,    53,    54,    54,    55,    55,    56,
      57,    57
  }
For a rule, its LHS.
Definition at line 271 of file parser.hpp.
Referenced by parse().
const unsigned char GT::GTL::Parser::yyr2_ static private
Initial value:
=
  {
         0,     2,     2,     1,     2,     1,     2,     2,     2,     2,
       2,     1,     2,     2,     3,     4,     5,     3,     1,     1,
       1,     1,     4,     4,     0,     1,     5,     5,     1,     1,
       3,     1,     3,     1,     1,     0,     3,     2,     4,     6,
       6,     8,     1,     3,     1,     5,     5,     3,     1,     3,
       1,     1
  }
For a rule, its RHS length.
Definition at line 273 of file parser.hpp.
Referenced by parse().
const rhs_number_type GT::GTL::Parser::yyrhs_[] static private
A `-1'-separated list of the rules' RHS.
Definition at line 287 of file parser.hpp.
const unsigned short int GT::GTL::Parser::yyrline_[] static private
For each rule, its source line number.
Definition at line 291 of file parser.hpp.
semantic_stack_type GT::GTL::Parser::yysemantic_stack_ private
The semantic value stack.
Definition at line 230 of file parser.hpp.
Referenced by parse(), and yypop_().
state_stack_type GT::GTL::Parser::yystate_stack_ private
The state stack.
Definition at line 228 of file parser.hpp.
Referenced by parse(), and yypop_().
const unsigned char GT::GTL::Parser::yystos_ static private
Initial value:
=
  {
         0,     0,     1,     3,     4,     5,     7,    19,    28,    32,
      33,    34,    35,    36,    37,    38,    39,    57,    29,    29,
       6,    29,    29,    48,     0,     0,    34,    27,    27,    27,
      27,    27,    29,     8,    20,    26,     9,    11,    12,    29,
      30,    41,    42,    45,    46,    40,    41,    29,    29,    10,
      10,    13,    26,    49,    50,    22,    13,    44,    44,     9,
      51,    41,    26,    48,    40,    18,    43,    43,    41,    51,
      23,    14,    16,    17,    21,    15,    41,    22,    41,    22,
      52,    53,    54,    17,    21,    40,    29,    55,    56,    26,
      22,    41,    23,    24,    25,    26,    54,    40,    29,    46,
      47,    53,    56,    23,    23,    26,    23,    46
  }
For a state, its accessing symbol.
Definition at line 268 of file parser.hpp.
Referenced by parse().
const unsigned char GT::GTL::Parser::yytable_ static private
Initial value:
=
  {
        41,    64,     1,     2,    71,     3,     4,     5,    18,     6,
      25,     2,    99,     3,     4,     5,    52,     6,    51,    61,
      83,     7,    85,   107,    84,    36,    68,    37,    38,     7,
       8,    52,    94,    95,    70,    97,    79,    35,     8,    76,
      24,    78,    34,    39,    40,    39,    40,    19,    35,    72,
      73,    91,    92,   103,    74,    52,    52,   104,   106,    20,
     105,    89,    33,    55,    27,    39,    40,    21,    22,    28,
      29,    30,    31,    49,    50,    32,    47,    48,    56,    59,
      65,    62,    75,    77,    89,    86,    98,    26,    79,    67,
      90,   101,     0,    93,    69,    96,   102,     0,     0,    58,
       0,     0,     0,     0,     0,    63
  }
What to do in a state. yytable_[yypact_[s]]: what to do in state s.
if positive, shift that token.
if negative, reduce the rule which number is the opposite.
if zero, do what YYDEFACT says.
Definition at line 262 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
const signed char GT::GTL::Parser::yytable_ninf_ = -1 static private
Definition at line 263 of file parser.hpp.
Referenced by yy_table_value_is_error_().
const int GT::GTL::Parser::yyterror_ = 1 static private
Definition at line 327 of file parser.hpp.
Referenced by parse(), and yysyntax_error_().
const char* const GT::GTL::Parser::yytname_[] static private
For a symbol, its name in clear.
Definition at line 277 of file parser.hpp.
Referenced by yysyntax_error_().
const unsigned short int GT::GTL::Parser::yytoken_number_[] static private
For each scanner token number, its symbol number.
Definition at line 293 of file parser.hpp.
const Parser::token_number_type GT::GTL::Parser::yyundef_token_ = 2 static private
Definition at line 331 of file parser.hpp.
Referenced by yytranslate_().
const unsigned int GT::GTL::Parser::yyuser_token_number_max_ = 285 static private
Definition at line 330 of file parser.hpp.
Referenced by yytranslate_().
The documentation for this class was generated from the following files:
include/gt/gtl/parser.hpp
src/gt/gtl/parser.cpp