Game Theory Tools (full documentation): GT::Model::Game Class Reference
GT::Model::Game Class Reference abstract
Defines Game.
#include <game.hpp>
Public Member Functions
virtual const PlayersPtr getPlayers () const =0
Returns Game's Players.
virtual const DataAccessorPtr getData () const =0
Grants access to Data specific to a Game.
virtual bool isEqual (const Root &root) const override
Defines equality relation.
virtual Message toString () const =0
Game's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Friends
bool operator== (const GamePtr &game1, const GamePtr &game2)
Syntax sugar for isEqual(const Root&)const method.
bool operator!= (const GamePtr &game1, const GamePtr &game2)
Syntax sugar for !isEqual(const Root&)const method.
OutputStream & operator<< (OutputStream &stream, const GamePtr &game)
Syntax sugar for toString()const method.
Detailed Description
Defines Game.
Author
Mateusz Kubuszok
Definition at line 37 of file game.hpp.
Member Function Documentation
virtual const DataAccessorPtr GT::Model::Game::getData () const pure virtual
Grants access to Data specific to a Game.
Returns
DataAccessor returns DataAccessor specific for a Game
Implemented in GT::Model::NullGame, GT::GTL::LazyGameProxy, GT::Model::ExtensiveGame, and GT::Model::StrategicGame.
Referenced by isEqual().
virtual const PlayersPtr GT::Model::Game::getPlayers () const pure virtual
Returns Game's Players.
Returns
Players
Implemented in GT::Model::NullGame, GT::GTL::LazyGameProxy, GT::Model::ExtensiveGame, and GT::Model::StrategicGame.
Referenced by isEqual().
bool GT::Model::Game::isEqual (const Root & root) const override virtual
Defines equality relation.
Parameters
root another root to compare
Returns
true if roots are equal
Reimplemented from GT::Model::Root.
Definition at line 31 of file game.cpp.
References getData(), and getPlayers().
         {
     const Game* game = dynamic_cast<const Game*>(&root);
     if (!game)
         return false;
     if (game == this)
         return true;
     if (*game->getPlayers() != *getPlayers())
         return false;
     if (*game->getData() != *getData())
         return false;
     return true;
 }
virtual Message GT::Model::Game::toString () const pure virtual
Game's Message.
Returns
Message
Implements GT::Model::Root.
Implemented in GT::Model::NullGame, GT::GTL::LazyGameProxy, GT::Model::ExtensiveGame, and GT::Model::StrategicGame.
Friends And Related Function Documentation
bool operator!= (const GamePtr & game1, const GamePtr & game2) friend
Syntax sugar for !isEqual(const Root&)const method.
Parameters
game1 first Game to compare
game2 second Game to compare
Returns
true if Games are not equal
Definition at line 57 of file game.cpp.
   {
     return (*game1) != (*game2);
 }
OutputStream& operator<< (OutputStream & stream, const GamePtr & game) friend
Syntax sugar for toString()const method.
Parameters
stream stream to concatenate
game Game to concatenate
Returns
stream for chaining
Definition at line 64 of file game.cpp.
   {
     return stream << game->toString();
 }
bool operator== (const GamePtr & game1, const GamePtr & game2) friend
Syntax sugar for isEqual(const Root&)const method.
Parameters
game1 first Game to compare
game2 second Game to compare
Returns
true if Games are equal
Definition at line 50 of file game.cpp.
   {
     return (*game1) == (*game2);
 }
The documentation for this class was generated from the following files:
include/gt/model/game.hpp
src/gt/model/game.cpp