Game Theory Tools (full documentation): GT::Routines::InformationSetRangeCondition Class Reference
GT::Routines::InformationSetRangeCondition Class Reference final
Condition that configures Routine to allow only allowed choices for some Player's information set.
#include <information_set_range_condition.hpp>
Public Member Functions
InformationSetRangeCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifiersPtr strategy)
Initiates Condition with Player's and information set's names and range of strategies.
virtual void configureRoutine (RoutineConfigPtr routineConfig) const override
Configureg given RoutineConfig.
virtual Message toString () const override
Returns Condition's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const IdentifierPtr player
Player's name.
const IdentifierPtr informationSet
Information set's name.
const IdentifiersPtr strategies
Allowed strategies.
Detailed Description
Condition that configures Routine to allow only allowed choices for some Player's information set.
Author
Mateusz Kubuszok
See Also
InformationSetChoiceRoutineConfig
Definition at line 39 of file information_set_range_condition.hpp.
Constructor & Destructor Documentation
GT::Routines::InformationSetRangeCondition::InformationSetRangeCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifiersPtr strategy)
Initiates Condition with Player's and information set's names and range of strategies.
Parameters
player Player that chooses strategy
informationSet information set
strategy range of strategies
Definition at line 35 of file information_set_range_condition.cpp.
   :
     player(definedPlayer),
     informationSet(definedInformationSet),
     strategies(definedStrategies)
     {}
Member Function Documentation
void GT::Routines::InformationSetRangeCondition::configureRoutine (RoutineConfigPtr routineConfig) const override virtual
Configureg given RoutineConfig.
Parameters
routineConfig RoutineConfig to set up
Exceptions
InvalidCondition thrown when Condition is invalid
Implements GT::Routines::Condition.
Definition at line 45 of file information_set_range_condition.cpp.
References GT::Routines::ExceptionFactory::getInstance(), informationSet, GT::Routines::ExceptionFactory::invalidCondition(), player, GT::Routines::InformationSetChoiceRoutineConfig::requireChoiceWithin(), and strategies.
         {
     InformationSetChoiceRoutineConfigPtr specificConfig =
         dynamic_pointer_cast<InformationSetChoiceRoutineConfig>(routineConfig);
     if (!specificConfig)
         return;
     try {
         specificConfig->requireChoiceWithin(*player, *informationSet, *strategies);
     } catch (const InvalidPlayerChoice& e) {
         throw ExceptionFactory::getInstance().invalidCondition(e);
     }
 }
Message GT::Routines::InformationSetRangeCondition::toString () const override virtual
Returns Condition's Message.
Returns
Condition's Message
Implements GT::Routines::Condition.
Definition at line 61 of file information_set_range_condition.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), informationSet, player, and strategies.
{
     ResultBuilderPtr strategiesBuilder = ResultFactory::getInstance().buildResult();
     for (Index i = 0; i < strategies->size(); i++)
         strategiesBuilder->addResult(
             createIdentifierPtr(i+1),
             createMessagePtr(strategies->at(i))
         );
     MessagePtr strategiesValue = createMessagePtr(strategiesBuilder->build()->getResult());
     MessagePtr setValue        = createMessagePtr(
         ResultFactory::getInstance()
         .buildResult()->addResult(informationSet, strategiesValue)
         .build()->getResult()
     );
     return ResultFactory::getInstance().buildResult()->addResult(player, setValue).build()->getResult();
 }
Member Data Documentation
const IdentifierPtr GT::Routines::InformationSetRangeCondition::informationSet private
Information set's name.
Definition at line 47 of file information_set_range_condition.hpp.
Referenced by configureRoutine(), and toString().
const IdentifierPtr GT::Routines::InformationSetRangeCondition::player private
Player's name.
Definition at line 43 of file information_set_range_condition.hpp.
Referenced by configureRoutine(), and toString().
const IdentifiersPtr GT::Routines::InformationSetRangeCondition::strategies private
Allowed strategies.
Definition at line 51 of file information_set_range_condition.hpp.
Referenced by configureRoutine(), and toString().
The documentation for this class was generated from the following files:
src/gt/routines/information_set_range_condition.hpp
src/gt/routines/information_set_range_condition.cpp