Game Theory Tools (full documentation): GT::GTL::NullValueDriver Class Reference
GT::GTL::NullValueDriver Class Reference final
Null ValueDriver for handling invalid situations.
#include <value_driver.hpp>
Public Member Functions
NullValueDriver ()
virtual ParamPtr * get (const InputLocation &inputLocation, const IdentifierPtr *) const override
Creates Param by its name.
virtual ParamPtr * get (const GT::GTL::InputLocation &inputLocation, const NumberPtr *) const override
Creates Param by its value.
virtual ObjectPtr * toObject (const GamePtr *game) const override
Converts passed Game to Object.
virtual ObjectPtr * toObject (const PlayerPtr *player) const override
Converts passed Player to Object.
virtual ObjectPtr * toObject (const ParamPtr *param) const override
Converts passed Param to Object.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
ValueDriver message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null ValueDriver for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 109 of file value_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::NullValueDriver::NullValueDriver () inline
Definition at line 111 of file value_driver.hpp.
                       :
         ValueDriver()
         {}
Member Function Documentation
virtual ParamPtr* GT::GTL::NullValueDriver::get (const InputLocation & inputLocation, const IdentifierPtr * identifier) const inline override virtual
Creates Param by its name.
Parameters
inputLocation input location of created Param
identifier Param's Identifier
Returns
Param
Implements GT::GTL::ValueDriver.
Definition at line 115 of file value_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ParamPtr(
             setupLocation<Param>(
                 NullFactory::getInstance().createParam(),
                 inputLocation
             )
         );
     }
virtual ParamPtr* GT::GTL::NullValueDriver::get (const GT::GTL::InputLocation & inputLocation, const NumberPtr * number) const inline override virtual
Creates Param by its value.
Parameters
inputLocation input location of created Param
number Param's value
Returns
Param
Implements GT::GTL::ValueDriver.
Definition at line 127 of file value_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ParamPtr(
             setupLocation<Param>(
                 NullFactory::getInstance().createParam(),
                 inputLocation
             )
         );
     }
virtual bool GT::GTL::NullValueDriver::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 172 of file value_driver.hpp.
{
         return false;
     }
virtual ObjectPtr* GT::GTL::NullValueDriver::toObject (const GamePtr * game) const inline override virtual
Converts passed Game to Object.
Parameters
game Game to convert
Returns
Object
Implements GT::GTL::ValueDriver.
Definition at line 139 of file value_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ObjectPtr(
             setupLocation<Object>(
                 NullFactory::getInstance().createObject(),
                 *(*game)->getInputLocation()
             )
         );
     }
virtual ObjectPtr* GT::GTL::NullValueDriver::toObject (const PlayerPtr * player) const inline override virtual
Converts passed Player to Object.
Parameters
player Player to convert
Returns
Object
Implements GT::GTL::ValueDriver.
Definition at line 150 of file value_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ObjectPtr(
             setupLocation<Object>(
                 NullFactory::getInstance().createObject(),
                 *(*player)->getInputLocation()
             )
         );
     }
virtual ObjectPtr* GT::GTL::NullValueDriver::toObject (const ParamPtr * param) const inline override virtual
Converts passed Param to Object.
Parameters
param Param to convert
Returns
Object
Implements GT::GTL::ValueDriver.
Definition at line 161 of file value_driver.hpp.
References GT::GTL::NullFactory::getInstance().
                      {
         return new ObjectPtr(
             setupLocation<Object>(
                 NullFactory::getInstance().createObject(),
                 *(*param)->getInputLocation()
             )
         );
     }
virtual Message GT::GTL::NullValueDriver::toString () const inline override virtual
ValueDriver message.
Returns
message
Implements GT::GTL::ValueDriver.
Definition at line 176 of file value_driver.hpp.
{
         return Message("NullValueDriver");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/value_driver.hpp