Game Theory Tools (full documentation): GT::GTL::ExecutionCoordinateDriver Class Reference
GT::GTL::ExecutionCoordinateDriver Class Reference final
Implementation used for handling Coordinates via ExecutionDriver.
#include <execution_coordinate_driver.hpp>
Public Member Functions
virtual CoordinatePtr * create (const InputLocation &inputLocation, const IdentifierPtr *player, const IdentifierPtr *strategy) const override
Creates coordinate.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *coordinate, const CoordinatesPtr *data) const override
Fills Coordinate with subcoordinates.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *coordinate, const ParamsPtr *data) const override
Fills Coordinate with Params.
virtual CoordinatePtr * merge (const InputLocation &inputLocation, const CoordinatePtr *coordinate1, const CoordinatePtr *coordinate2) const override
Merge two coordinates into one.
virtual Message toString () const override
ExecutionCoordinateDriver message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
CheckingCoordinateDriver checkingCoordinateDriver
Driver for error handling.
Detailed Description
Implementation used for handling Coordinates via ExecutionDriver.
Performs actual execution of instructions for Coordinates.
Author
Mateusz Kubuszok
See Also
ExecutionDriver
CoordinateDriver
Definition at line 42 of file execution_coordinate_driver.hpp.
Member Function Documentation
CoordinatePtr * GT::GTL::ExecutionCoordinateDriver::create (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifierPtr * strategy) const override virtual
Creates coordinate.
Parameters
inputLocation input location of created Coordinate
player dimension (Player)
strategy position (strategy)
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 31 of file execution_coordinate_driver.cpp.
References checkingCoordinateDriver, and GT::GTL::CheckingCoordinateDriver::create().
         {
     CoordinatePtr* errorCheck = checkingCoordinateDriver.create(inputLocation, playerPtr, strategyPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             CoordinatePtr(new Coordinate(*playerPtr, *strategyPtr)),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::ExecutionCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const CoordinatesPtr * data) const override virtual
Fills Coordinate with subcoordinates.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 49 of file execution_coordinate_driver.cpp.
References checkingCoordinateDriver, and GT::GTL::CheckingCoordinateDriver::fillWithData().
         {
     CoordinatePtr* errorCheck = checkingCoordinateDriver.fillWithData(inputLocation, coordinatePtr, dataPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     (*coordinatePtr)->addSubCoordinates(*dataPtr);
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             (*coordinatePtr),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::ExecutionCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const ParamsPtr * data) const override virtual
Fills Coordinate with Params.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 69 of file execution_coordinate_driver.cpp.
References checkingCoordinateDriver, and GT::GTL::CheckingCoordinateDriver::fillWithData().
         {
     CoordinatePtr* errorCheck = checkingCoordinateDriver.fillWithData(inputLocation, coordinatePtr, dataPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     (*coordinatePtr)->addParams(*dataPtr);
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             (*coordinatePtr),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::ExecutionCoordinateDriver::merge (const InputLocation & inputLocation, const CoordinatePtr * coordinate1, const CoordinatePtr * coordinate2) const override virtual
Merge two coordinates into one.
Parameters
inputLocation input location of created Condition
coordinate1 first Coorinate
coordinate2 second Coorinate
Returns
merged Coordinates
Implements GT::GTL::CoordinateDriver.
Definition at line 89 of file execution_coordinate_driver.cpp.
References checkingCoordinateDriver, and GT::GTL::CheckingCoordinateDriver::merge().
         {
     CoordinatePtr* errorCheck = checkingCoordinateDriver.merge(inputLocation, coordinate1Ptr, coordinate2Ptr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const Coordinate& coordinate1 = **coordinate1Ptr;
     const Coordinate& coordinate2 = **coordinate2Ptr;
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             CoordinatePtr(new Coordinate(coordinate1 + coordinate2)),
             inputLocation
         )
     );
 }
Message GT::GTL::ExecutionCoordinateDriver::toString () const override virtual
ExecutionCoordinateDriver message.
Returns
message
Implements GT::GTL::CoordinateDriver.
Definition at line 110 of file execution_coordinate_driver.cpp.
{
     return Message("ExecutionCoordinateDriver");
 }
Member Data Documentation
CheckingCoordinateDriver GT::GTL::ExecutionCoordinateDriver::checkingCoordinateDriver private
Driver for error handling.
Definition at line 46 of file execution_coordinate_driver.hpp.
Referenced by create(), fillWithData(), and merge().
The documentation for this class was generated from the following files:
src/gt/gtl/execution_coordinate_driver.hpp
src/gt/gtl/execution_coordinate_driver.cpp