Game Theory Tools (full documentation): GT::Routines::ExtensivePureEquilibriumRoutine Class Reference
GT::Routines::ExtensivePureEquilibriumRoutine Class Reference final
Routune returning pure strategy equilibrium for Extensive Game.
#include <extensive_pure_equilibrium_routine.hpp>
Public Member Functions
virtual ResultPtr findResultFor (const GamePtr game, const ConditionsPtr conditions) const override
Returns pure strategy equilibrium for Extensive Game.
virtual Message toString () const override
Returns Routine's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier, const
NumbersPtr > CalculatedPayoffs
Continas bottom-top best payoff partial results.
Private Member Functions
ExtensivePureEquilibriumRoutineConfig applyConditions (const ExtensiveDataNodePtr extensiveGameRoot, const Conditions &conditions) const
Creates RoutineConfig basing on passes Conditions.
NumbersPtr getBestPayoffWhen (const ExtensivePureEquilibriumRoutineConfig &routineConfig, const StrategicGamePositionsHelper &strategicPositionsHelper, const ExtensiveGamePositionsHelper &extensivePositionsHelper, const ExtensiveDataNode &checkedNode, ExtensivePureStrategyPath &optimalChoices) const
Returns best payoff for Player in checkedNode and adds that choice to optimalChoices.
Detailed Description
Routune returning pure strategy equilibrium for Extensive Game.
Author
Mateusz Kubuszok
See Also
Condition
Definition at line 47 of file extensive_pure_equilibrium_routine.hpp.
Member Typedef Documentation
typedef map<Identifier, const NumbersPtr> GT::Routines::ExtensivePureEquilibriumRoutine::CalculatedPayoffs private
Continas bottom-top best payoff partial results.
Definition at line 51 of file extensive_pure_equilibrium_routine.hpp.
Member Function Documentation
ExtensivePureEquilibriumRoutineConfig GT::Routines::ExtensivePureEquilibriumRoutine::applyConditions (const ExtensiveDataNodePtr extensiveGameRoot, const Conditions & conditions) const private
Creates RoutineConfig basing on passes Conditions.
Parameters
extensiveGameRoot root of a Game's tree
conditions Conditions to apply
Returns
conditioned RoutineConfig
Exceptions
InvalidCondition thrown when some Condition is invalid
Definition at line 109 of file extensive_pure_equilibrium_routine.cpp.
Referenced by findResultFor().
         {
     RoutineConfigPtr routineConfig(new ExtensivePureEquilibriumRoutineConfig(extensiveGameRoot));
     for (const ConditionPtr& condition : conditions)
         condition->configureRoutine(routineConfig);
     return *dynamic_pointer_cast<ExtensivePureEquilibriumRoutineConfig>(routineConfig);
 }
ResultPtr GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor (const GamePtr game, const ConditionsPtr conditions) const override virtual
Returns pure strategy equilibrium for Extensive Game.
Parameters
game Game definition
conditions Conditions for this Routine
Returns
Result for fiven Game and Conditions
Exceptions
InvalidCondition thrown when some Condition is invalid or when Conditions application leads to an invalid RoutineConfig or no result
InvalidGameType thrown when Game's type doesn't match Routine's one
Implements GT::Routines::Routine.
Definition at line 45 of file extensive_pure_equilibrium_routine.cpp.
References applyConditions(), GT::Model::ResultFactory::buildResult(), GT::Routines::ExceptionFactory::contradictoryConditions(), GT::createIdentifierPtr(), GT::createMessagePtr(), getBestPayoffWhen(), GT::Routines::ExceptionFactory::getInstance(), GT::Model::ResultFactory::getInstance(), GT::Routines::ExceptionFactory::invalidGameType(), GT::Routines::ExtensivePureEquilibriumRoutineConfig::isValid(), and toString().
         {
     const ExtensiveDataAccessorPtr data = dynamic_pointer_cast<ExtensiveDataAccessor>(game->getData());
     if (!data) {
         static Identifier extensiveGameName("Extensive Game");
         throw ExceptionFactory::getInstance().invalidGameType(extensiveGameName);
     }
     const ExtensivePureEquilibriumRoutineConfig routineConfig = applyConditions(data->getRoot(), *conditions);
     if (!routineConfig.isValid())
         throw ExceptionFactory::getInstance().contradictoryConditions();
     const StrategicGamePositionsHelper strategicPositionsHelper(data->getPlayers());
     const ExtensiveGamePositionsHelper extensivePositionsHelper(data->getRoot());
     const ExtensiveDataNode&           root = *data->getRoot();
     ExtensivePureStrategyPath          resultPath(game->getPlayers());
     NumbersPtr finalPayoff = getBestPayoffWhen(
         routineConfig,
         strategicPositionsHelper,
         extensivePositionsHelper,
         root,
         resultPath
     );
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     static const IdentifierPtr pureStrategiesName = createIdentifierPtr("Pure Strategies");
     ResultBuilderPtr pureStrategiesResult = ResultFactory::getInstance().buildResult();
     for (const ExtensivePureStrategyPath::PlayersChoices::value_type& playerChoices :
         resultPath.getPlayersChoices()) {
         const IdentifierPtr playerName = createIdentifierPtr(playerChoices.first);
         ResultBuilderPtr playerChoiceResult = ResultFactory::getInstance().buildResult();
         for (const Positions::value_type& position : playerChoices.second) {
             const IdentifierPtr informationSet = createIdentifierPtr(position.first);
             const MessagePtr    strategy       = createMessagePtr(position.second);
             playerChoiceResult->addResult( informationSet, strategy );
         }
         const MessagePtr decisions = createMessagePtr(playerChoiceResult->build()->getResult());
         pureStrategiesResult->addResult( playerName, decisions );
     }
     const MessagePtr pureStrategies = createMessagePtr(pureStrategiesResult->build()->getResult());
     resultBuilder->addResult( pureStrategiesName, pureStrategies );
     static const IdentifierPtr finalPayoffName = createIdentifierPtr("Payoff");
     const MessagePtr finalPayoffResult = createMessagePtr(
         PlainDataPiece(game->getPlayers(), finalPayoff).toString()
     );
     resultBuilder->addResult( finalPayoffName, finalPayoffResult );
     return resultBuilder->build();
 }
NumbersPtr GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen (const ExtensivePureEquilibriumRoutineConfig & routineConfig, const StrategicGamePositionsHelper & strategicPositionsHelper, const ExtensiveGamePositionsHelper & extensivePositionsHelper, const ExtensiveDataNode & checkedNode, ExtensivePureStrategyPath & optimalChoices) const private
Returns best payoff for Player in checkedNode and adds that choice to optimalChoices.
Parameters
routineConfig contains configureation for currently executed Routine
strategicPositionsHelper positions helper that calculates position of compared payoff
extensivePositionsHelper positions helper that calculates the information set of checkedNode
checkedNode node that should its best payoff calculated
optimalChoices contains all optimal choices of already checked decisions
Returns
value of optimal Payoff for current Player in checkedNode
Definition at line 119 of file extensive_pure_equilibrium_routine.cpp.
References GT::Routines::ExtensivePureStrategyPath::addPlayerChoice(), GT::Routines::ExceptionFactory::contradictoryConditions(), GT::createNumbersPtr(), GT::Routines::InformationSetChoiceRoutineConfig::getAvailableStrategies(), GT::Routines::ExceptionFactory::getInstance(), GT::Routines::ExceptionFactory::incompletePayoffInformation(), and GT::Routines::ExceptionFactory::playerNotFound().
Referenced by findResultFor().
         {
     NumbersPtr bestPayoff = createNumbersPtr();
     if (checkedNode.isLeaf()) {
         static const Positions emptyPositions;
         bestPayoff = checkedNode.getPayoffs(emptyPositions);
     } else {
         const Identifier& playerName = *checkedNode.getPlayer()->getName();
         if (!extensivePositionsHelper.isPlayerPossible(playerName))
             throw ExceptionFactory::getInstance().playerNotFound(playerName);
         const Identifier& informationSet =
             extensivePositionsHelper.getInformationSetsForPlayer( playerName )
             .right.at( const_cast<ExtensiveDataNode* const>(&checkedNode) );
         const Index comparedPayoffIndex = strategicPositionsHelper.calculatePlayer( playerName );
         CalculatedPayoffs calculatedPayoffs;
         for (const ExtensiveDataNodes::value_type& child : checkedNode.getChildren()) {
             const Identifier& strategy         = child.first;
             const ExtensiveDataNode& childNode = *child.second;
             const NumbersPtr& bestSubTreePayoff = getBestPayoffWhen(
                 routineConfig,
                 strategicPositionsHelper,
                 extensivePositionsHelper,
                 childNode,
                 optimalChoices
             );
             if (bestSubTreePayoff->size() <= comparedPayoffIndex)
                 throw ExceptionFactory::getInstance().incompletePayoffInformation(playerName, strategy);
             calculatedPayoffs.insert( CalculatedPayoffs::value_type(strategy, bestSubTreePayoff) );
         }
         Identifier decision          = calculatedPayoffs.begin()->first;
         NumberPtr  payoff            = calculatedPayoffs.begin()->second->at(comparedPayoffIndex);
         bool       decisionIsAllowed = false;
         const Identifiers& allowedStrategies =
             routineConfig.getAvailableStrategies(playerName, informationSet);
         for (const CalculatedPayoffs::value_type& calculatedPayoff : calculatedPayoffs) {
             const Identifier& nextDecision = calculatedPayoff.first;
             const NumberPtr&  nextPayoff   = calculatedPayoff.second->at(comparedPayoffIndex);
             if ((*nextPayoff > *payoff) || (!decisionIsAllowed && *nextPayoff == *payoff)) {
                 decision          = nextDecision;
                 payoff            = nextPayoff;
                 decisionIsAllowed = false;
             }
             if (!decisionIsAllowed && (*nextPayoff == *payoff))
                 decisionIsAllowed = allowedStrategies.end() != find_if(
                     allowedStrategies.begin(),
                     allowedStrategies.end(),
                     [decision](const IdentifierPtr& allowedDecision) {
                         return decision == *allowedDecision;
                     }
                 );
         }
         if (!decisionIsAllowed)
             throw ExceptionFactory::getInstance().contradictoryConditions();
         bestPayoff = calculatedPayoffs.at(decision);
         optimalChoices.addPlayerChoice(informationSet, playerName, decision);
     }
     return bestPayoff;
 }
Message GT::Routines::ExtensivePureEquilibriumRoutine::toString () const override virtual
Returns Routine's Message.
Returns
Routine's Message
Implements GT::Routines::Routine.
Definition at line 103 of file extensive_pure_equilibrium_routine.cpp.
Referenced by findResultFor().
{
     return Message("ExtensivePureEquilibriumRoutine");
 }
The documentation for this class was generated from the following files:
src/gt/routines/extensive_pure_equilibrium_routine.hpp
src/gt/routines/extensive_pure_equilibrium_routine.cpp