Game Theory Tools (full documentation): GT::GTL::StatementDriver Class Reference
GT::GTL::StatementDriver Class Reference abstract
Used for handling statements via Driver.
#include <statement_driver.hpp>
Public Member Functions
virtual bool executeDefinition (const DefinitionPtr *definition)=0
Executes Definition saving Object under defined name.
virtual bool executeQuery (const QueryPtr *query)=0
Executes Query saving Object under defined name.
virtual DefinitionPtr * createDefinition (const InputLocation &inputLocation, const IdentifierPtr *identifier, const ObjectPtr *object) const =0
Creates Definition saving Object under defined name.
virtual QueryPtr * createQuery (const InputLocation &inputLocation, const IdentifiersPtr *identifiers, const ObjectsPtr *objects, const ConditionsPtr *conditions) const =0
Creates Query for given properties.
virtual Message toString () const override=0
StatementDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Used for handling statements via Driver.
Author
Mateusz Kubuszok
See Also
Driver
Definition
Query
Parser
Definition at line 42 of file statement_driver.hpp.
Member Function Documentation
virtual DefinitionPtr* GT::GTL::StatementDriver::createDefinition (const InputLocation & inputLocation, const IdentifierPtr * identifier, const ObjectPtr * object) const pure virtual
Creates Definition saving Object under defined name.
Parameters
inputLocation input location of created Definition
identifier name of defined Object
object defined Object
Returns
Definition
Implemented in GT::GTL::NullStatementDriver, GT::GTL::ExecutionStatementDriver, and GT::GTL::CheckingStatementDriver.
Referenced by GT::GTL::Parser::parse().
virtual QueryPtr* GT::GTL::StatementDriver::createQuery (const InputLocation & inputLocation, const IdentifiersPtr * identifiers, const ObjectsPtr * objects, const ConditionsPtr * conditions) const pure virtual
Creates Query for given properties.
Parameters
inputLocation input location of created Definition
identifiers queried properties
objects queried Object
conditions Conditions
Returns
Query
Implemented in GT::GTL::NullStatementDriver, GT::GTL::ExecutionStatementDriver, and GT::GTL::CheckingStatementDriver.
Referenced by GT::GTL::Parser::parse().
virtual bool GT::GTL::StatementDriver::executeDefinition (const DefinitionPtr * definition) pure virtual
Executes Definition saving Object under defined name.
Parameters
definition definition to execute
Implemented in GT::GTL::NullStatementDriver, GT::GTL::ExecutionStatementDriver, and GT::GTL::CheckingStatementDriver.
Referenced by GT::GTL::Parser::parse().
virtual bool GT::GTL::StatementDriver::executeQuery (const QueryPtr * query) pure virtual
Executes Query saving Object under defined name.
Parameters
query query to execute
Implemented in GT::GTL::NullStatementDriver, GT::GTL::ExecutionStatementDriver, and GT::GTL::CheckingStatementDriver.
Referenced by GT::GTL::Parser::parse().
virtual Message GT::GTL::StatementDriver::toString () const override pure virtual
StatementDriver's Message.
Returns
Message
Implements GT::Model::Root.
Implemented in GT::GTL::NullStatementDriver, GT::GTL::ExecutionStatementDriver, and GT::GTL::CheckingStatementDriver.
The documentation for this class was generated from the following file:
include/gt/gtl/statement_driver.hpp