Game Theory Tools (full documentation): GT::GTL::Param Class Reference
GT::GTL::Param Class Reference abstract
Abstract class that defines interface for Params.
#include <param.hpp>
Public Types
typedef set< Identifier > VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Public Member Functions
Param ()
Default constructor.
virtual ResultPtr findProperty (const Context &context, const Identifier &propertyName) const override
Finds referred Objects' property and returns it as a Result.
virtual ResultPtr findPropertyWithConditions (const Context &context, const Identifier &propertyName, const Conditions &conditions) const override
Finds referred Objects' property for giver conditions and returns it as a Result.
virtual const ObjectPtr getObject (const Context &context) const
Returns Object for Context.
virtual const ObjectPtr getObject (const Context &context, VisitedIdentifiers &visitedIdentifiers) const =0
Returns Object for Context.
virtual const NumberPtr getNumber (const Context &context) const
Returns Number for context.
virtual const NumberPtr getNumber (const Context &context, VisitedIdentifiers &visitedIdentifiers) const =0
Returns Number for context.
virtual const Param & toParam () const override
Explicit cast to Param type.
Public Member Functions inherited from GT::GTL::Object
Object ()
Default constructor.
Object (const Identifier type)
Constructor initiated with Object's type.
virtual ~Object ()
Object's destructor.
virtual bool respondsTo (const Identifier &propertyName) const
Whether Object responds to some property.
virtual ResultPtr describeProperty (const Identifier &propertyName) const
Returns property's description.
virtual IdentifiersPtr listProperties () const
Returns list of available properties.
virtual const IdentifierPtr type () const
Returns type of an Object.
virtual Message toString () const override
Returns message about object.
virtual const Game & toGame () const
Explicit cast to Game type.
virtual const Player & toPlayer () const
Explicit cast to Player type.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Protected Member Functions
void checkVisitedIdentifiers (const VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Checks whether visited Identifiers contain current one.
Protected Member Functions inherited from GT::GTL::Object
bool isPropertyRegistered (const Identifier &propertyName) const
Whether property is registered or not.
const ObjectPropertyPtr getProperty (const Identifier &propertyName) const
Obtains ObjectProperty by name under which it was registered.
void registerProperty (const Identifier propertyName, const ObjectPropertyPtr property)
Registers property together with its name.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Abstract class that defines interface for Params.
Author
Mateusz Kubuszok
See Also
Context
Definition
ParamFactory
Definition at line 45 of file param.hpp.
Member Typedef Documentation
typedef set<Identifier> GT::GTL::Param::VisitedIdentifiers
Contains visited Identifiers to prevent cycles.
Definition at line 50 of file param.hpp.
Constructor & Destructor Documentation
GT::GTL::Param::Param ()
Default constructor.
Definition at line 31 of file param.cpp.
References GT::GTL::Object::registerProperty().
              :
     Object(createIdentifier("Param"))
 {
     registerProperty(Identifier("referred_properties"), ObjectPropertyPtr(new ParamKnownProperties(this)));
     registerProperty(Identifier("value"),               ObjectPropertyPtr(new ParamValueProperty(this)));
 }
Member Function Documentation
void GT::GTL::Param::checkVisitedIdentifiers (const VisitedIdentifiers & visitedIdentifiers, const Identifier & currentIdentifier) const protected
Checks whether visited Identifiers contain current one.
Parameters
visitedIdentifiers already cisited Identifiers
currentIdentifier currently visited Identifier
Exceptions
CyclicIdentifiers thrown when Identifiers create the cycle
Definition at line 89 of file param.cpp.
References GT::GTL::ExceptionFactory::cyclicIdentifiersFound(), and GT::GTL::ExceptionFactory::getInstance().
Referenced by GT::GTL::IdentifierParam::getNumber(), and GT::GTL::IdentifierParam::getObject().
         {
     for (const Identifier& visitedIdentifier : visitedIdentifiers)
         if (visitedIdentifier == currentIdentifier)
             throw ExceptionFactory::getInstance()
                 .cyclicIdentifiersFound(visitedIdentifiers, currentIdentifier);
 }
ResultPtr GT::GTL::Param::findProperty (const Context & context, const Identifier & propertyName) const override virtual
Finds referred Objects' property and returns it as a Result.
Returns Result for referred Object if there is any and it has required property.
Parameters
context Context with values
propertyName property's name
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 38 of file param.cpp.
References GT::GTL::Object::findProperty(), and getObject().
         {
     try {
         const ObjectPtr object = getObject(context);
         if (object->respondsTo(propertyName))
             return object->findProperty(context, propertyName);
     } catch (const CyclicIdentifiers&) {
     } catch (const InvalidContentRequest&) {
     } catch (const NotDefinedParam&) {}
     return Object::findProperty(context, propertyName);
 }
ResultPtr GT::GTL::Param::findPropertyWithConditions (const Context & context, const Identifier & propertyName, const Conditions & conditions) const override virtual
Finds referred Objects' property for giver conditions and returns it as a Result.
Returns Result for referred Object if there is any and it has required property.
Parameters
context Context with values
propertyName property's name
conditions Conditions to consider
Returns
Result for sought property
Exceptions
CyclicIdentifiers thrown when there is Param with cyclic references
InvalidProperty thrown when property is not available for an Object
Reimplemented from GT::GTL::Object.
Definition at line 53 of file param.cpp.
References GT::GTL::Object::findPropertyWithConditions(), and getObject().
         {
     try {
         const ObjectPtr object = getObject(context);
         if (object->respondsTo(propertyName))
             return object->findPropertyWithConditions(context, propertyName, conditions);
     } catch (const CyclicIdentifiers&) {
     } catch (const InvalidContentRequest&) {
     } catch (const NotDefinedParam&) {}
     return Object::findPropertyWithConditions(context, propertyName, conditions);
 }
const NumberPtr GT::GTL::Param::getNumber (const Context & context) const virtual
Returns Number for context.
Parameters
context Context with values
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented in GT::GTL::ErrorParam, and GT::GTL::NullParam.
Definition at line 76 of file param.cpp.
Referenced by GT::GTL::ParamValueProperty::findForConditions().
         {
     VisitedIdentifiers visitedIdentifiers;
     return getNumber(context, visitedIdentifiers);
 }
virtual const NumberPtr GT::GTL::Param::getNumber (const Context & context, VisitedIdentifiers & visitedIdentifiers) const pure virtual
Returns Number for context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Number
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Number
NotDefinedParam thrown when Param cannot find value inside Context
Implemented in GT::GTL::ErrorParam, GT::GTL::NullParam, GT::GTL::IdentifierParam, GT::GTL::NumberParam, and GT::GTL::ObjectParam.
const ObjectPtr GT::GTL::Param::getObject (const Context & context) const virtual
Returns Object for Context.
Parameters
context Context with values
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Reimplemented in GT::GTL::ErrorParam, and GT::GTL::NullParam.
Definition at line 69 of file param.cpp.
Referenced by GT::GTL::LazyGameProxy::accessGame(), GT::GTL::Query::execute(), GT::GTL::ParamKnownProperties::findForConditions(), GT::GTL::ParamValueProperty::findForConditions(), findProperty(), findPropertyWithConditions(), and GT::GTL::Condition::getIdentifier().
         {
     VisitedIdentifiers visitedIdentifiers;
     return getObject(context, visitedIdentifiers);
 }
virtual const ObjectPtr GT::GTL::Param::getObject (const Context & context, VisitedIdentifiers & visitedIdentifiers) const pure virtual
Returns Object for Context.
Parameters
context Context with values
visitedIdentifiers already visited Identifiers
Returns
Object
Exceptions
CyclicIdentifiers thrown when Identfiers create the cycle
InvalidContentRequest thrown when Param does not contain Object
NotDefinedParam thrown when Param cannot find value inside Context
Implemented in GT::GTL::ErrorParam, GT::GTL::NullParam, GT::GTL::IdentifierParam, GT::GTL::NumberParam, and GT::GTL::ObjectParam.
const Param & GT::GTL::Param::toParam () const override virtual
Explicit cast to Param type.
Returns
Param
Reimplemented from GT::GTL::Object.
Definition at line 83 of file param.cpp.
Referenced by GT::GTL::LazyGameProxy::accessGame(), GT::GTL::ParamFactory::createParam(), GT::GTL::CheckingStatementDriver::createQuery(), GT::GTL::Query::execute(), GT::GTL::Condition::getIdentifier(), GT::GTL::CheckingConditionDriver::hasIdentifier(), and GT::GTL::CheckingConditionDriver::isPlayerOrParam().
{
     return *this;
 }
The documentation for this class was generated from the following files:
include/gt/gtl/param.hpp
src/gt/gtl/param.cpp