Game Theory Tools (full documentation): GT::GTL::ExceptionFactory Class Reference
GT::GTL::ExceptionFactory Class Reference final
Used for creation of exception instances for GTL classes.
#include <exception_factory.hpp>
Public Member Functions
CyclicIdentifiers cyclicIdentifiersFound (const Param::VisitedIdentifiers &visitedIdentifiers, const Identifier &currentIdentifier) const
Thrown when Identfiers create the cycle.
InvalidProperty invalidObjectProperty (const Identifier &propertyName) const
Thrown when attepting to obtain nonexisting property from Object.
InvalidType invalidObjectType (const Identifier &expectedType) const
Thrown when attepting to obtain cast Object to invalid type.
NotDefinedParam notDefinedParam (const Identifier &paramName) const
Thrown when attepting to obtain not defined Param.
InvalidContentRequest requiredUnavailableNumberFromParam () const
Thrown when attemting to obtain Number from ObjectParam.
InvalidContentRequest requiredUnavailableObjectFromParam () const
Thrown when attemting to obtain Object from NumberParam.
Static Public Member Functions
static ExceptionFactory & getInstance ()
Returns the instance of an ExceptionFactory.
Private Member Functions
ExceptionFactory ()
Default constructor hidden from programmers.
ExceptionFactory (const ExceptionFactory &exceptionFactory)
Default copy constructor hidden from programmers.
~ExceptionFactory ()
Default destructor hidden from programmers.
Detailed Description
Used for creation of exception instances for GTL classes.
Author
Mateusz Kubuszok
Definition at line 37 of file exception_factory.hpp.
Constructor & Destructor Documentation
GT::GTL::ExceptionFactory::ExceptionFactory () private
Default constructor hidden from programmers.
Definition at line 93 of file exception_factory.cpp.
 {}
GT::GTL::ExceptionFactory::ExceptionFactory (const ExceptionFactory & exceptionFactory) private
Default copy constructor hidden from programmers.
Parameters
exceptionFactory object to copy
GT::GTL::ExceptionFactory::~ExceptionFactory () private
Default destructor hidden from programmers.
Definition at line 95 of file exception_factory.cpp.
 {}
Member Function Documentation
CyclicIdentifiers GT::GTL::ExceptionFactory::cyclicIdentifiersFound (const Param::VisitedIdentifiers & visitedIdentifiers, const Identifier & currentIdentifier) const
Thrown when Identfiers create the cycle.
Parameters
visitedIdentifiers already visited Identifiers
currentIdentifier current Identifier
Returns
CyclicIdentifiers exception to throw
Definition at line 37 of file exception_factory.cpp.
Referenced by GT::GTL::Param::checkVisitedIdentifiers().
         {
     std::stringstream result;
     result << "Cyclic Identifiers found in list:\n";
     for (const Identifier& identifier : visitedIdentifiers)
         result << "\t\'" << identifier << "\'\n";
     result << "identifier \'"
            << currentIdentifier
            << "\' already defined";
     return CyclicIdentifiers(result.str());
 }
ExceptionFactory & GT::GTL::ExceptionFactory::getInstance () static
Returns the instance of an ExceptionFactory.
Returns
ExceptionFactory instance
Definition at line 30 of file exception_factory.cpp.
Referenced by GT::GTL::LazyGameProxy::accessGame(), GT::GTL::Param::checkVisitedIdentifiers(), GT::GTL::Condition::getIdentifier(), GT::GTL::ObjectParam::getNumber(), GT::GTL::Context::getNumber(), GT::GTL::NumberParam::getObject(), GT::GTL::Context::getObject(), GT::GTL::Context::getParam(), and GT::GTL::Object::getProperty().
{
     static ExceptionFactory instance;
     return instance;
 }
InvalidProperty GT::GTL::ExceptionFactory::invalidObjectProperty (const Identifier & propertyName) const
Thrown when attepting to obtain nonexisting property from Object.
Parameters
propertyName invalid property name
Returns
InvalidProperty exception to throw
Definition at line 53 of file exception_factory.cpp.
Referenced by GT::GTL::Object::getProperty().
         {
     std::stringstream result;
     result << "Property \'" << propertyName << "\' not defined";
     return InvalidProperty(result.str());
 }
InvalidType GT::GTL::ExceptionFactory::invalidObjectType (const Identifier & expectedType) const
Thrown when attepting to obtain cast Object to invalid type.
Parameters
expectedType expected type of an Object
Returns
InvalidType exception to throw
Definition at line 63 of file exception_factory.cpp.
Referenced by GT::GTL::LazyGameProxy::accessGame(), and GT::GTL::Condition::getIdentifier().
         {
     std::stringstream result;
     result << "Object is not of type " << expectedType;
     return InvalidType(result.str());
 }
NotDefinedParam GT::GTL::ExceptionFactory::notDefinedParam (const Identifier & paramName) const
Thrown when attepting to obtain not defined Param.
Parameters
paramName invalid Param name
Returns
NotDefinedParam exception to throw
Definition at line 73 of file exception_factory.cpp.
Referenced by GT::GTL::Context::getNumber(), GT::GTL::Context::getObject(), and GT::GTL::Context::getParam().
         {
     std::stringstream result;
     result << "Param \'" << paramName << "\' not defined";
     return NotDefinedParam(result.str());
 }
InvalidContentRequest GT::GTL::ExceptionFactory::requiredUnavailableNumberFromParam () const
Thrown when attemting to obtain Number from ObjectParam.
Returns
InvalidContentRequest exception to throw
Definition at line 83 of file exception_factory.cpp.
Referenced by GT::GTL::ObjectParam::getNumber().
{
     return InvalidContentRequest("Cannot obtain Number from this Param");
 }
InvalidContentRequest GT::GTL::ExceptionFactory::requiredUnavailableObjectFromParam () const
Thrown when attemting to obtain Object from NumberParam.
Returns
InvalidContentRequest exception to throw
Definition at line 87 of file exception_factory.cpp.
Referenced by GT::GTL::NumberParam::getObject().
{
     return InvalidContentRequest("Cannot obtain Object from this Param");
 }
The documentation for this class was generated from the following files:
src/gt/gtl/exception_factory.hpp
src/gt/gtl/exception_factory.cpp