Game Theory Tools (full documentation): GT::GTL::PlayerStrategiesProperty Class Reference
GT::GTL::PlayerStrategiesProperty Class Reference final
Describes Player's strategies.
#include <player_strategies_property.hpp>
Public Member Functions
PlayerStrategiesProperty (const Player *describedPlayer)
Initiates ObjectProperty with Player it's describing.
virtual ResultPtr getDescription () const override
Returns ObjectProperty's description.
virtual ResultPtr findForConditions (const Context &context, const Conditions &conditions) const override
Finds Player's strategies.
Private Attributes
const Player * player
Described Player.
Detailed Description
Describes Player's strategies.
Author
Mateusz Kubuszok
See Also
Player
Definition at line 39 of file player_strategies_property.hpp.
Constructor & Destructor Documentation
GT::GTL::PlayerStrategiesProperty::PlayerStrategiesProperty (const Player * describedPlayer) explicit
Initiates ObjectProperty with Player it's describing.
Parameters
describedPlayer described Player
Definition at line 31 of file player_strategies_property.cpp.
   :
     player(describedPlayer)
     {}
Member Function Documentation
ResultPtr GT::GTL::PlayerStrategiesProperty::findForConditions (const Context & context, const Conditions & conditions) const override virtual
Finds Player's strategies.
Parameters
context Context with values
conditions Conditions to check
Returns
search Result
Implements GT::GTL::ObjectProperty.
Definition at line 43 of file player_strategies_property.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), GT::Model::Player::getStrategies(), and player.
         {
     static const IdentifierPtr strategiesName  = createIdentifierPtr("Strategies");
     static const IdentifierPtr name  = createIdentifierPtr("Strategy");
     ResultBuilderPtr subResultBuilder = ResultFactory::getInstance().buildResult();
     for (IdentifierPtr& strategy : *player->getStrategies()) {
         MessagePtr value = createMessagePtr(strategy);
         subResultBuilder->addResult(name, value);
     }
     MessagePtr strategiesValue = createMessagePtr(subResultBuilder->buildRaw()->getResult());
     return ResultFactory::getInstance().buildResult()->addResult(strategiesName, strategiesValue).build();
 }
ResultPtr GT::GTL::PlayerStrategiesProperty::getDescription () const override virtual
Returns ObjectProperty's description.
Returns
description
Implements GT::GTL::ObjectProperty.
Definition at line 37 of file player_strategies_property.cpp.
References GT::Model::ResultFactory::constResult(), and GT::Model::ResultFactory::getInstance().
{
     static Message description =
         "Shows strategies of a given Player";
     return ResultFactory::getInstance().constResult(description);
 }
Member Data Documentation
const Player* GT::GTL::PlayerStrategiesProperty::player private
Described Player.
Definition at line 43 of file player_strategies_property.hpp.
Referenced by findForConditions().
The documentation for this class was generated from the following files:
src/gt/gtl/player_strategies_property.hpp
src/gt/gtl/player_strategies_property.cpp