Game Theory Tools (full documentation): GT::Routines::StrategicPureEquilibriumRoutine Class Reference
GT::Routines::StrategicPureEquilibriumRoutine Class Reference final
Routune returning pure strategy equilibrium for Strategic Game.
#include <strategic_pure_equilibrium_routine.hpp>
Public Member Functions
virtual ResultPtr findResultFor (const GamePtr game, const ConditionsPtr conditions) const override
Returns pure strategy equilibrium for Strategic Game.
virtual Message toString () const override
Returns Routine's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
StrategicPureEquilibriumRoutineConfig applyConditions (const PlayersPtr players, const Conditions &conditions) const
Creates RoutineConfig basing on passes Conditions.
bool arePositionsAllowed (const StrategicPureEquilibriumRoutineConfig &routineConfig, const Positions &positions) const
Whether or not Positions are allowed to be used by configuration.
bool isNashEquilibrium (const StrategicDataAccessor &data, const Positions &positions) const
Whether or not passed Position points to a Nash equilibrium.
Detailed Description
Routune returning pure strategy equilibrium for Strategic Game.
Author
Mateusz Kubuszok
See Also
Condition
Definition at line 45 of file strategic_pure_equilibrium_routine.hpp.
Member Function Documentation
StrategicPureEquilibriumRoutineConfig GT::Routines::StrategicPureEquilibriumRoutine::applyConditions (const PlayersPtr players, const Conditions & conditions) const private
Creates RoutineConfig basing on passes Conditions.
Parameters
players Players definitions
conditions Conditions to apply
Returns
conditioned RoutineConfig
Exceptions
InvalidCondition thrown when some Condition is invalid
Definition at line 100 of file strategic_pure_equilibrium_routine.cpp.
Referenced by findResultFor().
         {
     RoutineConfigPtr routineConfig(new StrategicPureEquilibriumRoutineConfig(players));
     for (const ConditionPtr& condition : conditions)
         condition->configureRoutine(routineConfig);
     return *dynamic_pointer_cast<StrategicPureEquilibriumRoutineConfig>(routineConfig);
 }
bool GT::Routines::StrategicPureEquilibriumRoutine::arePositionsAllowed (const StrategicPureEquilibriumRoutineConfig & routineConfig, const Positions & positions) const private
Whether or not Positions are allowed to be used by configuration.
Parameters
routineConfig contains configureation for currently executed Routine
positions Positions to check
Returns
true if Positions are allowed to be used
Definition at line 110 of file strategic_pure_equilibrium_routine.cpp.
References GT::Routines::PlayerChoiceRoutineConfig::getAvailableStrategies().
Referenced by findResultFor().
         {
     for (const Positions::value_type& positionPair : currentPositions) {
         const Identifier& playerName = positionPair.first;
         const Identifier& strategy   = positionPair.second;
         const Identifiers& allowedForPlayer = routineConfig.getAvailableStrategies(playerName);
         bool isAllowed = allowedForPlayer.end() != find_if(
             allowedForPlayer.begin(),
             allowedForPlayer.end(),
             [strategy](const IdentifierPtr& checkedStrategy) {
                 return strategy == *checkedStrategy;
             }
         );
         if (!isAllowed)
             return false;
     }
     return true;
 }
ResultPtr GT::Routines::StrategicPureEquilibriumRoutine::findResultFor (const GamePtr game, const ConditionsPtr conditions) const override virtual
Returns pure strategy equilibrium for Strategic Game.
Parameters
game Game definition
conditions Conditions for this Routine
Returns
Result for fiven Game and Conditions
Exceptions
InvalidCondition thrown when some Condition is invalid or when Conditions application leads to an invalid RoutineConfig or no result
InvalidGameType thrown when Game's type doesn't match Routine's one
Implements GT::Routines::Routine.
Definition at line 43 of file strategic_pure_equilibrium_routine.cpp.
References applyConditions(), arePositionsAllowed(), GT::Model::ResultFactory::buildResult(), GT::Model::ResultFactory::constResult(), GT::Routines::ExceptionFactory::contradictoryConditions(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Routines::ExceptionFactory::getInstance(), GT::Model::ResultFactory::getInstance(), GT::Routines::ExceptionFactory::invalidGameType(), isNashEquilibrium(), and GT::Routines::StrategicPureEquilibriumRoutineConfig::isValid().
         {
     const StrategicDataAccessorPtr data = dynamic_pointer_cast<StrategicDataAccessor>(game->getData());
     if (!data) {
         static Identifier extensiveGameName("Strategic Game");
         throw ExceptionFactory::getInstance().invalidGameType(extensiveGameName);
     }
     const StrategicPureEquilibriumRoutineConfig routineConfig =
         applyConditions(data->getPlayers(), *conditions);
     if (!routineConfig.isValid())
         throw ExceptionFactory::getInstance().contradictoryConditions();
     const StrategicGamePositionsHelper positionsHelper(data->getPlayers());
     Index upperBound = positionsHelper.getUpperBound();
     for (Index index = 0; index < upperBound; index++) {
         const PositionsPtr positions = positionsHelper.retrievePositions(index);
         if (!arePositionsAllowed(routineConfig, *positions))
             continue;
         if (isNashEquilibrium(*data, *positions)) {
             ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
             static const IdentifierPtr pureStrategiesName = createIdentifierPtr("Pure Strategies");
             ResultBuilderPtr pureStrategiesResult = ResultFactory::getInstance().buildResult();
             for (const Positions::value_type& position : *positions) {
                 const IdentifierPtr& playerName = createIdentifierPtr(position.first);
                 const MessagePtr&    strategy   = createMessagePtr(position.second);
                 pureStrategiesResult->addResult( playerName, strategy );
             }
             const MessagePtr pureStrategies = createMessagePtr(pureStrategiesResult->build()->getResult());
             resultBuilder->addResult( pureStrategiesName, pureStrategies );
             static const IdentifierPtr finalPayoffName = createIdentifierPtr("Payoff");
             const MessagePtr finalPayoffResult = createMessagePtr(
                 data->getPayoffs(*positions)->toString()
             );
             resultBuilder->addResult( finalPayoffName, finalPayoffResult );
             return resultBuilder->build();
         }
     }
     // TODO: create MessageFactory
     return ResultFactory::getInstance().constResult(Message("No Nash equilibrium found"));
 }
bool GT::Routines::StrategicPureEquilibriumRoutine::isNashEquilibrium (const StrategicDataAccessor & data, const Positions & positions) const private
Whether or not passed Position points to a Nash equilibrium.
Parameters
data data with payoffs
positions Positions to check
Returns
true if Position point to Nash equilibrium
Definition at line 134 of file strategic_pure_equilibrium_routine.cpp.
Referenced by findResultFor().
         {
     const DataPiecePtr& currentPayoffs = data.getPayoffs(currentPositions);
     for (const Players::value_type& playerPair : *data.getPlayers()) {
         const Identifier&  playerName      = playerPair.first;
         const Identifiers& strategies      = *playerPair.second->getStrategies();
         const Identifier&  currentStrategy = currentPositions.at(playerName);
         const NumberPtr&   currentPayoff   = currentPayoffs->getPayoff(playerName);
         for (const IdentifierPtr& strategyPtr : strategies) {
             const Identifier& strategy = *strategyPtr;
             if (strategy != currentStrategy) {
                 Positions checkedPosition(currentPositions);
                 checkedPosition[playerName] = strategy;
                 const DataPiecePtr& checkedPayoffs = data.getPayoffs(checkedPosition);
                 if (*currentPayoff < *checkedPayoffs->getPayoff(playerName))
                     return false;
             }
         }
     }
     return true;
 }
Message GT::Routines::StrategicPureEquilibriumRoutine::toString () const override virtual
Returns Routine's Message.
Returns
Routine's Message
Implements GT::Routines::Routine.
Definition at line 94 of file strategic_pure_equilibrium_routine.cpp.
{
     return Message("StrategicPureEquilibriumRoutine");
 }
The documentation for this class was generated from the following files:
src/gt/routines/strategic_pure_equilibrium_routine.hpp
src/gt/routines/strategic_pure_equilibrium_routine.cpp