Game Theory Tools (full documentation): GT::GTL::CheckingDriver Class Reference
GT::GTL::CheckingDriver Class Reference final
Implementation used for executing only checking actions.
#include <checking_driver.hpp>
Public Member Functions
CheckingDriver (OutputStream *errorStream)
Initiates CheckingDriver with a output stream.
virtual ~CheckingDriver ()
Destructor.
virtual CoordinateDriver & forCoordinate () const override
Driver for Coordinate.
virtual CollectionsDriver
< Coordinate > & forCoordinates () const override
Driver for Coordinates.
virtual ConditionDriver & forCondition () const override
Driver for Condition.
virtual CollectionsDriver
< Condition > & forConditions () const override
Driver for Conditions.
virtual GameDriver & forGame () const override
Driver for Game.
virtual CollectionsDriver
< Identifier > & forIdentifiers () const override
Driver for Identifiers.
virtual CollectionsDriver
< Object > & forObjects () const override
Driver for Objects.
virtual CollectionsDriver
< Param > & forParams () const override
Driver for Params.
virtual ValueDriver & forValue () const override
Driver for value.
virtual StatementDriver & forStatement () const override
Driver for Statement.
virtual void showResult (const ResultPtr result) const override
Displays results.
virtual void showError (const InputLocation &location, const Message &message) const override
Displays error.
virtual void showError (const ValidableSymbol &symbol) const override
Displays error.
virtual void execute (const InputLocation &location, const Identifier &fileName) const override
Executes file.
virtual void load (const InputLocation &location, const Identifier &fileName) override
Loads file.
virtual void save (const InputLocation &location, const Identifier &fileName) const override
Saves all Params available in current Context (and it's parents) to file.
virtual Message toString () const override
Driver's Message.
Public Member Functions inherited from GT::GTL::Driver
virtual ~Driver ()
Default destructor.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
bool fileExists (const Identifier &fileName) const
Checks if file exists.
Private Attributes
CheckingCoordinateDriver coordinate
Driver for Coordinates.
CollectionsDriver
< GT::GTL::Coordinate > coordinates
Driver for Coordinates' collections.
CheckingConditionDriver condition
Driver for Conditions.
CollectionsDriver
< GT::GTL::Condition > conditions
Driver for Conditions' collections.
CheckingGameDriver game
Driver for Games.
CollectionsDriver< GT::Identifier > identifiers
Driver for Identifiers' collections.
CollectionsDriver
< GT::GTL::Object > objects
Driver for Objects' collections.
CollectionsDriver< GT::GTL::Param > params
Driver for Params' collections.
CheckingValueDriver value
Driver for values.
CheckingStatementDriver statement
Driver for statements.
OutputStream * errorStream
Error stream for displaying informations about errors.
Detailed Description
Implementation used for executing only checking actions.
Performs only syntax/type checking on input stream.
Author
Mateusz Kubuszok
See Also
Driver
Definition at line 41 of file checking_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::CheckingDriver::CheckingDriver (OutputStream * errorStream) explicit
Initiates CheckingDriver with a output stream.
Parameters
errorStream error stream
Definition at line 38 of file checking_driver.cpp.
   :
     coordinate(),
     condition(),
     game(),
     value(),
     statement(this),
     errorStream(newErrorStream)
     {}
GT::GTL::CheckingDriver::~CheckingDriver () virtual
Destructor.
Definition at line 49 of file checking_driver.cpp.
 {}
Member Function Documentation
void GT::GTL::CheckingDriver::execute (const InputLocation & location, const Identifier & fileName) const override virtual
Executes file.
It uses currently used output and error stream to display result but read input from file.
Operations are perfored on spawned Context so after all operations parental Context is instact.
Parameters
location location of file load call
fileName name of executed file
See Also
load(const InputLocation&, const Identifier&)
Implements GT::GTL::Driver.
Definition at line 122 of file checking_driver.cpp.
References fileExists(), and showError().
         {
     if (!fileExists(fileName)) {
         stringstream builder;
         builder << "Executed file <" << fileName << "> does not exists";
         string errorMessage(builder.str());
         showError(location, errorMessage);
     }
 }
bool GT::GTL::CheckingDriver::fileExists (const Identifier & fileName) const private
Checks if file exists.
Parameters
fileName name of checked file
Returns
true if file exists
Definition at line 159 of file checking_driver.cpp.
Referenced by execute(), and load().
         {
     ifstream f(fileName);
     return f.good();
 }
ConditionDriver & GT::GTL::CheckingDriver::forCondition () const override virtual
Driver for Condition.
Returns
ConditionDriver
Implements GT::GTL::Driver.
Definition at line 59 of file checking_driver.cpp.
References condition.
{
     return condition;
 }
CollectionsDriver< Condition > & GT::GTL::CheckingDriver::forConditions () const override virtual
Driver for Conditions.
Returns
CollectionDriver for Conditions
Implements GT::GTL::Driver.
Definition at line 63 of file checking_driver.cpp.
References conditions.
{
     return conditions;
 }
CoordinateDriver & GT::GTL::CheckingDriver::forCoordinate () const override virtual
Driver for Coordinate.
Returns
CoordinateDriver
Implements GT::GTL::Driver.
Definition at line 51 of file checking_driver.cpp.
References coordinate.
{
     return coordinate;
 }
CollectionsDriver< Coordinate > & GT::GTL::CheckingDriver::forCoordinates () const override virtual
Driver for Coordinates.
Returns
CollectionDriver for Coordinates
Implements GT::GTL::Driver.
Definition at line 55 of file checking_driver.cpp.
References coordinates.
{
     return coordinates;
 }
GameDriver & GT::GTL::CheckingDriver::forGame () const override virtual
Driver for Game.
Returns
GameDriver
Implements GT::GTL::Driver.
Definition at line 67 of file checking_driver.cpp.
References game.
{
     return game;
 }
CollectionsDriver< Identifier > & GT::GTL::CheckingDriver::forIdentifiers () const override virtual
Driver for Identifiers.
Returns
CollectionDriver for Identifiers
Implements GT::GTL::Driver.
Definition at line 71 of file checking_driver.cpp.
References identifiers.
{
     return identifiers;
 }
CollectionsDriver< Object > & GT::GTL::CheckingDriver::forObjects () const override virtual
Driver for Objects.
Returns
CollectionDriver for Objects
Implements GT::GTL::Driver.
Definition at line 75 of file checking_driver.cpp.
References objects.
{
     return objects;
 }
CollectionsDriver< Param > & GT::GTL::CheckingDriver::forParams () const override virtual
Driver for Params.
Returns
CollectionDriver for Params
Implements GT::GTL::Driver.
Definition at line 79 of file checking_driver.cpp.
References params.
{
     return params;
 }
StatementDriver & GT::GTL::CheckingDriver::forStatement () const override virtual
Driver for Statement.
Returns
StatementDriver
Implements GT::GTL::Driver.
Definition at line 87 of file checking_driver.cpp.
References statement.
{
     return statement;
 }
ValueDriver & GT::GTL::CheckingDriver::forValue () const override virtual
Driver for value.
Returns
ValueDriver
Implements GT::GTL::Driver.
Definition at line 83 of file checking_driver.cpp.
References value.
{
     return value;
 }
void GT::GTL::CheckingDriver::load (const InputLocation & location, const Identifier & fileName) override virtual
Loads file.
It uses currently used output and error stream to display result but read input from file.
Operations are performed in current Context so all changes will be persisted.
Parameters
location location of file load call
fileName name of loaded file
See Also
execute(const InputLocation&, const Identifier&)const
Implements GT::GTL::Driver.
Definition at line 135 of file checking_driver.cpp.
References fileExists(), and showError().
   {
     if (!fileExists(fileName)) {
         stringstream builder;
         builder << "Loaded file <" << fileName << "> does not exists";
         string errorMessage(builder.str());
         showError(location, errorMessage);
     }
 }
void GT::GTL::CheckingDriver::save (const InputLocation & location, const Identifier & fileName) const override virtual
Saves all Params available in current Context (and it's parents) to file.
Parameters
location location of file load call
fileName name of saved file
Implements GT::GTL::Driver.
Definition at line 148 of file checking_driver.cpp.
         {}
void GT::GTL::CheckingDriver::showError (const InputLocation & location, const Message & message) const override virtual
Displays error.
Parameters
location error's location
message Message to display
Implements GT::GTL::Driver.
Definition at line 95 of file checking_driver.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), errorStream, and GT::Model::ResultFactory::getInstance().
Referenced by execute(), load(), showError(), and GT::GTL::ExecutionDriver::showError().
         {
     if (errorStream) {
         stringstream builder;
         builder << message << endl
                 << "\tfrom line " << location.begin.line << " (column " << location.begin.column << ')'
                 << endl
                 << "\tto line " << location.end.line << " (column " << location.end.column << ')'
                 << endl;
         string errorMessage(builder.str());
         static const IdentifierPtr name   = createIdentifierPtr("Error");
         const MessagePtr           result = createMessagePtr(builder.str());
         (*errorStream)
             << ResultFactory::getInstance().buildResult()->addResult(name, result).build()->getResult();
     }
 }
void GT::GTL::CheckingDriver::showError (const ValidableSymbol & symbol) const override virtual
Displays error.
Parameters
symbol invalid symbol to display
Implements GT::GTL::Driver.
Definition at line 116 of file checking_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), showError(), and GT::Model::Root::toString().
         {
     showError(*symbol.getInputLocation(), symbol.toString());
 }
void GT::GTL::CheckingDriver::showResult (const ResultPtr result) const override virtual
Displays results.
Parameters
result Result to show
Implements GT::GTL::Driver.
Definition at line 91 of file checking_driver.cpp.
         {}
Message GT::GTL::CheckingDriver::toString () const override virtual
Driver's Message.
Returns
message
Implements GT::GTL::Driver.
Definition at line 153 of file checking_driver.cpp.
{
     return Message("CheckingDriver");
 }
Member Data Documentation
CheckingConditionDriver GT::GTL::CheckingDriver::condition mutable private
Driver for Conditions.
Definition at line 53 of file checking_driver.hpp.
Referenced by forCondition().
CollectionsDriver<GT::GTL::Condition> GT::GTL::CheckingDriver::conditions mutable private
Driver for Conditions' collections.
Definition at line 57 of file checking_driver.hpp.
Referenced by forConditions().
CheckingCoordinateDriver GT::GTL::CheckingDriver::coordinate mutable private
Driver for Coordinates.
Definition at line 45 of file checking_driver.hpp.
Referenced by forCoordinate().
CollectionsDriver<GT::GTL::Coordinate> GT::GTL::CheckingDriver::coordinates mutable private
Driver for Coordinates' collections.
Definition at line 49 of file checking_driver.hpp.
Referenced by forCoordinates().
OutputStream* GT::GTL::CheckingDriver::errorStream mutable private
Error stream for displaying informations about errors.
Definition at line 86 of file checking_driver.hpp.
Referenced by showError().
CheckingGameDriver GT::GTL::CheckingDriver::game mutable private
Driver for Games.
Definition at line 61 of file checking_driver.hpp.
Referenced by forGame().
CollectionsDriver<GT::Identifier> GT::GTL::CheckingDriver::identifiers mutable private
Driver for Identifiers' collections.
Definition at line 65 of file checking_driver.hpp.
Referenced by forIdentifiers().
CollectionsDriver<GT::GTL::Object> GT::GTL::CheckingDriver::objects mutable private
Driver for Objects' collections.
Definition at line 69 of file checking_driver.hpp.
Referenced by forObjects().
CollectionsDriver<GT::GTL::Param> GT::GTL::CheckingDriver::params mutable private
Driver for Params' collections.
Definition at line 73 of file checking_driver.hpp.
Referenced by forParams().
CheckingStatementDriver GT::GTL::CheckingDriver::statement mutable private
Driver for statements.
Definition at line 81 of file checking_driver.hpp.
Referenced by forStatement().
CheckingValueDriver GT::GTL::CheckingDriver::value mutable private
Driver for values.
Definition at line 77 of file checking_driver.hpp.
Referenced by forValue().
The documentation for this class was generated from the following files:
src/gt/gtl/checking_driver.hpp
src/gt/gtl/checking_driver.cpp