Game Theory Tools (full documentation): GT::GTL::Driver Class Reference
GT::GTL::Driver Class Reference abstract
Used for executing actions called by Parser.
#include <driver.hpp>
Public Member Functions
virtual ~Driver ()
Default destructor.
virtual CoordinateDriver & forCoordinate () const =0
Driver for Coordinate.
virtual CollectionsDriver
< Coordinate > & forCoordinates () const =0
Driver for Coordinates.
virtual ConditionDriver & forCondition () const =0
Driver for Condition.
virtual CollectionsDriver
< Condition > & forConditions () const =0
Driver for Conditions.
virtual GameDriver & forGame () const =0
Driver for Game.
virtual CollectionsDriver
< Identifier > & forIdentifiers () const =0
Driver for Identifiers.
virtual CollectionsDriver
< Object > & forObjects () const =0
Driver for Objects.
virtual CollectionsDriver
< Param > & forParams () const =0
Driver for Params.
virtual ValueDriver & forValue () const =0
Driver for value.
virtual StatementDriver & forStatement () const =0
Driver for Statement.
virtual void showResult (const ResultPtr result) const =0
Displays results.
virtual void showError (const InputLocation &location, const Message &message) const =0
Displays error.
virtual void showError (const ValidableSymbol &symbol) const =0
Displays error.
virtual void execute (const InputLocation &location, const Identifier &fileName) const =0
Executes file.
virtual void load (const InputLocation &location, const Identifier &fileName)=0
Loads file.
virtual void save (const InputLocation &location, const Identifier &fileName) const =0
Saves all Params available in current Context (and it's parents) to file.
virtual Message toString () const override=0
Driver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Used for executing actions called by Parser.
Author
Mateusz Kubuszok
Definition at line 37 of file driver.hpp.
Constructor & Destructor Documentation
virtual GT::GTL::Driver::~Driver () inline virtual
Default destructor.
Definition at line 42 of file driver.hpp.
 {}
Member Function Documentation
virtual void GT::GTL::Driver::execute (const InputLocation & location, const Identifier & fileName) const pure virtual
Executes file.
It uses currently used output and error stream to display result but read input from file.
Operations are perfored on spawned Context so after all operations parental Context is instact.
Parameters
location location of file load call
fileName name of executed file
See Also
load(const InputLocation&, const Identifier&)
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual ConditionDriver& GT::GTL::Driver::forCondition () const pure virtual
Driver for Condition.
Returns
ConditionDriver
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CollectionsDriver<Condition>& GT::GTL::Driver::forConditions () const pure virtual
Driver for Conditions.
Returns
CollectionDriver for Conditions
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CoordinateDriver& GT::GTL::Driver::forCoordinate () const pure virtual
Driver for Coordinate.
Returns
CoordinateDriver
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CollectionsDriver<Coordinate>& GT::GTL::Driver::forCoordinates () const pure virtual
Driver for Coordinates.
Returns
CollectionDriver for Coordinates
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual GameDriver& GT::GTL::Driver::forGame () const pure virtual
Driver for Game.
Returns
GameDriver
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CollectionsDriver<Identifier>& GT::GTL::Driver::forIdentifiers () const pure virtual
Driver for Identifiers.
Returns
CollectionDriver for Identifiers
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CollectionsDriver<Object>& GT::GTL::Driver::forObjects () const pure virtual
Driver for Objects.
Returns
CollectionDriver for Objects
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual CollectionsDriver<Param>& GT::GTL::Driver::forParams () const pure virtual
Driver for Params.
Returns
CollectionDriver for Params
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual StatementDriver& GT::GTL::Driver::forStatement () const pure virtual
Driver for Statement.
Returns
StatementDriver
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual ValueDriver& GT::GTL::Driver::forValue () const pure virtual
Driver for value.
Returns
ValueDriver
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual void GT::GTL::Driver::load (const InputLocation & location, const Identifier & fileName) pure virtual
Loads file.
It uses currently used output and error stream to display result but read input from file.
Operations are performed in current Context so all changes will be persisted.
Parameters
location location of file load call
fileName name of loaded file
See Also
execute(const InputLocation&, const Identifier&)const
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual void GT::GTL::Driver::save (const InputLocation & location, const Identifier & fileName) const pure virtual
Saves all Params available in current Context (and it's parents) to file.
Parameters
location location of file load call
fileName name of saved file
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual void GT::GTL::Driver::showError (const InputLocation & location, const Message & message) const pure virtual
Displays error.
Parameters
location error's location
message Message to display
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
Referenced by GT::GTL::CheckingStatementDriver::executeDefinition(), GT::GTL::CheckingStatementDriver::executeQuery(), and GT::GTL::ExecutionStatementDriver::executeQuery().
virtual void GT::GTL::Driver::showError (const ValidableSymbol & symbol) const pure virtual
Displays error.
Parameters
symbol invalid symbol to display
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
virtual void GT::GTL::Driver::showResult (const ResultPtr result) const pure virtual
Displays results.
Parameters
result Result to show
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
Referenced by GT::GTL::ExecutionStatementDriver::executeDefinition(), and GT::GTL::ExecutionStatementDriver::executeQuery().
virtual Message GT::GTL::Driver::toString () const override pure virtual
Driver's Message.
Returns
message
Implements GT::Model::Root.
Implemented in GT::GTL::NullDriver, GT::GTL::ExecutionDriver, and GT::GTL::CheckingDriver.
The documentation for this class was generated from the following file:
include/gt/gtl/driver.hpp