Game Theory Tools (full documentation): GT::Model::NullDataAccessor Class Reference
GT::Model::NullDataAccessor Class Reference final
Null DataAccessor for handling invalid situations.
#include <data_accessor.hpp>
Public Member Functions
virtual const PlayersPtr getPlayers () const override
Returns map of Players available in this DataAccessor.
virtual const DataPiecePtr getPayoffs (const Positions &) const override
Returns values handler for given coordiantes.
virtual const DataPiecePtr getPayoffs (const PositionsPtr) const override
Returns values handler for given coordiantes.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Data's message.
virtual const DataPiecePtr operator[] (const Positions &) const override
Overrides operator [] allowing easy access to values via DataPiece interface.
virtual const DataPiecePtr operator[] (const PositionsPtr) const override
Overrides operator [] allowing easy access to values via DataPiece interface.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null DataAccessor for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 112 of file data_accessor.hpp.
Member Function Documentation
virtual const DataPiecePtr GT::Model::NullDataAccessor::getPayoffs (const Positions & positions) const inline override virtual
Returns values handler for given coordiantes.
Parameters
positions coordinates in a Game
Returns
values of payoff
Exceptions
InvalidCoordinate thrown when coordinates are invalid
Implements GT::Model::DataAccessor.
Definition at line 118 of file data_accessor.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullDataAccessor::getPayoffs (const PositionsPtr positions) const inline override virtual
Returns values handler for given coordiantes.
Parameters
positions coordinates in a Game
Returns
values of payoff
Exceptions
InvalidCoordinate thrown when coordinates are invalid
Implements GT::Model::DataAccessor.
Definition at line 124 of file data_accessor.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const PlayersPtr GT::Model::NullDataAccessor::getPlayers () const inline override virtual
Returns map of Players available in this DataAccessor.
Returns
Players
Implements GT::Model::DataAccessor.
Definition at line 114 of file data_accessor.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual bool GT::Model::NullDataAccessor::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 130 of file data_accessor.hpp.
{
         return false;
     }
virtual const DataPiecePtr GT::Model::NullDataAccessor::operator[] (const Positions & positions) const inline override virtual
Overrides operator [] allowing easy access to values via DataPiece interface.
Parameters
positions coordinates
Returns
DataPiece object allowing access to concrete value
Exceptions
InvalidCoordinates thrown when positions coordinates are invalid
Implements GT::Model::DataAccessor.
Definition at line 138 of file data_accessor.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullDataAccessor::operator[] (const PositionsPtr positions) const inline override virtual
Overrides operator [] allowing easy access to values via DataPiece interface.
Parameters
positions coordinates
Returns
DataPiece object allowing access to concrete value
Exceptions
InvalidCoordinates thrown when positions coordinates are invalid
Implements GT::Model::DataAccessor.
Definition at line 144 of file data_accessor.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual Message GT::Model::NullDataAccessor::toString () const inline override virtual
Returns Data's message.
Returns
Message
Implements GT::Model::DataAccessor.
Definition at line 134 of file data_accessor.hpp.
{
         return Message("NullData");
     }
The documentation for this class was generated from the following file:
include/gt/model/data_accessor.hpp