Game Theory Tools (full documentation): GT::GTL::GameMixedEquilibriumProperty Class Reference
GT::GTL::GameMixedEquilibriumProperty Class Reference final
Describes mixed-strategy equilibria of Games.
#include <game_mixed_equilibrium_property.hpp>
Public Member Functions
GameMixedEquilibriumProperty (const Game *describedGame)
Initiates ObjectProperty with Game it's describing.
virtual ResultPtr getDescription () const override
Returns ObjectProperty's description.
virtual ResultPtr findForConditions (const Context &context, const Conditions &conditions) const override
Finds equilibrium for given Conditions.
Private Attributes
const Game * game
Described Game.
Detailed Description
Describes mixed-strategy equilibria of Games.
Author
Mateusz Kubuszok
See Also
Game
Definition at line 39 of file game_mixed_equilibrium_property.hpp.
Constructor & Destructor Documentation
GT::GTL::GameMixedEquilibriumProperty::GameMixedEquilibriumProperty (const Game * describedGame) explicit
Initiates ObjectProperty with Game it's describing.
Parameters
describedGame described Game
Definition at line 31 of file game_mixed_equilibrium_property.cpp.
   :
     game(describedGame)
     {}
Member Function Documentation
ResultPtr GT::GTL::GameMixedEquilibriumProperty::findForConditions (const Context & context, const Conditions & conditions) const override virtual
Finds equilibrium for given Conditions.
Parameters
context Context with values
conditions Conditions to check
Returns
search Result
Implements GT::GTL::ObjectProperty.
Definition at line 43 of file game_mixed_equilibrium_property.cpp.
References game, and GT::GTL::Game::mixedEquilibrium().
         {
     return game->mixedEquilibrium(context, conditions);
 }
ResultPtr GT::GTL::GameMixedEquilibriumProperty::getDescription () const override virtual
Returns ObjectProperty's description.
Returns
description
Implements GT::GTL::ObjectProperty.
Definition at line 37 of file game_mixed_equilibrium_property.cpp.
References GT::Model::ResultFactory::constResult(), and GT::Model::ResultFactory::getInstance().
{
     static Message description =
         "Finds mixed strategies' Nash equilibrium";
     return ResultFactory::getInstance().constResult(description);
 }
Member Data Documentation
const Game* GT::GTL::GameMixedEquilibriumProperty::game private
Described Game.
Definition at line 43 of file game_mixed_equilibrium_property.hpp.
Referenced by findForConditions().
The documentation for this class was generated from the following files:
src/gt/gtl/game_mixed_equilibrium_property.hpp
src/gt/gtl/game_mixed_equilibrium_property.cpp