Game Theory Tools (full documentation): GT::GTL::CheckingStatementDriver Class Reference
GT::GTL::CheckingStatementDriver Class Reference final
Implementation used for handling statements via CheckingDriver.
#include <checking_statement_driver.hpp>
Public Member Functions
CheckingStatementDriver (Driver *parentDriver)
Initiates CheckingStatementDriver with its parent.
virtual bool executeDefinition (const DefinitionPtr *definition) override
Executes Definition saving Object under defined name.
virtual bool executeQuery (const QueryPtr *query) override
Executes Query saving Object under defined name.
virtual DefinitionPtr * createDefinition (const InputLocation &inputLocation, const IdentifierPtr *identifier, const ObjectPtr *object) const override
Creates Definition saving Object under defined name.
virtual QueryPtr * createQuery (const InputLocation &inputLocation, const IdentifiersPtr *identifiers, const ObjectsPtr *objects, const ConditionsPtr *conditions) const override
Creates Query for given properties.
virtual Message toString () const override
CheckingStatementDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
Driver * driver
Implementation of a main Driver.
Detailed Description
Implementation used for handling statements via CheckingDriver.
Performs only syntax/type checking on statements' tokens.
Author
Mateusz Kubuszok
See Also
CheckingDriver
StatementDriver
Definition at line 42 of file checking_statement_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::CheckingStatementDriver::CheckingStatementDriver (Driver * parentDriver) explicit
Initiates CheckingStatementDriver with its parent.
Parameters
parentDriver parent Driver
Definition at line 31 of file checking_statement_driver.cpp.
   :
     driver(parentDriver)
     {}
Member Function Documentation
DefinitionPtr * GT::GTL::CheckingStatementDriver::createDefinition (const InputLocation & inputLocation, const IdentifierPtr * identifier, const ObjectPtr * object) const override virtual
Creates Definition saving Object under defined name.
Parameters
inputLocation input location of created Definition
identifier name of defined Object
object defined Object
Returns
Definition
Implements GT::GTL::StatementDriver.
Definition at line 55 of file checking_statement_driver.cpp.
References GT::GTL::ErrorFactory::getInstance(), and GT::GTL::NullFactory::getInstance().
Referenced by GT::GTL::ExecutionStatementDriver::createDefinition().
         {
     const Identifier& identifier = **identifierPtr;
     const Object&     object     = **objectPtr;
     if (!object) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Count not define parameter '" + identifier + "': " + object.toString();
         return new DefinitionPtr(
             setupLocation<Definition>(
                 ErrorFactory::getInstance().createDefinition(errorMessage),
                 *object.getInputLocation()
             )
         );
     }
     return new DefinitionPtr(
         setupLocation<Definition>(
             NullFactory::getInstance().createDefinition(),
             inputLocation
         )
     );
 }
QueryPtr * GT::GTL::CheckingStatementDriver::createQuery (const InputLocation & inputLocation, const IdentifiersPtr * identifiers, const ObjectsPtr * objects, const ConditionsPtr * conditions) const override virtual
Creates Query for given properties.
Parameters
inputLocation input location of created Definition
identifiers queried properties
objects queried Object
conditions Conditions
Returns
Query
Implements GT::GTL::StatementDriver.
Definition at line 83 of file checking_statement_driver.cpp.
References createQuery(), GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::NullFactory::getInstance(), GT::GTL::Condition::toString(), and toString().
Referenced by createQuery(), and GT::GTL::ExecutionStatementDriver::createQuery().
         {
     const Identifiers& identifiers = **identifiersPtr;
     const Objects&     objects     = **objectsPtr;
     const Conditions&  conditions  = **conditionsPtr;
     for (const ObjectPtr& objectPtr : objects) {
         const Object& object = *objectPtr;
         if (!object)
             return new QueryPtr(
                 setupLocation<Query>(
                     ErrorFactory::getInstance().createQuery(object.toString()),
                     *object.getInputLocation()
                 )
             );
         for (const IdentifierPtr& propertyPtr : identifiers) {
             const Identifier& property = *propertyPtr;
             if (!object.respondsTo(property)) {
                 const Param& param = object;
                 if (!param) {
                     // TODO: create MessageFactory
                     Message errorMessage = Message() +
                         "Object: " + object.toString() + '\n' +
                         "has no property: " + property;
                     return new QueryPtr(
                         setupLocation<Query>(
                             ErrorFactory::getInstance().createQuery(errorMessage),
                             *param.getInputLocation()
                         )
                     );
                 }
             }
         }
     }
     for (const ConditionPtr& conditionPtr : conditions) {
         const Condition& condition = *conditionPtr;
         if (!condition) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Condition is not valid: " + condition.toString();
             return new QueryPtr(
                 setupLocation<Query>(
                     ErrorFactory::getInstance().createQuery(errorMessage),
                     *condition.getInputLocation()
                 )
             );
         }
     }
     return new QueryPtr(
         setupLocation<Query>(
             NullFactory::getInstance().createQuery(),
             inputLocation
         )
     );
 }
bool GT::GTL::CheckingStatementDriver::executeDefinition (const DefinitionPtr * definition) override virtual
Executes Definition saving Object under defined name.
Parameters
definition definition to execute
Implements GT::GTL::StatementDriver.
Definition at line 37 of file checking_statement_driver.cpp.
References driver, GT::GTL::ValidableSymbol::isValid(), and GT::GTL::Driver::showError().
Referenced by GT::GTL::ExecutionStatementDriver::executeDefinition().
   {
     const Definition& definition = **definitionPtr;
     if (!definition)
         driver->showError(definition);
     return definition.isValid();
 }
bool GT::GTL::CheckingStatementDriver::executeQuery (const QueryPtr * query) override virtual
Executes Query saving Object under defined name.
Parameters
query query to execute
Implements GT::GTL::StatementDriver.
Definition at line 46 of file checking_statement_driver.cpp.
References driver, GT::GTL::ValidableSymbol::isValid(), and GT::GTL::Driver::showError().
Referenced by GT::GTL::ExecutionStatementDriver::executeQuery().
   {
     const Query& query = **queryPtr;
     if (!query)
         driver->showError(query);
     return query.isValid();
 }
Message GT::GTL::CheckingStatementDriver::toString () const override virtual
CheckingStatementDriver's Message.
Returns
message
Implements GT::GTL::StatementDriver.
Definition at line 150 of file checking_statement_driver.cpp.
Referenced by createQuery().
{
     return Message("CheckingStatementDriver");
 }
Member Data Documentation
Driver* GT::GTL::CheckingStatementDriver::driver private
Implementation of a main Driver.
Definition at line 46 of file checking_statement_driver.hpp.
Referenced by executeDefinition(), and executeQuery().
The documentation for this class was generated from the following files:
src/gt/gtl/checking_statement_driver.hpp
src/gt/gtl/checking_statement_driver.cpp