Game Theory Tools (full documentation): GT::Model::Player Class Reference
GT::Model::Player Class Reference
Defines Player.
#include <player.hpp>
Public Member Functions
Player (const IdentifierPtr playerName, const IdentifiersPtr playerStrategies)
Constructor of the Player.
virtual const IdentifierPtr getName () const
Returns name ot the Player.
virtual const IdentifiersPtr getStrategies () const
Returns Player's strategies.
virtual Index getStrategiesNumber () const
Returns number of strategies.
virtual Index getStrategyOrdinal (const Identifier &strategy) const
Returns ordinal of a strategy with given Identifier.
virtual bool hasStrategy (const Identifier &strategy) const
Returns whether strategy with such name exists.
virtual bool isEqual (const Root &root) const override
Defines equality relation.
virtual Message toString () const override
Returns Message with Player's name and strategies.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Types
typedef map< Identifier, Index > StrategyMap
Type storing strategy-to-ordinal mapping.
Private Attributes
const IdentifierPtr name
Player's name.
const IdentifiersPtr strategies
Player's strategies.
StrategyMap strategyMapping
Mapps strategies to its ordinal.
Friends
bool operator== (const PlayerPtr &player1, const PlayerPtr &player2)
Syntax sugar for isEqual(const Root&)const method.
bool operator!= (const PlayerPtr &player1, const PlayerPtr &player2)
Syntax sugar for !isEqual(const Root&)const method.
OutputStream & operator<< (OutputStream &stream, const PlayerPtr &player)
Syntax sugar for toString()const method.
Detailed Description
Defines Player.
Each Player is defined by its name and used strategies. They will later be used during Game definition and calculation of equilibria.
Author
Mateusz Kubuszok
See Also
Game
GameBuilder
Definition at line 47 of file player.hpp.
Member Typedef Documentation
typedef map<Identifier, Index> GT::Model::Player::StrategyMap private
Type storing strategy-to-ordinal mapping.
Definition at line 51 of file player.hpp.
Constructor & Destructor Documentation
GT::Model::Player::Player (const IdentifierPtr playerName, const IdentifiersPtr playerStrategies)
Constructor of the Player.
Parameters
playerName name of the Player
playerStrategies declared strategies
Definition at line 31 of file player.cpp.
References strategies, and strategyMapping.
   :
     name(playerName),
     strategies(playerStrategies),
     strategyMapping()
 {
     Index index = 0;
     for (IdentifierPtr& strategy : *strategies)
         strategyMapping.insert( StrategyMap::value_type(*strategy, index++) );
 }
Member Function Documentation
const IdentifierPtr GT::Model::Player::getName () const virtual
Returns name ot the Player.
Returns
Player's name
Reimplemented in GT::Model::NullPlayer.
Definition at line 44 of file player.cpp.
References name.
Referenced by GT::GTL::LazyGameProxy::accessGame(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::fillUpProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::fillUpProblem(), GT::GTL::PlayerNameProperty::findForConditions(), GT::GTL::Player::serialize(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::solveProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::solveProblem(), and toString().
{
     return name;
 }
const IdentifiersPtr GT::Model::Player::getStrategies () const virtual
Returns Player's strategies.
Returns
Player's strategies
Reimplemented in GT::Model::NullPlayer.
Definition at line 48 of file player.cpp.
References strategies.
Referenced by GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::fillUpProblem(), GT::GTL::PlayerStrategiesProperty::findForConditions(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::initializeProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::initializeProblem(), GT::Model::StrategicGamePositionsHelper::retrievePositions(), GT::GTL::Player::serialize(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::solveProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::solveProblem(), and GT::Model::StrategicGamePositionsHelper::StrategicGamePositionsHelper().
{
     return strategies;
 }
Index GT::Model::Player::getStrategiesNumber () const virtual
Returns number of strategies.
Returns
number of strategies
Reimplemented in GT::Model::NullPlayer.
Definition at line 52 of file player.cpp.
References strategies.
Referenced by GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::fillUpProblem(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::initializeProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::initializeProblem(), GT::Model::StrategicGamePositionsHelper::retrievePositions(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::solveProblem(), and GT::Model::StrategicGamePositionsHelper::StrategicGamePositionsHelper().
{
     return strategies->size();
 }
Index GT::Model::Player::getStrategyOrdinal (const Identifier & strategy) const virtual
Returns ordinal of a strategy with given Identifier.
Parameters
strategy strategy name
Returns
ordinal of strategy with given Identifier
Exceptions
InvalidCoordinate thrown if Player has no such strategy
Reimplemented in GT::Model::NullPlayer.
Definition at line 56 of file player.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidStrategy(), and strategyMapping.
Referenced by GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::fillUpProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::fillUpProblem(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::initializeProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::initializeProblem(), GT::Routines::Strategic2Player0SumMixedEquilibriumRoutine::solveProblem(), GT::Routines::Strategic2PlayerMixedEquilibriumRoutine::solveProblem(), GT::Model::StrategicGamePositionsHelper::StrategicGamePositionsHelper(), and toString().
         {
     if (strategyMapping.count(strategy))
         return strategyMapping.at(strategy);
     throw ExceptionFactory::getInstance().invalidStrategy(strategy);
 }
bool GT::Model::Player::hasStrategy (const Identifier & strategy) const virtual
Returns whether strategy with such name exists.
Parameters
strategy strategy name
Returns
true if Player has such strategy
Definition at line 64 of file player.cpp.
References strategyMapping.
         {
     return strategyMapping.count(strategy);
 }
bool GT::Model::Player::isEqual (const Root & root) const override virtual
Defines equality relation.
Parameters
root another root to compare
Returns
true if roots are equal
Reimplemented from GT::Model::Root.
Definition at line 70 of file player.cpp.
References name, and strategies.
         {
     const Player* player = dynamic_cast<const Player*>(&root);
     if (!player)
         return false;
     if (player == this)
         return true;
     if (player->name != name)
         return false;
     if (*player->strategies != *strategies)
         return false;
     return true;
 }
Message GT::Model::Player::toString () const override virtual
Returns Message with Player's name and strategies.
Returns
Player's name and strategies
Implements GT::Model::Root.
Reimplemented in GT::Model::NullPlayer, GT::GTL::ErrorPlayer, GT::GTL::NullPlayer, and GT::GTL::Player.
Definition at line 85 of file player.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), getName(), getStrategyOrdinal(), name, and strategies.
Referenced by GT::GTL::Player::toString().
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     static const IdentifierPtr playerName      = createIdentifierPtr("Name");
     const MessagePtr           playerNameValue = createMessagePtr(getName());
     resultBuilder->addResult(playerName, playerNameValue);
     for (IdentifierPtr& strategy : *strategies) {
         IdentifierPtr name  = createIdentifierPtr(getStrategyOrdinal(*strategy)+1);
         MessagePtr    value = createMessagePtr(strategy);
         resultBuilder->addResult(name, value);
     }
     return resultBuilder->build()->getResult();
 }
Friends And Related Function Documentation
bool operator!= (const PlayerPtr & player1, const PlayerPtr & player2) friend
Syntax sugar for !isEqual(const Root&)const method.
Parameters
player1 first Player to compare
player2 second Player to compare
Returns
true if Players are not equal
Definition at line 112 of file player.cpp.
   {
     return (*player1) != (*player2);
 }
OutputStream& operator<< (OutputStream & stream, const PlayerPtr & player) friend
Syntax sugar for toString()const method.
Parameters
stream stream to concatenate
player Player to concatenate
Returns
stream for chaining
Definition at line 119 of file player.cpp.
   {
     return stream << player->toString();
 }
bool operator== (const PlayerPtr & player1, const PlayerPtr & player2) friend
Syntax sugar for isEqual(const Root&)const method.
Parameters
player1 first Player to compare
player2 second Player to compare
Returns
true if Players are equal
Definition at line 105 of file player.cpp.
   {
     return (*player1) == (*player2);
 }
Member Data Documentation
const IdentifierPtr GT::Model::Player::name private
Player's name.
Definition at line 56 of file player.hpp.
Referenced by getName(), isEqual(), and toString().
const IdentifiersPtr GT::Model::Player::strategies private
Player's strategies.
Definition at line 61 of file player.hpp.
Referenced by getStrategies(), getStrategiesNumber(), isEqual(), Player(), and toString().
StrategyMap GT::Model::Player::strategyMapping private
Mapps strategies to its ordinal.
Definition at line 66 of file player.hpp.
Referenced by getStrategyOrdinal(), hasStrategy(), and Player().
The documentation for this class was generated from the following files:
include/gt/model/player.hpp
src/gt/model/player.cpp