Game Theory Tools (full documentation): GT::Model::ExceptionFactory Class Reference
GT::Model::ExceptionFactory Class Reference final
Used for creation of exceptions with predefined message format.
#include <exception_factory.hpp>
Public Member Functions
InvalidCoordinate duplicatedPlayerName (const Identifier &playerName) const
Thrown when Players don't have unique names.
InvalidCoordinate duplicatedStrategyName (const Identifier &playerName, const Identifier &strategyName) const
Thrown when Player doesn't have unique strategies.
InvalidCoordinate emptyPlayerName () const
Thrown when Player has empty name.
InvalidCoordinate coordinatesAlreadySet (const Positions &positions) const
Thrown when values for given Positions are already set.
IllegalInnerState incompleteCoordinates () const
Thrown when some coordinates are uknown yet attept to store values is made.
InvalidCoordinate invalidCoordinateFormat (const Positions &position) const
Thrown when some of the Players' names or strategies are invalid.
InvalidCoordinate invalidExtensiveCoordinateFormat (const Positions &position) const
Thrown when there are colliding definitions of Player's playing in some turn.
InvalidCoordinate noParamsForPositions (const Index positionInStorage, const Index maxPosition) const
Thrown when ettepting to read from position that has not values defined.
InvalidCoordinate invalidPlayer (const Identifier &playerName) const
Thrown when no Player with given name has been defined.
InvalidCoordinate invalidStrategy (const Identifier &strategyName) const
Thrown when no strategy with given name has been defined.
InvalidCoordinate invalidInformationSet (const Identifier &informationSetName) const
Thrown when no information set with given name has been defined.
IllegalInnerState playersAlreadySet () const
Thrown when attempt to redefine Players is made.
IllegalInnerState propertiesAndResultsDontMatchInSize (const Index propertiesSize, const Index resultsSize) const
Thrown during attempt to build Result with properties' names and results not matching in size.
Static Public Member Functions
static ExceptionFactory & getInstance ()
Returns the instance of an ExceptionFactory.
Private Member Functions
ExceptionFactory ()=default
Default constructor hidden from programmers.
ExceptionFactory (const ExceptionFactory &exceptionFactory)=delete
Default copy constructor hidden from programmers.
~ExceptionFactory ()=default
Default destructor hidden from programmers.
Detailed Description
Used for creation of exceptions with predefined message format.
Author
Mateusz Kubuszok
Definition at line 37 of file exception_factory.hpp.
Constructor & Destructor Documentation
GT::Model::ExceptionFactory::ExceptionFactory () private default
Default constructor hidden from programmers.
GT::Model::ExceptionFactory::ExceptionFactory (const ExceptionFactory & exceptionFactory) private delete
Default copy constructor hidden from programmers.
Parameters
exceptionFactory object to copy
GT::Model::ExceptionFactory::~ExceptionFactory () private default
Default destructor hidden from programmers.
Member Function Documentation
InvalidCoordinate GT::Model::ExceptionFactory::coordinatesAlreadySet (const Positions & positions) const
Thrown when values for given Positions are already set.
Parameters
positions invalid Positions
Returns
InvalidCoordinate exception to throw
Definition at line 66 of file exception_factory.cpp.
Referenced by GT::Model::StrategicDataBuilder::addNextPositions(), GT::Model::ExtensiveDataNode::setPayoffs(), and GT::Model::ExtensiveDataNode::setPlayer().
         {
     stringstream result;
     result << "Coordinates:";
     for (const Positions::value_type& position : positions) {
         const Identifier  playerName   = position.first;
         const Identifier& strategyName = position.second;
         result << " '" << playerName << "'='" << strategyName << "'";
     }
     result << " already has defined payoff";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::duplicatedPlayerName (const Identifier & playerName) const
Thrown when Players don't have unique names.
Parameters
playerName duplicated name
Returns
InvalidCoordinate exception to throw
Definition at line 40 of file exception_factory.cpp.
Referenced by GT::Model::checkPlayers().
         {
     stringstream result;
     result << "Name '" << playerName << "' already used for another player";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::duplicatedStrategyName (const Identifier & playerName, const Identifier & strategyName) const
Thrown when Player doesn't have unique strategies.
Parameters
playerName Player's name
strategyName duplicated name
Returns
InvalidCoordinate exception to throw
Definition at line 50 of file exception_factory.cpp.
Referenced by GT::Model::checkPlayers().
         {
     stringstream result;
     result << "Name '" << strategyName << "' already used for another strategy for player '"
                        << playerName << "'";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::emptyPlayerName () const
Thrown when Player has empty name.
Parameters
name duplicated name
Returns
InvalidCoordinate exception to throw
Definition at line 62 of file exception_factory.cpp.
Referenced by GT::Model::checkPlayers().
{
     return InvalidCoordinate("Player's name cannot be empty");
 }
ExceptionFactory & GT::Model::ExceptionFactory::getInstance () static
Returns the instance of an ExceptionFactory.
Returns
ConditionFactory instance
Definition at line 35 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveDataBuilder::addNextPositions(), GT::Model::StrategicDataBuilder::addNextPositions(), GT::Model::checkPlayers(), GT::Model::AbstractResultBuilder::checkPropertyToResultMatching(), GT::Model::ExtensiveGamePositionsHelper::getInformationSetForPlayer(), GT::Model::ExtensiveGamePositionsHelper::getInformationSetsForPlayer(), GT::Model::ExtensiveDataNode::getNodeForChoice(), GT::Model::PlainDataPiece::getPayoff(), GT::Model::StrategicData::getPayoffs(), GT::Model::ExtensiveData::getPayoffs(), GT::Model::ExtensiveDataNode::getPayoffs(), GT::Model::ExtensiveDataNode::getPlayer(), GT::Model::ExtensiveGamePositionsHelper::getPossibleInformationSetsForPlayer(), GT::Model::Player::getStrategyOrdinal(), GT::Model::StrategicDataBuilder::setPayoffs(), GT::Model::StrategicData::setPayoffs(), GT::Model::ExtensiveData::setPayoffs(), GT::Model::ExtensiveDataNode::setPayoffs(), GT::Model::ExtensiveDataNode::setPlayer(), GT::Model::ExtensiveDataBuilder::setPlayers(), and GT::Model::StrategicDataBuilder::setPlayers().
{
     static ExceptionFactory instance;
     return instance;
 }
IllegalInnerState GT::Model::ExceptionFactory::incompleteCoordinates () const
Thrown when some coordinates are uknown yet attept to store values is made.
Returns
IllegalInnerState exception to throw
Definition at line 82 of file exception_factory.cpp.
Referenced by GT::Model::StrategicDataBuilder::setPayoffs().
{
     return IllegalInnerState("Cannot set parameters when not all coordinates are known");
 }
InvalidCoordinate GT::Model::ExceptionFactory::invalidCoordinateFormat (const Positions & position) const
Thrown when some of the Players' names or strategies are invalid.
Parameters
position invalid Positions
Returns
InvalidCoordinate exception to throw
Definition at line 86 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveDataBuilder::addNextPositions(), GT::Model::StrategicDataBuilder::addNextPositions(), GT::Model::ExtensiveData::getPayoffs(), GT::Model::ExtensiveDataNode::getPayoffs(), GT::Model::ExtensiveDataNode::getPlayer(), GT::Model::StrategicData::setPayoffs(), GT::Model::ExtensiveData::setPayoffs(), GT::Model::ExtensiveDataNode::setPayoffs(), and GT::Model::ExtensiveDataNode::setPlayer().
         {
     stringstream result;
     result << "Coordinates:";
     for (const Positions::value_type& position : positions) {
         const Identifier  playerName   = position.first;
         const Identifier& strategyName = position.second;
         result << " '" << playerName << "'='" << strategyName << "'";
     }
     result << " has invalid format - make sure chosen Players' names and strategies are valid";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::invalidExtensiveCoordinateFormat (const Positions & position) const
Thrown when there are colliding definitions of Player's playing in some turn.
Parameters
position invalid Positions
Returns
InvalidCoordinate exception to throw
Definition at line 102 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveDataBuilder::addNextPositions().
         {
     stringstream result;
     result << "Coordinates:";
     for (Positions::value_type position : positions) {
         const Identifier  playerName   = position.first;
         const Identifier& strategyName = position.second;
         result << " '" << playerName << "'='" << strategyName << "'";
     }
     result << " has invalid format - make sure chosen Players' names does not collide"
               " with other coordinates on the same level of tree";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::invalidInformationSet (const Identifier & informationSetName) const
Thrown when no information set with given name has been defined.
Parameters
informationSetName invalid strategy's name
Returns
InvalidCoordinate exception to throw
Definition at line 154 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveGamePositionsHelper::getInformationSetForPlayer().
         {
     stringstream result;
     result << "No Information Set '" << infromationSetName << "' has been defined";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::invalidPlayer (const Identifier & playerName) const
Thrown when no Player with given name has been defined.
Parameters
playerName invalid Player's name
Returns
InvalidCoordinate exception to throw
Definition at line 134 of file exception_factory.cpp.
Referenced by GT::Model::StrategicDataBuilder::addNextPositions(), GT::Model::ExtensiveGamePositionsHelper::getInformationSetForPlayer(), GT::Model::ExtensiveGamePositionsHelper::getInformationSetsForPlayer(), GT::Model::PlainDataPiece::getPayoff(), GT::Model::ExtensiveData::getPayoffs(), GT::Model::ExtensiveGamePositionsHelper::getPossibleInformationSetsForPlayer(), and GT::Model::ExtensiveData::setPayoffs().
         {
     stringstream result;
     result << "No Player '" << playerName << "' has been defined";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::invalidStrategy (const Identifier & strategyName) const
Thrown when no strategy with given name has been defined.
Parameters
strategyName invalid strategy's name
Returns
InvalidCoordinate exception to throw
Definition at line 144 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveDataNode::getNodeForChoice(), and GT::Model::Player::getStrategyOrdinal().
         {
     stringstream result;
     result << "No Strategy '" << strategyName << "' has been defined";
     return InvalidCoordinate(result.str());
 }
InvalidCoordinate GT::Model::ExceptionFactory::noParamsForPositions (const Index positionInStorage, const Index maxPosition) const
Thrown when ettepting to read from position that has not values defined.
Parameters
positionInStorage invalid position in storage
maxPosition maximal position
Returns
InvalidCoordinate exception to throw
Definition at line 119 of file exception_factory.cpp.
Referenced by GT::Model::PlainDataPiece::getPayoff(), GT::Model::StrategicData::getPayoffs(), and GT::Model::StrategicData::setPayoffs().
         {
     stringstream result;
     result << "Calculated position ("
            << positionInStorage
            << ") has no defined payoff - make sure all Coordinates in range [0,"
            << (maxPosition-1)
            << "] has defined payoff";
     return InvalidCoordinate(result.str());
 }
IllegalInnerState GT::Model::ExceptionFactory::playersAlreadySet () const
Thrown when attempt to redefine Players is made.
Returns
IllegalInnerState exception to throw
Definition at line 164 of file exception_factory.cpp.
Referenced by GT::Model::ExtensiveDataBuilder::setPlayers(), and GT::Model::StrategicDataBuilder::setPlayers().
{
     return IllegalInnerState("Cannot change already set Players");
 }
IllegalInnerState GT::Model::ExceptionFactory::propertiesAndResultsDontMatchInSize (const Index propertiesSize, const Index resultsSize) const
Thrown during attempt to build Result with properties' names and results not matching in size.
Parameters
propertiesSize properties' size
resultsSize results' size
Returns
IllegalInnerState exception to throw
Definition at line 168 of file exception_factory.cpp.
Referenced by GT::Model::AbstractResultBuilder::checkPropertyToResultMatching().
         {
     stringstream result;
     result << "Properties size ("
            << propertiesSize
            << ") and Results size ("
            << resultsSize
            << ") does not match";
     return IllegalInnerState(result.str());
 }
The documentation for this class was generated from the following files:
src/gt/model/exception_factory.hpp
src/gt/model/exception_factory.cpp