Game Theory Tools (full documentation): GT::GTL::ExecutionDriver Class Reference
GT::GTL::ExecutionDriver Class Reference final
Implementation used for executing both checking and actual actions.
#include <execution_driver.hpp>
Public Member Functions
ExecutionDriver (OutputStream *outputStream, OutputStream *errorStream)
Initiates ExecutionDriver with a output stream.
virtual ~ExecutionDriver ()
Destructor.
virtual CoordinateDriver & forCoordinate () const override
Driver for Coordinate.
virtual CollectionsDriver
< Coordinate > & forCoordinates () const override
Driver for Coordinates.
virtual ConditionDriver & forCondition () const override
Driver for Condition.
virtual CollectionsDriver
< Condition > & forConditions () const override
Driver for Conditions.
virtual GameDriver & forGame () const override
Driver for Game.
virtual CollectionsDriver
< Identifier > & forIdentifiers () const override
Driver for Identifiers.
virtual CollectionsDriver
< Object > & forObjects () const override
Driver for Objects.
virtual CollectionsDriver
< Param > & forParams () const override
Driver for Params.
virtual ValueDriver & forValue () const override
Driver for value.
virtual StatementDriver & forStatement () const override
Driver for Statement.
virtual void showResult (const ResultPtr result) const override
Displays results.
virtual void showError (const InputLocation &location, const Message &message) const override
Displays error.
virtual void showError (const ValidableSymbol &symbol) const override
Displays error.
virtual void execute (const InputLocation &location, const Identifier &fileName) const override
Executes file.
virtual void load (const InputLocation &location, const Identifier &fileName) override
Loads file.
virtual void save (const InputLocation &location, const Identifier &fileName) const override
Saves all Params available in current Context (and it's parents) to file.
virtual Message toString () const override
Driver's Message.
Public Member Functions inherited from GT::GTL::Driver
virtual ~Driver ()
Default destructor.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Member Functions
ExecutionDriver (OutputStream *outputStream, OutputStream *errorStream, ContextPtr parentContext)
Initiates ExecutionDriver with a output stream.
Private Attributes
CheckingDriver checkingDriver
CheckingDriver for error handling.
ContextPtr context
Contains Context.
ExecutionCoordinateDriver coordinate
Driver for Coordinates.
CollectionsDriver
< GT::GTL::Coordinate > coordinates
Driver for Coordinates' collections.
ExecutionConditionDriver condition
Driver for Conditions.
CollectionsDriver
< GT::GTL::Condition > conditions
Driver for Conditions' collections.
ExecutionGameDriver game
Driver for Games.
CollectionsDriver< GT::Identifier > identifiers
Driver for Identifiers' collections.
CollectionsDriver
< GT::GTL::Object > objects
Driver for Objects' collections.
CollectionsDriver< GT::GTL::Param > params
Driver for Params' collections.
ExecutionValueDriver value
Driver for values.
ExecutionStatementDriver statement
Driver for statements.
OutputStream * outputStream
Output stream for displaying results.
OutputStream * errorStream
Error stream for displaying informations about errors.
Detailed Description
Implementation used for executing both checking and actual actions.
Performs actual execution of instructions from input stream.
Author
Mateusz Kubuszok
See Also
Driver
Definition at line 41 of file execution_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::ExecutionDriver::ExecutionDriver (OutputStream * outputStream, OutputStream * errorStream)
Initiates ExecutionDriver with a output stream.
Parameters
outputStream output stream
errorStream error stream
Definition at line 39 of file execution_driver.cpp.
   :
     checkingDriver(newErrorStream),
     context(new Context()),
     coordinate(),
     condition(),
     game(context.get()),
     value(),
     statement(this, context.get()),
     outputStream(newOutputStream),
     errorStream(newErrorStream)
     {}
GT::GTL::ExecutionDriver::~ExecutionDriver () virtual
Destructor.
Definition at line 54 of file execution_driver.cpp.
 {}
GT::GTL::ExecutionDriver::ExecutionDriver (OutputStream * outputStream, OutputStream * errorStream, ContextPtr parentContext) private
Initiates ExecutionDriver with a output stream.
Parameters
outputStream output stream
errorStream error stream
parentContext parent's Context
Definition at line 231 of file execution_driver.cpp.
   :
     checkingDriver(newErrorStream),
     context(new Context(parentContext)),
     coordinate(),
     condition(),
     game(context.get()),
     value(),
     statement(this, context.get()),
     outputStream(newOutputStream)
     {}
Member Function Documentation
void GT::GTL::ExecutionDriver::execute (const InputLocation & location, const Identifier & fileName) const override virtual
Executes file.
It uses currently used output and error stream to display result but read input from file.
Operations are perfored on spawned Context so after all operations parental Context is instact.
Parameters
location location of file load call
fileName name of executed file
See Also
load(const InputLocation&, const Identifier&)
Implements GT::GTL::Driver.
Definition at line 116 of file execution_driver.cpp.
References GT::Model::ResultFactory::buildResult(), context, GT::createIdentifierPtr(), errorStream, GT::Model::ResultFactory::getInstance(), outputStream, showError(), showResult(), and value.
         {
     scoped_ptr<ifstream> file(new ifstream(fileName));
     if (!file->good()) {
         stringstream builder;
         builder << "Executed file <" << fileName << "> does not exists";
         string errorMessage(builder.str());
         showError(location, errorMessage);
         return;
     }
     ExecutionDriver driver(outputStream, errorStream, context);
     Scanner         scanner(file.get());
     Parser          parser(scanner, driver);
     bool      success = parser.parse() == 0;
     ResultPtr result;
     if (success) {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("File executed without errors");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     } else {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("There were errors during execution of this file");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     }
     showResult(result);
 }
ConditionDriver & GT::GTL::ExecutionDriver::forCondition () const override virtual
Driver for Condition.
Returns
ConditionDriver
Implements GT::GTL::Driver.
Definition at line 64 of file execution_driver.cpp.
References condition.
{
     return condition;
 }
CollectionsDriver< Condition > & GT::GTL::ExecutionDriver::forConditions () const override virtual
Driver for Conditions.
Returns
CollectionDriver for Conditions
Implements GT::GTL::Driver.
Definition at line 68 of file execution_driver.cpp.
References conditions.
{
     return conditions;
 }
CoordinateDriver & GT::GTL::ExecutionDriver::forCoordinate () const override virtual
Driver for Coordinate.
Returns
CoordinateDriver
Implements GT::GTL::Driver.
Definition at line 56 of file execution_driver.cpp.
References coordinate.
{
     return coordinate;
 }
CollectionsDriver< Coordinate > & GT::GTL::ExecutionDriver::forCoordinates () const override virtual
Driver for Coordinates.
Returns
CollectionDriver for Coordinates
Implements GT::GTL::Driver.
Definition at line 60 of file execution_driver.cpp.
References coordinates.
{
     return coordinates;
 }
GameDriver & GT::GTL::ExecutionDriver::forGame () const override virtual
Driver for Game.
Returns
GameDriver
Implements GT::GTL::Driver.
Definition at line 72 of file execution_driver.cpp.
References game.
{
     return game;
 }
CollectionsDriver< Identifier > & GT::GTL::ExecutionDriver::forIdentifiers () const override virtual
Driver for Identifiers.
Returns
CollectionDriver for Identifiers
Implements GT::GTL::Driver.
Definition at line 76 of file execution_driver.cpp.
References identifiers.
{
     return identifiers;
 }
CollectionsDriver< Object > & GT::GTL::ExecutionDriver::forObjects () const override virtual
Driver for Objects.
Returns
CollectionDriver for Objects
Implements GT::GTL::Driver.
Definition at line 80 of file execution_driver.cpp.
References objects.
{
     return objects;
 }
CollectionsDriver< Param > & GT::GTL::ExecutionDriver::forParams () const override virtual
Driver for Params.
Returns
CollectionDriver for Params
Implements GT::GTL::Driver.
Definition at line 84 of file execution_driver.cpp.
References params.
{
     return params;
 }
StatementDriver & GT::GTL::ExecutionDriver::forStatement () const override virtual
Driver for Statement.
Returns
StatementDriver
Implements GT::GTL::Driver.
Definition at line 92 of file execution_driver.cpp.
References statement.
{
     return statement;
 }
ValueDriver & GT::GTL::ExecutionDriver::forValue () const override virtual
Driver for value.
Returns
ValueDriver
Implements GT::GTL::Driver.
Definition at line 88 of file execution_driver.cpp.
References value.
{
     return value;
 }
void GT::GTL::ExecutionDriver::load (const InputLocation & location, const Identifier & fileName) override virtual
Loads file.
It uses currently used output and error stream to display result but read input from file.
Operations are performed in current Context so all changes will be persisted.
Parameters
location location of file load call
fileName name of loaded file
See Also
execute(const InputLocation&, const Identifier&)const
Implements GT::GTL::Driver.
Definition at line 148 of file execution_driver.cpp.
References GT::Model::ResultFactory::buildResult(), context, GT::createIdentifierPtr(), GT::Model::ResultFactory::getInstance(), GT::GTL::Context::getMaxLegalDepth(), showError(), showResult(), and value.
   {
     scoped_ptr<ifstream> file(new ifstream(fileName));
     if (!file->good()) {
         stringstream builder;
         builder << "Loaded file <" << fileName << "> does not exists";
         string errorMessage(builder.str());
         showError(location, errorMessage);
         return;
     }
     if (!context->canLegallySpawnChild()) {
         stringstream builder;
         builder << "Maximal depth level (" << Context::getMaxLegalDepth() << ") exceeded";
         string errorMessage(builder.str());
         showError(location, errorMessage);
     }
     Scanner scanner(file.get());
     Parser  parser(scanner, *this);
     bool      success = parser.parse() == 0;
     ResultPtr result;
     if (success) {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("File loaded without errors");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     } else {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("There were errors during loading of this file");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     }
     showResult(result);
 }
void GT::GTL::ExecutionDriver::save (const InputLocation & location, const Identifier & fileName) const override virtual
Saves all Params available in current Context (and it's parents) to file.
Parameters
location location of file load call
fileName name of saved file
Implements GT::GTL::Driver.
Definition at line 187 of file execution_driver.cpp.
References GT::Model::ResultFactory::buildResult(), context, GT::createIdentifierPtr(), GT::Model::ResultFactory::getInstance(), GT::GTL::Context::getMaxLegalDepth(), showError(), showResult(), and value.
         {
     ofstream file(fileName);
     if (!file.good()) {
         stringstream builder;
         builder << "Cannot save to file <" << fileName << ">";
         string errorMessage(builder.str());
         showError(location, errorMessage);
         return;
     }
     if (!context->canLegallySpawnChild()) {
         stringstream builder;
         builder << "Maximal depth level (" << Context::getMaxLegalDepth() << ") exceeded";
         string errorMessage(builder.str());
         showError(location, errorMessage);
     }
     file << context->serialize();
     bool      success = !file.fail();
     ResultPtr result;
     if (success) {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("Context saved without errors");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     } else {
         static IdentifierPtr name  = createIdentifierPtr("Result");
         static MessagePtr    value = createIdentifierPtr("There were errors during saving of this context");
         result = ResultFactory::getInstance().buildResult()->addResult(name, value).build();
     }
     showResult(result);
 }
void GT::GTL::ExecutionDriver::showError (const InputLocation & location, const Message & message) const override virtual
Displays error.
Parameters
location error's location
message Message to display
Implements GT::GTL::Driver.
Definition at line 103 of file execution_driver.cpp.
References checkingDriver, and GT::GTL::CheckingDriver::showError().
Referenced by execute(), load(), and save().
         {
     checkingDriver.showError(location, message);
 }
void GT::GTL::ExecutionDriver::showError (const ValidableSymbol & symbol) const override virtual
Displays error.
Parameters
symbol invalid symbol to display
Implements GT::GTL::Driver.
Definition at line 110 of file execution_driver.cpp.
References checkingDriver, and GT::GTL::CheckingDriver::showError().
         {
     checkingDriver.showError(symbol);
 }
void GT::GTL::ExecutionDriver::showResult (const ResultPtr result) const override virtual
Displays results.
Parameters
result Result to show
Implements GT::GTL::Driver.
Definition at line 96 of file execution_driver.cpp.
References outputStream.
Referenced by execute(), load(), and save().
         {
     if (outputStream)
         (*outputStream) << result->getResult();
 }
Message GT::GTL::ExecutionDriver::toString () const override virtual
Driver's Message.
Returns
message
Implements GT::GTL::Driver.
Definition at line 225 of file execution_driver.cpp.
{
     return Message("ExecutionDriver");
 }
Member Data Documentation
CheckingDriver GT::GTL::ExecutionDriver::checkingDriver mutable private
CheckingDriver for error handling.
Definition at line 45 of file execution_driver.hpp.
Referenced by showError().
ExecutionConditionDriver GT::GTL::ExecutionDriver::condition mutable private
Driver for Conditions.
Definition at line 63 of file execution_driver.hpp.
Referenced by forCondition().
CollectionsDriver<GT::GTL::Condition> GT::GTL::ExecutionDriver::conditions mutable private
Driver for Conditions' collections.
Definition at line 67 of file execution_driver.hpp.
Referenced by forConditions().
ContextPtr GT::GTL::ExecutionDriver::context mutable private
Contains Context.
Definition at line 50 of file execution_driver.hpp.
Referenced by execute(), load(), and save().
ExecutionCoordinateDriver GT::GTL::ExecutionDriver::coordinate mutable private
Driver for Coordinates.
Definition at line 55 of file execution_driver.hpp.
Referenced by forCoordinate().
CollectionsDriver<GT::GTL::Coordinate> GT::GTL::ExecutionDriver::coordinates mutable private
Driver for Coordinates' collections.
Definition at line 59 of file execution_driver.hpp.
Referenced by forCoordinates().
OutputStream* GT::GTL::ExecutionDriver::errorStream mutable private
Error stream for displaying informations about errors.
Definition at line 100 of file execution_driver.hpp.
Referenced by execute().
ExecutionGameDriver GT::GTL::ExecutionDriver::game mutable private
Driver for Games.
Definition at line 71 of file execution_driver.hpp.
Referenced by forGame().
CollectionsDriver<GT::Identifier> GT::GTL::ExecutionDriver::identifiers mutable private
Driver for Identifiers' collections.
Definition at line 75 of file execution_driver.hpp.
Referenced by forIdentifiers().
CollectionsDriver<GT::GTL::Object> GT::GTL::ExecutionDriver::objects mutable private
Driver for Objects' collections.
Definition at line 79 of file execution_driver.hpp.
Referenced by forObjects().
OutputStream* GT::GTL::ExecutionDriver::outputStream mutable private
Output stream for displaying results.
Definition at line 96 of file execution_driver.hpp.
Referenced by execute(), and showResult().
CollectionsDriver<GT::GTL::Param> GT::GTL::ExecutionDriver::params mutable private
Driver for Params' collections.
Definition at line 83 of file execution_driver.hpp.
Referenced by forParams().
ExecutionStatementDriver GT::GTL::ExecutionDriver::statement mutable private
Driver for statements.
Definition at line 91 of file execution_driver.hpp.
Referenced by forStatement().
ExecutionValueDriver GT::GTL::ExecutionDriver::value mutable private
Driver for values.
Definition at line 87 of file execution_driver.hpp.
Referenced by execute(), forValue(), load(), and save().
The documentation for this class was generated from the following files:
src/gt/gtl/execution_driver.hpp
src/gt/gtl/execution_driver.cpp