Game Theory Tools (full documentation): GT::GTL Namespace Reference
GT::GTL Namespace Reference
Contains classes related to parsing text input as a GTL language.
Classes
class CollectionsDriver
Used for handling collections via Driver.
class NullCollectionsDriver
Null CollectionsDriver for handling invalid situations.
class Condition
Condition used for querying Objects with some requirements.
class NullCondition
Null Condition for handling invalid situations.
class ErrorCondition
Error Condition for handling invalid situations.
class ConditionDriver
Used for handling Games via Driver.
class NullConditionDriver
Null ConditionDriver for handling invalid situations.
class ConditionFactory
Used for creation of Conditions for GT model.
class Context
Context containing identifiers and values befind then.
class NullContext
Null Context for handling invalid situations.
class Coordinate
Contains some Coordinate as well as data bound to it.
class NullCoordinate
Null Coordinate for handling invalid situations.
class ErrorCoordinate
Error Coordinate for handling invalid situations.
class CoordinateDriver
Used for handling Coordinates via Driver.
class NullCoordinateDriver
Null CoordinateDriver for handling invalid situations.
class Definition
Definition used to define Context.
class NullDefinition
Null Definition for handling invalid situations.
class ErrorDefinition
Error Definition for handling invalid situations.
class Details
Contains Coordinates as well as defined Players.
class NullDetails
Null Details for handling invalid situations.
class ErrorDetails
Error Details for handling invalid situations.
class Driver
Used for executing actions called by Parser.
class NullDriver
Null Driver for handling invalid situations.
class DriverFactory
Used for creation of Error instances for GTL classes.
class ErrorFactory
Used for creation of Error instances for GTL classes.
class CyclicIdentifiers
Intened to be thrown when Params create the cycle.
class InvalidContentRequest
Intened to be thrown when attempting to access content in invalid way.
class InvalidProperty
Intended to be thrown when accessing non-existing Objects' property.
class InvalidType
Intened to be thrown when casting Object to invalid type.
class NotDefinedParam
Intened to be thrown when attempting to access not defined Param.
class Game
Defines Game.
class NullGame
Null Game for handling invalid situations.
class ErrorGame
Error Condition for handling invalid situations.
class GameDriver
Used for handling Games via Driver.
class NullGameDriver
Null GameDriver for handling invalid situations.
class location
Abstract a location.
class NullFactory
Used for creation of Null instances for GTL classes.
class Object
Root of all Objects used as a data in parsed by GTL.
class NullObject
Null Object for handling invalid situations.
class ErrorObject
Error Object for handling invalid situations.
class Param
Abstract class that defines interface for Params.
class NullParam
Null Param for handling invalid situations.
class ErrorParam
Error Param for handling invalid situations.
class ParamFactory
Used for creation of Params that may differs in behaviour.
class Parser
A Bison parser.
class Player
Defines Player.
class NullPlayer
Null Player for handling invalid situations.
class ErrorPlayer
Error Player for handling invalid situations.
class position
Abstract a position.
class Query
Defines Query.
class NullQuery
Null Query for handling invalid situations.
class ErrorQuery
Error Query for handling invalid situations.
class Scanner
Scans for tokens declared by Parser class in given InputStream.
class stack
class slice
Present a slice of the top of a stack.
class StatementDriver
Used for handling statements via Driver.
class NullStatementDriver
Null StatementDriver for handling invalid situations.
class ValidableSymbol
Interface used for marking objects that are valid (or not) symbols in Parser.
class ValueDriver
Used for handling values via Driver.
class NullValueDriver
Null ValueDriver for handling invalid situations.
class CheckingConditionDriver
Implementation used for handling Conditions via CheckingDriver.
class CheckingCoordinateDriver
Implementation used for handling Coordinates via CheckingDriver.
class CheckingDriver
Implementation used for executing only checking actions.
class CheckingGameDriver
Implementation used for handling Games via CheckingDriver.
class CheckingStatementDriver
Implementation used for handling statements via CheckingDriver.
class CheckingValueDriver
Implementation used for handling values via CheckingDriver.
class CurrentContext
Abstract class that defines interface for Params.
class CurrentContextValuesProperty
Describes CurrentContext's values.
class ExceptionFactory
Used for creation of exception instances for GTL classes.
class ExecutionConditionDriver
Implementation used for handling Conditions via ExecutionDriver.
class ExecutionCoordinateDriver
Implementation used for handling Coordinates via ExecutionDriver.
class ExecutionDriver
Implementation used for executing both checking and actual actions.
class ExecutionGameDriver
Implementation used for handling Games via ExecutionDriver.
class ExecutionStatementDriver
Implementation used for handling statements via ExecutionDriver.
class ExecutionValueDriver
Implementation used for handling values via ExecutionDriver.
class GameBehaviorEquilibriumProperty
Describes behavior-strategy equilibria of Games.
class GameMixedEquilibriumProperty
Describes mixed-strategy equilibria of Games.
class GamePureEquilibriumProperty
Describes pure-strategy equilibria for Games.
class IdentifierParam
Param containing reference to other Param.
class InformationSetChoiceCondition
Condition used for selecting strategy for an information set.
class InformationSetRangeCondition
Condition used for selecting strategy for an information set.
class LazyGameProxy
Makes Game act in functional manner by building it from scratch each time some property is required.
class NumberParam
Param containing Number value.
class ObjectKnownProperties
Describes Object's known properties.
class ObjectParam
Param containing Object value.
class ObjectProperty
Root of all Object's properties that can be registered.
class ObjectTypeProperty
Describes Object's type.
class ParamKnownProperties
Describes referred Object's known properties.
class ParamValueProperty
Describes Param's value.
class PlayerChoiceCondition
Condition used for selecting strategy for a Player.
class PlayerNameProperty
Describes Player's name.
class PlayerRangeCondition
Condition used for selecting strategies for a Player.
class PlayerStrategiesProperty
Describes Player's strategies.
Typedefs
typedef shared_ptr< Object > ObjectPtr
Smart pointer to Object.
typedef shared_ptr
< ObjectProperty > ObjectPropertyPtr
Smart pointer to ObjectProperty.
typedef shared_ptr< Condition > ConditionPtr
Smart pointer to Condition.
typedef shared_ptr< Context > ContextPtr
Smart pointer to Context.
typedef shared_ptr< Coordinate > CoordinatePtr
Smart pointer to Coordinate.
typedef shared_ptr< Definition > DefinitionPtr
Smart pointer to Definition.
typedef shared_ptr< Details > DetailsPtr
Smart pointer to Details.
typedef shared_ptr< Game > GamePtr
Smart pointer to Game.
typedef shared_ptr< Query > QueryPtr
Smart pointer to Query.
typedef shared_ptr< Param > ParamPtr
Smart pointer to Param.
typedef shared_ptr< Player > PlayerPtr
Smart pointer to Player.
typedef vector< ConditionPtr > Conditions
Vector of Conditions.
typedef shared_ptr< Conditions > ConditionsPtr
Smart pointer to Conditions.
typedef vector< CoordinatePtr > Coordinates
Vector of Coordinates.
typedef shared_ptr< Coordinates > CoordinatesPtr
Smart pointer to Coordinates.
typedef vector< ObjectPtr > Objects
Vector of Objects.
typedef shared_ptr< Objects > ObjectsPtr
Smart pointer to Objects.
typedef map< Identifier,
ObjectPropertyPtr > ObjectPropertyMap
Maps Identifer to ObjectProperty.
typedef vector< ParamPtr > Params
Vector of Params.
typedef shared_ptr< Params > ParamsPtr
Smart pointer to Params.
typedef shared_ptr< Parser > ParserPtr
Smart pointer to Parser.
typedef shared_ptr< Scanner > ScannerPtr
Smart pointer to Scanner.
typedef shared_ptr< Driver > DriverPtr
Smart pointer to Driver.
typedef shared_ptr
< ConditionDriver > ConditionDriverPtr
Smart pointer to ConditionDriver.
typedef shared_ptr
< CoordinateDriver > CoordinateDriverPtr
Smart pointer to CoordinateDriver.
typedef shared_ptr< GameDriver > GameDriverPtr
Smart pointer to GameDriver.
typedef shared_ptr< ValueDriver > ValueDriverPtr
Smart pointer to ValueDriver.
typedef shared_ptr
< StatementDriver > StatementDriverPtr
Smart pointer to StatementDriver.
template<typename Content >
using CollectionsDriverPtr = shared_ptr< CollectionsDriver< Content >>
Smart pointer to CollectionsDriver.
typedef location InputLocation
Alias for Bison-generated class.
typedef shared_ptr< InputLocation > InputLocationPtr
Smart pointer to InputLocation.
typedef Model::Root Root
Alias for Model::Root.
typedef Model::Result Result
Alias for Model::Result.
typedef Model::NullResult NullResult
Alias for Model::NullResult.
typedef Model::ResultPtr ResultPtr
Alias for Model::ResultPtr.
typedef Model::ResultFactory ResultFactory
typedef Model::ResultBuilderPtr ResultBuilderPtr
Functions
bool operator== (const Conditions &conditions1, const Conditions &conditions2)
Check if Conditions are equal.
bool operator!= (const Conditions &conditions1, const Conditions &conditions2)
Check if Conditions are different.
bool operator== (const Coordinates &coordinates1, const Coordinates &coordinates2)
Check if Coordinates are equal.
bool operator!= (const Coordinates &coordinates1, const Coordinates &coordinates2)
Check if Coordinates are different.
bool operator== (const Objects &objects1, const Objects &objects2)
Check if Objects are equal.
bool operator!= (const Objects &objects1, const Objects &objects2)
Check if Objects are different.
bool operator== (const Params &params1, const Params &params2)
Check if Params are equal.
bool operator!= (const Params &params1, const Params &params2)
Check if Params are different.
template<typename Symbol >
shared_ptr< Symbol > setupLocation (shared_ptr< Symbol > symbol, const InputLocation &inputLocation)
Sets up location for ValidableSymbols.
Message suberrorMessage (const Message &parentMessage, const ValidableSymbol &invalidSymbol)
Creates error Message for given parent message and error origin.
const location operator+ (const location &begin, const location &end)
Join two location objects to create a location.
const location operator+ (const location &begin, unsigned int width)
Add two location objects.
location & operator+= (location &res, unsigned int width)
Add and assign a location.
bool operator== (const location &loc1, const location &loc2)
Compare two location objects.
bool operator!= (const location &loc1, const location &loc2)
Compare two location objects.
std::ostream & operator<< (std::ostream &ostr, const location &loc)
Intercept output stream redirection.
const position & operator+= (position &res, const int width)
Add and assign a position.
const position operator+ (const position &begin, const int width)
Add two position objects.
const position & operator-= (position &res, const int width)
Add and assign a position.
const position operator- (const position &begin, const int width)
Add two position objects.
bool operator== (const position &pos1, const position &pos2)
Compare two position objects.
bool operator!= (const position &pos1, const position &pos2)
Compare two position objects.
std::ostream & operator<< (std::ostream &ostr, const position &pos)
Intercept output stream redirection.
Coordinate operator+ (const Coordinate &coordinate1, const Coordinate &coordinate2)
Detailed Description
Contains classes related to parsing text input as a GTL language.
It consists of Parser, Scanner, Drivers responsible for specific tasks and Object classes that help turn Parser's input into Model instances and Routines Results.
Typedef Documentation
template<typename Content > using GT::GTL::CollectionsDriverPtr = typedef shared_ptr<CollectionsDriver<Content>>
Smart pointer to CollectionsDriver.
Definition at line 128 of file common.hpp.
typedef shared_ptr<ConditionDriver> GT::GTL::ConditionDriverPtr
Smart pointer to ConditionDriver.
Definition at line 121 of file common.hpp.
typedef shared_ptr<Condition> GT::GTL::ConditionPtr
Smart pointer to Condition.
Definition at line 98 of file common.hpp.
typedef vector<ConditionPtr> GT::GTL::Conditions
Vector of Conditions.
Definition at line 108 of file common.hpp.
typedef shared_ptr<Conditions> GT::GTL::ConditionsPtr
Smart pointer to Conditions.
Definition at line 109 of file common.hpp.
typedef shared_ptr<Context> GT::GTL::ContextPtr
Smart pointer to Context.
Definition at line 99 of file common.hpp.
typedef shared_ptr<CoordinateDriver> GT::GTL::CoordinateDriverPtr
Smart pointer to CoordinateDriver.
Definition at line 122 of file common.hpp.
typedef shared_ptr<Coordinate> GT::GTL::CoordinatePtr
Smart pointer to Coordinate.
Definition at line 100 of file common.hpp.
typedef vector<CoordinatePtr> GT::GTL::Coordinates
Vector of Coordinates.
Definition at line 110 of file common.hpp.
typedef shared_ptr<Coordinates> GT::GTL::CoordinatesPtr
Smart pointer to Coordinates.
Definition at line 111 of file common.hpp.
typedef shared_ptr<Definition> GT::GTL::DefinitionPtr
Smart pointer to Definition.
Definition at line 101 of file common.hpp.
typedef shared_ptr<Details> GT::GTL::DetailsPtr
Smart pointer to Details.
Definition at line 102 of file common.hpp.
typedef shared_ptr<Driver> GT::GTL::DriverPtr
Smart pointer to Driver.
Definition at line 120 of file common.hpp.
typedef shared_ptr<GameDriver> GT::GTL::GameDriverPtr
Smart pointer to GameDriver.
Definition at line 123 of file common.hpp.
typedef shared_ptr<Game> GT::GTL::GamePtr
Smart pointer to Game.
Definition at line 103 of file common.hpp.
typedef location GT::GTL::InputLocation
Alias for Bison-generated class.
Definition at line 130 of file common.hpp.
typedef shared_ptr<InputLocation> GT::GTL::InputLocationPtr
Smart pointer to InputLocation.
Definition at line 131 of file common.hpp.
typedef Model::NullResult GT::GTL::NullResult
Alias for Model::NullResult.
Definition at line 135 of file common.hpp.
typedef map<Identifier,ObjectPropertyPtr> GT::GTL::ObjectPropertyMap
Maps Identifer to ObjectProperty.
Definition at line 114 of file common.hpp.
typedef shared_ptr<ObjectProperty> GT::GTL::ObjectPropertyPtr
Smart pointer to ObjectProperty.
Definition at line 97 of file common.hpp.
typedef shared_ptr<Object> GT::GTL::ObjectPtr
Smart pointer to Object.
Definition at line 90 of file common.hpp.
typedef vector<ObjectPtr> GT::GTL::Objects
Vector of Objects.
Definition at line 112 of file common.hpp.
typedef shared_ptr<Objects> GT::GTL::ObjectsPtr
Smart pointer to Objects.
Definition at line 113 of file common.hpp.
typedef shared_ptr<Param> GT::GTL::ParamPtr
Smart pointer to Param.
Definition at line 105 of file common.hpp.
typedef vector<ParamPtr> GT::GTL::Params
Vector of Params.
Definition at line 115 of file common.hpp.
typedef shared_ptr<Params> GT::GTL::ParamsPtr
Smart pointer to Params.
Definition at line 116 of file common.hpp.
typedef shared_ptr<Parser> GT::GTL::ParserPtr
Smart pointer to Parser.
Definition at line 118 of file common.hpp.
typedef shared_ptr<Player> GT::GTL::PlayerPtr
Smart pointer to Player.
Definition at line 106 of file common.hpp.
typedef shared_ptr<Query> GT::GTL::QueryPtr
Smart pointer to Query.
Definition at line 104 of file common.hpp.
typedef Model::Result GT::GTL::Result
Alias for Model::Result.
Definition at line 134 of file common.hpp.
typedef Model::ResultBuilderPtr GT::GTL::ResultBuilderPtr
Definition at line 95 of file inner_common.hpp.
typedef Model::ResultFactory GT::GTL::ResultFactory
Definition at line 90 of file inner_common.hpp.
typedef Model::ResultPtr GT::GTL::ResultPtr
Alias for Model::ResultPtr.
Definition at line 136 of file common.hpp.
typedef Model::Root GT::GTL::Root
Alias for Model::Root.
Definition at line 133 of file common.hpp.
typedef shared_ptr<Scanner> GT::GTL::ScannerPtr
Smart pointer to Scanner.
Definition at line 119 of file common.hpp.
typedef shared_ptr<StatementDriver> GT::GTL::StatementDriverPtr
Smart pointer to StatementDriver.
Definition at line 125 of file common.hpp.
typedef shared_ptr<ValueDriver> GT::GTL::ValueDriverPtr
Smart pointer to ValueDriver.
Definition at line 124 of file common.hpp.
Function Documentation
bool GT::GTL::operator!= (const location & loc1, const location & loc2) inline
Compare two location objects.
Definition at line 134 of file location.hh.
   {
     return !(loc1 == loc2);
   }
bool GT::GTL::operator!= (const position & pos1, const position & pos2) inline
Compare two position objects.
Definition at line 141 of file position.hh.
   {
     return !(pos1 == pos2);
   }
bool GT::GTL::operator!= (const Conditions & conditions1, const Conditions & conditions2)
Check if Conditions are different.
Parameters
conditions1 first Conditions vector
conditions2 second Conditions vector
Returns
true if vectors have different content
Definition at line 41 of file common.cpp.
   {
     return !(conditions1 == conditions2);
 }
bool GT::GTL::operator!= (const Coordinates & coordinates1, const Coordinates & coordinates2)
Check if Coordinates are different.
Parameters
coordinates1 first Coordinates vector
coordinates2 second Coordinates vector
Returns
true if vectors have different content
Definition at line 61 of file common.cpp.
   {
     return !(coordinates1 == coordinates2);
 }
bool GT::GTL::operator!= (const Objects & objects1, const Objects & objects2)
Check if Objects are different.
Parameters
objects1 first Objects vector
objects2 second Objects vector
Returns
true if vectors have different content
Definition at line 81 of file common.cpp.
   {
     return !(objects1 == objects2);
 }
bool GT::GTL::operator!= (const Params & params1, const Params & params2)
Check if Params are different.
Parameters
params1 first Params vector
params2 second Params vector
Returns
true if vectors have different content
Definition at line 101 of file common.cpp.
   {
     return !(params1 == params2);
 }
const location GT::GTL::operator+ (const location & begin, const location & end) inline
Join two location objects to create a location.
Definition at line 103 of file location.hh.
References GT::GTL::location::end.
   {
     location res = begin;
     res.end = end.end;
     return res;
   }
const position GT::GTL::operator+ (const position & begin, const int width) inline
Add two position objects.
Definition at line 108 of file position.hh.
   {
     position res = begin;
     return res += width;
   }
const location GT::GTL::operator+ (const location & begin, unsigned int width) inline
Add two location objects.
Definition at line 111 of file location.hh.
References GT::GTL::location::columns().
   {
     location res = begin;
     res.columns (width);
     return res;
   }
Coordinate GT::GTL::operator+ (const Coordinate & coordinate1, const Coordinate & coordinate2)
Parameters
coordinate1 first Coordinate
coordinate2 second Coordinate
Returns
merged Coordinates
Definition at line 221 of file coordinate.cpp.
References GT::GTL::Coordinate::getParams(), GT::GTL::Coordinate::getPositions(), GT::GTL::Coordinate::getSubCoordinates(), GT::GTL::Coordinate::params, GT::GTL::Coordinate::positions, and GT::GTL::Coordinate::subCoordinates.
   {
     Coordinate result;
     for (const Positions::value_type& position : *coordinate1.getPositions())
         result.positions->insert(position);
     for (const Positions::value_type& position : *coordinate2.getPositions())
         result.positions->insert(position);
     for (const ParamPtr& param : *coordinate1.getParams())
         result.params->push_back(param);
     for (const ParamPtr& param : *coordinate2.getParams())
         result.params->push_back(param);
     for (const CoordinatePtr& subCoordinate : *coordinate1.getSubCoordinates())
         result.subCoordinates->push_back(subCoordinate);
     for (const CoordinatePtr& subCoordinate : *coordinate2.getSubCoordinates())
         result.subCoordinates->push_back(subCoordinate);
     return result;
 }
const position& GT::GTL::operator+= (position & res, const int width) inline
Add and assign a position.
Definition at line 100 of file position.hh.
References GT::GTL::position::columns().
   {
     res.columns (width);
     return res;
   }
location& GT::GTL::operator+= (location & res, unsigned int width) inline
Add and assign a location.
Definition at line 119 of file location.hh.
References GT::GTL::location::columns().
   {
     res.columns (width);
     return res;
   }
const position GT::GTL::operator- (const position & begin, const int width) inline
Add two position objects.
Definition at line 123 of file position.hh.
   {
     return begin + -width;
   }
const position& GT::GTL::operator-= (position & res, const int width) inline
Add and assign a position.
Definition at line 116 of file position.hh.
   {
     return res += -width;
   }
std::ostream& GT::GTL::operator<< (std::ostream & ostr, const location & loc) inline
Intercept output stream redirection.
Parameters
ostr the destination output stream
loc a reference to the location to redirect
Avoid duplicate information.
Definition at line 145 of file location.hh.
References GT::GTL::location::begin, GT::GTL::position::column, GT::GTL::location::end, GT::GTL::position::filename, and GT::GTL::position::line.
   {
     position last = loc.end - 1;
     ostr << loc.begin;
     if (last.filename
     && (!loc.begin.filename
         || *loc.begin.filename != *last.filename))
       ostr << '-' << last;
     else if (loc.begin.line != last.line)
       ostr << '-' << last.line  << '.' << last.column;
     else if (loc.begin.column != last.column)
       ostr << '-' << last.column;
     return ostr;
   }
std::ostream& GT::GTL::operator<< (std::ostream & ostr, const position & pos) inline
Intercept output stream redirection.
Parameters
ostr the destination output stream
pos a reference to the position to redirect
Definition at line 151 of file position.hh.
References GT::GTL::position::column, GT::GTL::position::filename, and GT::GTL::position::line.
   {
     if (pos.filename)
       ostr << *pos.filename << ':';
     return ostr << pos.line << '.' << pos.column;
   }
bool GT::GTL::operator== (const location & loc1, const location & loc2) inline
Compare two location objects.
Definition at line 127 of file location.hh.
References GT::GTL::location::begin, and GT::GTL::location::end.
   {
     return loc1.begin == loc2.begin && loc1.end == loc2.end;
   }
bool GT::GTL::operator== (const position & pos1, const position & pos2) inline
Compare two position objects.
Definition at line 130 of file position.hh.
References GT::GTL::position::column, GT::GTL::position::filename, and GT::GTL::position::line.
   {
     return (pos1.line == pos2.line
             && pos1.column == pos2.column
             && (pos1.filename == pos2.filename
                 || (pos1.filename && pos2.filename
                     && *pos1.filename == *pos2.filename)));
   }
bool GT::GTL::operator== (const Conditions & conditions1, const Conditions & conditions2)
Check if Conditions are equal.
Parameters
conditions1 first Conditions vector
conditions2 second Conditions vector
Returns
true if vectors have equal content
Definition at line 28 of file common.cpp.
   {
     if (&conditions1 == &conditions2)
         return true;
     if (conditions1.size() != conditions2.size())
         return false;
     for (Index i = 0; i < conditions1.size(); i++)
         if (conditions1[i] !=conditions2[i])
             return false;
     return true;
 }
bool GT::GTL::operator== (const Coordinates & coordinates1, const Coordinates & coordinates2)
Check if Coordinates are equal.
Parameters
coordinates1 first Coordinates vector
coordinates2 second Coordinates vector
Returns
true if vectors have equal content
Definition at line 48 of file common.cpp.
   {
     if (&coordinates1 == &coordinates2)
         return true;
     if (coordinates1.size() != coordinates2.size())
         return false;
     for (Index i = 0; i < coordinates1.size(); i++)
         if (coordinates1[i] !=coordinates2[i])
             return false;
     return true;
 }
bool GT::GTL::operator== (const Objects & objects1, const Objects & objects2)
Check if Objects are equal.
Parameters
objects1 first Objects vector
objects2 second Objects vector
Returns
true if vectors have equal content
Definition at line 68 of file common.cpp.
   {
     if (&objects1 == &objects2)
         return true;
     if (objects1.size() != objects2.size())
         return false;
     for (Index i = 0; i < objects1.size(); i--)
         if (objects1[i] !=objects2[i])
             return false;
     return true;
 }
bool GT::GTL::operator== (const Params & params1, const Params & params2)
Check if Params are equal.
Parameters
params1 first Params vector
params2 second Params vector
Returns
true if vectors have equal content
Definition at line 88 of file common.cpp.
   {
     if (&params1 == &params2)
         return true;
     if (params1.size() != params2.size())
         return false;
     for (Index i = 0; i < params1.size(); i--)
         if (params1[i] !=params2[i])
             return false;
     return true;
 }
template<typename Symbol > shared_ptr<Symbol> GT::GTL::setupLocation (shared_ptr< Symbol > symbol, const InputLocation & inputLocation)
Sets up location for ValidableSymbols.
Parameters
symbol symbol to set
inputLocation location to set
Returns
reference to selffor chaining
Message GT::GTL::suberrorMessage (const Message & parentMessage, const ValidableSymbol & invalidSymbol)
Creates error Message for given parent message and error origin.
Parameters
parentMessage parent message that will be explained by suberror message
invalidSymbol invalid symbol to display
Returns
message to show
Definition at line 36 of file helpers.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), and GT::Model::Root::toString().
   {
     stringstream result;
     result << parentMessage << ":" << endl;
     Message content = invalidSymbol.toString();
     std::vector<Message> lines;
     split(lines, content, is_any_of("\n"));
     for (Message& line : lines)
         if (!line.empty() && line != "\n")
             result << '\t' << line << endl;
     result <<  '\t' << "at line " << invalidSymbol.getInputLocation() << endl;
     return result.str();
 }