Game Theory Tools (full documentation): GT::GTL::ExecutionConditionDriver Class Reference
GT::GTL::ExecutionConditionDriver Class Reference final
Implementation used for handling Conditions via ExecutionDriver.
#include <execution_condition_driver.hpp>
Public Member Functions
ExecutionConditionDriver (Driver *parentDriver)
Initiates ExecutionConditionDriver with its parent.
virtual ConditionPtr * informationSetChoosed (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *informationSetPtr, const ObjectPtr *strategyPtr) const override
Create condition for Player choosing strategy in information set.
virtual ConditionPtr * informationSetWithin (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *informationSetPtr, const ObjectsPtr *strategiesPtr) const override
Create condition for Player limiting allowed strategies in information set.
virtual ConditionPtr * playerChoosed (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectPtr *strategyPtr) const override
Create Condition for Player choosing strategy.
virtual ConditionPtr * playerWithin (const InputLocation &inputLocation, const ObjectPtr *playerPtr, const ObjectsPtr *strategiesPtr) const override
Create condition for Player limiting allowed strategies.
virtual Message toString () const override
ExecutionConditionDriver's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
CheckingConditionDriver checkingConditionDriver
Driver for error handling.
Driver * driver
Implementation of a main Driver.
Detailed Description
Implementation used for handling Conditions via ExecutionDriver.
Performs actual execution of instructions for Conditions.
Author
Mateusz Kubuszok
See Also
ExecutionDriver
ConditionDriver
Definition at line 42 of file execution_condition_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::ExecutionConditionDriver::ExecutionConditionDriver (Driver * parentDriver) explicit
Initiates ExecutionConditionDriver with its parent.
Parameters
parentDriver parent Driver
Definition at line 31 of file execution_condition_driver.cpp.
   :
     checkingConditionDriver(parentDriver),
     driver(parentDriver)
     {}
Member Function Documentation
ConditionPtr * GT::GTL::ExecutionConditionDriver::informationSetChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectPtr * strategyPtr) const override virtual
Create condition for Player choosing strategy in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 38 of file execution_condition_driver.cpp.
References checkingConditionDriver, GT::GTL::ConditionFactory::getInstance(), and GT::GTL::CheckingConditionDriver::informationSetChoosed().
         {
     ConditionPtr* errorCheck = checkingConditionDriver
         .informationSetChoosed(inputLocation, playerPtr, informationSetPtr, strategyPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const ObjectPtr& playerObject         = *playerPtr;
     const ObjectPtr& informationSetObject = *informationSetPtr;
     const ObjectPtr& strategyObject       = *strategyPtr;
     return new ConditionPtr(
         setupLocation<Condition>(
             ConditionFactory::getInstance()
                 .createInformationSetChoiceCondition(playerObject, informationSetObject, strategyObject),
             inputLocation
         )
     );
 }
ConditionPtr * GT::GTL::ExecutionConditionDriver::informationSetWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * informationSetPtr, const ObjectsPtr * strategiesPtr) const override virtual
Create condition for Player limiting allowed strategies in information set.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
informationSetPtr Player's information set
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 63 of file execution_condition_driver.cpp.
References checkingConditionDriver, GT::GTL::ConditionFactory::getInstance(), and GT::GTL::CheckingConditionDriver::informationSetWithin().
         {
     ConditionPtr* errorCheck = checkingConditionDriver
         .informationSetWithin(inputLocation, playerPtr, informationSetPtr, strategiesPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const ObjectPtr&  playerObject         = *playerPtr;
     const ObjectPtr&  informationSetObject = *informationSetPtr;
     const ObjectsPtr& strategiesObjects    = *strategiesPtr;
     return new ConditionPtr(
         setupLocation<Condition>(
             ConditionFactory::getInstance()
                 .createInformationSetRangeCondition(playerObject, informationSetObject, strategiesObjects),
             inputLocation
         )
     );
 }
ConditionPtr * GT::GTL::ExecutionConditionDriver::playerChoosed (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectPtr * strategyPtr) const override virtual
Create Condition for Player choosing strategy.
Parameters
inputLocation input location of created Condition
playerPtr Player's name
strategyPtr chosen strategy
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 88 of file execution_condition_driver.cpp.
References checkingConditionDriver, GT::GTL::ConditionFactory::getInstance(), and GT::GTL::CheckingConditionDriver::playerChoosed().
         {
     ConditionPtr* errorCheck = checkingConditionDriver.playerChoosed(inputLocation, playerPtr, strategyPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const ObjectPtr& playerObject   = *playerPtr;
     const ObjectPtr& strategyObject = *strategyPtr;
     return new ConditionPtr(
         setupLocation<Condition>(
             ConditionFactory::getInstance().createPlayerChoiceCondition(playerObject, strategyObject),
             inputLocation
         )
     );
 }
ConditionPtr * GT::GTL::ExecutionConditionDriver::playerWithin (const InputLocation & inputLocation, const ObjectPtr * playerPtr, const ObjectsPtr * strategiesPtr) const override virtual
Create condition for Player limiting allowed strategies.
Parameters
inputLocation input location of a created Condition
playerPtr Player's name
strategiesPtr allowed strategies
Returns
Condition
Implements GT::GTL::ConditionDriver.
Definition at line 109 of file execution_condition_driver.cpp.
References checkingConditionDriver, GT::GTL::ConditionFactory::getInstance(), and GT::GTL::CheckingConditionDriver::playerWithin().
         {
     ConditionPtr* errorCheck = checkingConditionDriver.playerWithin(inputLocation, playerPtr, strategiesPtr);
     if (!(*errorCheck)->isValid())
         return errorCheck;
     delete errorCheck;
     const ObjectPtr&  playerObject      = *playerPtr;
     const ObjectsPtr& strategiesObjects = *strategiesPtr;
     return new ConditionPtr(
         setupLocation<Condition>(
             ConditionFactory::getInstance().createPlayerRangeCondition(playerObject, strategiesObjects),
             inputLocation
         )
     );
 }
Message GT::GTL::ExecutionConditionDriver::toString () const override virtual
ExecutionConditionDriver's Message.
Returns
message
Implements GT::GTL::ConditionDriver.
Definition at line 130 of file execution_condition_driver.cpp.
{
     return Message("ExecutionConditionDriver");
 }
Member Data Documentation
CheckingConditionDriver GT::GTL::ExecutionConditionDriver::checkingConditionDriver private
Driver for error handling.
Definition at line 46 of file execution_condition_driver.hpp.
Referenced by informationSetChoosed(), informationSetWithin(), playerChoosed(), and playerWithin().
Driver* GT::GTL::ExecutionConditionDriver::driver private
Implementation of a main Driver.
Definition at line 50 of file execution_condition_driver.hpp.
The documentation for this class was generated from the following files:
src/gt/gtl/execution_condition_driver.hpp
src/gt/gtl/execution_condition_driver.cpp