Game Theory Tools (full documentation): GT::Model::NullGameBuilder Class Reference
GT::Model::NullGameBuilder Class Reference final
Null GameBuilder for handling invalid situations.
#include <game_builder.hpp>
Public Member Functions
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual DataBuilder & setPlayers (const PlayersPtr) override
Sets Players defined for Game.
virtual DataBuilder & addNextPositions (const PositionsPtr) override
Adds next positions to Data.
virtual DataBuilder & setPayoffs (const NumbersPtr) override
Sets Params with values.
virtual DataBuilderPtr dataBuilder () const override
Returns inner DataBuilder.
virtual GamePtr build () const override
Builds Game.
virtual DataBuilderPtr clone () const override
Clones DataBuilder for recursive building.
virtual GameBuilderPtr cloneBuilder () const override
Returns new copy of this GameBuilder's type.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
DataBuilder's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null GameBuilder for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 94 of file game_builder.hpp.
Member Function Documentation
virtual DataBuilder& GT::Model::NullGameBuilder::addNextPositions (const PositionsPtr positions) inline override virtual
Adds next positions to Data.
Parameters
positions Positions
Returns
reference to itself
Exceptions
IllegalInnerState thrown when some of Positions are already set
InvalidCoordinate thrown when some of values are not valid players/strategies names
Implements GT::Model::DataBuilder.
Definition at line 106 of file game_builder.hpp.
                {
         return *this;
     }
virtual GamePtr GT::Model::NullGameBuilder::build () const inline override virtual
Builds Game.
Returns
Game
Implements GT::Model::GameBuilder.
Definition at line 122 of file game_builder.hpp.
References GT::Model::NullFactory::createGame(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createGame();
     }
virtual DataBuilderPtr GT::Model::NullGameBuilder::clone () const inline override virtual
Clones DataBuilder for recursive building.
Returns
DataBuilder clone
Implements GT::Model::DataBuilder.
Definition at line 126 of file game_builder.hpp.
References GT::Model::NullFactory::createDataBuilder(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createDataBuilder();
     }
virtual GameBuilderPtr GT::Model::NullGameBuilder::cloneBuilder () const inline override virtual
Returns new copy of this GameBuilder's type.
Returns
GameBuilder
Implements GT::Model::GameBuilder.
Definition at line 130 of file game_builder.hpp.
References GT::Model::NullFactory::createGameBuilder(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createGameBuilder();
     }
virtual DataBuilderPtr GT::Model::NullGameBuilder::dataBuilder () const inline override virtual
Returns inner DataBuilder.
Returns
DataBuilder
Implements GT::Model::GameBuilder.
Definition at line 118 of file game_builder.hpp.
References GT::Model::NullFactory::createDataBuilder(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createDataBuilder();
     }
virtual const PlayersPtr GT::Model::NullGameBuilder::getPlayers () const inline override virtual
Returns Players' definitions.
Returns
Players' definitions
Implements GT::Model::GameBuilder.
Definition at line 96 of file game_builder.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual bool GT::Model::NullGameBuilder::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 134 of file game_builder.hpp.
{
         return false;
     }
virtual DataBuilder& GT::Model::NullGameBuilder::setPayoffs (const NumbersPtr params) inline override virtual
Sets Params with values.
Parameters
params Params
Returns
reference to itself
Exceptions
IllegalInnerState thrown when attempting to set Params when not all coordinates are known
Implements GT::Model::DataBuilder.
Definition at line 112 of file game_builder.hpp.
                {
         return *this;
     }
virtual DataBuilder& GT::Model::NullGameBuilder::setPlayers (const PlayersPtr players) inline override virtual
Sets Players defined for Game.
Parameters
players Players
Returns
reference to itself
Exceptions
IllegalInnerState thrown when Players are already set or Players or their Strategies are not unique
Implements GT::Model::DataBuilder.
Definition at line 100 of file game_builder.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullGameBuilder::toString () const inline override virtual
DataBuilder's Message.
Returns
Message
Implements GT::Model::DataBuilder.
Definition at line 138 of file game_builder.hpp.
{
         return Message("NullGameBuilder");
     }
The documentation for this class was generated from the following file:
include/gt/model/game_builder.hpp