Game Theory Tools (full documentation): GT::Model::NullStrategicData Class Reference
GT::Model::NullStrategicData Class Reference final
Null StrategicData for handling invalid situations.
#include <strategic_data.hpp>
Public Member Functions
NullStrategicData ()
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual const DataPiecePtr getPayoffs (const Index) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const Positions &) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const PositionsPtr) const override
Returns DataPiece that gives access to payoffs.
virtual Data & setPayoffs (const Index, const NumbersPtr) override
Sets Positions to contains given payoffs.
virtual Data & setPayoffs (const Positions &, const NumbersPtr) override
Sets Positions to contains given payoffs.
virtual Data & setPayoffs (const PositionsPtr, const NumbersPtr) override
Sets Positions to contains given payoffs.
virtual Index getUpperBound () const override
Returns upport bound of index for accessing data via position in storage.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns StrategicData Message.
virtual const DataPiecePtr operator[] (const Index) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const Positions &) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const PositionsPtr) const override
Returns DataPiece that gives access to payoffs.
Public Member Functions inherited from GT::Model::StrategicData
StrategicData (const PlayersPtr playersDefinitions)
Initiates Data with Players' definitions.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Null StrategicData for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 214 of file strategic_data.hpp.
Constructor & Destructor Documentation
GT::Model::NullStrategicData::NullStrategicData () inline
Definition at line 216 of file strategic_data.hpp.
                         :
         StrategicData(NullFactory::getInstance().createPlayers())
         {}
Member Function Documentation
virtual const DataPiecePtr GT::Model::NullStrategicData::getPayoffs (const Index positionInStorage) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positionInStorage Index of positon in payoff storage according to StrategicGamePositionsHelper
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 224 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullStrategicData::getPayoffs (const Positions & positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 230 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullStrategicData::getPayoffs (const PositionsPtr positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 236 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const PlayersPtr GT::Model::NullStrategicData::getPlayers () const inline override virtual
Returns Players' definitions.
Returns
Players' definitions
Reimplemented from GT::Model::StrategicData.
Definition at line 220 of file strategic_data.hpp.
References GT::Model::NullFactory::createPlayers(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayers();
     }
virtual Index GT::Model::NullStrategicData::getUpperBound () const inline override virtual
Returns upport bound of index for accessing data via position in storage.
Returns
upper bound of positions in storage (highest available Index is upper bound - 1)
Reimplemented from GT::Model::StrategicData.
Definition at line 263 of file strategic_data.hpp.
{
         return 0;
     }
virtual bool GT::Model::NullStrategicData::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 267 of file strategic_data.hpp.
{
         return false;
     }
virtual const DataPiecePtr GT::Model::NullStrategicData::operator[] (const Index positionInStorage) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positionInStorage Index of positon in payoff storage according to StrategicGamePositionsHelper
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 275 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullStrategicData::operator[] (const Positions & positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 281 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual const DataPiecePtr GT::Model::NullStrategicData::operator[] (const PositionsPtr positions) const inline override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented from GT::Model::StrategicData.
Definition at line 287 of file strategic_data.hpp.
References GT::Model::NullFactory::createDataPiece(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createDataPiece();
     }
virtual Data& GT::Model::NullStrategicData::setPayoffs (const Index positionInStorage, const NumbersPtr numbers) inline override virtual
Sets Positions to contains given payoffs.
Parameters
positionInStorage Index of position in payoff storage
numbers payoffs values
Returns
reference to itself for chaining
Exceptions
InvalidCoordinate thrown when Index in not in allowed range
Reimplemented from GT::Model::StrategicData.
Definition at line 242 of file strategic_data.hpp.
                {
         return *this;
     }
virtual Data& GT::Model::NullStrategicData::setPayoffs (const Positions & positions, const NumbersPtr numbers) inline override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Reimplemented from GT::Model::StrategicData.
Definition at line 249 of file strategic_data.hpp.
                {
         return *this;
     }
virtual Data& GT::Model::NullStrategicData::setPayoffs (const PositionsPtr positions, const NumbersPtr numbers) inline override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Reimplemented from GT::Model::StrategicData.
Definition at line 256 of file strategic_data.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullStrategicData::toString () const inline override virtual
Returns StrategicData Message.
Returns
Message
Reimplemented from GT::Model::StrategicData.
Definition at line 271 of file strategic_data.hpp.
{
         return Message("NullStrategicData");
     }
The documentation for this class was generated from the following file:
src/gt/model/strategic_data.hpp