Game Theory Tools (full documentation): GT::Routines::ExceptionFactory Class Reference
GT::Routines::ExceptionFactory Class Reference final
Used for creation of exception instances for Routines classes.
#include <exception_factory.hpp>
Public Member Functions
InvalidCondition invalidCondition (const std::exception &exception) const
Thrown when Condition is invalid for some Routine.
InvalidCondition contradictoryConditions () const
Thrown when Conditions create invalid RoutineConfig.
InvalidGameType invalidGameType (const Identifier &expectedGame) const
Thrown when Condition is invalid for some Routine.
InvalidPlayerChoice playerNotFound (const Identifier &playerName) const
Thrown when non existing Player is chosen.
InvalidPlayerChoice informationSetNotFound (const Identifier &playerName, const Identifier &informationSet) const
Thrown when non existing information set is chosen.
InvalidPlayerChoice strategyNotFound (const Identifier &playerName, const Identifier &strategy) const
Thrown when non existing strategy is chosen.
IncompletePayoffInformation incompletePayoffInformation (const Identifier &playerName, const Identifier &strategy) const
Thrown when payoff is not available for some Player's strategy.
Static Public Member Functions
static ExceptionFactory & getInstance ()
Returns the instance of an ExceptionFactory.
Private Member Functions
ExceptionFactory ()=default
Default constructor hidden from programmers.
ExceptionFactory (const ExceptionFactory &exceptionFactory)=delete
Default copy constructor hidden from programmers.
~ExceptionFactory ()=default
Default destructor hidden from programmers.
Detailed Description
Used for creation of exception instances for Routines classes.
Author
Mateusz Kubuszok
Definition at line 37 of file exception_factory.hpp.
Constructor & Destructor Documentation
GT::Routines::ExceptionFactory::ExceptionFactory () private default
Default constructor hidden from programmers.
GT::Routines::ExceptionFactory::ExceptionFactory (const ExceptionFactory & exceptionFactory) private delete
Default copy constructor hidden from programmers.
Parameters
exceptionFactory object to copy
GT::Routines::ExceptionFactory::~ExceptionFactory () private default
Default destructor hidden from programmers.
Member Function Documentation
InvalidCondition GT::Routines::ExceptionFactory::contradictoryConditions () const
Thrown when Conditions create invalid RoutineConfig.
Returns
InvalidCondition exception to throw
Definition at line 50 of file exception_factory.cpp.
Referenced by GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor(), and GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen().
{
     return InvalidCondition("Contradictory conditions lead to an invalid configuration");
 }
ExceptionFactory & GT::Routines::ExceptionFactory::getInstance () static
Returns the instance of an ExceptionFactory.
Returns
ExceptionFactory instance
Definition at line 35 of file exception_factory.cpp.
Referenced by GT::Routines::ExtensivePureStrategyPath::addPlayerChoice(), GT::Routines::PlayerChoiceCondition::configureRoutine(), GT::Routines::PlayerRangeCondition::configureRoutine(), GT::Routines::InformationSetRangeCondition::configureRoutine(), GT::Routines::InformationSetChoiceCondition::configureRoutine(), GT::Routines::MatrixMixedEquilibriumRoutine::findResultFor(), GT::Routines::BimatrixMixedEquilibriumRoutine::findResultFor(), GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor(), GT::Routines::PlayerChoiceRoutineConfig::getAvailableStrategies(), GT::Routines::InformationSetChoiceRoutineConfig::getAvailableStrategies(), and GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen().
{
     static ExceptionFactory instance;
     return instance;
 }
IncompletePayoffInformation GT::Routines::ExceptionFactory::incompletePayoffInformation (const Identifier & playerName, const Identifier & strategy) const
Thrown when payoff is not available for some Player's strategy.
Parameters
playerName name of Player
strategy name of strategy
Returns
IncompletePayoffInformation exception to throw
Definition at line 96 of file exception_factory.cpp.
Referenced by GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen().
         {
     stringstream result;
     result << "There is no Payoff information about \"" << strategy
            << "\" for player \"" <<  playerName << "\"";
     return IncompletePayoffInformation(result.str());
 }
InvalidPlayerChoice GT::Routines::ExceptionFactory::informationSetNotFound (const Identifier & playerName, const Identifier & informationSet) const
Thrown when non existing information set is chosen.
Parameters
playerName name of Player
informationSet name of sought information set
Returns
InvalidPlayerChoice exception to throw
Definition at line 85 of file exception_factory.cpp.
Referenced by GT::Routines::InformationSetChoiceRoutineConfig::getAvailableStrategies().
         {
     stringstream result;
     result << "There is no information set \"" << informationSet << "\" for player \"" <<  playerName << "\"";
     return InvalidPlayerChoice(result.str());
 }
InvalidCondition GT::Routines::ExceptionFactory::invalidCondition (const std::exception & exception) const
Thrown when Condition is invalid for some Routine.
Parameters
exception exception to pass
Returns
InvalidCondition exception to throw
Definition at line 40 of file exception_factory.cpp.
Referenced by GT::Routines::PlayerChoiceCondition::configureRoutine(), GT::Routines::PlayerRangeCondition::configureRoutine(), GT::Routines::InformationSetChoiceCondition::configureRoutine(), and GT::Routines::InformationSetRangeCondition::configureRoutine().
         {
     stringstream result;
     result << "Invalid Condition: " << exception.what();
     return InvalidCondition(result.str());
 }
InvalidGameType GT::Routines::ExceptionFactory::invalidGameType (const Identifier & expectedGame) const
Thrown when Condition is invalid for some Routine.
Parameters
expectedGame expected Game type
Returns
InvalidGameType exception to throw
Definition at line 54 of file exception_factory.cpp.
Referenced by GT::Routines::MatrixMixedEquilibriumRoutine::findResultFor(), GT::Routines::BimatrixMixedEquilibriumRoutine::findResultFor(), GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), and GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor().
         {
     stringstream result;
     result << "Invalid Game Type: " << expectedGame << " expected" ;
     return InvalidGameType(result.str());
 }
InvalidPlayerChoice GT::Routines::ExceptionFactory::playerNotFound (const Identifier & playerName) const
Thrown when non existing Player is chosen.
Parameters
playerName name of sought Player
Returns
InvalidPlayerChoice exception to throw
Definition at line 64 of file exception_factory.cpp.
Referenced by GT::Routines::ExtensivePureStrategyPath::addPlayerChoice(), GT::Routines::PlayerChoiceRoutineConfig::getAvailableStrategies(), GT::Routines::InformationSetChoiceRoutineConfig::getAvailableStrategies(), and GT::Routines::ExtensivePureEquilibriumRoutine::getBestPayoffWhen().
         {
     stringstream result;
     result << "Player \"" << playerName << "\" do not exists";
     return InvalidPlayerChoice(result.str());
 }
InvalidPlayerChoice GT::Routines::ExceptionFactory::strategyNotFound (const Identifier & playerName, const Identifier & strategy) const
Thrown when non existing strategy is chosen.
Parameters
playerName name of Player
strategy name of strategy
Returns
InvalidPlayerChoice exception to throw
Definition at line 74 of file exception_factory.cpp.
Referenced by GT::Routines::ExtensivePureStrategyPath::addPlayerChoice().
         {
     stringstream result;
     result << "There is no strategy \"" << strategy << "\" for player \"" <<  playerName << "\"";
     return InvalidPlayerChoice(result.str());
 }
The documentation for this class was generated from the following files:
src/gt/routines/exception_factory.hpp
src/gt/routines/exception_factory.cpp