Game Theory Tools (full documentation): GT::Model::ResultFactory Class Reference
GT::Model::ResultFactory Class Reference final
Creates some simple Results as well as supplies builders for more complex of them.
#include <result_factory.hpp>
Public Member Functions
ResultBuilderPtr buildResult () const
Returns ResultBuilder.
ResultPtr constResult (const Message &content) const
Returns Results with predefined const content.
ResultPtr emptyResult () const
Returns empty Result.
ResultBuilderMode getBuilderMode () const
Returns current builder mode.
ResultFactory & setBuilderMode (const ResultBuilderMode builderMode)
Sets current builder mode.
ResultIndentationMode getIndentationMode () const
Returns current indentation mode.
ResultFactory & setIndentationMode (const ResultIndentationMode indentationMode)
Sets current indentation mode.
Static Public Member Functions
static ResultFactory & getInstance ()
Returns the instance of a ResultFactory.
Private Member Functions
ResultFactory ()
Private constructor.
ResultFactory (const ResultFactory &resultFactory)=delete
Private copy constructor.
~ResultFactory ()=default
Private destructor.
Private Attributes
ResultBuilderMode builderMode
Contains current Builder Mode setting.
ResultIndentationMode indentationMode
Contains current Indentation Mode setting.
Detailed Description
Creates some simple Results as well as supplies builders for more complex of them.
The type of ResultBuilder returned by factory is determined by builderMode settings.
Author
Mateusz Kubuszok
See Also
Result
ResultBuilder
Definition at line 60 of file result_factory.hpp.
Constructor & Destructor Documentation
GT::Model::ResultFactory::ResultFactory () private
Private constructor.
Definition at line 94 of file result_factory.cpp.
References builderMode, indentationMode, GT::Model::PLAIN, and GT::Model::TABS.
{
     builderMode     = ResultBuilderMode::PLAIN;
     indentationMode = ResultIndentationMode::TABS;
 }
GT::Model::ResultFactory::ResultFactory (const ResultFactory & resultFactory) private delete
Private copy constructor.
GT::Model::ResultFactory::~ResultFactory () private default
Private destructor.
Member Function Documentation
ResultBuilderPtr GT::Model::ResultFactory::buildResult () const
Returns ResultBuilder.
Returns
ResultBuilder
Definition at line 36 of file result_factory.cpp.
References builderMode, indentationMode, GT::Model::JSON, GT::Model::NONE, GT::Model::PLAIN, GT::Model::SPACES, GT::Model::TABS, and GT::Model::XML.
Referenced by GT::GTL::Query::execute(), GT::GTL::ExecutionDriver::execute(), GT::GTL::ExecutionStatementDriver::executeDefinition(), GT::GTL::ObjectKnownProperties::findForConditions(), GT::GTL::ObjectTypeProperty::findForConditions(), GT::GTL::ParamKnownProperties::findForConditions(), GT::GTL::PlayerNameProperty::findForConditions(), GT::GTL::PlayerStrategiesProperty::findForConditions(), GT::GTL::CurrentContextValuesProperty::findForConditions(), GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor(), GT::GTL::ExecutionDriver::load(), GT::GTL::ExecutionDriver::save(), GT::GTL::CheckingDriver::showError(), GT::Routines::MatrixMixedEquilibriumRoutine::solveProblem(), GT::Routines::BimatrixMixedEquilibriumRoutine::solveProblem(), GT::GTL::PlayerChoiceCondition::toString(), GT::GTL::PlayerRangeCondition::toString(), GT::Routines::PlayerChoiceCondition::toString(), GT::Routines::PlayerRangeCondition::toString(), GT::GTL::InformationSetChoiceCondition::toString(), GT::GTL::InformationSetRangeCondition::toString(), GT::Routines::InformationSetChoiceCondition::toString(), GT::Routines::InformationSetRangeCondition::toString(), GT::Model::StrategicGame::toString(), GT::GTL::Details::toString(), GT::GTL::Definition::toString(), GT::Model::ExtensiveGame::toString(), GT::Model::PlainDataPiece::toString(), GT::GTL::Query::toString(), GT::GTL::NumberParam::toString(), GT::GTL::ObjectParam::toString(), GT::GTL::IdentifierParam::toString(), GT::Routines::ExtensivePureStrategyPath::toString(), GT::Model::ExtensiveGameBuilder::toString(), GT::Model::ExtensiveDataAccessor::toString(), GT::Model::StrategicGameBuilder::toString(), GT::Model::ExtensiveDataBuilder::toString(), GT::Model::StrategicDataBuilder::toString(), GT::Model::Player::toString(), GT::Model::StrategicDataAccessor::toString(), GT::Model::ExtensiveData::toString(), GT::Model::StrategicGamePositionsHelper::toString(), GT::GTL::Coordinate::toString(), GT::Model::ExtensiveDataNode::toString(), GT::Model::StrategicData::toString(), and GT::GTL::Context::toString().
{
     Message indent;
     switch (indentationMode) {
     case ResultIndentationMode::TABS:
         indent = Message("\t");
         break;
     case ResultIndentationMode::SPACES:
         indent = Message(" ");
     case ResultIndentationMode::NONE:
     default:
         break;
     }
     switch (builderMode) {
     case ResultBuilderMode::JSON:
         return ResultBuilderPtr(new JSONResultBuilder(indent));
     case ResultBuilderMode::XML:
         return ResultBuilderPtr(new XMLResultBuilder(indent));
     case ResultBuilderMode::PLAIN:
     default:
         return ResultBuilderPtr(new PlainResultBuilder(indent));
     }
 }
ResultPtr GT::Model::ResultFactory::constResult (const Message & content) const
Returns Results with predefined const content.
Parameters
content content to be contained by the Result
Returns
Result with constant content
Definition at line 60 of file result_factory.cpp.
Referenced by GT::Model::JSONResultBuilder::build(), GT::Model::JSONResultBuilder::buildRaw(), GT::Model::PlainResultBuilder::buildRaw(), GT::GTL::ParamValueProperty::findForConditions(), GT::Routines::NotYetImplementedRoutine::findResultFor(), GT::Routines::PropertyUndefinedRoutine::findResultFor(), GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), GT::GTL::GameMixedEquilibriumProperty::getDescription(), GT::GTL::ObjectTypeProperty::getDescription(), GT::GTL::PlayerStrategiesProperty::getDescription(), GT::GTL::PlayerNameProperty::getDescription(), GT::GTL::ParamKnownProperties::getDescription(), GT::GTL::GameBehaviorEquilibriumProperty::getDescription(), GT::GTL::CurrentContextValuesProperty::getDescription(), GT::GTL::GamePureEquilibriumProperty::getDescription(), GT::GTL::ObjectKnownProperties::getDescription(), GT::GTL::ParamValueProperty::getDescription(), GT::Routines::MatrixMixedEquilibriumRoutine::solveProblem(), and GT::Routines::BimatrixMixedEquilibriumRoutine::solveProblem().
         {
     return ResultPtr(new ConstResult(content));
 }
ResultPtr GT::Model::ResultFactory::emptyResult () const
Returns empty Result.
Returns
an empty result
Definition at line 66 of file result_factory.cpp.
{
     return ResultPtr(new EmptyResult());
 }
ResultBuilderMode GT::Model::ResultFactory::getBuilderMode () const
Returns current builder mode.
Returns
currently used builder mode
Definition at line 70 of file result_factory.cpp.
References builderMode.
{
     return builderMode;
 }
ResultIndentationMode GT::Model::ResultFactory::getIndentationMode () const
Returns current indentation mode.
Returns
currently used indentation mode
Definition at line 81 of file result_factory.cpp.
References indentationMode.
{
     return indentationMode;
 }
ResultFactory & GT::Model::ResultFactory::getInstance () static
Returns the instance of a ResultFactory.
Returns
ResultFactory instance
Definition at line 31 of file result_factory.cpp.
Referenced by GT::Model::JSONResultBuilder::build(), GT::Model::JSONResultBuilder::buildRaw(), GT::Model::PlainResultBuilder::buildRaw(), GT::GTL::Query::execute(), GT::GTL::ExecutionDriver::execute(), GT::GTL::ExecutionStatementDriver::executeDefinition(), GT::GTL::PlayerNameProperty::findForConditions(), GT::GTL::PlayerStrategiesProperty::findForConditions(), GT::GTL::CurrentContextValuesProperty::findForConditions(), GT::GTL::ObjectKnownProperties::findForConditions(), GT::GTL::ObjectTypeProperty::findForConditions(), GT::GTL::ParamKnownProperties::findForConditions(), GT::GTL::ParamValueProperty::findForConditions(), GT::Routines::NotYetImplementedRoutine::findResultFor(), GT::Routines::PropertyUndefinedRoutine::findResultFor(), GT::Routines::StrategicPureEquilibriumRoutine::findResultFor(), GT::Routines::ExtensivePureEquilibriumRoutine::findResultFor(), GT::GTL::ParamValueProperty::getDescription(), GT::GTL::CurrentContextValuesProperty::getDescription(), GT::GTL::PlayerNameProperty::getDescription(), GT::GTL::PlayerStrategiesProperty::getDescription(), GT::GTL::ObjectKnownProperties::getDescription(), GT::GTL::GameMixedEquilibriumProperty::getDescription(), GT::GTL::ObjectTypeProperty::getDescription(), GT::GTL::GameBehaviorEquilibriumProperty::getDescription(), GT::GTL::ParamKnownProperties::getDescription(), GT::GTL::GamePureEquilibriumProperty::getDescription(), GT::GTL::ExecutionDriver::load(), GT::GTL::ExecutionDriver::save(), GT::GTL::CheckingDriver::showError(), GT::Routines::MatrixMixedEquilibriumRoutine::solveProblem(), GT::Routines::BimatrixMixedEquilibriumRoutine::solveProblem(), GT::GTL::PlayerRangeCondition::toString(), GT::GTL::PlayerChoiceCondition::toString(), GT::Routines::PlayerChoiceCondition::toString(), GT::Routines::PlayerRangeCondition::toString(), GT::GTL::InformationSetChoiceCondition::toString(), GT::GTL::InformationSetRangeCondition::toString(), GT::Routines::InformationSetChoiceCondition::toString(), GT::Routines::InformationSetRangeCondition::toString(), GT::Model::StrategicGame::toString(), GT::GTL::Details::toString(), GT::GTL::Definition::toString(), GT::Model::ExtensiveGame::toString(), GT::Model::PlainDataPiece::toString(), GT::GTL::Query::toString(), GT::GTL::NumberParam::toString(), GT::GTL::ObjectParam::toString(), GT::GTL::IdentifierParam::toString(), GT::Routines::ExtensivePureStrategyPath::toString(), GT::Model::StrategicGameBuilder::toString(), GT::Model::ExtensiveGameBuilder::toString(), GT::Model::ExtensiveDataAccessor::toString(), GT::Model::ExtensiveDataBuilder::toString(), GT::Model::StrategicDataBuilder::toString(), GT::Model::Player::toString(), GT::Model::StrategicDataAccessor::toString(), GT::Model::ExtensiveData::toString(), GT::Model::StrategicGamePositionsHelper::toString(), GT::GTL::Coordinate::toString(), GT::Model::ExtensiveDataNode::toString(), GT::Model::StrategicData::toString(), and GT::GTL::Context::toString().
{
     static ResultFactory instance;
     return instance;
 }
ResultFactory & GT::Model::ResultFactory::setBuilderMode (const ResultBuilderMode builderMode)
Sets current builder mode.
Parameters
builderMode new builder mode
Returns
ResultsFactory for chaining
Definition at line 74 of file result_factory.cpp.
References builderMode.
   {
     builderMode = newBuilderMode;
     return *this;
 }
ResultFactory & GT::Model::ResultFactory::setIndentationMode (const ResultIndentationMode indentationMode)
Sets current indentation mode.
Parameters
indentationMode new indentation mode
Returns
ResultsFactory for chaining
Definition at line 85 of file result_factory.cpp.
References indentationMode.
   {
     indentationMode = newIndentationMode;
     return *this;
 }
Member Data Documentation
ResultBuilderMode GT::Model::ResultFactory::builderMode private
Contains current Builder Mode setting.
Definition at line 64 of file result_factory.hpp.
Referenced by buildResult(), getBuilderMode(), ResultFactory(), and setBuilderMode().
ResultIndentationMode GT::Model::ResultFactory::indentationMode private
Contains current Indentation Mode setting.
Definition at line 69 of file result_factory.hpp.
Referenced by buildResult(), getIndentationMode(), ResultFactory(), and setIndentationMode().
The documentation for this class was generated from the following files:
include/gt/model/result_factory.hpp
src/gt/model/result_factory.cpp