Game Theory Tools (full documentation): GT::Routines::InformationSetChoiceCondition Class Reference
GT::Routines::InformationSetChoiceCondition Class Reference final
Condition that configures Routine to allow only one choice from some Player's information set.
#include <information_set_choice_condition.hpp>
Public Member Functions
InformationSetChoiceCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifierPtr strategy)
Initiates Condition with Player's and information set's names and chosen strategy.
virtual void configureRoutine (RoutineConfigPtr routineConfig) const override
Configureg given RoutineConfig.
virtual Message toString () const override
Returns Condition's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const IdentifierPtr player
Player's name.
const IdentifierPtr informationSet
Information set's name.
const IdentifierPtr strategy
Chosen strategy.
Detailed Description
Condition that configures Routine to allow only one choice from some Player's information set.
Author
Mateusz Kubuszok
See Also
InformationSetChoiceRoutineConfig
Definition at line 39 of file information_set_choice_condition.hpp.
Constructor & Destructor Documentation
GT::Routines::InformationSetChoiceCondition::InformationSetChoiceCondition (const IdentifierPtr player, const IdentifierPtr informationSet, const IdentifierPtr strategy)
Initiates Condition with Player's and information set's names and chosen strategy.
Parameters
player Player that chooses strategy
informationSet information set
strategy chosen strategy
Definition at line 35 of file information_set_choice_condition.cpp.
   :
     player(definedPlayer),
     informationSet(definedInformationSet),
     strategy(definedStrategy)
     {}
Member Function Documentation
void GT::Routines::InformationSetChoiceCondition::configureRoutine (RoutineConfigPtr routineConfig) const override virtual
Configureg given RoutineConfig.
Parameters
routineConfig RoutineConfig to set up
Exceptions
InvalidCondition thrown when Condition is invalid
Implements GT::Routines::Condition.
Definition at line 45 of file information_set_choice_condition.cpp.
References GT::Routines::ExceptionFactory::getInstance(), informationSet, GT::Routines::ExceptionFactory::invalidCondition(), player, GT::Routines::InformationSetChoiceRoutineConfig::requireChoiceExactly(), and strategy.
         {
     InformationSetChoiceRoutineConfigPtr specificConfig =
         dynamic_pointer_cast<InformationSetChoiceRoutineConfig>(routineConfig);
     if (!specificConfig)
         return;
     try {
         specificConfig->requireChoiceExactly(*player, *informationSet, *strategy);
     } catch (const InvalidPlayerChoice& e) {
         throw ExceptionFactory::getInstance().invalidCondition(e);
     }
 }
Message GT::Routines::InformationSetChoiceCondition::toString () const override virtual
Returns Condition's Message.
Returns
Condition's Message
Implements GT::Routines::Condition.
Definition at line 61 of file information_set_choice_condition.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), informationSet, player, and strategy.
{
     MessagePtr strategyName = createMessagePtr(strategy);
     MessagePtr setValue     = createMessagePtr(
         ResultFactory::getInstance()
         .buildResult()->addResult(informationSet, strategyName)
         .build()->getResult()
     );
     return ResultFactory::getInstance().buildResult()->addResult(player, setValue).build()->getResult();
 }
Member Data Documentation
const IdentifierPtr GT::Routines::InformationSetChoiceCondition::informationSet private
Information set's name.
Definition at line 47 of file information_set_choice_condition.hpp.
Referenced by configureRoutine(), and toString().
const IdentifierPtr GT::Routines::InformationSetChoiceCondition::player private
Player's name.
Definition at line 43 of file information_set_choice_condition.hpp.
Referenced by configureRoutine(), and toString().
const IdentifierPtr GT::Routines::InformationSetChoiceCondition::strategy private
Chosen strategy.
Definition at line 51 of file information_set_choice_condition.hpp.
Referenced by configureRoutine(), and toString().
The documentation for this class was generated from the following files:
src/gt/routines/information_set_choice_condition.hpp
src/gt/routines/information_set_choice_condition.cpp