Game Theory Tools (public API): GT::GTL::NullContext Class Reference
GT::GTL::NullContext Class Reference final
Null Context for handling invalid situations.
#include <context.hpp>
Public Member Functions
virtual Context & registerParam (const IdentifierPtr, const ParamPtr) override
Adds/overrides identifier with value.
virtual Context & registerParam (const DefinitionPtr) override
Adds/overrides identifier with value.
virtual const NumberPtr getNumber (const Identifier &) const override
Obtains value from context by identifer.
virtual const ObjectPtr getObject (const Identifier &) const override
Obtains value from context by identifer.
virtual const ParamPtr getParam (const Identifier &) const override
Obtains param from context by identifer.
virtual Message serialize () const override
Returns serialized Message for a Context.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
Returns Message about Context.
Public Member Functions inherited from GT::GTL::Context
Context ()
Default constructor.
Context (const ContextPtr parentContext)
Constructor with parental context inheritance.
virtual ~Context ()
Default destructor.
virtual bool hasRegistered (const Identifier &identifier) const
Returns true if Identifier has been registed.
virtual const KnownObjects getKnownObjects () const
Returns map of KnownObjects.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Public Types inherited from GT::GTL::Context
typedef map< Identifier, ParamPtr > KnownObjects
Known objects map.
Detailed Description
Null Context for handling invalid situations.
Author
Mateusz Kubuszok
Definition at line 185 of file context.hpp.
Member Function Documentation
virtual const NumberPtr GT::GTL::NullContext::getNumber (const Identifier & identifier) const inline override virtual
Obtains value from context by identifer.
Parameters
identifier identifier to obtain
Returns
value to retur
Reimplemented from GT::GTL::Context.
Definition at line 200 of file context.hpp.
References GT::Model::NullFactory::createNumber(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumber();
     }
virtual const ObjectPtr GT::GTL::NullContext::getObject (const Identifier & identifier) const inline override virtual
Obtains value from context by identifer.
Parameters
identifier identifier to obtain
Returns
value to retur
Reimplemented from GT::GTL::Context.
Definition at line 206 of file context.hpp.
References GT::GTL::NullFactory::createObject(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createObject();
     }
virtual const ParamPtr GT::GTL::NullContext::getParam (const Identifier & identifier) const inline override virtual
Obtains param from context by identifer.
If Object is not a Param then exception will be thrown.
Parameters
identifier param to obtain
Returns
value to retur
Reimplemented from GT::GTL::Context.
Definition at line 212 of file context.hpp.
References GT::GTL::NullFactory::createParam(), and GT::GTL::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createParam();
     }
virtual bool GT::GTL::NullContext::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 222 of file context.hpp.
{
         return false;
     }
virtual Context& GT::GTL::NullContext::registerParam (const IdentifierPtr identifier, const ParamPtr param) inline override virtual
Adds/overrides identifier with value.
Parameters
identifier identifer to register
param new value to register
Returns
reference to context for chaining
Reimplemented from GT::GTL::Context.
Definition at line 187 of file context.hpp.
                {
         return *this;
     }
virtual Context& GT::GTL::NullContext::registerParam (const DefinitionPtr definition) inline override virtual
Adds/overrides identifier with value.
Parameters
definition definition of an Object with name
Returns
reference to context for chaining
Reimplemented from GT::GTL::Context.
Definition at line 194 of file context.hpp.
                {
         return *this;
     }
virtual Message GT::GTL::NullContext::serialize () const inline override virtual
Returns serialized Message for a Context.
Returns
serialization result
Reimplemented from GT::GTL::Context.
Definition at line 218 of file context.hpp.
{
         return Message();
     }
virtual Message GT::GTL::NullContext::toString () const inline override virtual
Returns Message about Context.
Returns
Context's Message
Reimplemented from GT::GTL::Context.
Definition at line 226 of file context.hpp.
{
         return Message("NullContext");
     }
The documentation for this class was generated from the following file:
include/gt/gtl/context.hpp