Game Theory Tools (full documentation): GT::GTL::Condition Class Reference
GT::GTL::Condition Class Reference abstract
Condition used for querying Objects with some requirements.
#include <condition.hpp>
Public Member Functions
virtual ~Condition ()
Default destructor.
virtual Routines::ConditionPtr getCondition (const Context &context) const =0
Returns Condition applicable to Routine.
virtual Message toString () const override=0
Returns Message about Condition.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Protected Member Functions
Identifier getIdentifier (const Context &context, const ObjectPtr &object) const
Obtains Identifier from Object.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Condition used for querying Objects with some requirements.
Each kind of Condition should have its own representation recognized by Parser. It should be then created by ConditionDriver (which in turn would use ConditionFactory). Conditions would be used e.g. like that:
FIND pure_equilibrium
FOR  some_game
WITH [condition1](, [condition2](, ...));
Author
Mateusz Kubuszok
See Also
ConditionDriver
ConditionFactory
Query
Parser
Definition at line 52 of file condition.hpp.
Constructor & Destructor Documentation
GT::GTL::Condition::~Condition () virtual
Default destructor.
Definition at line 36 of file condition.cpp.
 {}
Member Function Documentation
virtual Routines::ConditionPtr GT::GTL::Condition::getCondition (const Context & context) const pure virtual
Returns Condition applicable to Routine.
Parameters
context Context
Returns
Condition applicable to Routine
Exceptions
InvalidType thrown when condition make use of not accepted Objects
Implemented in GT::GTL::ErrorCondition, GT::GTL::NullCondition, GT::GTL::InformationSetChoiceCondition, GT::GTL::InformationSetRangeCondition, GT::GTL::PlayerChoiceCondition, and GT::GTL::PlayerRangeCondition.
Identifier GT::GTL::Condition::getIdentifier (const Context & context, const ObjectPtr & object) const protected
Obtains Identifier from Object.
Parameters
context Context
object Object that should contain Identifier
Returns
Identifier stored/rfered by that Object
Exceptions
InvalidType thrown when condition make use of not accepted Objects
Definition at line 40 of file condition.cpp.
References GT::createIdentifier(), GT::GTL::ExceptionFactory::getInstance(), GT::GTL::Param::getObject(), GT::GTL::ExceptionFactory::invalidObjectType(), and GT::GTL::Param::toParam().
Referenced by GT::GTL::PlayerChoiceCondition::getCondition(), GT::GTL::PlayerRangeCondition::getCondition(), GT::GTL::InformationSetChoiceCondition::getCondition(), and GT::GTL::InformationSetRangeCondition::getCondition().
         {
     const Param& param = object->toParam();
     if (!param) {
         static const Identifier expectedType = createIdentifier("Param");
         throw ExceptionFactory::getInstance().invalidObjectType(expectedType);
     }
     shared_ptr<IdentifierParam> identifierParam;
     try {
         identifierParam = dynamic_pointer_cast<IdentifierParam>( param.getObject(context) );
     } catch (const InvalidContentRequest& e) {
         identifierParam = dynamic_pointer_cast<IdentifierParam>( object );
     } catch (const NotDefinedParam& e) {
         identifierParam = dynamic_pointer_cast<IdentifierParam>( object );
     }
     if (!identifierParam) {
         static const Identifier expectedType = createIdentifier("Identifier Param");
         throw ExceptionFactory::getInstance().invalidObjectType(expectedType);
     }
     return identifierParam->getIdentifier();
 }
virtual Message GT::GTL::Condition::toString () const override pure virtual
Returns Message about Condition.
Returns
Condition's Message
Implements GT::Model::Root.
Implemented in GT::GTL::ErrorCondition, GT::GTL::NullCondition, GT::GTL::InformationSetChoiceCondition, GT::GTL::InformationSetRangeCondition, GT::GTL::PlayerChoiceCondition, and GT::GTL::PlayerRangeCondition.
Referenced by GT::GTL::CheckingStatementDriver::createQuery().
The documentation for this class was generated from the following files:
include/gt/gtl/condition.hpp
src/gt/gtl/condition.cpp