Game Theory Tools (full documentation): GT::Model::DataPiece Class Reference
GT::Model::DataPiece Class Reference abstract
Interface for accessing Data coordinates for better access to values.
#include <data_piece.hpp>
Public Member Functions
virtual const NumberPtr & getPayoff (const Identifier &playerName) const =0
Returns Player's payoff by its name.
const NumberPtr & getPayoff (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
virtual bool is0Sum () const =0
Returns whether this Data piece is 0-sum one.
const NumberPtr & operator[] (const Identifier &playerName) const
Returns Player's payoff by its name.
const NumberPtr & operator[] (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
virtual Message toString () const =0
Returns DataPiece's message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Detailed Description
Interface for accessing Data coordinates for better access to values.
Author
Mateusz Kubuszok
Definition at line 37 of file data_piece.hpp.
Member Function Documentation
virtual const NumberPtr& GT::Model::DataPiece::getPayoff (const Identifier & playerName) const pure virtual
Returns Player's payoff by its name.
Parameters
playerName name of Player for which payoff is required
Returns
value of a payoff
Exceptions
InvalidCoordinate thrown when Player name is not known
Implemented in GT::Model::NullDataPiece, and GT::Model::PlainDataPiece.
Referenced by getPayoff(), and operator[]().
const NumberPtr & GT::Model::DataPiece::getPayoff (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
Parameters
playerName name of Player for which payoff is required
Returns
value of a payoff
Exceptions
InvalidCoordinate thrown when Player name is not known
Definition at line 31 of file data_piece.cpp.
References getPayoff().
         {
     return getPayoff(*playerName);
 }
virtual bool GT::Model::DataPiece::is0Sum () const pure virtual
Returns whether this Data piece is 0-sum one.
DataPiece is 0-sum if it's defined for 2 Players with 1 Payoff (first Player's one) or if sum of Payoffs is equal to 0.
Returns
true if it is 0-sum data piece
Implemented in GT::Model::NullDataPiece, and GT::Model::PlainDataPiece.
const NumberPtr & GT::Model::DataPiece::operator[] (const Identifier & playerName) const
Returns Player's payoff by its name.
Parameters
playerName name of Player for which payoff is required
Returns
value of a payoff
Exceptions
InvalidCoordinate thrown when Player name is not known
Definition at line 37 of file data_piece.cpp.
References getPayoff().
         {
     return getPayoff(playerName);
 }
const NumberPtr & GT::Model::DataPiece::operator[] (const IdentifierPtr playerName) const
Returns Player's payoff by its name.
Parameters
playerName name of Player for which payoff is required
Returns
value of a payoff
Exceptions
InvalidCoordinate thrown when Player name is not known
Definition at line 43 of file data_piece.cpp.
References getPayoff().
         {
     return getPayoff(playerName);
 }
virtual Message GT::Model::DataPiece::toString () const pure virtual
Returns DataPiece's message.
Returns
Message
Implements GT::Model::Root.
Implemented in GT::Model::NullDataPiece, and GT::Model::PlainDataPiece.
The documentation for this class was generated from the following files:
include/gt/model/data_piece.hpp
src/gt/model/data_piece.cpp