Game Theory Tools (full documentation): GT::Model::JSONResultBuilder Class Reference
GT::Model::JSONResultBuilder Class Reference final
Builder used for creating Results displayed to user in JSON format.
#include <json_result_builder.hpp>
Public Member Functions
JSONResultBuilder (const Message indentation)
Constructor initiating class with indentation.
virtual ResultPtr build () const override
Build Result.
virtual ResultPtr buildRaw () const override
Build raw Result - one that can be inserted into other results.
Public Member Functions inherited from GT::Model::AbstractResultBuilder
AbstractResultBuilder (const Message indentation)
Constructor initiating class with indentation.
virtual ResultBuilder & setHeaders (const IdentifiersPtr &propertiesNames) override
Sets headers used for displaying records.
virtual ResultBuilder & addRecord (const IdentifierPtr &name, const MessagesPtr &propertiesValues) override
Adds record to displayed Result.
virtual ResultBuilder & addResult (const IdentifierPtr &name, const MessagePtr &result) override
Adds single named subresult.
virtual Message toString () const override
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Protected Types inherited from GT::Model::AbstractResultBuilder
typedef std::pair
< IdentifierPtr, MessagesPtr > PartialResult
Type containing name-properties pair.
typedef
boost::container::vector
< PartialResult > PartialResults
Type containing name to properties mapping.
typedef std::pair
< IdentifierPtr, MessagePtr > SubResult
Type containing name-subresult pair.
typedef
boost::container::vector
< SubResult > SubResults
Type containing name to subresult mapping.
Protected Member Functions inherited from GT::Model::AbstractResultBuilder
void checkPropertyToResultMatching () const
Check whether all records has the same size as headers.
Message addIndent (const Message content) const
Adds indent to the beginning of each line of passes content.
Protected Attributes inherited from GT::Model::AbstractResultBuilder
IdentifiersPtr propertiesNames
Names of properties.
PartialResults partialResults
Values of declared properties.
SubResults subResults
SubResults.
Message indent
Indent used.
Detailed Description
Builder used for creating Results displayed to user in JSON format.
Implements ResultBuilder interface via AbstractResultBuilder class.
Used when ResultFactory's BuilderMode is set to BuilderMode::JSON.
Indentation depends on ResultFactory's IndentationMode.
Author
Mateusz Kubuszok
See Also
ResultBuilder
AbstractResultBuilder
ResultFactory::buildResult()
Definition at line 47 of file json_result_builder.hpp.
Constructor & Destructor Documentation
GT::Model::JSONResultBuilder::JSONResultBuilder (const Message indentation) explicit
Constructor initiating class with indentation.
Parameters
indentation sequence used for indentation
Definition at line 36 of file json_result_builder.cpp.
   :
     AbstractResultBuilder(indentation)
     {}
Member Function Documentation
ResultPtr GT::Model::JSONResultBuilder::build () const override virtual
Build Result.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages for any Object does not match properties' ones
See Also
buildRaw()
Implements GT::Model::AbstractResultBuilder.
Definition at line 42 of file json_result_builder.cpp.
References GT::Model::AbstractResultBuilder::addIndent(), buildRaw(), GT::Model::ResultFactory::constResult(), and GT::Model::ResultFactory::getInstance().
{
     stringstream result;
     result << '{' << endl;
     result << addIndent( buildRaw()->getResult() ) << endl;
     result << '}' << endl;
     return ResultFactory::getInstance().constResult(Message(result.str()));
 }
ResultPtr GT::Model::JSONResultBuilder::buildRaw () const override virtual
Build raw Result - one that can be inserted into other results.
Returns
Result
Exceptions
IllegalInnerState thrown when number of Messages for any Object does not match properties' ones
See Also
build()
Implements GT::Model::AbstractResultBuilder.
Definition at line 52 of file json_result_builder.cpp.
References GT::Model::AbstractResultBuilder::checkPropertyToResultMatching(), GT::Model::ResultFactory::constResult(), GT::Model::ResultFactory::getInstance(), GT::Model::AbstractResultBuilder::indent, GT::Model::AbstractResultBuilder::partialResults, GT::Model::AbstractResultBuilder::propertiesNames, and GT::Model::AbstractResultBuilder::subResults.
Referenced by build().
{
     checkPropertyToResultMatching();
     Index propertiesSize = propertiesNames->size();
     stringstream result;
     if (propertiesSize > 0) {
         bool firstPartial = true;
         for (const PartialResult& partialResult : partialResults) {
             if (!firstPartial)
                 result << ',' << endl;
             Identifier recordName = *partialResult.first;
             Messages   properties = *partialResult.second;
             result << '"' << recordName << '"' << " : [";
             bool firstProperty = true;
             for (Index property = 0; property < propertiesSize; property++) {
                 if (firstProperty)
                     result << endl;
                 else
                     result << ',' << endl;
                 Identifier propertyName  = *(*propertiesNames)[property];
                 Message    propertyValue = *(*partialResult.second)[property];
                 result << indent
                        << '"' << propertyName << '"'
                        << " : "
                        << '"' << propertyValue << '"';
                 firstProperty = false;
             }
             result << endl << ']';
             firstPartial = false;
         }
         if (!subResults.empty())
             result << ',';
     }
     if (!subResults.empty()) {
         bool firstSubResult = true;
         for (const SubResult& subResult : subResults) {
             if (firstSubResult)
                 result << endl;
             else
                 result << ',' << endl;
             Identifier resultName  = *subResult.first;
             Message    resultValue = *subResult.second;
             result << '"' << resultName << '"' << " : " << resultValue;
             firstSubResult = false;
         }
         result << endl;
     }
     return ResultFactory::getInstance().constResult(Message(result.str()));
 }
The documentation for this class was generated from the following files:
src/gt/model/json_result_builder.hpp
src/gt/model/json_result_builder.cpp