Game Theory Tools (full documentation): GT::Routines Namespace Reference
GT::Routines Namespace Reference
Contains classes related to calculating Nash equilibria for given Models.
Classes
class Condition
Condition that sets up Routine before actual calculation.
class NullCondition
Null Condition for handling invalid situations.
class ConditionFactory
Used for creation of Null instances for Routines classes.
class InvalidCondition
Intened to be thrown when Condition is in some way invalid.
class InvalidGameType
Intened to be thrown when passed Game is not allowed for such Routine.
class InvalidPlayerChoice
Intened to be thrown when non existing Player or strategy is chosen.
class IncompletePayoffInformation
Intened to be thrown when payoff for some player is not set.
class NullFactory
Used for creation of Null instances for Routines classes.
class Routine
Routine that calculates some Result e.g. Nash equilibrium.
class NullRoutine
Null Routine for handling invalid situations.
class RoutineFactory
Used for creation of Null instances for Routines classes.
class BimatrixMixedEquilibriumRoutine
Routune returning mixed strategy equilibrium for any sum Strategic Game with 2 Players.
class ExceptionFactory
Used for creation of exception instances for Routines classes.
class ExtensivePureEquilibriumRoutine
Routune returning pure strategy equilibrium for Extensive Game.
class ExtensivePureEquilibriumRoutineConfig
Contains information for ExtensivePureEquilibriumRoutine.
class ExtensivePureStrategyPath
Contains path to a payoff (with payoff).
class InformationSetChoiceCondition
Condition that configures Routine to allow only one choice from some Player's information set.
class InformationSetChoiceRoutineConfig
Contains information about available choices for each information set.
class InformationSetRangeCondition
Condition that configures Routine to allow only allowed choices for some Player's information set.
class MatrixMixedEquilibriumRoutine
Routune returning mixed strategy equilibrium for 0-sum Strategic Game with 2 Players.
class NotYetImplementedRoutine
Routine returning "Not yet implemented" Message.
class PlayerChoiceCondition
Condition that configures Routine to allow only one choice from some Player.
class PlayerChoiceRoutineConfig
Contains information about available choices for each Player.
class PlayerRangeCondition
Condition that configures Routine to allow only allowed choices for some Player.
class PropertyUndefinedRoutine
Routune returning "Property not defined for this kind of Game" Message.
class RoutineConfig
Parent of RoutineConfigs that will store configuration specific to a Routine.
class NullRoutineConfig
Null RoutineConfig for handling invalid situations.
class StrategicPureEquilibriumRoutine
Routune returning pure strategy equilibrium for Strategic Game.
class StrategicPureEquilibriumRoutineConfig
Contains information for StrategicPureEquilibriumRoutine.
Typedefs
typedef shared_ptr< Condition > ConditionPtr
Smart pointer to Condition.
typedef vector< ConditionPtr > Conditions
Vector of Conditions.
typedef shared_ptr< Conditions > ConditionsPtr
Smart pointer to Conditions.
typedef shared_ptr< Routine > RoutinePtr
Smart pointer to Routine.
typedef vector< RoutinePtr > Routines
Vector of Routines.
typedef shared_ptr< Routines > RoutinesPtr
Smart pointer to Routines.
typedef shared_ptr< RoutineConfig > RoutineConfigPtr
Smart pointer to RoutineConfig.
typedef Model::Root Root
Alias for Model::Root.
typedef Model::Game Game
Alias for Model::Game.
typedef Model::NullGame NullGame
Alias for Model::NullGame.
typedef Model::GamePtr GamePtr
Alias for Model::GamePtr.
typedef Model::Result Result
Alias for Model::Result.
typedef Model::NullResult NullResult
Alias for Model::NullResult.
typedef Model::ResultPtr ResultPtr
Alias for Model::ResultPtr.
typedef glp_prob LPProblem
Alias for GLPK's problem structure.
typedef unique_ptr< LPProblem,
void(*)(LPProblem *)> LPProblemPtr
Defines wrapper with automatic deletion for GLPK's problem structure.
typedef shared_ptr
< PlayerChoiceRoutineConfig > PlayerChoiceRoutineConfigPtr
Shared pointer to PlayerChoiceRoutineConfig.
typedef shared_ptr
< InformationSetChoiceRoutineConfig > InformationSetChoiceRoutineConfigPtr
Shared pointer to InformationSetChoiceRoutineConfig.
typedef vector
< ExtensivePureStrategyPath > ExtensivePureStrategyPaths
Vector of ExtensivePureStrategyPaths.
typedef Model::Player Player
typedef Model::PlayerPtr PlayerPtr
typedef Model::Players Players
typedef Model::PlayersPtr PlayersPtr
typedef Model::ResultFactory ResultFactory
typedef Model::ResultBuilderPtr ResultBuilderPtr
Functions
void freeGLPK ()
LPProblemPtr createLPProblem ()
Creates LPProblem instance.
Detailed Description
Contains classes related to calculating Nash equilibria for given Models.
It consists of Routines, Conditions and their factories.
Typedef Documentation
typedef shared_ptr<Condition> GT::Routines::ConditionPtr
Smart pointer to Condition.
Definition at line 63 of file common.hpp.
typedef vector<ConditionPtr> GT::Routines::Conditions
Vector of Conditions.
Definition at line 68 of file common.hpp.
typedef shared_ptr<Conditions> GT::Routines::ConditionsPtr
Smart pointer to Conditions.
Definition at line 69 of file common.hpp.
typedef vector<ExtensivePureStrategyPath> GT::Routines::ExtensivePureStrategyPaths
Vector of ExtensivePureStrategyPaths.
Definition at line 96 of file inner_common.hpp.
typedef Model::Game GT::Routines::Game
Alias for Model::Game.
Definition at line 76 of file common.hpp.
typedef Model::GamePtr GT::Routines::GamePtr
Alias for Model::GamePtr.
Definition at line 78 of file common.hpp.
typedef shared_ptr<InformationSetChoiceRoutineConfig> GT::Routines::InformationSetChoiceRoutineConfigPtr
Shared pointer to InformationSetChoiceRoutineConfig.
Definition at line 93 of file inner_common.hpp.
typedef glp_prob GT::Routines::LPProblem
Alias for GLPK's problem structure.
Definition at line 81 of file inner_common.hpp.
typedef unique_ptr<LPProblem, void(*)(LPProblem*)> GT::Routines::LPProblemPtr
Defines wrapper with automatic deletion for GLPK's problem structure.
Definition at line 88 of file inner_common.hpp.
typedef Model::NullGame GT::Routines::NullGame
Alias for Model::NullGame.
Definition at line 77 of file common.hpp.
typedef Model::NullResult GT::Routines::NullResult
Alias for Model::NullResult.
Definition at line 80 of file common.hpp.
typedef Model::Player GT::Routines::Player
Definition at line 98 of file inner_common.hpp.
typedef shared_ptr<PlayerChoiceRoutineConfig> GT::Routines::PlayerChoiceRoutineConfigPtr
Shared pointer to PlayerChoiceRoutineConfig.
Definition at line 91 of file inner_common.hpp.
typedef Model::PlayerPtr GT::Routines::PlayerPtr
Definition at line 99 of file inner_common.hpp.
typedef Model::Players GT::Routines::Players
Definition at line 100 of file inner_common.hpp.
typedef Model::PlayersPtr GT::Routines::PlayersPtr
Definition at line 101 of file inner_common.hpp.
typedef Model::Result GT::Routines::Result
Alias for Model::Result.
Definition at line 79 of file common.hpp.
typedef Model::ResultBuilderPtr GT::Routines::ResultBuilderPtr
Definition at line 104 of file inner_common.hpp.
typedef Model::ResultFactory GT::Routines::ResultFactory
Definition at line 103 of file inner_common.hpp.
typedef Model::ResultPtr GT::Routines::ResultPtr
Alias for Model::ResultPtr.
Definition at line 81 of file common.hpp.
typedef Model::Root GT::Routines::Root
Alias for Model::Root.
Definition at line 75 of file common.hpp.
typedef shared_ptr<RoutineConfig> GT::Routines::RoutineConfigPtr
Smart pointer to RoutineConfig.
Definition at line 73 of file common.hpp.
typedef shared_ptr<Routine> GT::Routines::RoutinePtr
Smart pointer to Routine.
Definition at line 70 of file common.hpp.
typedef vector<RoutinePtr> GT::Routines::Routines
Vector of Routines.
Definition at line 71 of file common.hpp.
typedef shared_ptr<Routines> GT::Routines::RoutinesPtr
Smart pointer to Routines.
Definition at line 72 of file common.hpp.
Function Documentation
LPProblemPtr GT::Routines::createLPProblem ()
Creates LPProblem instance.
Definition at line 38 of file inner_common.cpp.
References freeGLPK().
Referenced by GT::Routines::MatrixMixedEquilibriumRoutine::initializeProblem(), and GT::Routines::BimatrixMixedEquilibriumRoutine::initializeProblem().
{
     static bool initialized = false;
     if (!initialized) {
         atexit(freeGLPK);
         initialized = true;
     }
     return LPProblemPtr(glp_create_prob(), glp_delete_prob);
 }
void GT::Routines::freeGLPK ()
Definition at line 32 of file inner_common.cpp.
Referenced by createLPProblem().
                 {
     glp_free_env();
 }