Game Theory Tools (full documentation): GT::GTL::PlayerNameProperty Class Reference
GT::GTL::PlayerNameProperty Class Reference final
Describes Player's name.
#include <player_name_property.hpp>
Public Member Functions
PlayerNameProperty (const Player *describedPlayer)
Initiates Property with Player it's describing.
virtual ResultPtr findForConditions (const Context &context, const Conditions &conditions) const override
Finds Player's strategies.
Private Attributes
const Player * player
Described Player.
Detailed Description
Describes Player's name.
Author
Mateusz Kubuszok
See Also
Player
Definition at line 39 of file player_name_property.hpp.
Constructor & Destructor Documentation
GT::GTL::PlayerNameProperty::PlayerNameProperty (const Player * describedPlayer) explicit
Initiates Property with Player it's describing.
Parameters
describedPlayer described Player
Definition at line 31 of file player_name_property.cpp.
   :
     player(describedPlayer)
     {}
Member Function Documentation
ResultPtr GT::GTL::PlayerNameProperty::findForConditions (const Context & context, const Conditions & conditions) const override virtual
Finds Player's strategies.
Parameters
context Context with values
conditions Conditions to check
Returns
search Result
Implements GT::GTL::ObjectProperty.
Definition at line 37 of file player_name_property.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), GT::Model::Player::getName(), and player.
         {
     static const IdentifierPtr name  = createIdentifierPtr("Name");
     MessagePtr                 value = createMessagePtr(player->getName());
     return ResultFactory::getInstance().buildResult()->addResult(name, value).build();
 }
Member Data Documentation
const Player* GT::GTL::PlayerNameProperty::player private
Described Player.
Definition at line 43 of file player_name_property.hpp.
Referenced by findForConditions().
The documentation for this class was generated from the following files:
src/gt/gtl/player_name_property.hpp
src/gt/gtl/player_name_property.cpp