Game Theory Tools (full documentation): GT::Model::ExtensiveGamePositionsHelper Class Reference
GT::Model::ExtensiveGamePositionsHelper Class Reference final
Helper used for calculating information sets for ExtensiveGames.
#include <extensive_game_positions_helper.hpp>
Public Types
typedef bimap< Identifier,
ExtensiveDataNode * > PlayerInformationSets
Contains single element information set for one Player.
typedef map< Identifier,
PlayerInformationSets > PlayersInformationSets
Contains information sets' collections for each Player.
Public Member Functions
ExtensiveGamePositionsHelper (const ExtensiveDataNodePtr extensiveGameRoot)
Inititiates helper with ExtensiveGame tree's root.
IdentifiersPtr getPossiblePlayers () const
Returns list of available Players.
bool isPlayerPossible (const Identifier &player) const
Returns whether Player is available.
IdentifiersPtr getPossibleInformationSetsForPlayer (const Identifier &player) const
Returns list of available information sets.
const PlayerInformationSets & getInformationSetsForPlayer (const Identifier &player) const
Returns available information sets.
const ExtensiveDataNode & getInformationSetForPlayer (const Identifier &player, const Identifier &setName) const
Returns list of available information sets.
virtual Message toString () const override
Retuns ExtensiveGamePositionsHelper's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const ExtensiveDataNodePtr root
Root of Data tree.
map< Identifier, bimap
< Identifier,
ExtensiveDataNode * > > playersInformationSets
PlayersInformationSets.
Detailed Description
Helper used for calculating information sets for ExtensiveGames.
Author
Mateusz Kubuszok
Definition at line 42 of file extensive_game_positions_helper.hpp.
Member Typedef Documentation
typedef bimap<Identifier, ExtensiveDataNode*> GT::Model::ExtensiveGamePositionsHelper::PlayerInformationSets
Contains single element information set for one Player.
Definition at line 57 of file extensive_game_positions_helper.hpp.
typedef map<Identifier, PlayerInformationSets> GT::Model::ExtensiveGamePositionsHelper::PlayersInformationSets
Contains information sets' collections for each Player.
Definition at line 62 of file extensive_game_positions_helper.hpp.
Constructor & Destructor Documentation
GT::Model::ExtensiveGamePositionsHelper::ExtensiveGamePositionsHelper (const ExtensiveDataNodePtr extensiveGameRoot) explicit
Inititiates helper with ExtensiveGame tree's root.
Parameters
extensiveGameRoot root of Game's tree
Definition at line 37 of file extensive_game_positions_helper.cpp.
References GT::createIdentifier(), playersInformationSets, and root.
   :
     root(extensiveGameRoot),
     playersInformationSets()
 {
     vector<ExtensiveDataNode*> currentlyChecked;
     vector<ExtensiveDataNode*> nextToBeChecked;
     currentlyChecked.push_back( root.get() );
     while (!currentlyChecked.empty()) {
         for (ExtensiveDataNode* currentNode : currentlyChecked) {
             // leafs doesn't contains decisions and thus cannot make information sets
             if (!currentNode->isLeaf()) {
                 const Identifier& player = *currentNode->getPlayer()->getName();
                 if (!playersInformationSets.count(player))
                     playersInformationSets.insert(
                         PlayersInformationSets::value_type( player, PlayerInformationSets() )
                     );
                 PlayerInformationSets& informationSets = playersInformationSets.at(player);
                 informationSets.insert(
                     PlayerInformationSets::value_type(
                         createIdentifier(informationSets.size()+1),
                         currentNode
                     )
                 );
                 const ExtensiveDataNodes& children = currentNode->getChildren();
                 nextToBeChecked.reserve( nextToBeChecked.size() + children.size() );
                 for (const ExtensiveDataNodePtr& nextNode : children | map_values)
                     nextToBeChecked.push_back( nextNode.get() );
             }
         }
         currentlyChecked.clear();
         currentlyChecked.reserve( nextToBeChecked.size() );
         currentlyChecked.insert(currentlyChecked.end(), nextToBeChecked.begin(), nextToBeChecked.end());
         nextToBeChecked.clear();
     }
 }
Member Function Documentation
const ExtensiveDataNode & GT::Model::ExtensiveGamePositionsHelper::getInformationSetForPlayer (const Identifier & player, const Identifier & setName) const
Returns list of available information sets.
Parameters
player Player's name
setName information set's name
Returns
list of available information sets for a Player
Exceptions
InvalidCoordinate thrown when no such Player or information set available
Definition at line 122 of file extensive_game_positions_helper.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidInformationSet(), GT::Model::ExceptionFactory::invalidPlayer(), and playersInformationSets.
         {
     if (!playersInformationSets.count(player))
         throw ExceptionFactory::getInstance().invalidPlayer(player);
     if (!playersInformationSets.at(player).left.count(setName))
         throw ExceptionFactory::getInstance().invalidInformationSet(setName);
     return *playersInformationSets.at(player).left.at(setName);
 }
const ExtensiveGamePositionsHelper::PlayerInformationSets & GT::Model::ExtensiveGamePositionsHelper::getInformationSetsForPlayer (const Identifier & player) const
Returns available information sets.
Parameters
player Player's name
Returns
information sets for a Player
Exceptions
InvalidCoordinate thrown when no such Player available
Definition at line 113 of file extensive_game_positions_helper.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidPlayer(), and playersInformationSets.
Referenced by GT::Model::ExtensiveDataNode::toString().
         {
     if (!playersInformationSets.count(player))
         throw ExceptionFactory::getInstance().invalidPlayer(player);
     return playersInformationSets.at(player);
 }
IdentifiersPtr GT::Model::ExtensiveGamePositionsHelper::getPossibleInformationSetsForPlayer (const Identifier & player) const
Returns list of available information sets.
Parameters
player Player's name
Returns
list of available information sets for a Player
Exceptions
InvalidCoordinate thrown when no such Player available
Definition at line 98 of file extensive_game_positions_helper.cpp.
References GT::createIdentifierPtr(), GT::createIdentifiersPtr(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidPlayer(), and playersInformationSets.
         {
     if (!playersInformationSets.count(player))
         throw ExceptionFactory::getInstance().invalidPlayer(player);
     IdentifiersPtr informationSets = createIdentifiersPtr();
     for (Identifier setName : playersInformationSets.at(player).left | map_keys)
         informationSets->push_back( createIdentifierPtr(setName) );
     return informationSets;
 }
IdentifiersPtr GT::Model::ExtensiveGamePositionsHelper::getPossiblePlayers () const
Returns list of available Players.
Returns
list of available Players
Definition at line 80 of file extensive_game_positions_helper.cpp.
References GT::createIdentifierPtr(), GT::createIdentifiersPtr(), and playersInformationSets.
{
     IdentifiersPtr players = createIdentifiersPtr();
     for (Identifier playerName : playersInformationSets | map_keys)
         players->push_back( createIdentifierPtr(playerName) );
     return players;
 }
bool GT::Model::ExtensiveGamePositionsHelper::isPlayerPossible (const Identifier & player) const
Returns whether Player is available.
Parameters
player Player's name
Returns
true if Player is available
Definition at line 89 of file extensive_game_positions_helper.cpp.
References playersInformationSets.
         {
     for (Identifier checkedPlayerName : playersInformationSets | map_keys)
         if (playerName == checkedPlayerName)
             return true;
     return false;
 }
Message GT::Model::ExtensiveGamePositionsHelper::toString () const override virtual
Retuns ExtensiveGamePositionsHelper's Message.
Returns
Message
Implements GT::Model::Root.
Definition at line 134 of file extensive_game_positions_helper.cpp.
{
     return Message("ExtensiveGamePositionsHelper");
 }
Member Data Documentation
map<Identifier, bimap<Identifier, ExtensiveDataNode*> > GT::Model::ExtensiveGamePositionsHelper::playersInformationSets private
PlayersInformationSets.
Definition at line 51 of file extensive_game_positions_helper.hpp.
Referenced by ExtensiveGamePositionsHelper(), getInformationSetForPlayer(), getInformationSetsForPlayer(), getPossibleInformationSetsForPlayer(), getPossiblePlayers(), and isPlayerPossible().
const ExtensiveDataNodePtr GT::Model::ExtensiveGamePositionsHelper::root private
Root of Data tree.
Definition at line 46 of file extensive_game_positions_helper.hpp.
Referenced by ExtensiveGamePositionsHelper().
The documentation for this class was generated from the following files:
src/gt/model/extensive_game_positions_helper.hpp
src/gt/model/extensive_game_positions_helper.cpp