Game Theory Tools (full documentation): GT::GTL::ObjectTypeProperty Class Reference
GT::GTL::ObjectTypeProperty Class Reference final
Describes Object's type.
#include <object_type_property.hpp>
Public Member Functions
ObjectTypeProperty (const Object *describedObject)
Initiates Property with Object it's describing.
virtual ResultPtr findForConditions (const Context &context, const Conditions &conditions) const override
Finds Object's type.
Private Attributes
const Object * object
Described Object.
Detailed Description
Describes Object's type.
Author
Mateusz Kubuszok
See Also
Object
Definition at line 39 of file object_type_property.hpp.
Constructor & Destructor Documentation
GT::GTL::ObjectTypeProperty::ObjectTypeProperty (const Object * describedObject) explicit
Initiates Property with Object it's describing.
Parameters
describedObject described Object
Definition at line 31 of file object_type_property.cpp.
   :
     object(describedObject)
     {}
Member Function Documentation
ResultPtr GT::GTL::ObjectTypeProperty::findForConditions (const Context & context, const Conditions & conditions) const override virtual
Finds Object's type.
Parameters
context Context with values
conditions Conditions to check
Returns
search Result
Implements GT::GTL::ObjectProperty.
Definition at line 37 of file object_type_property.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), object, and GT::GTL::Object::type().
         {
     static const IdentifierPtr name  = createIdentifierPtr("Type");
     MessagePtr                 value = createMessagePtr(object->type());
     return ResultFactory::getInstance().buildResult()->addResult(name, value).build();
 }
Member Data Documentation
const Object* GT::GTL::ObjectTypeProperty::object private
Described Object.
Definition at line 43 of file object_type_property.hpp.
Referenced by findForConditions().
The documentation for this class was generated from the following files:
src/gt/gtl/object_type_property.hpp
src/gt/gtl/object_type_property.cpp