Game Theory Tools (full documentation): GT::GTL::Coordinate Class Reference
GT::GTL::Coordinate Class Reference
Contains some Coordinate as well as data bound to it.
#include <coordinate.hpp>
Public Member Functions
Coordinate ()
Default constructor.
Coordinate (const IdentifierPtr player, const IdentifierPtr strategy)
Constructor for initial strategies.
virtual Coordinate & addParam (const ParamPtr param)
Adds Param to the list.
virtual Coordinate & addParams (const ParamsPtr params)
Adds Params to the list.
virtual Coordinate & addPosition (const IdentifierPtr player, const IdentifierPtr strategy)
Add Position to known Coordinates.
virtual Coordinate & addSubCoordinate (const CoordinatePtr subCoordinate)
Adds SubCoordinate.
virtual Coordinate & addSubCoordinates (const CoordinatesPtr subCoordinates)
Adds SubCoordinates.
virtual const ParamsPtr getParams () const
Obtains Params.
virtual const PositionsPtr getPositions () const
Obtains Positions.
virtual const CoordinatesPtr getSubCoordinates () const
Obtain SubCoordinates.
virtual void fillDataBuilder (const Context &context, DataBuilderPtr &dataBuilder) const
Fill DataBuilder with its data.
virtual Message serialize () const override
Returns serialized Message for a Coordinate.
virtual Message toString () const override
Returns Coordinate Message.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const PositionsPtr positions
Defined Positions.
const ParamsPtr params
Defined Params.
const CoordinatesPtr subCoordinates
Defined subCoordinetes.
Friends
Coordinate operator+ (const Coordinate &coordinate1, const Coordinate &coordinate2)
Merges two Coordinates into one.
Additional Inherited Members
Static Public Member Functions inherited from GT::GTL::ValidableSymbol
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Detailed Description
Contains some Coordinate as well as data bound to it.
They can be considered pieces from which sets of pure strategies will be built. For strategic-form games it means putting together all player-strategy pairs as to create whole vector for payoff function. For extensive-form games it means going from root to leafs, one node at a time.
Example of piece of code recognized by Parser:
{
   p1 = p1s1 :
   { p2 = p2s1 : 10, 20 },
   { p2 = p2s2 : 30, 40 }
},
{
   p1 = p1s2 :
   { p2 = p2s1 : 50, 60 },
   { p2 = p2s2 : 70, 80 }
}
Author
Mateusz Kubuszok
See Also
CoordinateDriver
Parser
Definition at line 63 of file coordinate.hpp.
Constructor & Destructor Documentation
GT::GTL::Coordinate::Coordinate ()
Default constructor.
Definition at line 36 of file coordinate.cpp.
                        :
     Root(),
     positions(new Positions()),
     params(new Params()),
     subCoordinates(new Coordinates())
     {}
GT::GTL::Coordinate::Coordinate (const IdentifierPtr player, const IdentifierPtr strategy)
Constructor for initial strategies.
Parameters
player player identifier
strategy strategy identifier
Definition at line 43 of file coordinate.cpp.
References positions.
   :
     Root(),
     positions(new Positions()),
     params(new Params()),
     subCoordinates(new Coordinates())
 {
     positions->insert( Positions::value_type(*player, *strategy) );
 }
Member Function Documentation
Coordinate & GT::GTL::Coordinate::addParam (const ParamPtr param) virtual
Adds Param to the list.
Parameters
param single Param
Returns
reference to itself
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 55 of file coordinate.cpp.
References params.
   {
     params->push_back(param);
     return *this;
 }
Coordinate & GT::GTL::Coordinate::addParams (const ParamsPtr params) virtual
Adds Params to the list.
Parameters
params Params' vector
Returns
reference to itself
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 62 of file coordinate.cpp.
References params.
   {
     params->reserve(params->size() + newParams->size());
     params->insert(params->end(), newParams->begin(), newParams->end());
     return *this;
 }
Coordinate & GT::GTL::Coordinate::addPosition (const IdentifierPtr player, const IdentifierPtr strategy) virtual
Add Position to known Coordinates.
Parameters
player player (dimension)
strategy strategy (position on dimension)
Returns
reference to itself
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 70 of file coordinate.cpp.
References positions.
   {
     positions->insert( Positions::value_type(*player, *strategy) );
     return *this;
 }
Coordinate & GT::GTL::Coordinate::addSubCoordinate (const CoordinatePtr subCoordinate) virtual
Adds SubCoordinate.
Parameters
subCoordinate SubCoordinate
Returns
reference to itself
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 78 of file coordinate.cpp.
References subCoordinates.
   {
     subCoordinates->push_back(subCoordinate);
     return *this;
 }
Coordinate & GT::GTL::Coordinate::addSubCoordinates (const CoordinatesPtr subCoordinates) virtual
Adds SubCoordinates.
Parameters
subCoordinates SubCoordinate
Returns
reference to itself
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 85 of file coordinate.cpp.
References subCoordinates.
   {
     subCoordinates->reserve(subCoordinates->size() + newSubCoordinates->size());
     subCoordinates->insert(subCoordinates->end(), newSubCoordinates->begin(), newSubCoordinates->end());
     return *this;
 }
void GT::GTL::Coordinate::fillDataBuilder (const Context & context, DataBuilderPtr & dataBuilder) const virtual
Fill DataBuilder with its data.
Parameters
context Context with params
dataBuilder DataBuilder to fill
Exceptions
CyclicIdentifiers thrown when some Identfiers create the cycle
InvalidContentRequest thrown when some Param does not contain Number
NotDefinedParam thrown when some Param cannot find value inside Context
IllegalInnerState thrown when some of positions are already set
InvalidCoordinate thrown when some of values are not valid strategies names
IllegalInnerState thrown when attempting to set params when not all coordinates are known
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 105 of file coordinate.cpp.
References params, positions, and subCoordinates.
         {
     if (positions->size())
         dataBuilder->addNextPositions(positions);
     if (params->size()) {
         NumbersPtr values(new Numbers());
         for (ParamPtr& param : *params)
             values->push_back(param->getNumber(context));
         dataBuilder->setPayoffs(values);
     }
     if (subCoordinates->size()){
         for (CoordinatePtr& coordinate : *subCoordinates) {
             Model::DataBuilderPtr passedBuilder = dataBuilder->clone();
             coordinate->fillDataBuilder(context, passedBuilder);
         }
     }
 }
const ParamsPtr GT::GTL::Coordinate::getParams () const virtual
Obtains Params.
Returns
Params
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 93 of file coordinate.cpp.
References params.
Referenced by GT::GTL::operator+().
{
     return params;
 }
const PositionsPtr GT::GTL::Coordinate::getPositions () const virtual
Obtains Positions.
Returns
Positions
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 97 of file coordinate.cpp.
References positions.
Referenced by GT::GTL::operator+().
{
     return positions;
 }
const CoordinatesPtr GT::GTL::Coordinate::getSubCoordinates () const virtual
Obtain SubCoordinates.
Returns
SubCoordinates
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 101 of file coordinate.cpp.
References subCoordinates.
Referenced by GT::GTL::operator+().
{
     return subCoordinates;
 }
Message GT::GTL::Coordinate::serialize () const override virtual
Returns serialized Message for a Coordinate.
Returns
serialization result
Reimplemented from GT::GTL::ValidableSymbol.
Definition at line 127 of file coordinate.cpp.
References GT::GTL::ValidableSymbol::addIndent(), params, positions, and subCoordinates.
{
     stringstream result;
     result << '{';
     if (positions->size()) {
         bool firstElement = true;
         for (const Positions::value_type& position : *positions) {
             if (!firstElement)
                 result << ',';
             result << ' ' << position.first << " = " << position.second;
             firstElement = false;
         }
     }
     result << " :";
     if (subCoordinates->size()) {
         bool firstElement = true;
         for (const CoordinatePtr& subCoordinate : *subCoordinates) {
             if (!firstElement)
                 result << ',';
             result << endl;
             result << addIndent(subCoordinate->serialize());
             firstElement = false;
         }
     } else if (params->size()) {
         bool firstElement = true;
         for (const ParamPtr& param : *params) {
             if (!firstElement)
                 result << ',';
             result << endl;
             result << addIndent(param->serialize());
             firstElement = false;
         }
     }
     result << endl;
     result << '}';
     return result.str();
 }
Message GT::GTL::Coordinate::toString () const override virtual
Returns Coordinate Message.
Returns
Message
Implements GT::Model::Root.
Reimplemented in GT::GTL::ErrorCoordinate, and GT::GTL::NullCoordinate.
Definition at line 169 of file coordinate.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), params, positions, and subCoordinates.
Referenced by GT::GTL::CheckingGameDriver::createDetails(), GT::GTL::CheckingCoordinateDriver::fillWithData(), and GT::GTL::CheckingCoordinateDriver::merge().
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     if (params->size()) {
         static const IdentifierPtr paramsName = createIdentifierPtr("Params");
         ResultBuilderPtr subResultBuilder = ResultFactory::getInstance().buildResult();
         static const IdentifierPtr name = createIdentifierPtr("Param");
         for (const ParamPtr& param : *params) {
             MessagePtr value = createMessagePtr(param->toString());
             subResultBuilder->addResult(name, value);
         }
         MessagePtr paramsValue = createMessagePtr(subResultBuilder->build()->getResult());
         resultBuilder->addResult(paramsName, paramsValue);
     }
     if (positions->size()) {
         static const IdentifierPtr positionsName = createIdentifierPtr("Positions");
         ResultBuilderPtr subResultBuilder = ResultFactory::getInstance().buildResult();
         for (const Positions::value_type& position : *positions) {
             IdentifierPtr name  = createIdentifierPtr(position.first);
             MessagePtr    value = createMessagePtr(position.second);
             subResultBuilder->addResult(name, value);
         }
         MessagePtr positionsValue = createMessagePtr(subResultBuilder->build()->getResult());
         resultBuilder->addResult(positionsName, positionsValue);
     }
     if (subCoordinates->size()) {
         static const IdentifierPtr subCoordinatesName = createIdentifierPtr("SubCoordinates");
         static const IdentifierPtr name               = createIdentifierPtr("Coordinate");
         ResultBuilderPtr subResultBuilder = ResultFactory::getInstance().buildResult();
         for (const CoordinatePtr& subCoordinate : *subCoordinates) {
             MessagePtr value = createMessagePtr(subCoordinate->toString());
             subResultBuilder->addResult(name, value);
         }
         MessagePtr subCoordinatesValue = createMessagePtr(subResultBuilder->build()->getResult());
         resultBuilder->addResult(subCoordinatesName, subCoordinatesValue);
     }
     return resultBuilder->build()->getResult();
 }
Friends And Related Function Documentation
Coordinate operator+ (const Coordinate & coordinate1, const Coordinate & coordinate2) friend
Merges two Coordinates into one.
Parameters
coordinate1 first Coordinate
coordinate2 second Coordinate
Returns
merged Coordinates
Definition at line 221 of file coordinate.cpp.
   {
     Coordinate result;
     for (const Positions::value_type& position : *coordinate1.getPositions())
         result.positions->insert(position);
     for (const Positions::value_type& position : *coordinate2.getPositions())
         result.positions->insert(position);
     for (const ParamPtr& param : *coordinate1.getParams())
         result.params->push_back(param);
     for (const ParamPtr& param : *coordinate2.getParams())
         result.params->push_back(param);
     for (const CoordinatePtr& subCoordinate : *coordinate1.getSubCoordinates())
         result.subCoordinates->push_back(subCoordinate);
     for (const CoordinatePtr& subCoordinate : *coordinate2.getSubCoordinates())
         result.subCoordinates->push_back(subCoordinate);
     return result;
 }
Member Data Documentation
const ParamsPtr GT::GTL::Coordinate::params private
Defined Params.
Definition at line 73 of file coordinate.hpp.
Referenced by addParam(), addParams(), fillDataBuilder(), getParams(), GT::GTL::operator+(), serialize(), and toString().
const PositionsPtr GT::GTL::Coordinate::positions private
Defined Positions.
Definition at line 68 of file coordinate.hpp.
Referenced by addPosition(), Coordinate(), fillDataBuilder(), getPositions(), GT::GTL::operator+(), serialize(), and toString().
const CoordinatesPtr GT::GTL::Coordinate::subCoordinates private
Defined subCoordinetes.
Definition at line 78 of file coordinate.hpp.
Referenced by addSubCoordinate(), addSubCoordinates(), fillDataBuilder(), getSubCoordinates(), GT::GTL::operator+(), serialize(), and toString().
The documentation for this class was generated from the following files:
include/gt/gtl/coordinate.hpp
src/gt/gtl/coordinate.cpp