Game Theory Tools (full documentation): GT::Model::StrategicData Class Reference
GT::Model::StrategicData Class Reference
Contains data specific for Game in a strategic form.
#include <strategic_data.hpp>
Public Member Functions
StrategicData (const PlayersPtr playersDefinitions)
Initiates Data with Players' definitions.
virtual const PlayersPtr getPlayers () const override
Returns Players' definitions.
virtual const DataPiecePtr getPayoffs (const Index positionInStorage) const
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const PositionsPtr positions) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr getPayoffs (const Positions &positions) const override
Returns DataPiece that gives access to payoffs.
virtual Data & setPayoffs (const Index positionInStorage, const NumbersPtr numbers)
Sets Positions to contains given payoffs.
virtual Data & setPayoffs (const Positions &positions, const NumbersPtr numbers) override
Sets Positions to contains given payoffs.
virtual Data & setPayoffs (const PositionsPtr positions, const NumbersPtr numbers) override
Sets Positions to contains given payoffs.
virtual Index getUpperBound () const
Returns upport bound of index for accessing data via position in storage.
virtual const DataPiecePtr operator[] (const Index positionInStorage) const
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const Positions &positions) const override
Returns DataPiece that gives access to payoffs.
virtual const DataPiecePtr operator[] (const PositionsPtr positions) const override
Returns DataPiece that gives access to payoffs.
virtual Message toString () const override
Returns StrategicData Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
StrategicGamePositionsHelper positionsHelper
StrategicGamePositionsHelper used to calculate positions in storage vector.
vector< NumbersPtr > payoffStorage
Contains Payoff - indexes can be calculated with PostionsHelper.
vector< bool > payoffStorageAllocation
Contains information whether or not some storage poition is already used.
Detailed Description
Contains data specific for Game in a strategic form.
Games in this form should have all coordinates filled with payoffs. Since all Players and their strategies are known beforehand, positions can also be hashed to Indexes with StrategicGamePositionsHelper.
Author
Mateusz Kubuszok
See Also
DataAccessor
Data
DataPiece
StrategicDataAccessor
StrategicDataPiece
StrategicDataBuilder
StrategicGamePositionsHelper
Definition at line 54 of file strategic_data.hpp.
Constructor & Destructor Documentation
GT::Model::StrategicData::StrategicData (const PlayersPtr playersDefinitions) explicit
Initiates Data with Players' definitions.
Parameters
playersDefinitions Players' definitions
Definition at line 31 of file strategic_data.cpp.
References GT::createNumbers(), GT::Model::NullFactory::getInstance(), GT::Model::StrategicGamePositionsHelper::getUpperBound(), payoffStorage, payoffStorageAllocation, and positionsHelper.
   :
     positionsHelper(players),
     payoffStorage(),
     payoffStorageAllocation()
 {
     Index maxPosition = positionsHelper.getUpperBound();
     for (Index i = 0; i < maxPosition; i++) {
         payoffStorage.push_back( NullFactory::getInstance().createNumbers() );
         payoffStorageAllocation.push_back( false );
     }
 }
Member Function Documentation
const DataPiecePtr GT::Model::StrategicData::getPayoffs (const Index positionInStorage) const virtual
Returns DataPiece that gives access to payoffs.
Parameters
positionInStorage Index of positon in payoff storage according to StrategicGamePositionsHelper
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented in GT::Model::NullStrategicData.
Definition at line 49 of file strategic_data.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::StrategicGamePositionsHelper::getPlayers(), GT::Model::StrategicGamePositionsHelper::getUpperBound(), GT::Model::ExceptionFactory::noParamsForPositions(), payoffStorage, payoffStorageAllocation, and positionsHelper.
Referenced by getPayoffs(), and operator[]().
         {
     if (!payoffStorageAllocation.at(positionInStorage))
         throw ExceptionFactory::getInstance().noParamsForPositions(
             positionInStorage,
             positionsHelper.getUpperBound()
         );
     return DataPiecePtr(
         new PlainDataPiece(
             positionsHelper.getPlayers(),
             payoffStorage.at(positionInStorage)
         )
     );
 }
const DataPiecePtr GT::Model::StrategicData::getPayoffs (const PositionsPtr positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 72 of file strategic_data.cpp.
References getPayoffs().
         {
     return getPayoffs(*positions);
 }
const DataPiecePtr GT::Model::StrategicData::getPayoffs (const Positions & positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 66 of file strategic_data.cpp.
References GT::Model::StrategicGamePositionsHelper::calculatePosition(), getPayoffs(), and positionsHelper.
         {
     return getPayoffs(positionsHelper.calculatePosition(positions));
 }
const PlayersPtr GT::Model::StrategicData::getPlayers () const override virtual
Returns Players' definitions.
Returns
Players' definitions
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 45 of file strategic_data.cpp.
References GT::Model::StrategicGamePositionsHelper::getPlayers(), and positionsHelper.
{
     return positionsHelper.getPlayers();
 }
Index GT::Model::StrategicData::getUpperBound () const virtual
Returns upport bound of index for accessing data via position in storage.
Returns
upper bound of positions in storage (highest available Index is upper bound - 1)
Reimplemented in GT::Model::NullStrategicData.
Definition at line 114 of file strategic_data.cpp.
References GT::Model::StrategicGamePositionsHelper::getUpperBound(), and positionsHelper.
{
     return positionsHelper.getUpperBound();
 }
const DataPiecePtr GT::Model::StrategicData::operator[] (const Index positionInStorage) const virtual
Returns DataPiece that gives access to payoffs.
Parameters
positionInStorage Index of positon in payoff storage according to StrategicGamePositionsHelper
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Reimplemented in GT::Model::NullStrategicData.
Definition at line 118 of file strategic_data.cpp.
References getPayoffs().
         {
     return getPayoffs(positionInStorage);
 }
const DataPiecePtr GT::Model::StrategicData::operator[] (const Positions & positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 124 of file strategic_data.cpp.
References getPayoffs().
         {
     return getPayoffs(positions);
 }
const DataPiecePtr GT::Model::StrategicData::operator[] (const PositionsPtr positions) const override virtual
Returns DataPiece that gives access to payoffs.
Parameters
positions Positions in payoff storage
Returns
DataPiece handling access to payoffs
Exceptions
InvalidCoordinate thrown when no data is set under such position
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 130 of file strategic_data.cpp.
References getPayoffs().
         {
     return getPayoffs(positions);
 }
Data & GT::Model::StrategicData::setPayoffs (const Index positionInStorage, const NumbersPtr numbers) virtual
Sets Positions to contains given payoffs.
Parameters
positionInStorage Index of position in payoff storage
numbers payoffs values
Returns
reference to itself for chaining
Exceptions
InvalidCoordinate thrown when Index in not in allowed range
Reimplemented in GT::Model::NullStrategicData.
Definition at line 78 of file strategic_data.cpp.
References GT::Model::ExceptionFactory::getInstance(), GT::Model::StrategicGamePositionsHelper::getUpperBound(), GT::Model::ExceptionFactory::noParamsForPositions(), payoffStorage, payoffStorageAllocation, and positionsHelper.
Referenced by setPayoffs().
   {
     if (positionsHelper.getUpperBound() <= positionInStorage)
         throw ExceptionFactory::getInstance().noParamsForPositions(
             positionInStorage,
             positionsHelper.getUpperBound()
         );
     payoffStorage.at(positionInStorage)           = numbers;
     payoffStorageAllocation.at(positionInStorage) = true;
     return *this;
 }
Data & GT::Model::StrategicData::setPayoffs (const Positions & positions, const NumbersPtr numbers) override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 94 of file strategic_data.cpp.
References GT::Model::StrategicGamePositionsHelper::calculatePosition(), GT::Model::StrategicGamePositionsHelper::checkPositions(), GT::Model::ExceptionFactory::getInstance(), GT::Model::ExceptionFactory::invalidCoordinateFormat(), positionsHelper, and setPayoffs().
   {
     if (!positionsHelper.checkPositions(positions))
         throw ExceptionFactory::getInstance().invalidCoordinateFormat(positions);
     return setPayoffs(
         positionsHelper.calculatePosition(positions),
         numbers
     );
 }
Data & GT::Model::StrategicData::setPayoffs (const PositionsPtr positions, const NumbersPtr numbers) override virtual
Sets Positions to contains given payoffs.
Parameters
positions Positions to set
numbers payoffs values
Returns
reference to itself for chaining
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 107 of file strategic_data.cpp.
References setPayoffs().
   {
     return setPayoffs(*positions, numbers);
 }
Message GT::Model::StrategicData::toString () const override virtual
Returns StrategicData Message.
Returns
Message
Implements GT::Model::Data.
Reimplemented in GT::Model::NullStrategicData.
Definition at line 136 of file strategic_data.cpp.
References GT::Model::ResultFactory::buildResult(), GT::Model::StrategicGamePositionsHelper::calculatePlayer(), GT::createIdentifierPtr(), GT::createIdentifiersPtr(), GT::createMessagePtr(), GT::createMessagesPtr(), GT::Model::ResultFactory::getInstance(), GT::Model::StrategicGamePositionsHelper::getPlayers(), payoffStorage, payoffStorageAllocation, positionsHelper, GT::Model::StrategicGamePositionsHelper::retrievePlayer(), and GT::Model::StrategicGamePositionsHelper::retrievePositions().
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     static const IdentifierPtr positionName  = createIdentifierPtr("Position");
     static const IdentifierPtr payoffName    = createIdentifierPtr("Payoff");
     IdentifiersPtr playersNames = createIdentifiersPtr();
     for (Index i = 0; i < positionsHelper.getPlayers()->size(); i++)
         playersNames->push_back( createIdentifierPtr(positionsHelper.retrievePlayer(i)) );
     Index maxPosition = payoffStorage.size();
     for (Index i = 0; i < maxPosition; i++)
         if (payoffStorageAllocation.at(i)) {
             static const IdentifierPtr name       = createIdentifierPtr("Value");
             const PositionsPtr         positions  = positionsHelper.retrievePositions(i);
             const NumbersPtr           numbers    = payoffStorage[i];
             const IdentifiersPtr       strategies = createIdentifiersPtr();
             const MessagesPtr          numbersStr = createMessagesPtr();
             for (const IdentifierPtr& playerName : (*playersNames)) {
                 strategies->push_back( createIdentifierPtr((*positions)[*playerName]) );
                 numbersStr->push_back( createMessagePtr(
                     (*numbers)[positionsHelper.calculatePlayer(playerName)]
                 ) );
             }
             ResultBuilderPtr subresultBuilder = ResultFactory::getInstance().buildResult();
             subresultBuilder->setHeaders(playersNames)
                              .addRecord(positionName, strategies)
                              .addRecord(payoffName, numbersStr);
             MessagePtr subresult = createMessagePtr(subresultBuilder->buildRaw()->getResult());
             resultBuilder->addResult(name, subresult);
         }
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
vector<NumbersPtr> GT::Model::StrategicData::payoffStorage private
Contains Payoff - indexes can be calculated with PostionsHelper.
Definition at line 63 of file strategic_data.hpp.
Referenced by getPayoffs(), setPayoffs(), StrategicData(), and toString().
vector<bool> GT::Model::StrategicData::payoffStorageAllocation private
Contains information whether or not some storage poition is already used.
Definition at line 67 of file strategic_data.hpp.
Referenced by getPayoffs(), setPayoffs(), StrategicData(), and toString().
StrategicGamePositionsHelper GT::Model::StrategicData::positionsHelper private
StrategicGamePositionsHelper used to calculate positions in storage vector.
Definition at line 58 of file strategic_data.hpp.
Referenced by getPayoffs(), getPlayers(), getUpperBound(), setPayoffs(), StrategicData(), and toString().
The documentation for this class was generated from the following files:
src/gt/model/strategic_data.hpp
src/gt/model/strategic_data.cpp