Game Theory Tools (full documentation): GT::Model::NullExtensiveDataNode Class Reference
GT::Model::NullExtensiveDataNode Class Reference final
Null ExtensiveDriver for acting as a root's parent.
#include <extensive_data_node.hpp>
Public Member Functions
NullExtensiveDataNode ()
virtual const ExtensiveDataNode & getParent () const override
Returns parent of this Node (Null object for Root).
virtual const PlayerPtr getPlayer () const override
Returns Player of a current Node.
virtual const PlayerPtr getPlayer (const Positions &) const override
Returns Player for a given Positions.
virtual ExtensiveDataNode & setPlayer (const PlayerPtr) override
Sets Player of a current Node.
virtual ExtensiveDataNode & setPlayer (const Positions &, const PlayerPtr) override
Sets Player of a current Node.
virtual const NumbersPtr getPayoffs (const Positions &) const override
Returns Payoff values.
virtual ExtensiveDataNode & setPayoffs (const Positions &, const NumbersPtr) override
Sets Payoff values.
virtual IdentifiersPtr getChoices () const override
Returns available choices.
virtual bool isLeaf () const override
Returns whether the node is a leaf.
virtual bool isNotNull () const override
Wheter Root is not a null Object (null guardian).
virtual Message toString () const override
ExtensiveDataNode's Message.
Public Member Functions inherited from GT::Model::ExtensiveDataNode
ExtensiveDataNode ()
Tree's root's constructor.
virtual ~ExtensiveDataNode ()
Tree's root's destructor.
virtual const ExtensiveDataNodes & getChildren () const
Returns children of this Node (empty for leaf).
virtual bool hasChoice (const Identifier &strategy) const
Returns whether such choice is available.
virtual const ExtensiveDataNode & getNodeForChoice (const Identifier &strategy) const
Returns node for given choice.
virtual Message toString (const ExtensiveGamePositionsHelper &positionsHelper) const
ExtensiveDataNode's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
bool isNull () const
Wheter Root is a null Object (null guardian).
Additional Inherited Members
Protected Member Functions inherited from GT::Model::ExtensiveDataNode
ExtensiveDataNode (ExtensiveDataNode *parent, Index depth)
Child Node constructor.
ExtensiveDataNode (ExtensiveDataNode *parent, NumbersPtr values)
Leaf Node constructor.
Detailed Description
Null ExtensiveDriver for acting as a root's parent.
Author
Mateusz Kubuszok
Definition at line 266 of file extensive_data_node.hpp.
Constructor & Destructor Documentation
GT::Model::NullExtensiveDataNode::NullExtensiveDataNode () inline
Definition at line 268 of file extensive_data_node.hpp.
                             :
         ExtensiveDataNode(
             nullptr, // prevents infinite loop of constructor calls
             Model::NullFactory::getInstance().createNumbers()
         )
         {}
Member Function Documentation
virtual IdentifiersPtr GT::Model::NullExtensiveDataNode::getChoices () const inline override virtual
Returns available choices.
Returns
choices
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 315 of file extensive_data_node.hpp.
References GT::Model::NullFactory::createIdentifiers(), and GT::Model::NullFactory::getInstance().
{
         return Model::NullFactory::getInstance().createIdentifiers();
     }
virtual const ExtensiveDataNode& GT::Model::NullExtensiveDataNode::getParent () const inline override virtual
Returns parent of this Node (Null object for Root).
Returns
parent Node
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 275 of file extensive_data_node.hpp.
{
         return *this;
     }
virtual const NumbersPtr GT::Model::NullExtensiveDataNode::getPayoffs (const Positions & positions) const inline override virtual
Returns Payoff values.
Parameters
positions Positions of a sought Payoff
Returns
values of Payoffs
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 302 of file extensive_data_node.hpp.
References GT::Model::NullFactory::createNumbers(), and GT::Model::NullFactory::getInstance().
                      {
         return Model::NullFactory::getInstance().createNumbers();
     }
virtual const PlayerPtr GT::Model::NullExtensiveDataNode::getPlayer () const inline override virtual
Returns Player of a current Node.
Returns
Player of this Node
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 279 of file extensive_data_node.hpp.
References GT::Model::NullFactory::createPlayer(), and GT::Model::NullFactory::getInstance().
{
         return NullFactory::getInstance().createPlayer();
     }
virtual const PlayerPtr GT::Model::NullExtensiveDataNode::getPlayer (const Positions & positions) const inline override virtual
Returns Player for a given Positions.
Parameters
positions Positions of a sought Player
Returns
Player of this Node
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 283 of file extensive_data_node.hpp.
References GT::Model::NullFactory::createPlayer(), and GT::Model::NullFactory::getInstance().
                      {
         return NullFactory::getInstance().createPlayer();
     }
virtual bool GT::Model::NullExtensiveDataNode::isLeaf () const inline override virtual
Returns whether the node is a leaf.
Returns
true if the node is a leaf
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 319 of file extensive_data_node.hpp.
{
         return true;
     }
virtual bool GT::Model::NullExtensiveDataNode::isNotNull () const inline override virtual
Wheter Root is not a null Object (null guardian).
Returns
true if object is not a null object
Reimplemented from GT::Model::Root.
Definition at line 323 of file extensive_data_node.hpp.
{
         return false;
     }
virtual ExtensiveDataNode& GT::Model::NullExtensiveDataNode::setPayoffs (const Positions & positions, const NumbersPtr values) inline override virtual
Sets Payoff values.
Parameters
positions Positions of a set Payoff
values Payoff value
Returns
reference to itself for chaining
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 308 of file extensive_data_node.hpp.
                {
         return *this;
     }
virtual ExtensiveDataNode& GT::Model::NullExtensiveDataNode::setPlayer (const PlayerPtr player) inline override virtual
Sets Player of a current Node.
Parameters
player Player of this Node
Returns
reference to itself for chaining
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 289 of file extensive_data_node.hpp.
                {
         return *this;
     }
virtual ExtensiveDataNode& GT::Model::NullExtensiveDataNode::setPlayer (const Positions & positions, const PlayerPtr player) inline override virtual
Sets Player of a current Node.
Parameters
positions Positions of a set Player
player Player of this Node
Returns
reference to itself for chaining
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 295 of file extensive_data_node.hpp.
                {
         return *this;
     }
virtual Message GT::Model::NullExtensiveDataNode::toString () const inline override virtual
ExtensiveDataNode's Message.
Returns
Message
Reimplemented from GT::Model::ExtensiveDataNode.
Definition at line 327 of file extensive_data_node.hpp.
{
         return Message("NullExtensiveDataNode");
     }
The documentation for this class was generated from the following file:
src/gt/model/extensive_data_node.hpp