Game Theory Tools (full documentation): GT::GTL::ValidableSymbol Class Reference
GT::GTL::ValidableSymbol Class Reference
Interface used for marking objects that are valid (or not) symbols in Parser.
#include <validable_symbol.hpp>
Public Member Functions
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether Object is valid.
virtual Message serialize () const
Returns serialized Message for a symbol.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
virtual Message toString () const =0
Returns Message about an Object allowing its debuging.
Static Public Member Functions
static Message addIndent (const Message content)
Adds indent to the beginning of each line of passes content.
Private Types
typedef void(ValidableSymbol::* SafeBoolIdiom)() const
Defines SafeBoolIdiom as pointer to the method with no argument and return.
Private Member Functions
void comparisonsAreNotAllowed () const
Defines some method of SafeBoolIdiom type that will not be accessible.
Private Attributes
InputLocationPtr inputLocation
Contains input location.
Detailed Description
Interface used for marking objects that are valid (or not) symbols in Parser.
Author
Mateusz Kubuszok
See Also
Condition
Coordinate
Definition
Details
Game
Object
Player
Param
Query
Parser
Definition at line 48 of file validable_symbol.hpp.
Member Typedef Documentation
typedef void(ValidableSymbol::* GT::GTL::ValidableSymbol::SafeBoolIdiom)() const private
Defines SafeBoolIdiom as pointer to the method with no argument and return.
Definition at line 52 of file validable_symbol.hpp.
Constructor & Destructor Documentation
GT::GTL::ValidableSymbol::ValidableSymbol ()
Default constructor initiating input location.
Definition at line 42 of file validable_symbol.cpp.
                                  :
     inputLocation(new InputLocation())
     {}
GT::GTL::ValidableSymbol::~ValidableSymbol () virtual
Default destructor.
Definition at line 46 of file validable_symbol.cpp.
 {}
Member Function Documentation
Message GT::GTL::ValidableSymbol::addIndent (const Message content) static
Adds indent to the beginning of each line of passes content.
Used during serialization.
Parameters
content content that should be indented
Returns
indented content
Definition at line 70 of file validable_symbol.cpp.
Referenced by GT::GTL::Game::serialize(), GT::GTL::Coordinate::serialize(), and GT::GTL::Context::serialize().
   {
     // do not use boost::container::vector here - it causes memory access violation with split function
     std::vector<Message> lines;
     split(lines, content, is_any_of("\n"));
     bool firstElement = true;
     stringstream result;
     for (Message& line : lines) {
         if (!line.empty() && line != "\n") {
             if (!firstElement)
                 result << endl;
             result << "  " << line;
             firstElement = false;
         }
     }
     return result.str();
 }
void GT::GTL::ValidableSymbol::comparisonsAreNotAllowed () const private
Defines some method of SafeBoolIdiom type that will not be accessible.
Definition at line 38 of file validable_symbol.cpp.
Referenced by operator SafeBoolIdiom().
 {}
const InputLocationPtr GT::GTL::ValidableSymbol::getInputLocation () const virtual
Returns input location.
Returns
input location
Definition at line 56 of file validable_symbol.cpp.
References inputLocation.
Referenced by GT::GTL::CheckingGameDriver::createDetails(), GT::GTL::CheckingGameDriver::createExtensive(), GT::GTL::CheckingStatementDriver::createQuery(), GT::GTL::CheckingGameDriver::createStrategic(), GT::GTL::ExecutionStatementDriver::executeQuery(), GT::GTL::CheckingCoordinateDriver::fillWithData(), GT::GTL::CheckingConditionDriver::informationSetChoosed(), GT::GTL::CheckingConditionDriver::informationSetWithin(), GT::GTL::CheckingCoordinateDriver::merge(), GT::GTL::CheckingConditionDriver::playerChoosed(), GT::GTL::CheckingConditionDriver::playerWithin(), GT::GTL::CheckingDriver::showError(), and GT::GTL::suberrorMessage().
{
     return inputLocation;
 }
bool GT::GTL::ValidableSymbol::isValid () const virtual
Returns whether Object is valid.
Returns
true if Object is valid
Reimplemented in GT::GTL::ErrorCoordinate, GT::GTL::ErrorObject, GT::GTL::ErrorParam, GT::GTL::ErrorGame, GT::GTL::ErrorQuery, GT::GTL::ErrorDefinition, GT::GTL::ErrorDetails, GT::GTL::ErrorCondition, and GT::GTL::ErrorPlayer.
Definition at line 48 of file validable_symbol.cpp.
Referenced by GT::GTL::CheckingStatementDriver::executeDefinition(), and GT::GTL::CheckingStatementDriver::executeQuery().
{
     return true;
 }
GT::GTL::ValidableSymbol::operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Definition at line 66 of file validable_symbol.cpp.
References comparisonsAreNotAllowed().
{
     return isValid() ? &ValidableSymbol::comparisonsAreNotAllowed : 0;
 }
Message GT::GTL::ValidableSymbol::serialize () const virtual
Returns serialized Message for a symbol.
Returns
serialization result
Reimplemented in GT::GTL::ErrorGame, GT::GTL::Coordinate, GT::GTL::NullGame, GT::GTL::Game, GT::GTL::IdentifierParam, GT::GTL::NumberParam, GT::GTL::ObjectParam, and GT::GTL::Player.
Definition at line 52 of file validable_symbol.cpp.
{
     return Message();
 }
void GT::GTL::ValidableSymbol::setInputLocation (const InputLocationPtr inputLocation) virtual
Sets input location.
Parameters
inputLocation input location
Definition at line 60 of file validable_symbol.cpp.
References inputLocation.
   {
     inputLocation = newInputLocation;
 }
Member Data Documentation
InputLocationPtr GT::GTL::ValidableSymbol::inputLocation private
Contains input location.
Definition at line 57 of file validable_symbol.hpp.
Referenced by getInputLocation(), and setInputLocation().
The documentation for this class was generated from the following files:
include/gt/gtl/validable_symbol.hpp
src/gt/gtl/validable_symbol.cpp