Game Theory Tools (full documentation): GT::GTL::CheckingCoordinateDriver Class Reference
GT::GTL::CheckingCoordinateDriver Class Reference final
Implementation used for handling Coordinates via CheckingDriver.
#include <checking_coordinate_driver.hpp>
Public Member Functions
CheckingCoordinateDriver (Driver *parentDriver)
Initiates CheckingCoordinateDriver with its parent.
virtual CoordinatePtr * create (const InputLocation &inputLocation, const IdentifierPtr *player, const IdentifierPtr *strategy) const override
Creates coordinate.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *coordinate, const CoordinatesPtr *data) const override
Fills Coordinate with subcoordinates.
virtual CoordinatePtr * fillWithData (const InputLocation &inputLocation, const CoordinatePtr *coordinate, const ParamsPtr *data) const override
Fills Coordinate with Params.
virtual CoordinatePtr * merge (const InputLocation &inputLocation, const CoordinatePtr *coordinate1, const CoordinatePtr *coordinate2) const override
Merge two coordinates into one.
virtual Message toString () const override
CheckingCoordinateDriver message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
Driver * driver
Implementation of a main Driver.
Detailed Description
Implementation used for handling Coordinates via CheckingDriver.
Performs only syntax/type checking on Coordinates' tokens.
Author
Mateusz Kubuszok
See Also
CheckingDriver
CoordinateDriver
Definition at line 42 of file checking_coordinate_driver.hpp.
Constructor & Destructor Documentation
GT::GTL::CheckingCoordinateDriver::CheckingCoordinateDriver (Driver * parentDriver) explicit
Initiates CheckingCoordinateDriver with its parent.
Parameters
parentDriver parent Driver
Definition at line 31 of file checking_coordinate_driver.cpp.
   :
     driver(parentDriver)
     {}
Member Function Documentation
CoordinatePtr * GT::GTL::CheckingCoordinateDriver::create (const InputLocation & inputLocation, const IdentifierPtr * player, const IdentifierPtr * strategy) const override virtual
Creates coordinate.
Parameters
inputLocation input location of created Coordinate
player dimension (Player)
strategy position (strategy)
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 37 of file checking_coordinate_driver.cpp.
References GT::GTL::NullFactory::getInstance().
Referenced by GT::GTL::ExecutionCoordinateDriver::create().
         {
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             NullFactory::getInstance().createCoordinate(),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::CheckingCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const CoordinatesPtr * data) const override virtual
Fills Coordinate with subcoordinates.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 50 of file checking_coordinate_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::NullFactory::getInstance(), GT::GTL::ErrorFactory::getInstance(), and GT::GTL::Coordinate::toString().
Referenced by GT::GTL::ExecutionCoordinateDriver::fillWithData().
         {
     const Coordinate&  coordinate = **coordinatePtr;
     const Coordinates& data       = **dataPtr;
     if (!coordinate) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Coordinate: " + coordinate.toString();
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 ErrorFactory::getInstance().createCoordinate(errorMessage),
                 *coordinate.getInputLocation()
             )
         );
     }
     for (CoordinatePtr subCoordinatePtr : data) {
         Coordinate& subCoordinate = *subCoordinatePtr;
         if (!subCoordinate) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Invalid Data: " + subCoordinate.toString();
             return new CoordinatePtr(
                 setupLocation<Coordinate>(
                     ErrorFactory::getInstance().createCoordinate(errorMessage),
                     *subCoordinate.getInputLocation()
                 )
             );
         }
     }
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             NullFactory::getInstance().createCoordinate(),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::CheckingCoordinateDriver::fillWithData (const InputLocation & inputLocation, const CoordinatePtr * coordinate, const ParamsPtr * data) const override virtual
Fills Coordinate with Params.
Parameters
inputLocation input location of created Condition
coordinate Coordinate to fill
data data to insert
Returns
Coordinate
Implements GT::GTL::CoordinateDriver.
Definition at line 93 of file checking_coordinate_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::NullFactory::getInstance(), GT::GTL::ErrorFactory::getInstance(), GT::GTL::Object::toString(), and GT::GTL::Coordinate::toString().
         {
     const Coordinate&  coordinate = **coordinatePtr;
     const Params&      data       = **dataPtr;
     if (!coordinate) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Coordinate: " + coordinate.toString();
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 ErrorFactory::getInstance().createCoordinate(errorMessage),
                 *coordinate.getInputLocation()
             )
         );
     }
     for (ParamPtr subDataPtr : data) {
         Param& subData = *subDataPtr;
         if (!subData) {
             // TODO: create MessageFactory
             Message errorMessage = Message() +
                 "Invalid Data: " + subData.toString();
             return new CoordinatePtr(
                 setupLocation<Coordinate>(
                     ErrorFactory::getInstance().createCoordinate(errorMessage),
                     *subData.getInputLocation()
                 )
             );
         }
     }
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             NullFactory::getInstance().createCoordinate(),
             inputLocation
         )
     );
 }
CoordinatePtr * GT::GTL::CheckingCoordinateDriver::merge (const InputLocation & inputLocation, const CoordinatePtr * coordinate1, const CoordinatePtr * coordinate2) const override virtual
Merge two coordinates into one.
Parameters
inputLocation input location of created Condition
coordinate1 first Coorinate
coordinate2 second Coorinate
Returns
merged Coordinates
Implements GT::GTL::CoordinateDriver.
Definition at line 136 of file checking_coordinate_driver.cpp.
References GT::GTL::ValidableSymbol::getInputLocation(), GT::GTL::NullFactory::getInstance(), GT::GTL::ErrorFactory::getInstance(), and GT::GTL::Coordinate::toString().
Referenced by GT::GTL::ExecutionCoordinateDriver::merge().
         {
     const Coordinate&  coordinate1 = **coordinate1Ptr;
     const Coordinate&  coordinate2 = **coordinate2Ptr;
     if (!coordinate1) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Coordinate: " + coordinate1.toString();
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 ErrorFactory::getInstance().createCoordinate(errorMessage),
                 *coordinate1.getInputLocation()
             )
         );
     }
     if (!coordinate2) {
         // TODO: create MessageFactory
         Message errorMessage = Message() +
             "Invalid Coordinate: " + coordinate2.toString();
         return new CoordinatePtr(
             setupLocation<Coordinate>(
                 ErrorFactory::getInstance().createCoordinate(errorMessage),
                 *coordinate2.getInputLocation()
             )
         );
     }
     return new CoordinatePtr(
         setupLocation<Coordinate>(
             NullFactory::getInstance().createCoordinate(),
             inputLocation
         )
     );
 }
Message GT::GTL::CheckingCoordinateDriver::toString () const override virtual
CheckingCoordinateDriver message.
Returns
message
Implements GT::GTL::CoordinateDriver.
Definition at line 176 of file checking_coordinate_driver.cpp.
{
     return Message("CheckingCoordinateDriver");
 }
Member Data Documentation
Driver* GT::GTL::CheckingCoordinateDriver::driver private
Implementation of a main Driver.
Definition at line 46 of file checking_coordinate_driver.hpp.
The documentation for this class was generated from the following files:
src/gt/gtl/checking_coordinate_driver.hpp
src/gt/gtl/checking_coordinate_driver.cpp