Game Theory Tools (full documentation): GT::GTL::Definition Class Reference
GT::GTL::Definition Class Reference
Definition used to define Context.
#include <definition.hpp>
Public Member Functions
Definition (const IdentifierPtr definedName, const ParamPtr definedValue)
Constructor for name and value.
virtual const IdentifierPtr getName () const
Returns name of the property.
virtual const ParamPtr getValue () const
Returns value of the property.
virtual Message toString () const override
Returns Message about Definition.
Public Member Functions inherited from GT::GTL::ValidableSymbol
ValidableSymbol ()
Default constructor initiating input location.
virtual ~ValidableSymbol ()
Default destructor.
virtual bool isValid () const
Returns whether object is valid.
virtual const InputLocationPtr getInputLocation () const
Returns input location.
virtual void setInputLocation (const InputLocationPtr inputLocation)
Sets input location.
operator SafeBoolIdiom () const
Safe Bool Idiom used to make checks without comparisons or algrbraic usage of bool.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const IdentifierPtr name
Name of the property.
const ParamPtr value
Value of the property.
Detailed Description
Definition used to define Context.
Contains pair Identifier-Param which will be insterted into current Context in the next step.
Author
Mateusz Kubuszok
See Also
StatementDriver
Parser
Context
Param
Definition at line 44 of file definition.hpp.
Constructor & Destructor Documentation
GT::GTL::Definition::Definition (const IdentifierPtr definedName, const ParamPtr definedValue)
Constructor for name and value.
Parameters
definedName name of the defined property
definedValue value of the defined property
Definition at line 31 of file definition.cpp.
   :
     name(definedName),
     value(definedValue)
     {}
Member Function Documentation
const IdentifierPtr GT::GTL::Definition::getName () const virtual
Returns name of the property.
Returns
value of the property
Reimplemented in GT::GTL::ErrorDefinition, and GT::GTL::NullDefinition.
Definition at line 39 of file definition.cpp.
References name.
{
     return name;
 }
const ParamPtr GT::GTL::Definition::getValue () const virtual
Returns value of the property.
Returns
value of the property
Reimplemented in GT::GTL::ErrorDefinition, and GT::GTL::NullDefinition.
Definition at line 43 of file definition.cpp.
References value.
{
     return value;
 }
Message GT::GTL::Definition::toString () const override virtual
Returns Message about Definition.
Returns
Definition's Message
Implements GT::Model::Root.
Reimplemented in GT::GTL::ErrorDefinition, and GT::GTL::NullDefinition.
Definition at line 47 of file definition.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::createMessagePtr(), GT::Model::ResultFactory::getInstance(), name, and value.
{
     IdentifierPtr nam = createIdentifierPtr(name);
     MessagePtr    val = createMessagePtr(value->toString());
     return ResultFactory::getInstance().buildResult()->addResult(nam, val).build()->getResult();
 }
Member Data Documentation
const IdentifierPtr GT::GTL::Definition::name private
Name of the property.
Definition at line 48 of file definition.hpp.
Referenced by getName(), and toString().
const ParamPtr GT::GTL::Definition::value private
Value of the property.
Definition at line 53 of file definition.hpp.
Referenced by getValue(), and toString().
The documentation for this class was generated from the following files:
include/gt/gtl/definition.hpp
src/gt/gtl/definition.cpp