Game Theory Tools (full documentation): GT::Model::StrategicGamePositionsHelper Class Reference
GT::Model::StrategicGamePositionsHelper Class Reference final
Helper used for calculating Positions into Index and the other way round.
#include <strategic_game_positions_helper.hpp>
Public Member Functions
StrategicGamePositionsHelper (const PlayersPtr players)
Constructor initiated with Players definitions.
const PlayersPtr getPlayers () const
Returns Players definitions.
Index getUpperBound () const
Returns upper bound of Indexes.
Index calculatePlayer (const Identifier &playerName) const
Calculates Player's position in Numbers collection.
Index calculatePlayer (const IdentifierPtr playerName) const
Calculates Player's position in Numbers collection.
const IdentifierPtr retrievePlayer (const Index playerPosition) const
Calculates Player's name by its position in Numbers collection.
Index calculatePosition (const Positions &positions) const
Calculates Numbers's position in params storage.
Index calculatePosition (const PositionsPtr positions) const
Calculates Numbers's position in params storage.
const PositionsPtr retrievePositions (const Index positionInStorage) const
Calculates Positions by its Index in params storage.
bool checkPlayer (const Identifier &playerName) const
Checks whether given Player exists.
bool checkPlayer (const IdentifierPtr playerName) const
Checks whether given Player exists.
bool checkPositions (const Positions &positions) const
Checks whether given Position is valid.
bool checkPositions (const PositionsPtr positions) const
Checks whether given Position is valid.
virtual Message toString () const override
Retuns StrategicGamePositionsHelper's Message.
Public Member Functions inherited from GT::Model::Root
virtual ~Root ()
Default destructor.
virtual bool isEqual (const Root &root) const
Defines equality relation.
virtual bool isNotNull () const
Wheter Root is not a null Object (null guardian).
bool isNull () const
Wheter Root is a null Object (null guardian).
Private Attributes
const PlayersPtr players
Players.
IdentifierMap playersHelper
Map Players' Identifeirs to a number to quickly find Player's ordinal.
StrategyMap strategiesHelper
Maps Players' Strategies to a number to match: index = sum playerNumber * strategyNumber.
IdentifierMap positionsHelper
Maps Players' Identifeirs to a number to match: index = sum playerNumber * strategyNumber.
Index upperBound
Upper bound of storage's positions.
Detailed Description
Helper used for calculating Positions into Index and the other way round.
Author
Mateusz Kubuszok
Definition at line 37 of file strategic_game_positions_helper.hpp.
Constructor & Destructor Documentation
GT::Model::StrategicGamePositionsHelper::StrategicGamePositionsHelper (const PlayersPtr players) explicit
Constructor initiated with Players definitions.
Parameters
players Players definitions
Definition at line 36 of file strategic_game_positions_helper.cpp.
References GT::Model::Player::getStrategies(), GT::Model::Player::getStrategiesNumber(), GT::Model::Player::getStrategyOrdinal(), players, playersHelper, positionsHelper, strategiesHelper, and upperBound.
   :
     players(playersDefinitions),
     playersHelper(),
     strategiesHelper(),
     positionsHelper()
 {
     Index playerIndex   = 0;
     Index positionIndex = 1;
     for (const Players::value_type& playerPair : (*players)) {
         const Identifier& playerName = playerPair.first;
         const Player&     player     = *playerPair.second;
         const Identifiers strategies = *player.getStrategies(); // usage of reference here makes valgrind
                                                                 // yell "Invalid read of size 8" in for below
         IdentifierMap strategiesMap;
         for (const IdentifierPtr& strategy : strategies)
             strategiesMap.insert(IdentifierMap::value_type(*strategy, player.getStrategyOrdinal(*strategy)));
         playersHelper.insert( IdentifierMap::value_type(playerName, playerIndex) );
         positionsHelper.insert( IdentifierMap::value_type(playerName, positionIndex) );
         strategiesHelper.insert( StrategyMap::value_type(playerName, strategiesMap) );
         playerIndex++;
         positionIndex *= player.getStrategiesNumber();
     }
     upperBound = positionIndex;
 }
Member Function Documentation
Index GT::Model::StrategicGamePositionsHelper::calculatePlayer (const Identifier & playerName) const
Calculates Player's position in Numbers collection.
Parameters
playerName name of required Player
Returns
Index of Player's Number
Definition at line 75 of file strategic_game_positions_helper.cpp.
References playersHelper.
Referenced by calculatePlayer(), GT::Model::PlainDataPiece::getPayoff(), GT::Model::PlainDataPiece::toString(), and GT::Model::StrategicData::toString().
         {
     return playersHelper.left.at(playerName);
 }
Index GT::Model::StrategicGamePositionsHelper::calculatePlayer (const IdentifierPtr playerName) const
Calculates Player's position in Numbers collection.
Parameters
playerName name of required Player
Returns
Index of Player's Number
Definition at line 81 of file strategic_game_positions_helper.cpp.
References calculatePlayer().
         {
     return calculatePlayer(*playerName);
 }
Index GT::Model::StrategicGamePositionsHelper::calculatePosition (const Positions & positions) const
Calculates Numbers's position in params storage.
Parameters
positions Positions as coordinates
Returns
Index in params storage
Definition at line 93 of file strategic_game_positions_helper.cpp.
References positionsHelper, and strategiesHelper.
Referenced by calculatePosition(), GT::Model::StrategicData::getPayoffs(), and GT::Model::StrategicData::setPayoffs().
         {
     Index storagePosition = 0;
     for (const Positions::value_type& position : positions) {
         const Identifier playerName   = position.first;
         const Identifier strategyName = position.second;
         storagePosition +=
             // dirty hack to "handle" situation when some players have only 1 strategy
             (positionsHelper.left.count(playerName) ? positionsHelper.left.at(playerName) : 0)
             *
             strategiesHelper.at(playerName).left.at(strategyName);
     }
     return storagePosition;
 }
Index GT::Model::StrategicGamePositionsHelper::calculatePosition (const PositionsPtr positions) const
Calculates Numbers's position in params storage.
Parameters
positions Positions as coordinates
Returns
Index in params storage
Definition at line 109 of file strategic_game_positions_helper.cpp.
References calculatePosition().
         {
     return calculatePosition(*positions);
 }
bool GT::Model::StrategicGamePositionsHelper::checkPlayer (const Identifier & playerName) const
Checks whether given Player exists.
Parameters
playerName name of checked Player
Returns
true if Player exists
Definition at line 163 of file strategic_game_positions_helper.cpp.
References playersHelper.
Referenced by checkPlayer(), checkPositions(), and GT::Model::PlainDataPiece::getPayoff().
         {
     return playersHelper.left.count(playerName);
 }
bool GT::Model::StrategicGamePositionsHelper::checkPlayer (const IdentifierPtr playerName) const
Checks whether given Player exists.
Parameters
playerName name of checked Player
Returns
true if Player exists
Definition at line 169 of file strategic_game_positions_helper.cpp.
References checkPlayer().
         {
     return checkPlayer(*playerName);
 }
bool GT::Model::StrategicGamePositionsHelper::checkPositions (const Positions & positions) const
Checks whether given Position is valid.
Parameters
positions checked positions
Returns
true if Position is valid
Definition at line 175 of file strategic_game_positions_helper.cpp.
References checkPlayer(), and strategiesHelper.
Referenced by checkPositions(), and GT::Model::StrategicData::setPayoffs().
         {
     for (Identifier playerName : positions | map_keys) {
         if (!checkPlayer(playerName))
             return false;
         Identifier strategyName = positions.at(playerName);
         if (!strategiesHelper.at(playerName).left.count(strategyName))
             return false;
     }
     return true;
 }
bool GT::Model::StrategicGamePositionsHelper::checkPositions (const PositionsPtr positions) const
Checks whether given Position is valid.
Parameters
positions checked positions
Returns
true if Position is valid
Definition at line 188 of file strategic_game_positions_helper.cpp.
References checkPositions().
         {
     return checkPositions(*positions);
 }
const PlayersPtr GT::Model::StrategicGamePositionsHelper::getPlayers () const
Returns Players definitions.
Returns
Players definitions
Definition at line 67 of file strategic_game_positions_helper.cpp.
References players.
Referenced by GT::Model::PlainDataPiece::getPayoff(), GT::Model::StrategicData::getPayoffs(), GT::Model::StrategicData::getPlayers(), GT::Model::PlainDataPiece::is0Sum(), GT::Model::PlainDataPiece::toString(), and GT::Model::StrategicData::toString().
{
     return players;
 }
Index GT::Model::StrategicGamePositionsHelper::getUpperBound () const
Returns upper bound of Indexes.
Returns
upper bound of Indexes
Definition at line 71 of file strategic_game_positions_helper.cpp.
References upperBound.
Referenced by GT::Model::PlainDataPiece::getPayoff(), GT::Model::StrategicData::getPayoffs(), GT::Model::StrategicData::getUpperBound(), GT::Model::StrategicData::setPayoffs(), and GT::Model::StrategicData::StrategicData().
{
     return upperBound;
 }
const IdentifierPtr GT::Model::StrategicGamePositionsHelper::retrievePlayer (const Index playerPosition) const
Calculates Player's name by its position in Numbers collection.
Parameters
playerPosition Index of Player's Number
Returns
name of required Player
Definition at line 87 of file strategic_game_positions_helper.cpp.
References GT::createIdentifierPtr(), and playersHelper.
Referenced by GT::Model::StrategicData::toString().
         {
     return createIdentifierPtr(playersHelper.right.at(playerPosition));
 }
const PositionsPtr GT::Model::StrategicGamePositionsHelper::retrievePositions (const Index positionInStorage) const
Calculates Positions by its Index in params storage.
Parameters
positionInStorage Index of Positions
Returns
Positions as coordinates
Definition at line 115 of file strategic_game_positions_helper.cpp.
References GT::createPositionsPtr(), GT::Model::Player::getStrategies(), GT::Model::Player::getStrategiesNumber(), players, positionsHelper, and strategiesHelper.
Referenced by GT::Model::StrategicData::toString().
         {
     PositionsPtr positions       = createPositionsPtr();
     Index        checkedPosition = positionInStorage;
     // this adds at most one Player with only 1 strategy!
     for (Index playerValue : positionsHelper.right | map_keys | reversed) {
         Identifier playerName = positionsHelper.right.at(playerValue);
         for (Index strategyValue = strategiesHelper.at(playerName).size()-1;
                    true;
                    strategyValue--
         ) {
             if (playerValue*strategyValue <= checkedPosition) {
                 positions->insert(
                     Positions::value_type(
                         playerName,
                         strategiesHelper.at(playerName).right.at(strategyValue)
                     )
                 );
                 checkedPosition -= playerValue*strategyValue;
                 break;
             }
             if (!strategyValue)
                 break;
         }
     }
     // dirty hack adding all missing Players with just 1 strategy
     for (const Players::value_type& player : *players) {
         const Identifier& playerName     = player.first;
         const Player&     playerInstance = *player.second;
         if (playerInstance.getStrategiesNumber() == 1 && !positions->count(playerName)) {
             const Identifier& strategy = *(*playerInstance.getStrategies())[0];
             positions->insert(
                 Positions::value_type(
                     playerName,
                     strategy
                 )
             );
         }
     }
     return positions;
 }
Message GT::Model::StrategicGamePositionsHelper::toString () const override virtual
Retuns StrategicGamePositionsHelper's Message.
Returns
Message
Implements GT::Model::Root.
Definition at line 194 of file strategic_game_positions_helper.cpp.
References GT::Model::ResultFactory::buildResult(), GT::createIdentifierPtr(), GT::Model::ResultFactory::getInstance(), and players.
{
     ResultBuilderPtr resultBuilder = ResultFactory::getInstance().buildResult();
     IdentifierPtr    name          = createIdentifierPtr("Player");
     for (const Players::value_type& player : (*players)) {
         MessagePtr playerContent = createIdentifierPtr(player.second->toString());
         resultBuilder->addResult(name, playerContent);
     }
     return resultBuilder->build()->getResult();
 }
Member Data Documentation
const PlayersPtr GT::Model::StrategicGamePositionsHelper::players private
Players.
Definition at line 41 of file strategic_game_positions_helper.hpp.
Referenced by getPlayers(), retrievePositions(), StrategicGamePositionsHelper(), and toString().
IdentifierMap GT::Model::StrategicGamePositionsHelper::playersHelper private
Map Players' Identifeirs to a number to quickly find Player's ordinal.
Definition at line 46 of file strategic_game_positions_helper.hpp.
Referenced by calculatePlayer(), checkPlayer(), retrievePlayer(), and StrategicGamePositionsHelper().
IdentifierMap GT::Model::StrategicGamePositionsHelper::positionsHelper private
Maps Players' Identifeirs to a number to match: index = sum playerNumber * strategyNumber.
Definition at line 54 of file strategic_game_positions_helper.hpp.
Referenced by calculatePosition(), retrievePositions(), and StrategicGamePositionsHelper().
StrategyMap GT::Model::StrategicGamePositionsHelper::strategiesHelper private
Maps Players' Strategies to a number to match: index = sum playerNumber * strategyNumber.
Definition at line 50 of file strategic_game_positions_helper.hpp.
Referenced by calculatePosition(), checkPositions(), retrievePositions(), and StrategicGamePositionsHelper().
Index GT::Model::StrategicGamePositionsHelper::upperBound private
Upper bound of storage's positions.
Definition at line 59 of file strategic_game_positions_helper.hpp.
Referenced by getUpperBound(), and StrategicGamePositionsHelper().
The documentation for this class was generated from the following files:
src/gt/model/strategic_game_positions_helper.hpp
src/gt/model/strategic_game_positions_helper.cpp